### ISSUE TITLE
Teams with negative scores on objective maps can appear below objectives.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1005]
![2014-08-19_21 17 41](https://cloud.githubusercontent.com/assets/7586568/3991874/a137ef50-28ec-11e4-8c5f-08715794bb60.png)
![2014-08-19_21 17 10](https://cloud.githubusercontent.com/assets/7586568/3991876/a3f907ba-28ec-11e4-84b1-65fe1ba7a941.png)
![2014-07-27_20 17 53](https://cloud.githubusercontent.com/assets/7586568/3991879/ab867f30-28ec-11e4-9ce0-6c3c013fe1d4.png)

**Comment by Electroid** [comment]
Fixed with new scoreboard layout in 1.8
