### ISSUE TITLE
Incorrect number of unread topics

### ISSUE THREAD

**Issue by ieatboulders2** [OvercastNetwork/Issues#1019]
![](http://i.gyazo.com/483c674a78a0ff09a290e08f8f759da8.png)
Not sure if this is a valid issue. I'd assuming this is caused by topics being hidden / deleted. It says there's one topic that I haven't seen in the Submissions area, when there are 0 topics in the Submissions area.

**Comment by ghost** [comment]
Fixed with the forums' revamp
