### ISSUE TITLE
Can't hide own threads under "Map Making/Submissions" sub forum.

### ISSUE THREAD

**Issue by chickolympics** [OvercastNetwork/Issues#1044]
I recently screwed up and realized that I accidentally posted the same topic several times under the Map Submissions sub forum. When I went to hide the posts, I saw that there was no option to hide the post itself. While normally there is a hide button under the "Edit" drop-down above the topic..
![screen shot 2014-08-26 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/4752118/4052714/ffdc9854-2d6e-11e4-9481-eb766f568192.png) 

This does not appear under the Submissions sub forum.

![screen shot 2014-08-26 at 3 20 49 pm](https://cloud.githubusercontent.com/assets/4752118/4052741/470b3a00-2d6f-11e4-8e74-be872c612e96.png)

 I'm not sure if this is intentional (Don't know why it would be?), I just wanted to report it incase.

**Comment by Electroid** [comment]
This was fixed a while ago.. it's also just a simple permissions thing.
