### ISSUE TITLE
Hidden posts cause issues with forum pagination

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1073]
EDIT: This now also applies to "Let's Play Applications".

So I made a topic for a map under the submittion subforum.

![](http://i.gyazo.com/08b65ba13c79fa555856925681f3525c.png)

You can see the map topic is clearly there

![](http://i.gyazo.com/cf964031efd1ec1c3353af64ca419d3e.png)

But the topic doesnt display under submittons (i am logged in)

![](http://i.gyazo.com/c6501b38a3d6f25585f376bb7419bc40.png)

**Comment by matic0basle** [comment]
EDIT: This now also applies to "Let's Play Applications".

**Comment by ElliottWhyman** [comment]
Closing in favor of the internal issue
