### ISSUE TITLE
Blood particles incorrect in 1.8

### ISSUE THREAD

**Issue by iPGz** [OvercastNetwork/Issues#1082]
The blood particles for all damage in 1.7.10 are displayed as Redstone and Lava particles,

![](http://i.imgur.com/OQ51SpZ.png)

In 1.8 these are shown as light grey, when the player receives damage via another player.

![](http://i.imgur.com/H1gJhKk.png)

(Unsure if this is a piece of the plugin that needs updating to work with 1.8 in the future or a Minecraft particle issue preventing the use of red Redstone).

**Comment by ghost** [comment]
Fixed in 1.9
