### ISSUE TITLE
Glistering Melon displaying Hunger missing texture

### ISSUE THREAD

**Issue by iPGz** [OvercastNetwork/Issues#1083]
Observing an inventory in 1.7.10
![](http://i.imgur.com/RffU8wL.png)
This is the regular hunger icon in the top right showing the player at 14 health in the form of a glistering melon.

Observing an inventory in 1.8
![](http://i.imgur.com/Rrilf5f.png)
When in 1.8 these melons are no longer displaying correctly and showing a pink and block block missing texture. The texture is not missing as the bottom right displays a glistering melon in the players inventory also.

Melon in inventory with texture (1.8)
![](http://i.imgur.com/1PtRgej.png)
This texture is shown and the ID is displayed as 382, minecraft:specklied_melon 

Melon in inventory without texture (1.8)
![](http://i.imgur.com/gdnxU3K.png)
This texture is not displayed and the ID is displayed as 382, minecraft:specklied_melon, with the addition of a NBT tag (which could be causing the issue however this is just the custom name preventing the texture from loading maybe although the names work for potions and health).

**Comment by Electroid** [comment]
Fixed
