### ISSUE TITLE
TNT Minecarts Bypassing Deny Regions on Pursuit of Happiness

### ISSUE THREAD

**Issue by nathancard** [OvercastNetwork/Issues#1101]
This may be occurring on other maps as well, I'm not sure. On Pursuit of Happiness, one can make a TNT minecart and set it off right next to the opposing team's target wool room (on your own side), destroying a good 1/3 of the other team's wool room, which is clearly a problem and seems relatively easy to fix.

**Comment by Electroid** [comment]
Not a plugin bug, feature in the XML.
