### ISSUE TITLE
Rules/Contact dropdown menus don't work on the 404 page

### ISSUE THREAD

**Issue by Narwhale** [OvercastNetwork/Issues#1110]
I'm guessing the same thing happens on the 500 page as well.

These things: 

![](http://i.imgur.com/9e8cw0N.png)

**Comment by ghost** [comment]
This is fixed (http://prntscr.com/9avwvy), but those dropdowns shouldn't exist anymore for the footer's revamp

**Comment by itsmartin** [comment]
#1589 covers the remaining parts of this issue.
