### ISSUE TITLE
Can't Donate More

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#12]
After you have already reached the level of Dux, you can no longer donate.

**Comment by TiTo-418** [comment]
"Pushed back to next weekly." xD
Im propose the "Dux" link redirect to donater profile
<a href="http://imgur.com/Q1IJ363"><img src="http://i.imgur.com/Q1IJ363.jpg" title="source: imgur.com" /></a>

**Comment by Ipskie** [comment]
@TiTo-418 We don't do feature requests here anymore (IIRC) and even if we did you're commenting on an unrelated issue which is not the way to go.

Also for most packages this would basically refresh the page, and for Secret Santa packages you're not supposed to know who donated for you. The current link works fine

**Comment by Electroid** [comment]
We decided not to do tipping.. plus we have our two new ranks for this purpose.
