### ISSUE TITLE
Subscription count

### ISSUE THREAD

**Issue by censink-** [OvercastNetwork/Issues#121]
Feature suggestion:

Simple & small, yet usefull piece of info
![schermafbeelding 2013-05-12 om 09 05 05](https://f.cloud.github.com/assets/3994234/492659/d3e4549a-bad2-11e2-8cab-f984487b4f94.png)
Should show above both subscribe and unsubscribe, on thread pages.
Only shows when hovering above the button, like with avatars on your profile.

**Comment by Electroid** [comment]
It hath been done.
