### ISSUE TITLE
Package Expiration on profiles incorrect

### ISSUE THREAD

**Issue by MrBloxley** [OvercastNetwork/Issues#1217]
The amount of time that a package expires according to the badge on a player's profile is not correct. Such as on this profile: https://oc.tc/slayersource. I had purchased Centurion for him on July 25th, just 2 months ago. The Centurion package lasts for 6 months. His profile says that it expires in about 1 month. It also appears with Optio. Yesterday, a player (https://oc.tc/Abusa3) had become confused because they had purchased Optio and on their profile it said that it expires in about 1 month even though Optio lasts for 2 months. Although this may be a minor problem, it does bring up confusion and I thought it was best to bring it up here.

**Comment by Electroid** [comment]
Isn't an issue anymore.
