### ISSUE TITLE
Scoreboard Errors

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#1241]
On a map that has both TDM and DTM gamemodes the scoreboard has errors. In the example posted a few of the inhibtators where broken aswell as the nexus, but shows and X and 0%.

http://cl.ly/image/061V1h2C1n1d

Team Kills also break scoreboard placement.

http://cl.ly/image/1M0Z28411s2n

It seems scoreboard placement is overridden by the built in placement system when the team has kills.

**Comment by Electroid** [comment]
We already have an issue internally for this one.
