### ISSUE TITLE
Greater and Less than don't show in Topic Titles

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#1245]
If you use a less than or greater than in your topic title it doesn't show on the forums, but does in the page title.

![](http://f.cl.ly/items/1Y0O150U0B0C1o1i3H30/Image%202014-10-07%20at%201.54.05%20PM.png)

![](http://f.cl.ly/items/0Y463r1z1A1a3u1U1g30/Image%202014-10-07%20at%201.53.51%20PM.png)

**Comment by JsKingBoo** [comment]
Additionally, if the title of the thread exclusively has "<" and ">" signs, it appears that the thread has no title. If you don't hide the thread, it looks weird on the front page as well because the thread information "JsKingBoo about 1 hour ago in Off topic" is higher than normal

**Comment by jedediah** [comment]
fixed
