### ISSUE TITLE
Some bugs with /nick and the new tablist

### ISSUE THREAD

**Issue by Superjd10** [OvercastNetwork/Issues#1251]
(I got permission to post the nick)

Today, I joined Mini02 (US) because I saw a friend there (Gaporigo), When I pressed tab in the server to check in what team was him, I didn't see his real nick, instead I saw his current nick

![image](https://cloud.githubusercontent.com/assets/1649155/4588289/183a3d64-503f-11e4-8727-5b866df4f3dd.png)

Also, /staff -a and /fr weren't showing his team color.

![image](https://cloud.githubusercontent.com/assets/1649155/4588286/f8183d38-503e-11e4-94de-10addbbc7633.png)

**Comment by Electroid** [comment]
Not anymore.
