### ISSUE TITLE
/seen show players as if they were on a different server when they are not 

### ISSUE THREAD

**Issue by Brottweiler** [OvercastNetwork/Issues#1252]
# The issue
Running `/seen` on a player that is on the same server as you, shows what server they are on even if they are on the same server as you

## Steps to reproduce
1. Go onto a server
2. Run `/seen <your username>`

## What I expected to happen
```
Brottweiler is online
```

## What actually happened
```
Brottweiler is online on <current server>
```

![](http://i.imgur.com/69VjncV.png)

**Comment by ghost** [comment]
Fixed http://prntscr.com/8rtf3x
