### ISSUE TITLE
Inventory cycle bug

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1261]
When a match ends and the map cycles the hotbar goes back to normal (books come back) if you changed anything in it but anything in your inventory not in the hotbar stays-

![](http://i.gyazo.com/fece266b16aa0276e6b4373f892155bb.png)

Still had armor after the map cycled but the books re-appeared

**Comment by Electroid** [comment]
This seems extremely rare, I have a feeling it has something to do with whatever client you have. @matic0basle 

Because I remember this happening when I use to have the macros mod with lite loader.

**Comment by mrapple** [comment]
Don't think we've seen this in a long time
