### ISSUE TITLE
/raindrops shows incorrect grammar

### ISSUE THREAD

**Issue by trevinwoodstock** [OvercastNetwork/Issues#1271]
The issue is that when running `/raindrops` on any server, incorrect grammar is returned. Currently, it returns `(number of raindrops) raindrop`. Correctly, it should return `(number of raindrops) raindrops` (notice the _s_), unless said user has one raindrop, in which case it'd be `1 raindrop`. 

To reproduce this, join a server (hub servers too) and run `/raindrops`.

Here's an example of what happens.
![Raindrops.](http://i.kmp.pw/vWZ1Q8.png)

**Comment by dentmaged** [comment]
I personally think this message should be translatable as well.

**Comment by Superjd10** [comment]
@dentmaged AFAIK, it's.

**Comment by dentmaged** [comment]
@Superjd10 I looked at the CrowdIn and I couldn't find anything. I'd like to translate it to Dutch! :D

**Comment by Superjd10** [comment]
@dentmaged Maybe they were hidden, I'll try to see if they are and ask why,
