### ISSUE TITLE
Disguises broken

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1275]
On that map, people look like skeletons or zombies, and get a colored nametag, and apparently they keep them on the next map:
![2014-10-18_08 35 10](https://cloud.githubusercontent.com/assets/8422075/4690028/546f9b50-56d7-11e4-8eb8-9e9c32d32347.png)
![2014-10-18_08 34 51](https://cloud.githubusercontent.com/assets/8422075/4690029/5479eb14-56d7-11e4-9f13-3c66ca3f28ef.png)

**Comment by Electroid** [comment]
Author of the plugin has signed off the project as unmaintained. All our maps have removed this feature. And until further notice, this feature won't come back.
