### ISSUE TITLE
All tags have a "expires in 98050 years" when hovering over them on some player accounts

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1277]
This only seems to happen on the account profiles of last_username, khazhyk, Matsuzen, ElectroidFilms, and maybe some others.  This also happens when hovering over the heart.
![m](https://cloud.githubusercontent.com/assets/7586568/4690909/3bbb03a6-56ff-11e4-912d-34ba82706837.png)

**Comment by Electroid** [comment]
Pretty sure this is gone.
