### ISSUE TITLE
Missing textures on some blocks.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1284]
![2014-10-19_12 32 12](https://cloud.githubusercontent.com/assets/7586568/4694495/4b17b8c2-57cb-11e4-9615-315038b73bf9.png)
![2014-10-19_12 32 15](https://cloud.githubusercontent.com/assets/7586568/4694496/4d426232-57cb-11e4-9838-08ae0762b3e8.png)

**Comment by Pugzy** [comment]
I'm currently working though these and once I have the known ones fixed I'll push what I have.
Currently I have fixed both Soviet Chills and Temple Run fixed on my server.

**Comment by Matic0B** [comment]
Interitus TE still has them in chests then @iPGz

**Comment by Pugzy** [comment]
I'm ready to push a fix for these, just wondering if any other maps not listed above have a similar item data value issue.

**Comment by Matic0B** [comment]
@iPGz Not that I know of.
