### ISSUE TITLE
Tweak server dynamics

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1368]
Mini01 - 11/24 (half)
Mini02 - Full
Capture - 29/64 (half)
Primed - 21/48 (half)
Alpha - Empty (no it did not just restart)

I think one more mini should shoult down. Currently all servers above are are online all the time but I think Mini02 should should shut down and turn on before Nostalgia

![](http://i.gyazo.com/94cfbd10bd76609330c5a78b6d7b0145.png)

Another one:

Mini01 - Empty (no it did not just restart)
Mini02 - 12/32 (a third?)
Capture - 21/64 (a third?)
Primed - 10/48 (a quarter?)
Alpha - Empty (no it did not just restart)

![](http://i.gyazo.com/7cba5934a6513aa0f6a2fd966b0f0a97.png)

**Comment by Electroid** [comment]
The changes suggested here are long gone and done.
