### ISSUE TITLE
TNT ignited with flint & steel is not credited corectly

### ISSUE THREAD

**Issue by YukonAppleGeek** [OvercastNetwork/Issues#137]
TNT ignited with flint and steel is counted as a melee kill not TNT.

This is from the Tracter issue OvercastNetwork/Tracker#4 that is a PGM bug not Tracker. That issue should be closed and moved here.

**Comment by Electroid** [comment]
I believe this has been fixed? Haven't seem this issue for a while.

**Comment by mrapple** [comment]
Yep. #close
