### ISSUE TITLE
Enchanted Iron Sword on Irongate Harbor only does 1 heart

### ISSUE THREAD

**Issue by Seode** [OvercastNetwork/Issues#1386]
The enchanted iron sword on Irongate Harbor, with sharpness 1 and -15% speed, only does one heart of damage. This video linked, https://www.youtube.com/watch?v=x_hyXWTRdsI , showcases how much damage the sword does against someone with no armor. My suspicion is that because the "+n Attack Damage" is not shown when hovering over the item, the regular iron sword damage is not dealt. The damage dealt is the Sharpness 1 (+1.25) shown on the item and a fist (+1).

**Comment by Fireblast168** [comment]
It is not intended, and it is a bug. It actually does 3.5 damage (1 3/4 hearts), as Sharpness adds 1.5 attack damage per level.

**Comment by Ipskie** [comment]
Doesn't sharpness rely on an RNG? Hence higher sharpness will lead to a more random amount of damage, making damage attribute a better choice

**Comment by Fireblast168** [comment]
*Waits silently for this annoying issue to be fixed*

**Comment by Seode** [comment]
For a quick fix, you can get some exp bottles (by giving gold ingots to one of the villagers) and repair your iron sword with the sharpness sword. It will take off the speed effect and make the sword a regular sharpness 1 sword.
