### ISSUE TITLE
Redstone glitches on DATAstation

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1395]
![2014-11-24_19 47 20](https://cloud.githubusercontent.com/assets/7586568/5311259/6ddbe182-7bff-11e4-936a-08af39fbe043.png)
![2014-11-24_19 48 54](https://cloud.githubusercontent.com/assets/7586568/5311260/7c010904-7bff-11e4-81b9-486e1854feda.png)
It probably should be removed to that falling sand list so it doesn't fly around when blown up.

**Comment by CaptainElliott** [comment]
@Electroid has this been fixed? I cant seem to reproduce

**Comment by Electroid** [comment]
It's client side and occurs with great rarity.
