### ISSUE TITLE
Blitz maps with objectives have a messed up scoreboard

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1409]
![2014-12-06_16 29 34](https://cloud.githubusercontent.com/assets/8422075/5329415/8501c8cc-7d71-11e4-92c3-cf1ed9d5bd47.png)

![2014-12-06_15 34 45](https://cloud.githubusercontent.com/assets/8422075/5329417/8e5cb3aa-7d71-11e4-947c-691cb9132521.png)

**Comment by TiTo-418** [comment]
Fixed in 1.8
