### ISSUE TITLE
You can carpet bomb in DATAbasin spawn

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1410]
![2014-12-06_18 18 19](https://cloud.githubusercontent.com/assets/7586568/5329709/639700bc-7d7b-11e4-9f41-c147c3fc2410.png)
And because it digs a pit very easily if the chance is given, it can also make players impossible to escape spawn or the pit near and around it.

**Comment by Electroid** [comment]
I won't be fixing this.
