### ISSUE TITLE
Map Update - DK Crossovers DTE v1.3.1

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1427]
Small update concerning XML.

https://github.com/DoomRobotBoy/Maps-XML/blob/master/DK%20Crossover%20DTE.xml

I updated the proto to 1.3.6 and added water buckets back. However, I did not revert the changes of the dry-cannoning effect, similar to Electroid's try with that on DATAstation. 

I'm doing this because with only dry-cannoning the map seemed to be too fast-paced. I hope this will bring some changes in that.

If it won't work this time as well than I will make water-barriers (horizontal deny-water regions) to try to avoid the vertical movement of water.

**Comment by DoomRobotBoy** [comment]
Can this finally be completed? I don't want to be rude or forcing you, but I think that when a map update is 3 months old, and is only surrounded by web/plugin-issues, it is abandoned.

**Comment by rockymine** [comment]
I've experienced some problems with the dry-cannons too. Ones they've been killed it was just to simple to redo them, imo that did a drastic cut in the length of a match. I hope this gets added, somehow already nostalgic when playing it on SNS, which is somehow dead too.
