### ISSUE TITLE
Localization for new team picker has the previous string translated

### ISSUE THREAD

**Issue by Superjd10** [OvercastNetwork/Issues#1433]
What the title says.

![image](https://cloud.githubusercontent.com/assets/1649155/5422477/e452a5ce-8250-11e4-916b-a7a60960e81e.png)

(In the "lore" it says: Use this book to easily select your team!" (old string)

I think Apple will update the strings in Crowdin soon, so this is minor.

**Comment by ghost** [comment]
Fixed http://prntscr.com/8rszu8
