### ISSUE TITLE
[TM] Broken Spawn-location

### ISSUE THREAD

**Issue by Picajoluna** [OvercastNetwork/Issues#1462]
Hi,

I logged onto the TM lobbies today and discovered the spawn-point is outside of the actual lobby, about 20 blocks outside of it, resulting in an infinite void-loop spawn.  This is a pretty minor issue, you can /j onto the lobby-land or use the 'Murica gizmo.  This bug is on all three lobbies.

Thanks!

**Comment by mrapple** [comment]
@rmsy
