### ISSUE TITLE
Rank Order wrong? - Dux | Optio | Centurion - In Game

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1478]
If you look in each of the 3 following pictures, when people have all 3 ranks, the rank order is Dux Optio Centurion (purple star, lime star, yellow star). Shouldn't it be Dux Centurion Optio (purple star, yellow star, lime star), the order of the expensiveness/abilities from the ranks, from high to low.

1st picture; Red Team, second player from above:
http://i.imgur.com/T3YHesR.png

2nd picture; Blue Team, first player from above:
http://i.imgur.com/ura3iUY.png

3rd picture; Blue Team, first and fourth player from above of blue's list:
http://i.imgur.com/Fq1cu1O.png

Nothing important, mostly because such occurrence doesn't happen too often.

**Comment by ghost** [comment]
You're supposed to don't have more than one star, https://github.com/OvercastNetwork/Issues/issues/2292

**Comment by itsmartin** [comment]
Not sure what determines the flair order, but this will be a non-issue soon anyway when #2292 is fixed.
