### ISSUE TITLE
24 hour stats incorrect

### ISSUE THREAD

**Issue by mrapple** [OvercastNetwork/Issues#1479]

**Comment by SheriffSoco** [comment]
Do you know how to fix this? It's been 3 weeks and nothing has been changed

**Comment by TiTo-418** [comment]
This can be closed

**Comment by mrapple** [comment]
Nope

**Comment by TiTo-418** [comment]
http://gyazo.com/d120e570cf0c41b01e5d0e2098d123e3

**Comment by Ipskie** [comment]
@TiTo-418 what exactly does that prove, pray tell?

**Comment by TiTo-418** [comment]
The time selector (24 hours, week, all time) disappear in the stats

**Comment by itsmartin** [comment]
Please try to keep the unnecessary discussion to a minimum. This issue is being left open because the original issue isn't yet fixed.

**Comment by Electroid** [comment]
Fixed recently.
