### ISSUE TITLE
Aaerohohohos Holes in Bridge from Center to tunnel - Map Bug

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1481]
The North exit from the center gold spawner, which leads into a tunnel, has 2 holes in the bridge, who directly make you fall in the void. You can easily fall in them, especially because they are in a 3-block-wide bridge.

The bug is shown on the left side of both pictures:
http://i.imgur.com/4jR8FZz.png
http://i.imgur.com/qDMNuLx.png

I know the map is also returned to it's former state (due to the advent calendar and christmas ending), but it's a bug that could get some lives lost and even for 3 days I don't think that's worth it.

**Comment by eliyap** [comment]
I don't think this is in the repo anymore, maybe reopen this christmas if it come's back

**Comment by DoomRobotBoy** [comment]
@Ipskie It still is:
- https://maps.oc.tc/KOTH/Christmas/Aaerhohohos/
- https://oc.tc/maps/aaerhohohos
