### ISSUE TITLE
Reduce height limit on Placid Spring

### ISSUE THREAD

**Issue by 9grenier** [OvercastNetwork/Issues#1492]
Skybridging, as always, has become too overpowered. I am therefore asking for the height limit on the map to be reduced from 32 to 24. Thanks in advance!

**Comment by Dinner1111** [comment]
This repo is for technical issues and map updates, not for feature requests. If you contact the author to confirm this change, he can then create an issue or directly message a map developer to change it.

**Comment by Electroid** [comment]
Not if he _is_ the map maker.

**Comment by Dinner1111** [comment]
OH my bad :fearful:
