### ISSUE TITLE
You can bridge outside of the map on Warlock

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1493]
![2015-01-01_13 54 47](https://cloud.githubusercontent.com/assets/8422075/5593135/d8f2e32a-91bd-11e4-8809-0dfdff4e9b0f.png)

**Comment by Kitatist** [comment]
Holly...

**Comment by Tapetepato** [comment]
@Kitatist what?

**Comment by stormer1267** [comment]
some extra pics, these folks took it pretty far. 


![](http://puu.sh/gcDYC/6755917c2d.png)


![](http://puu.sh/gcDY9/170211540f.png)

**Comment by High-Tower98** [comment]
Currently spectating a match with a bridge of 800 blocks and still increasing

**Comment by kroest** [comment]
this should not be to hard to fix...

**Comment by Tapetepato** [comment]
it's also a problem on Warlock CTF

**Comment by Brettogden** [comment]
After speaking with both map makers they consider this a feature and not a bug
