### ISSUE TITLE
XML "parsing error" on The Core

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1496]
https://maps.oc.tc/DTM/Standard/The%20Core/map.xml

http://puu.sh/dWHcb.png
Apparently the XML declaration is not well formed, according to my error on Firefox.

**Comment by nixter1029** [comment]
I see absolutely zero errors in that xml.

**Comment by Dinner1111** [comment]
This is not technically an issue because this has no effect in-game, but I'll fix it.
