### ISSUE TITLE
Sometimes the maps page (oc.tc/maps/*) doesn't display any maps.

### ISSUE THREAD

**Issue by RastaLulz** [OvercastNetwork/Issues#1497]
### Issue ###

Sometimes the maps page (oc.tc/maps/*) doesn't display any maps, when it should.

![screencapture-oc-tc-maps-all](https://cloud.githubusercontent.com/assets/1159106/5594827/595f4b1e-9224-11e4-8633-4ee97c986af8.png)

### How to Reproduce ###

1. Go to any maps page (i.e. [oc.tc/maps](https://oc.tc/maps)).
2. Refresh the page until it displays no maps.

### Miscellaneous ###

This issue must be recent, because it only recently started affecting [OCNotifier](https://oc.tc/forums/topics/5472835967d522c35300139c) as far as I'm aware, as it relies on those pages to generate [this](https://ocn.rastalulz.com/api/maps) file.

**Comment by mrapple** [comment]
This will be fixed shortly.
