### ISSUE TITLE
Relapse UHC (Blitz)  Spawn Damage

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1500]
When you spawn (only tested on orange team) you take damage. Now this doesn't seem that big of an issue since you would normaly regenerate that half a heart but this map is UHC so normal regeneration is turned off.

**Comment by minimitch0199** [comment]
I fixed this in the Christmas version but it doesn't look like I did it to the regular version. Will get around to it later today along with a few other changes.

**Comment by matic0basle** [comment]
Should be fixed with #1505
