### ISSUE TITLE
Broken Regions on Fairytales 2: A Tale or Two

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1503]
I was trying to defend the green wool however when I was over there, I got spammed with region messages to where I could hardly see chat.

http://imgur.com/a/bgpU3

**Comment by Dinner1111** [comment]
This happened while you were waling around or when you were placing blocks?

**Comment by ParaSpider** [comment]
Walking around.

**Comment by Pandaboyy** [comment]
Had you lit anything on fire, like a skybridge at height limit? The fire trying to spread onto the top of the skybridge would trigger these messages. This happens to me when I defend on RFV and light the wool on the sides on fire.

**Comment by ParaSpider** [comment]
Nope @Pandaboyy

**Comment by EyQu** [comment]
How to reproduce?

**Comment by ParaSpider** [comment]
I was just walking around. That's all there was?

**Comment by EyQu** [comment]
The only way I can reproduce is when I place fire, like what was said above.

http://puu.sh/epMgb/bcc5bdb1ff.png
![image](https://cloud.githubusercontent.com/assets/6625777/5703581/57a9bd4c-9a60-11e4-9573-a12acfe49ee7.png)


Unless you can find what actully caused this and how to reproduce, i think this is invalid

**Comment by ParaSpider** [comment]
I didn't burn down anything, however I suppose if it can't be reproduced then I'll close it.

**Comment by Ipskie** [comment]
I'm willing to guess that what's happening here is that due to fire tracking (checking which player ignited the fire and crediting fire spread accordingly) is causing PGM to think that you're trying to place blocks in places you can't when the fire tries to spread there. In which case this is a PGM bug

**Comment by ParaSpider** [comment]
It was stated that I never lit a fire however.

**Comment by EyQu** [comment]
You can can find any other way to reproduce this, then say
