### ISSUE TITLE
Allow placing/breaking of blocks in Deepwind wool room

### ISSUE THREAD

**Issue by Cevans98** [OvercastNetwork/Issues#1504]
I don't see why it isin't allowed. In every scrimmage server dl of the map, and even the tourney edition, you could place blocks inside the region.

A) If you are an attacker, the only way out is by breaking through the wall and even at that, its very easy to replace blocks in the wall. Add in multiple (painlooping, although for a good cause) defenders and it's nigh on impossible to get out. Being able to get above them and use the height to your advantage would be a good thing.

B) As a defender you can't block off the easy, and relatively op, sidejump. Unless the wall is 4-5 thick , it can still be sidejumped. 

It would balance out for both parties and make gameplay more enjoyable.

**Comment by Dinner1111** [comment]
This repo is for technical issues only; not for map suggestions. Feel free to [make a forum post](https://oc.tc/forums/53f7a8d0d7c83698b7b67498) on our website to discuss the topic, and if the author of the map approves they can post a request to update the map here.
