### ISSUE TITLE
Ratings are displayed with stars but are not displayed on the map page

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1508]
Example map: SamplesDTM

In the small "window" on the map list you can see the ratings by mousing over the stars. On the map page the ratings say "Not enough player ratings"

![](http://i.imgur.com/uojmtIT.png?1)

![](http://i.gyazo.com/ac2777f76631c234a4ec39382eef1098.png)

**Comment by nixter1029** [comment]
Probably because the rating showed on the maps page is the latest version ...

**Comment by matic0basle** [comment]
Closing at it fixed now. Looks like it just needed some time to update maybe?
