### ISSUE TITLE
Teams and objective don't display if the map has them as <include> on the map page

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1511]
Example map: Retro FFA

The map uses the <include> module to add teams and objective to the map from the united gs ffa xml file. Because of that teams and objective are not displayed on the map page.

![](http://i.gyazo.com/b0652628e57f84287b49157fb232d43a.png)

![](http://i.gyazo.com/b1bd9ac514f25c2f7af55b1cd97e7649.png)

From the include file:
![](http://i.gyazo.com/835feb9de79714558af72fdc5a20c6b2.png)

**Comment by Electroid** [comment]
This was a hacky solution, it's gone now we ffa.
