### ISSUE TITLE
GS: Retro (Void teleport)

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1512]
I was a Leprechaun and was playing on the map Retro (not the FFA) and when I jumped up on top of the pipe where we spawn, I telported directly below it into the void and died.

**Comment by matic0basle** [comment]
This is not a bug. Its there to stop players from jumping onto the big blocks. The map will be updated soon so you don't spawn in the tubes but right now its intended.

**Comment by ParaSpider** [comment]
I don't think it's fair that if you go somewhere unintended, it takes you straight into the void, but whatever. Could teleport them down, that's more sensible instead of causing deaths that several players have had and complained about.

**Comment by ItsMiiOlly** [comment]
I'm not sure why it teleports you to the void. It's a deny-enter region.
