### ISSUE TITLE
GS Maps Don't Show Ratings

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#1514]
### The Issue:

Maps page does not generate ratings for Ghost Squadron maps.

### Steps to reproduce:

- Go to: https://oc.tc/maps/gamemode/gs
- Look at any Ghost Squadron Map

**Comment by EyQu** [comment]
http://puu.sh/eaAtp/fcbe5d856b.png

There isn't enough for a solid average

**Comment by mrapple** [comment]
Correct
