### ISSUE TITLE
Podcast not downloading

### ISSUE THREAD

**Issue by bleongcw** [OvercastNetwork/Issues#1516]
The issue: Users subscribing to the Analyse Asia Podcast are unable to download the episodes from the feed. I tested it on my own iPhone 6+ with the latest iOS version. Here is my process to trace the bug: I have downloaded the Overcast App from iTunes and did a search for Analyse Asia. Then I tried to download the episodes and it is just hung there. I have attached a screenshot here.

Original feed of the podcast: http://analyse.asia/category/podcast/feed
Feedburner of the podcast: https://feeds.feedburner.com/analyseasia

Here are some potential hypotheses to why the bug may happen:
1. The audio files of the podcast are stored on Internet.org archive and not on any hosting service.
2. The posts on the podcast on Wordpress are relying on the powerpress plugin to deliver. 

Hope that you can resolve the issue. Thank you. 

![b6rhp2bcyaetp7i](https://cloud.githubusercontent.com/assets/457370/5639008/666c017e-964a-11e4-93b9-a5e7463ec3e3.jpg)

**Comment by Ipskie** [comment]
Why is this relevan to OCN?

**Comment by Electroid** [comment]
Wrong issue tracker?

**Comment by khazhyk** [comment]
yay spambots

**Comment by bleongcw** [comment]
@Ipskie Yes, it's on the overcast app.

**Comment by itsmartin** [comment]
This is a different Overcast. A Minecraft server rather than a podcast app. Hope you get it fixed though :)

**Comment by bleongcw** [comment]
My apologies, got it wrong.
Bernard
