### ISSUE TITLE
you always get an sword and a leather cap when you get a kill on Remnant Souls

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1520]
![2015-01-10_13 07 40](https://cloud.githubusercontent.com/assets/8422075/5693712/66d0d15a-98f0-11e4-8844-0421fd46ae5f.png)

**Comment by CoWinkKeyDinkInc** [comment]
The sword and helmet should be added to a kill reward kit

**Comment by EyQu** [comment]
https://github.com/OvercastNetwork/Maps/commit/6120aae
