### ISSUE TITLE
Items Dropping as an Observer

### ISSUE THREAD

**Issue by HerobrineKillerz** [OvercastNetwork/Issues#1522]
When the match starts, sometimes the items will drop from the observers, and the players will be able to pick them up. I picked a few up while playing earlier
http://imgur.com/a/A8RYR

**Comment by mrapple** [comment]
We've only ever seen this in very rare, random cases in tournament matches. Did you just notice this happening more often recently? We have no way to reproduce this bug currently.

**Comment by HerobrineKillerz** [comment]
It has happened a few times in the past few days. Usually the helmet might just drop or a book, but it's been happening a lot more lately.

**Comment by twizmwazin** [comment]
I just had this happen on a match of superprism
http://i.imgur.com/hBlhsLx.png

**Comment by HerobrineKillerz** [comment]
A solution to this may be for the observers that once they join their inventory gets cleared? Not sure how easy/hard this would be to code, but could work.

**Comment by mrapple** [comment]
Sorry, but you have no clue how our internals work. Guessing at fixes doesn't help anything.

**Comment by rywarsaw** [comment]
Can confirm, this happened again on Rage just a few minutes ago. Exactly like the image @twizmwazin posted.

**Comment by twizmwazin** [comment]
I don't know if more pictures help, but [here] (http://imgur.com/EAWekVY,EP43VIJ,KBXtLai#0) are a few more from a match of Tebulas. The issue happens quite often.

**Comment by mrapple** [comment]
We have a fix in code review

**Comment by mrapple** [comment]
Just deployed a fix, if you guys could see if this still happens over the next few days that would be appreciated.

**Comment by twizmwazin** [comment]
@mrapple Thanks, will do.

**Comment by rywarsaw** [comment]
Thanks @mrapple

**Comment by mrapple** [comment]
```[08:42:47] Pugsley_:	Off topic but I thought they fixed the observers dropping their items
[08:42:56] Pugsley_:	in-game, because it just happened
```

**Comment by mrapple** [comment]
Does anyone know if this only happens at match start or if it can happen in the middle of a match?

**Comment by yoyopower** [comment]
@mrapple I just had this happen to me in a ghost squadron game, might be related to this. http://i.imgur.com/DBUPOVS.png

**Comment by rywarsaw** [comment]
@yoyopower That is a client glitch.

**Comment by rywarsaw** [comment]
@mrapple I don't know if this has anything to do with it, but right before someone leaves you can see their player. When this happens, sometimes the player items drop. It happens when a player disconnects, not when the match starts.

**Comment by Electroid** [comment]
This bug seems to be gone.

**Comment by Superjd10** [comment]
The bug itself isn't gone, it's just client-sided. 1 hour ago, I joined a RFV2 match using the Team Picket, it was in my head, when I tried to "shift+click" (send to inventory) it, the item disappear.

**Comment by Electroid** [comment]
That's a separate issue from items dropping. I'll create an issue.
