### ISSUE TITLE
Moderators on Resident Mapmaker servers have their star

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1524]
![](http://i.imgur.com/GtVia5R.jpg?1)

**Comment by Ipskie** [comment]
I'm almost certain this is intentional, also can confirm this is on all mapdev servers (checked on Elliott's)

**Comment by Superjd10** [comment]
In some way the friend list is connected too, I have seen my friends with italics in the tab list and I wasn't able to do /fr (unknown command)

**Comment by mrapple** [comment]
Intentional
