### ISSUE TITLE
"/seen or /find" isn't working sometimes.

### ISSUE THREAD

**Issue by Brekou** [OvercastNetwork/Issues#1525]
![2015-01-11_15 55 51](https://cloud.githubusercontent.com/assets/9677703/5695576/9c8e0860-99ab-11e4-8ac6-155339daf47c.png)
![2015-01-11_16 04 34](https://cloud.githubusercontent.com/assets/9677703/5695577/9c90cc3a-99ab-11e4-9b94-8bd2b3d5460a.png)

As you can see it works with other players:
![2015-01-11_16 05 25](https://cloud.githubusercontent.com/assets/9677703/5695578/ac81a7cc-99ab-11e4-88e3-dfb0c94caef2.png)

**Comment by Brekou** [comment]
I've been testing it and works when you try to find a friend, if the person isn't in your friendlist, or you try to find yourself, it doesn't work.

- Friends:
![2015-01-11_17 14 14](https://cloud.githubusercontent.com/assets/9677703/5695860/9c43596e-99b5-11e4-80f2-3db59c1838de.png)
![2015-01-11_17 14 25](https://cloud.githubusercontent.com/assets/9677703/5695862/a06547f0-99b5-11e4-89e9-8d74725bb0b0.

- Not friends: 
![2015-01-11_17 14 34](https://cloud.githubusercontent.com/assets/9677703/5695865/ad049600-99b5-11e4-8dab-b005e34b68ad.png)
![2015-01-11_17 14 45](https://cloud.githubusercontent.com/assets/9677703/5695866/ad0581e6-99b5-11e4-9ba1-6c2cef98b8b4.png)

**Comment by Superjd10** [comment]
It's EU? Maybe it's something related to Datacenters and the way they share the database.

**Comment by CoWinkKeyDinkInc** [comment]
This happens on US as well.

**Comment by karst** [comment]
Still occuring: 
![cb93a9cac42f493572fde7704fffb4c2](https://cloud.githubusercontent.com/assets/1516893/5707177/ef9937f6-9a86-11e4-9a76-e8069e222fb2.png)

**Comment by jedediah** [comment]
Anybody know how to reproduce this? I'm trying friends and non-friends and I can't get it to happen.

**Comment by jedediah** [comment]
If you see it happen, post the player, server, and the exact time here, as precisely as you can.

**Comment by nixter1029** [comment]
17:05:08 EST - Lobby 1 EU - Myself
17:06:23 EST - Lobby 3 US - Myself

cc @jedediah

**Comment by Ipskie** [comment]
14 Jan 2015 7:38am SGT (GMT+8) Primed - Myself - 3 days ago
14 Jan 2015 7:39am SGT (GMT+8) Primed - xI_LIKE_A_PIGx - Online
14 Jan 2015 7:40am SGT (GMT+8) Primed - Java SDK - 3 days ago
@nixter1029 You got those logs from last year?

**Comment by Kenner390** [comment]
This happened to me too. It occurs in EU and US servers as it was already said above

**Comment by Kenner390** [comment]
This happened to me too. It occurs in EU and US servers as it was already said above

**Comment by ryush00** [comment]
Always it is not working correctly.

**Comment by Brekou** [comment]
It seems to be fixed, thanks.
