### ISSUE TITLE
[BUG??] TM Is Crazy...

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1527]
So, hi,

I just joined today the TM.oc.tc lobby and I suddenli appeart a buch of blocks away and flipping up and down gliched and buged. I tried to re"enter" the game but nothing changes, I made some screenshots...

I couldn move or select any item, neither change the lobby!

http://i.imgur.com/paKD31f.png

http://i.imgur.com/NuEZh3h.png

:package:

**Comment by Tapetepato** [comment]
https://github.com/OvercastNetwork/Issues/issues/1462
