### ISSUE TITLE
Admin not on /staff list when not nicked

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1531]
Server: Capture1 US
Time: 2:50 PM GMT+1 / 14:50 GMT+1 
17th January 2015

![](http://i.imgur.com/GqGp1I4.png)

**Comment by Superjd10** [comment]
When I reported a similar issue @mrapple told me that it's because they have a nick set for the next time they join the server.

**Comment by itsmartin** [comment]
Guessing this is the same issue as #1545?

**Comment by matic0basle** [comment]
@itsmartin You can see it showed lord_creeper01 in the chat.

**Comment by Electroid** [comment]
This isn't a bug anymore
