### ISSUE TITLE
Theres no height limit on Midnight Train

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1532]
This causes some crazy skybridge and giant water pools dropping from y 256 that makes everyone that gets near get 0 fps.

**Comment by SuicuneScale** [comment]
I believe this is intended.

**Comment by Brottweiler** [comment]
If this wasn't intended it would have been fixed already I'm sure.

>giant water pools dropping from y 256 that makes everyone that gets near get 0 fps.
Update to 1.8, don't use 1.7 if you dont want lag.

**Comment by firstvirus92** [comment]
Giant water walls can be an FPS killer, but that only happens when the enemies create extreme amounts of flowing water at the same time. Not worth fixing imo since it's almost impossible to get it to a game-breaking stage.

**Comment by Brottweiler** [comment]
@firstvirus92 it's a 1.7 bug, fixed in 1.8.

**Comment by firstvirus92** [comment]
@Brottweiler I know (because you already mentioned it, obviously), I just wanted to note that players with obsolete minecraft versions will most likely not be affected by this in a game-breaking way.

**Comment by Dinner1111** [comment]
twas intended

**Comment by Ipskie** [comment]
@Dinner1111 why though? It seems only screwy gameplay could come out of it, and few other maps neglect to have a height limit

**Comment by Dinner1111** [comment]
What's screwy about building bridges in the sky to get to the objective? Maps these days don't like that but Midnight Train was built when large void gaps and skybridges were cool

**Comment by Tapetepato** [comment]
well if its intended...
