### ISSUE TITLE
Revenge TE Uneven Stacks of Defense Items

### ISSUE THREAD

**Issue by Shab1** [OvercastNetwork/Issues#1533]
Chests with defense Items, there is 3 half stacks of crafting tables, 1 full stack
![2015-01-17_22 05 17](https://cloud.githubusercontent.com/assets/10359235/5790541/31b97e36-9e95-11e4-843a-ffe66da4135f.png)   
![2015-01-17_22 07 33](https://cloud.githubusercontent.com/assets/10359235/5790542/42cb0f64-9e95-11e4-86ad-cfba5d95caa1.png)

**Comment by Ipskie** [comment]
Fixed, please close. Thanks for the heads up!

**Comment by Electroid** [comment]
Only make issues for maps on production (maps played on public servers, no map dev/resident servers)
