### ISSUE TITLE
NCP spams and wont let me walk on random times

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1537]
This is an example that just happened on tetrad, for no reason, it just wouldnt let me move
![2015-01-20_18 30 37](https://cloud.githubusercontent.com/assets/8422075/5829086/8b456232-a0d2-11e4-8a97-f58576d4ed97.png)
It also happens a lot when you place a tnt near you on Lost World CTP or Dust and attemp to use it as icarus. You wont go further than 1 block before it spams you and teleports you back.

**Comment by Ipskie** [comment]
NCP is pretty hyperactive on certain servers or maps, but I wouldn't label this a bug, more of a general problem with NCP

**Comment by mrapple** [comment]
This is random client/server desync that we can't really fix.
