### ISSUE TITLE
Incorrect regions on Belcrest near wool

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1538]
I was defending today on the Blue Team, the Yellow Wool, and i started getting this when placing blocks right next to the wall: "You may not intercat with the enemy wool room! and i wasnt interacting with it
![2015-01-20_17 47 17](https://cloud.githubusercontent.com/assets/8422075/5829114/dc79fcbc-a0d2-11e4-9965-a3da6696f57b.png)
![2015-01-20_17 46 59](https://cloud.githubusercontent.com/assets/8422075/5829117/ded67ce2-a0d2-11e4-8377-865fc2ecdbf9.png)
![2015-01-20_17 46 38](https://cloud.githubusercontent.com/assets/8422075/5829118/e02d918e-a0d2-11e4-811a-f267789046f6.png)

**Comment by Ipskie** [comment]
Not a wrong message, rather a wrong region
