### ISSUE TITLE
Some Player Heads disappear on player's profiles

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1539]
On some of the profiles from players, if not on every profile, when you have linked other players (e.g. showing your team for tournaments) their heads are missing. It just leaves the little question-mark box indicating it is in error, even though the links are usually correct.

Examples:
http://i.imgur.com/JlPZiwv.png
http://i.imgur.com/KVmXCyu.png

**Comment by Brottweiler** [comment]
Tried rightclicking and selecting "view image in new tab" or similar? What happens then?

**Comment by Brottweiler** [comment]
Actually, maybe try using this instead: https://avatar.oc.tc/Guicotsch/16@2x.png

**Comment by mrapple** [comment]
Our avatar server was never intended for public use and we aren't going to provide support for incorrect usage ;)
