### ISSUE TITLE
You can create a team called 'new'

### ISSUE THREAD

**Issue by Akorlith** [OvercastNetwork/Issues#1542]
The team URL which is of the form `oc.tc/teams/team` clashes with the create team page `oc.tc/teams/new` if the team name is literally 'new'.

**Comment by Ipskie** [comment]
I can confirm this, and as a result now cannot leave said team. Drat

**Comment by Akorlith** [comment]
@Ipskie You can use `oc.tc/teams/new/edit` to edit your team name, then leave it.

**Comment by jedediah** [comment]
fixed
