### ISSUE TITLE
/staff command not showing staff correctly 

### ISSUE THREAD

**Issue by vobaseball12** [OvercastNetwork/Issues#1545]
The /staff command is not showing the right staff on, and where they are at.

**Comment by jacobbearden** [comment]
![Looks Fine](http://i.imgur.com/di7bCVm.png)

Looks fine to me

**Comment by mrapple** [comment]
/staff doesn't show staff on the server you're currently on

**Comment by Ipskie** [comment]
new miner isn't online but is still showing up on the list. I checked TM lobby 3

**Comment by CaptainElliott** [comment]
All of the staff listen in that screenshot are still showing up whilst not being on any server 

![](http://i.imgur.com/Hi6VLqE.png)

**Comment by vobaseball12** [comment]
Yes, that's what I meant, what Elliott said. I'm sorry I didn't take a screenshot.

**Comment by Brekou** [comment]
/staff is not working on EU. It doesn't show staff members. I took these screenshots right now:
> US:

![2015-01-26_22 22 12](https://cloud.githubusercontent.com/assets/9677703/5908721/5715fef4-a5aa-11e4-83a3-276d4eb1c031.png)


> EU:
![2015-01-26_22 22 41](https://cloud.githubusercontent.com/assets/9677703/5908684/0eaac60e-a5aa-11e4-8742-11363af3617e.png)

**Comment by Electroid** [comment]
Does now.
