### ISSUE TITLE
/servers command not listing servers correctly 

### ISSUE THREAD

**Issue by pelpelajax** [OvercastNetwork/Issues#1546]
![screen shot 2015-01-25 at 08 53 13](https://cloud.githubusercontent.com/assets/7715330/5890825/dde0a312-a46f-11e4-9f3c-d186fe021e44.png)
![screen shot 2015-01-25 at 08 52 50](https://cloud.githubusercontent.com/assets/7715330/5890826/e1d80348-a46f-11e4-8119-fba20881788b.png)

As you can see, the servers are listed in the wrong order

**Comment by Electroid** [comment]
It lists by amount of players per server now.
