### ISSUE TITLE
Tags not showing up in sidebar

### ISSUE THREAD

**Issue by HerobrineKillerz** [OvercastNetwork/Issues#1550]
Sometimes the tags won't work for referees, it'll tag them as a normal player.
http://prntscr.com/5wva9n
notice DoomRobotBoy nor NeWminEr37 dont have referee colors

**Comment by pelpelajax** [comment]
DoomRobotBoy's tag got removed because he is playing this tourney. Same for picajoluna who is also playing.

**Comment by Brottweiler** [comment]
@pelpelajax Since DoomRobot is between two refs, it looks like he's still a ref, he just don't have the badge? Otherwise he would be listed after the refs.

**Comment by matic0basle** [comment]
@Brottweiler If he is playing they probably removed him from the staff page, removed  badge, removed color of the name and removed in-game permissions. Though he probably still has the forum permissions which is why hes being listed with other referees.

**Comment by Brottweiler** [comment]
@matic0basle seems logical.

**Comment by pelpelajax** [comment]
@Brottweiler What @matic0basle said is correct. Regarding NeWminEr37, I am pretty sure he is a live streamer. However I could be wrong.
