### ISSUE TITLE
[Bug] Problem at deleting friends

### ISSUE THREAD

**Issue by goelcomquell** [OvercastNetwork/Issues#1551]
I was trying to delete one of my friends and it happened.

<img src="http://i.gyazo.com/8c8d3782f87c47736fa8fac2c3afe429.gif">

**Comment by Kitatist** [comment]
I hope this works,

**Comment by matic0basle** [comment]
Can confirm that it doesn't work from there though if you go on the persons profile and delete them from there it will work.

**Comment by Brottweiler** [comment]
@Kitatist Please stop commenting useless posts on these github issues, you've done it multiple times I've seen.

**Comment by Kitatist** [comment]
In fackt you DONT KNOW that I was SKYPING with GOELLCOMQUELL telling him
HOW TO DO THE POST, helping him at registration and guiding him trought
GITHUB.
If you WANT evidences ASK HIM!
El 25/01/2015 19:42, "Christoffer Tibell" <notifications@github.com>
escribió:
>
> @Kitatist Please stop commenting useless posts on these github issues,
you've done it multiple times I've seen.

**Comment by CaptainElliott** [comment]
@Kitatist if you were skyping with him why could you not say that to him in the call, and please don't use caps.

A lot of us get email notifications and we want to keep issue comments relevant to the issue, makes life easier for us

**Comment by Electroid** [comment]
This was fixed.
