### ISSUE TITLE
Void region error on Deadwater (GS)

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1552]
http://imgur.com/a/4xkfL

Upon falling into the void, you are stuck and the match is endless unless you leave it. The map also (worth mentioning) has the leprechaun/water glitch, and a lot of the map is water, so it should be kept out for now.

**Comment by CaptainElliott** [comment]
Are you stuck falling or are you stuck still?

**Comment by ParaSpider** [comment]
I'm stuck still.

**Comment by Electroid** [comment]
Fixed.

**Comment by CaptainElliott** [comment]
I reckon its because of the playable region stopping you entering below y=0, don't have time to check or fix until tomorron
