### ISSUE TITLE
Compass not working on practice servers.

### ISSUE THREAD

**Issue by manucide** [OvercastNetwork/Issues#1553]
You cannot use the compass on the practice servers, not sure if this happens on mapdev servers too.
It doesnt work even if you have the op.

https://www.youtube.com/watch?v=1Nu3Zc4aK0o

**Comment by CaptainElliott** [comment]
World edit permissions are disabled on practice servers no matter if you are op.
This is intentional.

**Comment by CaptainElliott** [comment]
Uh actually you should have permission to use the compass in observers

**Comment by Superjd10** [comment]
The compass is a world edit tool and I think there isn't world edit on the servers (not sure if the plugin is installed or not. I haven't checked)

**Comment by AngelCasillas01** [comment]
@Superjd10 Is installed but you dont have the permissions, no matter you are an opped player, however, we should have the permissions when we are on observers team

**Comment by ghost** [comment]
Just tested, fixed
