### ISSUE TITLE
Names colors persist after badge expires

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1554]
![screen shot 2015-01-26 at 8 57 43 pm](https://cloud.githubusercontent.com/assets/7846005/5899978/2c1185cc-a59e-11e4-899a-bf14990ebf5f.png)
![screen shot 2015-01-26 at 8 57 57 pm](https://cloud.githubusercontent.com/assets/7846005/5899976/2c0c465c-a59e-11e4-9baf-1076979b1e86.png)
![screen shot 2015-01-26 at 8 57 39 pm](https://cloud.githubusercontent.com/assets/7846005/5899977/2c10eb8a-a59e-11e4-899d-b6acd96e2d3c.png)
![screen shot 2015-01-26 at 8 59 43 pm](https://cloud.githubusercontent.com/assets/7846005/5899990/48a21a08-a59e-11e4-8a90-8b0201fca6b1.png)

**Comment by itsmartin** [comment]
Looks like this is just caching, the colours update when the player's cache is cleared.

**Comment by Brottweiler** [comment]
Probably, the cache isn't cleared automatically when the rank is removed. Unsure if it should be added or not, though.

**Comment by rmsy** [comment]
A solution would be to calculate the user's name colour each time instead of caching it (the groups are already cached, with expiry time).

**Comment by Electroid** [comment]
This was fixed some time ago.
