### ISSUE TITLE
How-To Guide Book Minor Issues

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1555]
A couple issues that I found. Even with them being minor issues I still decided to report them.

Page 6/15
The description for the /rate command cuts off making it only say "/rate (1-5) ra"

Page 8/15
The "Destroy the Monument" text has different spacing in front. A fix would be remove one space before other gamemodes.

? Page 11/15
Premium Users are ordered from Optio to Dux (lowest to highest) while staff is ordered from Admin to Junior Mod (highest to lowest)
 - Not really a mistake just would be nice to see a different order as stars in tab also follow from Dux to Optio

Page 12/15
"socalize with friends"
Should probably be "socialize with friends".

SUG - Add a page for Ranks (2) and include some other stars under "Other" that people might see in-game such as Map Maker, Internet Famous

Like I said these are MINOR issues but should still be fixed when you have the time / work on the guide book.

**Comment by CaptainElliott** [comment]
>The description for the /rate command cuts off making it only say "/rate (1-5) ra" 

The rate description looks fine to me
![](http://i.imgur.com/IAQV8lW.png)

**Comment by matic0basle** [comment]
@CaptainElliott It depends on the map I think. I checked some maps and they were fine but some were not. I think the map that this happened on was Jungle Beat or PixelMix not sure.
