### ISSUE TITLE
Interitus TE - Texture

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1557]
Leaves in the chests display the missing texture. Chests are located in the side towers where the diamonds are.

**Comment by CaptainElliott** [comment]
What minecraft version are you using? 1.7 clients have no problems

**Comment by matic0basle** [comment]
@CaptainElliott 1.8.1

**Comment by Ipskie** [comment]
Similar problems have occured before, it's due to a data value IIRC, something similar to #1253

**Comment by matic0basle** [comment]
@Ipskie Probably. The ID is 18/4 I believe just for anyone thats curious.

**Comment by Brettogden** [comment]
Issue #1284 covers this topic so I'm gonna close this one.
