### ISSUE TITLE
Pharaoh's Catacombs - Unbalanced spawn portals

### ISSUE THREAD

**Issue by Zozoo1** [OvercastNetwork/Issues#1561]
Just letting you know that the red team have a slight advantage over the blue team, because

red team portal region gives instant heal potions effect while blue team portal region don't.

You should give instant health while in both portal, so it is easier to get back in the fights.

**Comment by thestrangeboy1** [comment]
I have tested this on my server and each team's portals give off the same exact potion effect with the same amount of time. The XML shows it works perfectly as well.

    <apply kit="strength">
        <cuboid min="-1,86,-13" max="2,89,-12"/>
        <cuboid min="-1,86,11" max="2,89,12"/>
    </apply>
    <apply kit="regen" enter="red-only">
        <cuboid min="10,64,-21" max="13,67,-18"/>
    </apply>
    <apply kit="regen" enter="blue-only">
        <cuboid min="8,64,24" max="11,67,26"/>
    </apply>

**Comment by Zozoo1** [comment]
First, sorry to re-open this issue, but after further testing with a friend, I have some videos to
explain the issue better :

When entering the red portal : http://youtu.be/sG5MjrLHDgI

When entering the blue portal : http://youtu.be/rv6_p5VOj_g

(these 2 clips were taken yesterday on eu.oc.tc)

You can see that the blue player doesn't actually get the regeneration effect, while the red one does.

From the XML, 

-<apply kit="strength">
<cuboid max="2,89,-12" min="-1,86,-13"/>
<cuboid max="2,89,12" min="-1,86,11"/>
</apply>

-<apply enter="red-only" kit="regen">
<cuboid max="13,67,-18" min="10,64,-21"/>
</apply>

-<apply enter="blue-only" kit="regen">
<cuboid max="11,67,26" min="8,64,24"/>  <--------
</apply>
</regions>

-<portals>

-<portal z="@28" y="@64" x="@9.5">
<cuboid max="2,89,12" min="-1,86,11"/>
</portal>

-<portal z="@5.5" y="@85" x="@0.5">
<cuboid max="11,67,26" min="8,64,24"/>  <----------
</portal>


-<portal z="@-19.5" y="@64" x="@14" yaw="90">
<cuboid max="2,89,-12" min="-1,86,-13"/>
</portal>

-<portal z="@-6.5" y="@85" x="@0.5" yaw="-90">
<cuboid max="12,67,-18" min="9,64,-21"/>
</portal>
</portals>

I don't know much about XML, but if I understand correctly, I think that the regeneration region is bigger than the teleporter region on the red side, which allows to stand on the last block in the water area to get the regen effect while not being teleported, but on the blue side, this can't be done as the regeneration region is too "short", and the same as the teleporter region.

Sorry for any English mistakes, please feel free to ask for any clarification if needed.

Thanks
