### ISSUE TITLE
You can bridge on the sides of Infernal Shadow far outside the map

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1564]
![2015-01-28_16 43 41](https://cloud.githubusercontent.com/assets/8422075/5948843/f03b6b1e-a70d-11e4-8bce-4e78a6480ace.png)
![2015-01-28_16 44 53](https://cloud.githubusercontent.com/assets/8422075/5948844/f03c6fd2-a70d-11e4-8a01-62a8d019866b.png)

**Comment by HerobrineKillerz** [comment]
had this happen: https://oc.tc/matches/54cfd331c8f265eff86143c1
http://imgur.com/0B1vA3n
http://imgur.com/wQc08fz
