### ISSUE TITLE
You can create a team with the old long threads

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1571]
Before the oc.tc/teams/team-name thing, there were these long threads see, and these long threads still direct you to the team roster. You can however, create a team with the long name. Hijinks ensue

e.g. https://oc.tc/Qauz

See where that dopamine link on his profile (the one in the about me section, not the team link)

**Comment by CaptainElliott** [comment]
I will label this as a bug, but what team would want to have a huge alphanumeric string as their name. In addition, I don't see where this causes a problem apart from when someone is using the deprecated links.

Best solution remove support for the long alphanumeric string/hash.

**Comment by orky48** [comment]
@CaptainElliott I wouldn't count this as a bug he is using a old link which is now going to a new team. Plus there are teams with long names.

**Comment by CaptainElliott** [comment]
considering it, I agree with @orky48, its not a bug
