### ISSUE TITLE
"Alerts" shows each person who has responded instead of "X and Y more..."

### ISSUE THREAD

**Issue by Edde** [OvercastNetwork/Issues#1575]
Basically, this have happened me a few times this morning, and I do not know what causes it.

http://i.imgur.com/38k7R0D.png
http://i.imgur.com/wSC1sFy.png

These are all from the same thread and all disappear when I view it.

**Comment by Edde** [comment]
Also, I see now that clicking at a specific alert takes you to the post.

**Comment by Brottweiler** [comment]
Still seems to be pretty spammy...

**Comment by nixter1029** [comment]
Did this start breaking early this morning after @jedediah's fixes for alerts?

**Comment by Edde** [comment]
Most likely, as it did not occur yesterday

**Comment by jedediah** [comment]
fixed
