### ISSUE TITLE
Different colour leaves on Khaba

### ISSUE THREAD

**Issue by Craftia** [OvercastNetwork/Issues#1577]
I think there might be some sort of issue with the biomes on Khaba, because a part of the red base has much greener leaves than blue's side... Also, i dont know how to add labels. So yeah

**Comment by Craftia** [comment]
I'm sorry, but this is really annoying my OCD. And this shouldn't be like this. Hopefully this well get fixed!

**Comment by Brottweiler** [comment]
First of all, this is an extremely minor bug. It doesn't affect gameplay in the slightest.

Second, you don't have OCD if you're not diagnosed with it (which I don't know if you are or not, but from the sound of it, you seem to think OCD is just getting annoyed by unsymmetry which is false).

**Comment by Ipskie** [comment]
Sounds like a biome issue, but as brott said incredibly minor

**Comment by Electroid** [comment]
Minor, it's fine.
