### ISSUE TITLE
Some users have black names

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1578]
![screen shot 2015-02-02 at 6 10 19 pm](https://cloud.githubusercontent.com/assets/7846005/5998839/d079fdac-ab06-11e4-9d40-6d1e51398619.png)
![screen shot 2015-02-02 at 6 10 27 pm](https://cloud.githubusercontent.com/assets/7846005/5998838/d0793b60-ab06-11e4-9680-c6ff48a34c47.png)

**Comment by Brottweiler** [comment]
It's just cache. I cleared his cache manually. It will clear automatically sooner or later.
