### ISSUE TITLE
Wrong username displaying and linking to 404 with name changes on /matches

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1585]
On a match page the players names don't change to the new names.

Example:
https://oc.tc/matches/5497fc4ac8f2112fa23337cd
BrettOgden played in the match but currently his name is Breferee. The match still shows BrettOgden and clicking on it will lead to a 404 page because there is no BrettOgden since his name is Breferee.

![](http://i.gyazo.com/7032865bd48c11ccf38619357ac3fd51.png)

![](http://i.gyazo.com/794b515f314ee6983a76ed6686593d8f.png)

![](http://i.gyazo.com/db18ee3159d413cbe1ae515856c6777f.png)

While this might not be a bug since he was named BrettOgden at that time, it still should be considered to be changed otherwise a lot of these will lead to 404 pages when name changes hit.

Another example:
https://oc.tc/matches/516f78840cf2af4800222828
Look for last_username or now called LastUsername

*Off Topic* The images on /matches websites don't have borders around them like the maps pages.

**Comment by Superjd10** [comment]
Fixed in OvercastNetwork/Web@75d990 (I know I don't have access or permissions but anyways)
