### ISSUE TITLE
Adding a user as a friend causes the page to explode (Error 500)

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1586]
![](http://i.gyazo.com/063e18688e1d6d6c9341f6d20ba809f0.gif)

Tested adding these players to test this:
MaticGaming
R
HappyBDayApple
Anxuiz
hdt80bro

**Comment by themtz** [comment]
Same thing happens at me too.

**Comment by HerobrineKillerz** [comment]
Doesn't happen for me. Tried on R, HPlayz, and BuckStick.
