### ISSUE TITLE
avatar.oc.tc goes to the normal website but without content

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1587]
Searching avatar.oc.tc brought be to the Overcast Network website but its an outdated version.

The title is "Overcast Network - 404"

![](http://i.gyazo.com/f1f5570992f1a434241842e6fdc8da07.png)

In the footer you can see "Copyright 2014" while the site has 2015.
Clicking any link in the footer leads you to a 404 page because it goes to avatar.oc.tc. Example:"https://avatar.oc.tc/terms".

![](http://i.gyazo.com/df7f70e2e72409ac7378ddd4b49fab98.png)

There is also no "page exploded" image explaining what went wrong except the title and the Overcast Network logo does not display. The text is there but since its in white you can't see it without a background image. Draging over it reveals the text.

![](http://i.gyazo.com/99d575eb7a287fd34d52b5664bd6022b.png)

It also displays the 404 site if there is no user found with that name
Example:
![](http://i.gyazo.com/7c77718267b88a3d10f3943bedb3ef8a.png)

**Comment by ghost** [comment]
Seems to be fixed http://prntscr.com/8sii73 & http://prntscr.com/8sii9o
