### ISSUE TITLE
Revisions do not show new names

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1588]
Revisions pages show old usernames and lead to 404 pages.

Example:
last_username / LastUsername

![](http://i.gyazo.com/620de42901462ddcc2648b1f8f859414.png)

![](http://i.gyazo.com/0cd4fa22432579bd12d6cdd112da2403.png)

**Comment by itsmartin** [comment]
Now fixed.

**Comment by Superjd10** [comment]
It isn't working as indeed: https://oc.tc/revisions/maps 

![image](https://cloud.githubusercontent.com/assets/1649155/6048750/98cbc96e-ac80-11e4-9b72-7942201f721b.png)

(Lord_creeper01 isn't linked as he changed his name, I comment here because it's somehow related)

**Comment by matic0basle** [comment]
@Superjd10 He wasn't linked before. Look at ItsMiiOlly. Hes linked and his name changed. Lord just isn't added on the "list of added people" (i dont know what they actually call it)

**Comment by itsmartin** [comment]
See #1596 for the remaining issues.
