### ISSUE TITLE
Some players don't have a stats page

### ISSUE THREAD

**Issue by pelpelajax** [OvercastNetwork/Issues#1594]
![screen shot 2015-02-03 at 21 19 45](https://cloud.githubusercontent.com/assets/7715330/6028508/68d02e4e-abea-11e4-8500-6a80ec4e54e5.png)
https://oc.tc/Brooklyn_de_BBA

**Comment by jolteony** [comment]
There's a page there. It's possible when you took this the system didnt have time to create a page yet.

**Comment by mrapple** [comment]
There wasn't before. This should be fixed with some pending changes.
