### ISSUE TITLE
Incorrect capitalization of former names

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1597]
https://oc.tc/Santilam

He changed the lowercase s to uppercase, but the old name shows it as uppercase

**Comment by Brottweiler** [comment]
This was fixed earlier but apparently it still happens...

**Comment by matic0basle** [comment]
Avaleer changed from uppercase to lowercase and it was fine.
https://oc.tc/avaleer

**Comment by mrapple** [comment]
New users that change their case shouldn't have an issue. If you changed your username case before yesterday, please email support@oc.tc and we can correct your username history.
