### ISSUE TITLE
Skin head color is shown wrong on the forums

### ISSUE THREAD

**Issue by Edde** [OvercastNetwork/Issues#1598]
I just realized that a completely black color on your skin is seen as white/transparent, and this have been seen before. So far I've only seen it occur on the forums.
http://i.imgur.com/Gsxyrfc.png
http://i.imgur.com/ZhCR5hX.png
http://i.imgur.com/IwX1pO8.png

I do not believe this have to do with the name change since it have occurred for other players earlier. Someone could possibly confirm this on other places too, such as you friends list.

**Comment by matic0basle** [comment]
https://github.com/OvercastNetwork/Issues/issues/1544
