### ISSUE TITLE
Teams in wrong columns

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1599]
Depending on the amount of players on teams (3+ teams on the map) the teams might not go in the right column

![](http://i.gyazo.com/d3fe5ca7843f56af94a537a81b89a77e.png)
https://oc.tc/matches/54c4db00c8f2cb4cee03e8d2

Yellow Team should be under Red Team

**Comment by jolteony** [comment]
are they supposed to be in the leftmost column? having it centered seems pretty logical to me.

**Comment by matic0basle** [comment]
@jolteony They are not. I saw another example where it was in the right one because the first two teams had two rows of players.

**Comment by ElliottWhyman** [comment]
No longer an issue
