### ISSUE TITLE
When clicking the name of the user "forums" it takes you to oc.tc/forums instead of to his profile

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1600]
How to reproduce: 
Go to a post like this one
https://oc.tc/forums/topics/54d1f15767d522ec9f0000ad?page=1#54d1f26967d52225d70000d3
Click on his name
!
EDIT: It also happens when searching him on oc.tc/stats

**Comment by Brottweiler** [comment]
Should use oc.tc/users/forums

**Comment by jolteony** [comment]
so i guess that you're solution to to make his linked profile name to go to oc.tc/users/forums. there are 2 ways to do this: make only his linked name go to /users/forums or make ALL names go to /users/names. I doubt its possible for Overcast to do the first just for his profile, and its ridiculous to make all linked profiles lead to /users/, as it make the site cluttered, unproffesional, and detracts to the clean look of the forums that we love.

**Comment by mrapple** [comment]
User path helper is outputting the wrong url for some reason

**Comment by mrapple** [comment]
Now fixed
