### ISSUE TITLE
Incorrect message when placing blocks on top of Ender Blast's Endstone Cuboid

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1601]
![2015-01-30_10 19 05](https://cloud.githubusercontent.com/assets/8422075/6052221/f29c537c-ac95-11e4-96b6-d7c588fe9a64.png)
as you can see im not trying to open any chests, but i get this message with every block i place.
It also occurs when you have not destroyed the enemies' cuboid and you spam tnt on top of it.

**Comment by Ipskie** [comment]
Aw frick. If possible I think people should be able to break into the wool room from the top, by the way (so please make the cyan clay breakable)
