### ISSUE TITLE
Recent website reports on profile

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1603]
Now this isn't really a bug but it does look weird and should be worked on.

![](http://i.gyazo.com/52ac773478b7e22355289c0b4cfff0f0.png)

The update times on recent website reports under the reports tab on your profile are too long for the space they are in. The space should be bigger to make it look nicer.

**Comment by matic0basle** [comment]
This has been fixed

![](http://i.gyazo.com/d0a9ddf75ae925721546d86954d835b3.png)

**Comment by matic0basle** [comment]
Reopening because it still happens now.

I think its because the "Reason" why you reported the player is so long.

![](http://i.gyazo.com/bc1a8eb218fd019be9cebd818aa1cf47.png)

**Comment by ghost** [comment]
Seems to be fixed http://prntscr.com/8rt7vt, http://prntscr.com/8rt7zo and http://prntscr.com/8rtccu
