### ISSUE TITLE
Not showing staff from EU/US depending on the server

### ISSUE THREAD

**Issue by Guicotsch** [OvercastNetwork/Issues#1604]
![photoeu](https://cloud.githubusercontent.com/assets/7735022/6069964/155700f8-ad89-11e4-80bd-8988d9cc97f7.png)
![photous](https://cloud.githubusercontent.com/assets/7735022/6069965/155982ec-ad89-11e4-9d2d-c2e92e9f3f3f.png)
 The first photo was taken on the US servers, the second one on EU lobby (It took me like 15secs to go from one to another). So yeah, staff on US isn't showing on EU.
EDIT: The first photo taken was on US ( the second one)

**Comment by mrapple** [comment]
Please search the issue tracker first. This is a dupe.
