### ISSUE TITLE
Maps made by people whose name changed still have the old player's name

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1605]
yeah basically what the title says, just do /map on some map made by someone that changed his name (example DATAstation still says ElectroidFilms while his name is Electric)

**Comment by matic0basle** [comment]
The XML files would have to be changed manualy. Not really an issue since the map XML doesn't auto update when someone changes their name.

**Comment by CaptainElliott** [comment]
Map authors are planned to use UUIDs
