### ISSUE TITLE
In Game Reports don't update to profile.

### ISSUE THREAD

**Issue by pelpelajax** [OvercastNetwork/Issues#1607]
I don't want to add screenshot so that identities remain safe but, when you report some one in game, it won't show up on your profile under "Recent in game reports by...".

**Comment by matic0basle** [comment]
Tested in the lobby with my alt. Can confirm.

**Comment by Superjd10** [comment]
@ItsMiiOlly Cache. Indeed.

**Comment by ghost** [comment]
Seems to be fixed http://prntscr.com/8rt6xu
