### ISSUE TITLE
Last `whats new` page displays duplicates of recent topics that have no other data

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1609]
This!

<img src="http://i.imgur.com/S2JxMu7.jpg">

**Comment by matic0basle** [comment]
You don't need [BUG][WEB] in the title as labels will be added later. But I can confirm I see this. Last 4 topics are recent topics (under two weeks)

**Comment by Kitatist** [comment]
Oh, okay, thanks mat!

**Comment by CaptainElliott** [comment]
https://oc.tc/forums/topics/54d51dff67d522b4bb001c2f and https://oc.tc/forums/topics/54d5206fc2963502cf001708

For example

**Comment by Kitatist** [comment]
Yes, thanks elliot

**Comment by Electroid** [comment]
Doesn't occur anymore.
