### ISSUE TITLE
You can place water on the ceiling of BoomBox

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1610]
Not sure if intended but i think its not since this way people can go from one base to the other placing 0 blocks, and its very difficult to get rid of. People have been using this lately like a bridge, they place a bucket, wait like 1 second, take it out, place it 2-3 blocks infront and repeat til you get to the other base. Since the water connects, the ones made first don't dissapear, but instead connect to make big water curtains.
![2015-02-06_15 11 48](https://cloud.githubusercontent.com/assets/8422075/6087718/83e56c86-ae14-11e4-95c9-78ffd98d258e.png)

**Comment by Ipskie** [comment]
I honestly don't think this is an issue, balance or XML wise. People in water streams are pretty easy to shoot down, and really slow, so it's not like this is super OP or anything

**Comment by Electroid** [comment]
Author ways it's not a bug.
