### ISSUE TITLE
Fix blockspam and improve woolrooms - Thunderstorm

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#1611]
Due to recent tastings I've discovered that there still is way to much blockspam on Thunderstorm even though I already cut the blocks by half. It is needed to reduce each type of block in the spawnkit to make it a bit more enjoyable again. As for the sandstone the new amount would be 16, for the planks it would be 16 too. So basically the half again.

Also I've discovered that the woolroom is a bit complex, since you can't place blocks in it it makes it really hard for players to get out. It would be great to see a small update in XML so that you can place blocks in the woolroom, this would also mean that you would have to be able to destroy these again, but not the ones of the woolroom.

I've also seen that the terrain still is a bit of a problem, gonna remove or simplify some structures soonish.

That's about it.

**Comment by Ipskie** [comment]
Ideally the map maker should post an update to perceived issues: you really shouldn't leave it to the map devs to improve your maps for you. Both of these are balance issues that you can post fixes to.

**Comment by AnthonyTag** [comment]
If you wish for this map to still be updated, please update it yourself and make another issue. Map creators are in charge of making updates to their own maps, mapdevs push the updates.

**Comment by rockymine** [comment]
@ajtag5: It was already fixed. Forgot to close this my own.
