### ISSUE TITLE
Antiquis pickaxe trading broken in 1.8

### ISSUE THREAD

**Issue by SuicuneScale** [OvercastNetwork/Issues#1612]
Because 1.8 does not allow for different damage values when trading, using a pickaxe once on Antiquis prevents you from trading that pick + infused shards into a better pickaxe. 

To reproduce, simply use 1.8 while playing Antiquis, get a pickaxe, use it once, and try to trade it to the villagers.

**Comment by CoWinkKeyDinkInc** [comment]
It does work, it's just that it is glitchy.  Just click on the empty square were the pickaxe should appear, put it in your inventory, and try messing around with it.  It should appear afterwards.

**Comment by SuicuneScale** [comment]
Even so, it probably shouldn't do that either, because how is a new player
supposed to figure that out? Not to mention the map will be broken when 1.7
support is dropped. Picks should probably be changed to a killreward.

**Comment by Ipskie** [comment]
This is more of a version compatiblilty issue, any fix applied now I'll be irrelevant when 1.8 rolls around or will be a deviation from vanilla

**Comment by jedediah** [comment]
I'm working on a fix that will let you use the old trading behavior with an XML setting.

**Comment by matic0basle** [comment]
@jedediah So we will be able to have the new one as an XML feature?

**Comment by nygiants10** [comment]
I would like to add that this affects Aztecatti as well, in an even more major way. Since sword trading requires you to trade in your old sword, if you melee anyone, you cannot upgrade your sword.

**Comment by CoWinkKeyDinkInc** [comment]
Trading has failed to work for me in Moonlight Summit.
