### ISSUE TITLE
/toggle pms not working

### ISSUE THREAD

**Issue by Eudaldca** [OvercastNetwork/Issues#1613]
Issue: If I /toggle pms everybody can still pm me, independently of them being or not my friends or having pm's toggled for friends or none.
Misc: I was on official servers, with streamer perms, observing. 
And no, this wasn't because changing servers and my settings resetting.

**Comment by Ipskie** [comment]
I uh, hope you mean toggle pms or whatever the setting is, because toggling dms is thinking your death messages

**Comment by eudaldca** [comment]
I mean private messages ofc.

**Comment by Brottweiler** [comment]
This is a known bug. You need to go to the public servers, change your PM setting there, then join the TM servers.

**Comment by TiTo-418** [comment]
In the lobby works: http://youtu.be/r-MyDZBb13M

**Comment by eudaldca** [comment]
No longer an issue
