### ISSUE TITLE
Different spacing on stats on profile 

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1614]
If a player has no kills, deaths or friends this is what you see:

![](http://i.gyazo.com/ea916aa8eccda5890a5e2adffee929f7.png)

The friends column has more space than kills and deaths. 
I went into inspect element and friends had an extra br tag in there.

https://oc.tc/Vechs1

**Comment by ghost** [comment]
Fixed with the players` page update
