### ISSUE TITLE
Attempting to purchase a gizmo results in an internal error

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/Issues#1615]
Verification needed. I can't test this because I have no unpurchased gizmos. It was reported by https://oc.tc/Desert_Eagle on the forums - [link to thread](https://oc.tc/forums/topics/54d7c3815f35b938e9000c12).

![Screenshot 1](http://i.imgur.com/Qq8IxHU.png)

![Screenshot 2](http://i.imgur.com/USiFblO.png)

**Comment by Superjd10** [comment]
Maybe it's something related to the fact that you can't use the DIsguiser's gizmo (but he said he can't buy anything else so I don't know)

**Comment by CaptainElliott** [comment]
@Superjd10 the error occurs on any time

**Comment by Fireblast168** [comment]
I'm Desert_Eagle, I could not buy small ball, either. (Same error) It have to do with the fact I changed my name from Fireblast168 to Desert_Eagle.

**Comment by mrapple** [comment]
Fixed
