### ISSUE TITLE
Listed servers displaying incorrect MOTD for 1.8.2 (pre6) clients

### ISSUE THREAD

**Issue by odsseus** [OvercastNetwork/Issues#1619]
![2015-02-12 21 37 40](https://cloud.githubusercontent.com/assets/7188301/6176528/f2c75804-b2ff-11e4-9aa9-591d56e6eb3e.png)
Edit : I am not sure if this is worth to consider as it might be a Minecraft issue.

**Comment by CaptainElliott** [comment]
This is known, its a bug with pre6 not OCN

**Comment by mrapple** [comment]
We will need to change our MOTD is this persists

**Comment by odsseus** [comment]
Fixed in 1.8.2 pre7 !

**Comment by mrapple** [comment]
Perfect, thank you for the update
