### ISSUE TITLE
Bug at searching the player Breezily

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1622]
There are 2 links wich aparent the same but...

1:

<img src="http://i.imgur.com/GloCnYd.jpg">

2:

<img src="http://i.imgur.com/H2NPo5j.jpg">

**Comment by Electroid** [comment]
These are different players.. the font is a bit misleading.

**Comment by Kitatist** [comment]
I dont see any diference btween those both players

**Comment by CoWinkKeyDinkInc** [comment]
One has a capital I and the other a capital L, the font does not have a horizontal line to distinguish them easily, but you can notice that the L is taller than the lowercase i.

**Comment by Kitatist** [comment]
Well, thanks, as I saw this it generates me some questions... The was a
similar issue I guess on the player called forums?

**Comment by Brottweiler** [comment]
@Kitatist no

**Comment by matic0basle** [comment]
The case here is one players is Breezily with an L (lowercase) and one is BreeziIy with a capital I.

**Comment by Kitatist** [comment]
Just checked randomly reports and I saw that this user was banned, now, as my neutral point of view I asking if this was needed? :open_mouth:

**Comment by Brottweiler** [comment]
>§A. 6. Do not impersonate any member of the Overcast Network staff, or claim to be a staff member.

https://oc.tc/rules
