### ISSUE TITLE
Bug with skins, black pixels turning white on the webpage.

### ISSUE THREAD

**Issue by manucide** [OvercastNetwork/Issues#1623]
Some examples:
My skin:
http://gyazo.com/ff258278a192f0d6bc78a97952298372
Last:
http://gyazo.com/51aa0a158bcf1a9af0107f54b8d31b9d
Aceman and Brett's alt:
http://gyazo.com/2c028ea86cde2765d0d315ac9ffaea77

**Comment by mrapple** [comment]
Dupe, please search before posting
