### ISSUE TITLE
Monument percentages don't total 100%

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1625]
During the Radical vs Proskekt match today a monument was destroyed by 2 players, with percentages 63% and 38%

Couldn't find an equivalent issue

**Comment by CaptainElliott** [comment]
The values round iirc

**Comment by matic0basle** [comment]
Going to leave this here just in case.
https://github.com/OvercastNetwork/Issues/issues/884

**Comment by mrapple** [comment]
Let's use #884
