### ISSUE TITLE
Incorrect regions on Utopia

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1626]
You can't place or break blocks on these 2 big sides of the map, because it say it is part of the void
![2015-02-14_14 44 04](https://cloud.githubusercontent.com/assets/8422075/6200996/40a866ae-b458-11e4-8b3d-b0d79d0f90e0.png)
![2015-02-14_14 44 47](https://cloud.githubusercontent.com/assets/8422075/6200995/40a881de-b458-11e4-89fb-eaf40c3a039b.png)
![2015-02-14_14 44 52](https://cloud.githubusercontent.com/assets/8422075/6200997/40abd816-b458-11e4-8a8f-d53c2464d005.png)

**Comment by thestrangeboy1** [comment]
Utopia was just recently updated so that those lanes were changed around a bit and are now given block 36 under to be able to place in that region.
