### ISSUE TITLE
scoreboard on War Wars

### ISSUE THREAD

**Issue by RubeGamerV** [OvercastNetwork/Issues#1627]
<a href="http://gyazo.com/e52833e9be0d5d02634fb960c640ba90"><img src="http://i.gyazo.com/e52833e9be0d5d02634fb960c640ba90.png" /></a>

**Comment by matic0basle** [comment]
You don't need [bug] because labels will be added later. It also doesn't only happen on War Wars.

**Comment by CoWinkKeyDinkInc** [comment]
Did you find a download to War Wars or did you just make your own version?  I'm looking for a War Wars download.

**Comment by CaptainElliott** [comment]
This is because it is mixed with the blitz module therefore not an issue

The first blue team deceleration is the amount of blue players left and the second is the blue teams core.

**Comment by RubeGamerV** [comment]
@CoWinkKeyDinkInc Is on tm.oc.tc
