### ISSUE TITLE
Incorrect translations in oc.tc/rules

### ISSUE THREAD

**Issue by AudreyDx** [OvercastNetwork/Issues#1629]
The point B of the rules in all the languages is bad translated, look at this photos: 

http://i.imgur.com/VfLCCY7.png oc.tc/rules/ru

http://i.imgur.com/dHDX4up.png oc.tc/rules/ko

**Comment by Superjd10** [comment]
Known. Still waiting for translations / approvation @OvercastNetwork/Rules I think they are gonna move the rules to Crowdin.

**Comment by CoWinkKeyDinkInc** [comment]
You can submit translations to https://github.com/OvercastNetwork/rules
