### ISSUE TITLE
Cake Wars TE is missing the jukebox + music disk

### ISSUE THREAD

**Issue by jolteony** [OvercastNetwork/Issues#1633]
gamebreaking imo. the music can be used tactically to impair the ability of the other team to hear core leaks, which we cannot do since the jukebox is missing

**Comment by Electroid** [comment]
Very interesting strategy.. Although people have already been scrimming this map for a while so it will stay as is.

**Comment by CoWinkKeyDinkInc** [comment]
You can just mute sounds from jukeboxes in your settings.

**Comment by jolteony** [comment]
and who would do that? the whole point is that players normally have it on,
so we can take advantage of that. and they wouldnt know to turn it off
