### ISSUE TITLE
My XML (Needs Fixing?)

### ISSUE THREAD

**Issue by RefGaming** [OvercastNetwork/Issues#1637]
Hey! I did my first XML and could someone see if this works good?
And if it doesnt can someone fix it? Thanks! 
https://gist.github.com/RefGaming/6a8b96bf5ca0b3453f65

-Ref_

**Comment by Electroid** [comment]
Hey. This isn't the place to ask for XML help, only issues with *current* maps and plugins. I would go to the forums to get help on that.
