### ISSUE TITLE
You can Deop Staff on TM Servers!

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1639]
Today randomly checking commands I found the /deop command, so I pressed "TAB" and a large list of my team members AND staff appears...

I dont know if this could harm anything,

Anyway, thanks!

**Comment by Brottweiler** [comment]
When you type `/deop <username>` it will always say you deopped someone regardless if they were OP or not, I am certain this is not a problem.

**Comment by khazhyk** [comment]
EC's are op'ed automatically on joining servers, and can /op themselves at any time (on tm servers), so this isn't an issue.

**Comment by Kitatist** [comment]
Thanks! :+1:

**Comment by Ipskie** [comment]
/command and tabbing wil always show up usernames, you should have hit enter and seen if it would work
