### ISSUE TITLE
1.8.1 and up has no Player Menu Color in lobbies

### ISSUE THREAD

**Issue by Fireblast168** [OvercastNetwork/Issues#1640]
I noticed that in games 1.8.1+ has player list color, but the lobbies do not have either player list color or ranks.
![image](https://cloud.githubusercontent.com/assets/9503165/6260523/ba2934ae-b7a5-11e4-83f2-a8171e9fa3e8.png)

**Comment by mrapple** [comment]
Dupe, also, this will be fixed when we make the switch to 1.8 anyways.
