### ISSUE TITLE
Remove disguised gizmo

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1641]
Since disguises aren't coming back for some time I think the gizmo should be removed. The shop should also be updated so you don't get access to mob disguises. And to notify the community make a forum thread why it happened.

Electroid:
>Author of the plugin has signed off the project as unmaintained. All our maps have removed this feature. And until further notice, this feature won't come back.

https://github.com/OvercastNetwork/Issues/issues/1275

**Comment by Brottweiler** [comment]
Might be good to temporary remove it.

**Comment by mrapple** [comment]
We're in the process of deciding the future of disguises on the server. Once that is done, we can reopen this if deemed appropriate.
