### ISSUE TITLE
Villagers are on wrong positions on the TM server!

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1645]
<img src="http://i.imgur.com/H9yWvpZ.png">

**Comment by Superjd10** [comment]
No, they are not (in lobby 1 and 3)

![image](https://cloud.githubusercontent.com/assets/1649155/6316056/a8eecffa-b9e4-11e4-9043-84548f03ccfc.png)

I checked lobby 2 and you are right, they are not on the indeed positions, an auto lobby restart will fix it soon

**Comment by matic0basle** [comment]
IMO still an issue if they escape. Could it be the potion thats keeping them there running out?

**Comment by Kitatist** [comment]
Maybe?  What if a solution would be applicate the /effect @entity Slownes 3600 (infinity) 255?

**Comment by Electroid** [comment]
Sometimes the villagers jump out. I'll give them negative jump boost.
