### ISSUE TITLE
Stats are broken

### ISSUE THREAD

**Issue by SheriffSoco** [OvercastNetwork/Issues#1648]
The stats on my profile page have not been updating today. I have talked with others about this, and they too are having the same problem.

Also, 24 hour and 1 week stats are broken on https://oc.tc/stats

**Comment by Oxinous** [comment]
Yes, maybe it is just lag. It happened before.

**Comment by Brottweiler** [comment]
Seems like stats are frozen for some reason

**Comment by samtheman43** [comment]
I'm getting this too, does this mean once it "un-freezes" we won't have the kills we got while this issue is still active?

**Comment by Oxinous** [comment]
No samtheman43, you will have your kills if they are lagged if frozen no.

**Comment by samtheman43** [comment]
I don't understand what you said, but ok.

**Comment by Oxinous** [comment]
If stats are lagged (takes some time to be updated) you will conserve them, if the are frozen nothing you do ingame is saved.

**Comment by Brottweiler** [comment]
@Oxinous that's not correct. Everything you do ingame will be saved.

**Comment by Oxinous** [comment]
@Brottweiler Hmm sorry, cool to know.

**Comment by khazhyk** [comment]
fixed

**Comment by SheriffSoco** [comment]
ty

**Comment by samtheman43** [comment]
yay
