### ISSUE TITLE
TM Sever lobby not symmetrical.

### ISSUE THREAD

**Issue by Oxinous** [OvercastNetwork/Issues#1649]
The cross/mark in lobby center is not symmetrical. http://gyazo.com/1cfeea4a68a22fe18e1d9e57559a202f

**Comment by matic0basle** [comment]
I don't think its an issue. If you haven't noticed the arrows in the ground are also different one one side compare to the other. Same with beacons. And also the colors (red/blue)

**Comment by Superjd10** [comment]
I agree with @matic0basle, I think it's indeed, the arrows on the ground prove it.

**Comment by CaptainElliott** [comment]
https://oc.tc/forums/posts/54ea2eec67d5222835001fb7
