### ISSUE TITLE
Searching the username forums in oc.tc/stats brings you to the forums instead of the user's profile

### ISSUE THREAD

**Issue by InternetSam** [OvercastNetwork/Issues#1654]
Title says it all

**Comment by TiTo-418** [comment]
![](http://i.gyazo.com/4d096b32e28a75c2a4f5d18764427d88.png)

**Comment by Brottweiler** [comment]
@TiTo-418 Just tested, still not fixed.

**Comment by Superjd10** [comment]
@Brettogden @TiTo-418 That commit was for the profile link on the forum posts, not in oc.tc/stats.

**Comment by TiTo-418** [comment]
In this page: https://oc.tc/teams/tacticalinfo if you click on "forums" you go to https://oc.tc/users/forums

**Comment by Brottweiler** [comment]
@TiTo-418 that's not what this issue is about.

**Comment by ghost** [comment]
Ok, the issue is about oc.tc/stats, but why isn't https://oc.tc/teams/tacticalinfo the same?

**Comment by Superjd10** [comment]
@TiTo-418 Because the link on https://oc.tc/teams/tacticalinfo goes to the user's profile (not an issue, that's how it should work). This issue is about the autocomplete / stats link going to the forums instead of the player's profile.

**Comment by Brettogden** [comment]
@superjd10 why was I mentioned?

**Comment by Brottweiler** [comment]
@Brettogden mistake, he was supposed to mention me.

**Comment by Superjd10** [comment]
@Brottweiler @Brettogden Yeah. Sorry Brett.
