### ISSUE TITLE
Odd forum archive behavior

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1655]
It looks like if a thread is archived without any posts in it, it pushes to the absolute back of the forum. 
![](http://i.gyazo.com/e62d03e0a0b6b1dfada9487665ee688c.png)
![](http://i.gyazo.com/3176755468f247339401f03e0e32af2e.png)

**Comment by matic0basle** [comment]
![](http://i.gyazo.com/2bc1ca28c7ce427256c4adf7d9de40d4.png)
