### ISSUE TITLE
Score Not Tracking Properly

### ISSUE THREAD

**Issue by ajtag5** [OvercastNetwork/Issues#1656]
I assume with the new 1.8 mapdev servers some bugs have arose. One of witch I found while trying to test a new TDM map. The first kill in a match is not tracked to the scoreboard and every kill following that kill will update the previously missed score.

Basically, a point is not added to the score per kill until another kill is made.

You can recreate this on a mapdev server or I assume Broken as well seeming it is also a 1.8 server.

Edit: Here is a video to show more clearly what I am talking about. http://youtu.be/baf5POetado

**Comment by mrapple** [comment]
Stats are not supposed to be tracked on mapdev servers

**Comment by Superjd10** [comment]
@mrapple I think he is referring to a bug with the scoreboard, not the stats.

**Comment by ajtag5** [comment]
@Superjd10 this is correct. Sorry @mrapple, should have been more clear.

**Comment by Electroid** [comment]
Hasn't occurred again.
