### ISSUE TITLE
There is nothing inside The Dome's spawnkit chest

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1657]
![2015-02-27_08 16 58](https://cloud.githubusercontent.com/assets/8422075/6414062/79ee3338-be5a-11e4-97a0-01a165961522.png)

**Comment by CaptainElliott** [comment]
The chest should probably just be removed

**Comment by ItsMiiOlly** [comment]
https://oc.tc/forums/topics/5418a2cdc296359af0003671
