### ISSUE TITLE
Players not being notified in-game when warned/kicked via web reports?

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/Issues#1659]
A player [reported on the forums](https://oc.tc/forums/posts/54f090b267d5221fb20007af) that they hadn't recieved any sort of in-game notification when they were warned via a web report.

There was also a post yesterday where the same user said they weren't notified on login if they had been warned or kicked while they were offline.

I will try and test to confirm this later.

**Comment by rywarsaw** [comment]
Thanks for making this issue report @itsmartin, I'm the user who is having this issue, incase anyone needs more information.

**Comment by ghost** [comment]
https://oc.tc/forums/topics/5629b3365f35b92096000ad6

**Comment by Brottweiler** [comment]
@TiTo-418 he was online when he got warned via web report.

**Comment by itsmartin** [comment]
Confirmed. Tested just now with both a warn and a kick, neither showed up when I joined.

**Comment by ghost** [comment]
@itsmartin Wait, what are you talking about? You don't receive a notification if you get a warn WHILE you are playing or if you get a warn when you are offline and it doesn't show up when you login into the server again?

**Comment by Superjd10** [comment]
@TiTo-418 Notification to offline players about the warn next time they login.

**Comment by ghost** [comment]
@Superjd10 Then this is dupe https://github.com/OvercastNetwork/Issues/issues/256

**Comment by itsmartin** [comment]
Closed in favour of the earlier issue.
