### ISSUE TITLE
Infractions removed from players?

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1661]
Hi!

Today searching the profiles of one of my IRL friends (If he connected recently) I saw that saab93ca (https://oc.tc/saab93ca) hasnt any infraction...

But.. the point is that im 200% sure that he got punished before...

Any answer?

**Comment by matic0basle** [comment]
Warns are no longer visible to the public. Same with other punishments that are stale. Not a bug.

Check out https://oc.tc/forums/topics/54eff21ac29635428c0007fb

**Comment by Kitatist** [comment]
Nice!

**Comment by samtheman43** [comment]
They aren't recorded because warns aren't considered punishments

**Comment by Kitatist** [comment]
True. All info is on the link wich deliverd matic
