### ISSUE TITLE
Some cores and wools have no names

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1663]
http://i.imgur.com/niM3r0r.png

**Comment by CaptainElliott** [comment]
The green wool is actually colored, it is just very dark, could you also link the profile that has the bugged objectives

**Comment by Brottweiler** [comment]
@CaptainElliott check  the bottom of the picture; https://oc.tc/Elijah

**Comment by CaptainElliott** [comment]
wait nvm its your profile, I don't see it

**Comment by CaptainElliott** [comment]
oh, whoops nvm, it was the cores

**Comment by Brottweiler** [comment]
Pretty obvious looking at his objectives

![](http://i.imgur.com/1qaiUfn.png)

![](http://i.imgur.com/qlQwBD8.png)

**Comment by CaptainElliott** [comment]
He stated that some wools have no colours not that they have no name

**Comment by Brottweiler** [comment]
@CaptainElliott Yes, but some wools doesn't have names. The color issue he's reporting is invalid, but some cores and *some wools* have no name.

**Comment by Ipskie** [comment]
Yes yes I get it. Brott's correct, though at first I didn't notice the missing wools

https://oc.tc/Apple is missing 3 cores

https://oc.tc/Cubist is missing 4

It would appear that this only happens to objectives from a really long time ago, like 2 years+ (except for that 1 wool 11 months ago) Maybe an issue with interpreting them from the database?

**Comment by rmsy** [comment]
These are malformed database documents; new documents should no longer have this issue.

**Comment by rmsy** [comment]
We do need to migrate them though
