### ISSUE TITLE
Tetrad: You can run through spawn to get to the wool room - Map Bug

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1667]
There is no protection to keep players from going through the spawn to the wool room, and thus this is an easy shortcut.

Here you see a blue player go through the red spawn:
http://i.imgur.com/VKqCdoC.png 

http://i.imgur.com/sMUYoRd.png

It doesn't matter if its a bug or intended, its way to easy to get in the wool room this way.

**Comment by Electroid** [comment]
Intentional.
