### ISSUE TITLE
Match Filter isnt ordred

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1668]
As you can see on  oc.tc/matches if you click on "Filter Matches" all server list isnt ordred from A-Z.

If this is so, i suggest that you could order ot from A-Z.

Have a nice day.

-Kita

**Comment by Electroid** [comment]
Duplicate: #255

**Comment by Kitatist** [comment]
Oh wow...! #255... #1668

Is there a way to know if something is done before you post the issue.

It would be great for future interventions.

**Comment by Ipskie** [comment]
@Kitatist Well, if you read the Main page for this you may notice that it instructs you to search the repo before posing issues. Please read the main page before making useless or existing issues
