### ISSUE TITLE
Players can enter enemy's spawn on Kings and Queens

### ISSUE THREAD

**Issue by TheMoMan** [OvercastNetwork/Issues#1670]
There are no team filters over the portals in Kings and Queens, so any team can use any portal. As a result, players can enter the enemy's spawn with higher tier gear and begin spawn killing.

On a side related to this map, TNT does not seem to have any fuction as there are no places in the map allowing you to place it,

**Comment by Timothee38** [comment]
Yes, this map is terribly broken, and I terribly need to fix it :s

**Comment by AnthonyTag** [comment]
For now I am removing the map so that it is not set. Tim can fix it if he wants it back in the repo

**Comment by Timothee38** [comment]
fixed!
