### ISSUE TITLE
[1.8] CTF Stats issue

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1672]
Yesterday I was testing on /server Broken new CTF maps.

When I asked if the kills would affect stats, people, and I think staff told me then yes.

As I pressed F5 on www.oc.tc/MCKita I found out that stats werent uploading.

The point is that I think its strange cuz I got raindrops at winning a match and when I killed someone. Also as I captured the flag:

![1](https://cloud.githubusercontent.com/assets/8619228/6440751/89a2a704-c0e0-11e4-8df8-0cac018e3ecc.JPG)

PD: This time I read If there is a dupplicated post, and comproved all 3 times.

**Comment by Ipskie** [comment]
What's the issue? It is well known that stats (kills etc.) don't update as they should

What specifically is wrong with the way CTF stats are being tracked?

**Comment by samtheman43** [comment]
Stats are recorded from /server Broken. That's why the flag objective is on your profile.

**Comment by Kitatist** [comment]
Well then...
