### ISSUE TITLE
There is snow on the top of the exits from SSB

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1673]
Is this normal?
![2015-02-28_19 34 46](https://cloud.githubusercontent.com/assets/8619228/6445393/dcf6affe-c103-11e4-8ca6-33c22c646fc4.png)
![2015-02-28_19 34 55](https://cloud.githubusercontent.com/assets/8619228/6445394/dcf8fad4-c103-11e4-8dcf-69716c0bc22b.png)
![2015-02-28_19 34 58](https://cloud.githubusercontent.com/assets/8619228/6445395/dcf993ea-c103-11e4-8270-18297f9a0f09.png)
![2015-02-28_19 35 01](https://cloud.githubusercontent.com/assets/8619228/6445396/dcfc47c0-c103-11e4-9278-e1e08794e130.png)

**Comment by CoWinkKeyDinkInc** [comment]
The snow has always been there.  The world is set to a winter biome so water may freeze so it doesn't become a huge mess with blown up cannons everywhere.
