### ISSUE TITLE
List of GS Issues

### ISSUE THREAD

**Issue by SheriffSoco** [OvercastNetwork/Issues#1674]
Hi there,

I've compiled a list of things that are bugs and need fixing from the Ghost Squadron server. Some are map issues, some are XML issues.

XML:
- Leprachaun still takes fall damage from double jump
- Kill rewards are broken;
    - Most killrewards are only for the first kill and not multiple kills
    - Archer gets an "explosive arrow" that isn't actually explosive. This is only for the first life
    - Other kits might have the same problem but I'm not certain
- Holding the KB stick as a scout does not make you faster from what I'm aware

Maps:
- Blocks causes very low frame rate on 1.8. I spike to 0 whenever breaking a block in Observers and I can't reach anything above 20 FPS
- Fairyland's tall grass makes it hard to hit players. This might of been a gameplay choice but I think it's just aesthetic. At least remove the tall grass so hits don't get rewarded with the flower breaking sound.

This is all of the GS issues I know for now.

**Comment by SheriffSoco** [comment]
Oh one more thing. The FFA scoreboard in 1.8 doesn't show all of the players. It's hard to explain and easier to show. Just go on the server and wait for an FFA and then press tab.

**Comment by matic0basle** [comment]
The FFA scoreboard issue has already been reported.
https://github.com/OvercastNetwork/Issues/issues/1443

**Comment by Ipskie** [comment]
Might want to consider breaking this into separate issues, as much as it would spam the tracker

**Comment by minimitch0199** [comment]
I've got a new version of Deadwater ready to release, which I will do when I have time.

**Comment by ItsMiiOlly** [comment]
Fixed the doors

**Comment by SheriffSoco** [comment]
I talked to ParaSpider/Tanpopo and he said that it's ok to remove Pseudo

**Comment by ParaSpider** [comment]
^ Confirming above statement. I thought it was good, but if it's the 2nd lowest rated GS map I don't think it has the place to really stay.

**Comment by AnthonyTag** [comment]
I'll try to look into some of this. This issue has been open for way too long.

**Comment by AnthonyTag** [comment]
- Kill rewards fixed
- Scout gets speed (maybe it was fixed previously?)
- Kinda difficult to disable fall damage for the leprechaun class, would need to update all GS XMLs to 1.4.0
  - Also kinda think it's a plugin bug that double jump doesn't automatically give no fall but idk

Can't figure out why Blocks would be causing lag. Also don't notice frame drops myself.

**Comment by SheriffSoco** [comment]
Is there someway you could fix potion particles? It has something to do
with the effect order.
