### ISSUE TITLE
You cant break some blocks when their are near the core

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1675]
On Iris DTC Match yesterday someone placed wood blocks on the core, later, trying to breake those block the chat told me that I couldnt cause of it was part of the core.

I think its something from the XML wich detects that those blocks form part of our own core, and you might not destroy them.

Maybe some images would help:

![2015-03-02_14 08 23](https://cloud.githubusercontent.com/assets/8619228/6459549/fa44364e-c18f-11e4-9c13-ea4793aa4582.png)
![2015-03-02_14 08 24](https://cloud.githubusercontent.com/assets/8619228/6459550/fa47ad42-c18f-11e4-9079-1aaf96dbbe9c.png)
![2015-03-02_14 08 26](https://cloud.githubusercontent.com/assets/8619228/6459551/fa4a79aa-c18f-11e4-8bf0-aa8295e99e02.png)

**Comment by Ipskie** [comment]
When a block of the core is broken and is subsequently replaced, the new block counts as a piece of the core. This is intentional and this issue is invalid.

To avoid things like this you might try asking around(mumble, IRC etc.) if something is intentional or actually a bug

**Comment by Kitatist** [comment]
Okay, only with good intentention! :)
