### ISSUE TITLE
Youtube badge not in aligned properly

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1677]
The gap between the youtube tag and other tags is larger than between normal badges

It's also slightly lower

It's also slightly blurry

**Comment by matic0basle** [comment]
>It's the official logo, downloaded from their site. We're not even allowed to change it, technically.
~ Cubist 
https://oc.tc/forums/topics/54f69365c29635aafc0002cb?page=2#54f6a02167d522136500002c

So they can't work on the blur and the reason why its lower (I think) is because the badge it self is different size.

**Comment by Brottweiler** [comment]
Maybe we can use [this icon](http://fortawesome.github.io/Font-Awesome/icon/youtube-play/) instead?

**Comment by matic0basle** [comment]
@Brottweiler The developers should consider that but honestly, I think its fine as it is and looks ok.

**Comment by Brottweiler** [comment]
@matic0basle I agree, even if it could look better, it's fine.

**Comment by Electroid** [comment]
Duplicate issue.
