### ISSUE TITLE
offline friend keeps being online in lobby-2 on oc.tc/friendships

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1678]
a guy on my friendlist is always in the lobby according to the friendlist, but if hes actually online, he shows up two times, and if he goes offline, the friendlist acts like hes still in the lobby. one day later, hes still online, in the lobby according to my friendlist. kinda annoying. here is the thread on the forum i made for it, with some screenshots and a vid. https://oc.tc/forums/topics/54f62f6cc2963528140014da

**Comment by Brottweiler** [comment]
If he shows up as online at oc.tc/friendships, does he also show up as online when you type `/friends` ingame?

**Comment by kroest** [comment]
i tried /friends, but nothing showed up. the guy disappeared from my oc.tc/friendships 4 horus ago.

**Comment by kroest** [comment]
by nothing showed up, i man, really, nohing showed up, no text line that something boke or so.

**Comment by mrapple** [comment]
Is this still an issue?
