### ISSUE TITLE
Skin pictures on the site broken, black/white boxes instead

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1679]
i know multiple people that have their skin replaced with a weird white/ or black box. if you check my oc.tc profile, https://oc.tc/Get_Rekt , and you scroll dowen, you can see 2 black, and 1 white box, and if you check the image links,

https://avatar.oc.tc/_meteor/32@2x.png (black)
https://avatar.oc.tc/amiralblendic/32@2x.png (black)

and even a white one https://avatar.oc.tc/Anxaanum/32@2x.png 

this should be noticed already, but i didnt see anything of it in the issue tracker, so thats why i post it here.

**Comment by matic0basle** [comment]
There is already an issue about this.
https://github.com/OvercastNetwork/Issues/issues/1544
