### ISSUE TITLE
Youtube link doesnt show on profiles

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1680]
On profiles...

![yt 4](https://cloud.githubusercontent.com/assets/8619228/6505296/cf44d018-c340-11e4-9760-784b720b2024.JPG)

**Comment by itsmartin** [comment]
Confirmed, seems to be missing whether a channel name or ID is used.

**Comment by jedediah** [comment]
fixed

**Comment by Kitatist** [comment]
Nice, thanks, and... @jedediah  or Cubist or Last,

Could we get back the forums tag where the map tag is now? :)

Im constantly clicking on maps! ;_;

**Comment by Ipskie** [comment]
Please keep your comments on an issue relevant to the issue itself, unrelated comments aren't really helpful and a little difficult for those of us with email alerts on. The issue tracker is not meant to be a chat room :/
