### ISSUE TITLE
Players on RAGE can lose their armor if attacked while in spawn

### ISSUE THREAD

**Issue by Kitatist** [OvercastNetwork/Issues#1683]
Today playing i saw this....

Apparently you cant do this?
![2015-03-05_18 03 07](https://cloud.githubusercontent.com/assets/8619228/6514534/828d0ae0-c383-11e4-93d3-042852a6a029.png)
![2015-03-05_18 03 15](https://cloud.githubusercontent.com/assets/8619228/6514553/a83e0654-c383-11e4-9092-2d0d5a09d843.png)
![2015-03-05_18 03 19](https://cloud.githubusercontent.com/assets/8619228/6514555/a8454bb2-c383-11e4-945d-b0a7e5a02df9.png)
![2015-03-05_18 03 20](https://cloud.githubusercontent.com/assets/8619228/6514554/a843e9d4-c383-11e4-9d6f-1be2a46b9a5d.png)
![2015-03-05_18 03 23](https://cloud.githubusercontent.com/assets/8619228/6514556/a847399a-c383-11e4-9c7f-398651dcfd13.png)
![2015-03-05_18 03 25](https://cloud.githubusercontent.com/assets/8619228/6514558/a84b34d2-c383-11e4-8d9f-5faa97e7ccfc.png)

**Comment by matic0basle** [comment]
Its up to the map creator if he wants players being able to remove armor or not since its an optional XML feature.

**Comment by Kitatist** [comment]
Arg! There you get me @matic0basle , I just remember that its PepsiDeSwag's map... hmmm

**Comment by Ipskie** [comment]
Please label your issues better, something like "Armor can be removed on only blue team on map x" and confirm the map before making the issue, as unspecific and badly labelled issues really don't help.

**Comment by manucide** [comment]
I think something like this is what happened: 
Someone (lets say on blue) was trying to spawnkill, then when the player from red respawned, he got hit by a sharp X sword / pow 10 bow, and his armor broke, but he didn't die because of the spawn protection.

**Comment by Ipskie** [comment]
Oh yeah, what manucide said. I've can confirm that is the cause of this issue, don't know if giving the usual -3000 damage will fix it though

**Comment by Diamyx** [comment]
This also commonly happens on RAGE TDM's.

**Comment by Kitatist** [comment]
Yes, it also affects plus side... here some sc.
![2015-03-05_23 18 00](https://cloud.githubusercontent.com/assets/8619228/6525963/945774fc-c40c-11e4-82ad-db8494a8b515.png)
![2015-03-05_23 18 02](https://cloud.githubusercontent.com/assets/8619228/6525964/945d57b4-c40c-11e4-8d6e-a637437b22c8.png)

**Comment by Brottweiler** [comment]
Doesn't this happen when you get hit but still have the resistant effect (which is there to prevent spawn killing)? Because the armor breaks in 1 hit...

**Comment by Kitatist** [comment]
@Brottweiler yes, but the resistant effect does prevent you from hitting.... maybe it makes so that the hit doesnt affect the ammo.... We could test it out on a private server maybe...

**Comment by Brottweiler** [comment]
Not sure what you mean. The resistance effect prevents you from dying, not from getting hit.

The resistance effect makes not die from getting hit, and then you also have instant health effect which will heal you to full health instantly. When you get hit right after spawning, your armor will break in 1 hit but you will not die. 

Doesn't sound like we can fix this, and I don't think this is actually an issue.

**Comment by Kitatist** [comment]
@Brottweiler so *I* close it?

**Comment by TiTo-418** [comment]
Maybe you can put unbreaking to the armor?

**Comment by Kitatist** [comment]
@TiTo-418  Maybe this could work! With unbreaking X maybe....

**Comment by TiTo-418** [comment]
Yeah, unbreaking 1000 is possible also

**Comment by Kitatist** [comment]
@TiTo-418 Well, in fact it does have the same effect.

**Comment by TiTo-418** [comment]
Yeah

**Comment by Electroid** [comment]
The XML coder didn't put the damage to `-3000`. This will be changed soon with `unbreakable` coming around.
