### ISSUE TITLE
There is a chiken on Truf War´s Observers spawn

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1684]
<a href="http://imgur.com/X1WYGYM"><img src="http://i.imgur.com/X1WYGYM.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/7xcVaAS"><img src="http://i.imgur.com/7xcVaAS.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/12WLi55"><img src="http://i.imgur.com/12WLi55.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/DMeiCJk"><img src="http://i.imgur.com/DMeiCJk.png" title="source: imgur.com" /></a>

**Comment by Superjd10** [comment]
Intentional IIRC.
