### ISSUE TITLE
Live, Long Name + Notification = New Line

### ISSUE THREAD

**Issue by High-Tower98** [OvercastNetwork/Issues#1686]
Forum Thread:
https://oc.tc/forums/topics/54fa5158c2963598d9003343

Without Notification:
http://i.imgur.com/bvx3xTY.png

With Notification:
http://i.imgur.com/0wjOPnq.png

Similar to:
#1685
#1682

**Comment by High-Tower98** [comment]
khazhyk replied to the forum thread and it appears that:
Any name that has eight characters or more, I guess, will get this issue. However those with seven characters or less won't.

**Comment by khazhyk** [comment]
We're working on it.

**Comment by YukonAppleGeek** [comment]
Resolved.
