### ISSUE TITLE
Live Page shows incorrect Week

### ISSUE THREAD

**Issue by High-Tower98** [OvercastNetwork/Issues#1688]
oc.tc/live says that people are "Currently Streaming: House of Cores - Week 2" when it is Week 5 of HoC.

http://oi57.tinypic.com/eraq92.jpg

**Comment by matic0basle** [comment]
Has to be updated by hand AFAIK. Its just developers not updating it. Not really a bug in that case IMO.

**Comment by High-Tower98** [comment]
It's not a bug as such but is still needs changing, when they get time.
