### ISSUE TITLE
Scout doesn't get the speed back after capturing the flag on TF2: Badlands CTF

### ISSUE THREAD

**Issue by Diamyx** [OvercastNetwork/Issues#1690]
If you pick the scout class and then hold the flag, you get the flag carrier debuff (slowness, I believe). You lose the debuff when you capture the flag, but you don't get the speed back.

**Comment by Brottweiler** [comment]
Not sure if this is a map or plugin bug, sounds like it's a bug in the CTF?

**Comment by CaptainElliott** [comment]
It is a map bug, the standard kit needs to be applied when the player drops the flag

**Comment by CaptainElliott** [comment]
actually a new feature would need to be implemented to add a kit to a player after dropping the flag if the players kit aren't always the same

**Comment by DoomRobotBoy** [comment]
Can't you just override the speed instead of disabling it? If you give Slowness II or III, while still keeping the Speed, the speed won't matter anymore, since the slowness has a higher level.

**Comment by Ipskie** [comment]
@DoomRobotBoy That's not really a fix, then you just run into issues with classes with slowness (eg. Heavy IIRC)

**Comment by Electroid** [comment]
It's currently impossible in PGM. However, there was recent discussion to code a solution for it.
