### ISSUE TITLE
"Green Wool" and "Green Flag" doesn't show in a green color on the stats

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1691]
lime wool does look green but green looks totally black
![cacaca](https://cloud.githubusercontent.com/assets/8422075/6544530/2a9ad95a-c51a-11e4-925a-4394dca2e6d7.png)

**Comment by Ipskie** [comment]
#1663 It's just a really really dark shade of green, similar to the cactus green in game, which makes it look almost black, especially against a white background. Not an issue

**Comment by matic0basle** [comment]
![](http://i.gyazo.com/11b5a41cfaccd296fc8896e09f45ddbc.png)

**Comment by Brottweiler** [comment]
They are green
