### ISSUE TITLE
You can't take off your armor on QuakeCTF so you can't use the map's gear

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1692]
![2015-03-07_22 08 35](https://cloud.githubusercontent.com/assets/8422075/6544536/5cbc209c-c51a-11e4-9017-ee14c041fe86.png)

**Comment by CaptainElliott** [comment]
I don't understand why you would need to take it off?

**Comment by matic0basle** [comment]
@CaptainElliott There is loot on the map. You can see he already has a chestplate but he is trying to replace it with another one.

**Comment by samtheman43** [comment]
I had this issue too.

**Comment by JTerwiesch** [comment]
Fixed. Also fixed two over powered jump pads that allowed you to get on the roof of the map.
