### ISSUE TITLE
To talk on team chat on /server broken, you need to type /t 2 times

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1693]
While on normal servers you have it by default, on /server broken you need to type it twice, as the picture shows, first /t gives an error message and on the second /t it gives a "you are already on teamchat" message. 
![2015-03-07_21 50 10](https://cloud.githubusercontent.com/assets/8422075/6544538/6e4da952-c51a-11e4-8ac1-6fa935c6f6be.png)

**Comment by ghost** [comment]
Broken doesn't exist anymore. Also there are others issues related with channels: https://github.com/OvercastNetwork/Issues/issues/1786 and https://github.com/OvercastNetwork/Issues/issues/1872
