### ISSUE TITLE
Post appears to reply to itself when replying

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1694]
If you reply to a post, and click the "Original Content" tab, it shows the OP, but also claims that the OP is replying to the OP itself

**Comment by Brottweiler** [comment]
It doesn't show the OP for me...

**Comment by matic0basle** [comment]
@Brottweiler Pretty sure he means "updated 22 hours ago **in reply to** About the Permanant Ban."

**Comment by Brottweiler** [comment]
@matic0basle hmm, but that's the thread you're posting in... should it say "in reply to <username>" or what?

Or does OP mean that, if you're replying to **the thread** and not a single post, it still says "in reply to <thread name>"?

**Comment by matic0basle** [comment]
@Brottweiler The first post is replying to it self because its replying to a thread. Though I don't really think this is an issue. 

The first post is replying to it self because its replying to the thread if you look at the title. I don't know how to explain better. I think thats it at least.

**Comment by Ipskie** [comment]
The OP of the thread is replying to the thread name, which is weird. It's a little like giving a speech on "The Internet" and starting your speech with: "This speech is in reply to the internet"

Anyway I just think when viewing the OP under the original content tab the little "In replay to" thing shouldn't be there

**Comment by Brottweiler** [comment]
Yeah, I see what you mean now. Sounds so minor it doesn't really matter
though.

**Comment by mrapple** [comment]
Yeah this is fine
