### ISSUE TITLE
Website profile button dosen't update.

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1695]
I changed my skin 2 days ago and the profile picture on the website still hasn't been updated, it should have changed by now, right?

**Comment by Brottweiler** [comment]
I checked your skin at `skins.minecraft.net/MinecraftSkins/samtheman43.png` and it seems to match your avatar.oc.tc skin.

**Comment by samtheman43** [comment]
I'll show you, the face on my profile, the (cat with sunglasses) is my current skin and is displayed on the left, on the right, is an older skin that I'm no longer using, but it's still displayed.http://i.imgur.com/BwqTXOE.png

**Comment by Brottweiler** [comment]
Try clear your cache. Or wait a little longer. It should fix itself.

**Comment by samtheman43** [comment]
clear my cache?

**Comment by Brottweiler** [comment]
Your browser cache. Google your web browser and `clear cache`.

**Comment by samtheman43** [comment]
That didn't work, maybe I'll wait another day, and if it dosen't update by then, I post pack?

**Comment by mrapple** [comment]
Skins update very quickly, even when you log in. You didn't change your skin properly or it's a bug on Mojang's end.
