### ISSUE TITLE
[1.8] "Your team lost" message shouldnt appear for observers.

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1697]
Since observers are not participating in the match the text "Your team lost" shouldn't appear for them at the end of the game.

Sorry for back image, got it just as the title started fading.

![](http://i.gyazo.com/3711df61f7d02aa9c31f695dc02b74a1.png)

**Comment by CaptainElliott** [comment]
closing this in favor of an Internal issue we already have
