### ISSUE TITLE
Update for Deadwater (GS)

### ISSUE THREAD

**Issue by minimitch0199** [OvercastNetwork/Issues#1702]
This update adds more land structures (and an updated map.png) in response to https://github.com/OvercastNetwork/Issues/issues/1674#issuecomment-76910225

[Updated download](http://www.mediafire.com/download/l5vt003l8wn3r3i/Deadwater_(gs)_update.zip)

**Comment by ParaSpider** [comment]
You forgot to link it.

**Comment by minimitch0199** [comment]
Oh, right.. It would definitely help

**Comment by ItsMiiOlly** [comment]
Updated.
