### ISSUE TITLE
Spaceship Battles spacesuit chest seems to be inconsistent

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Issues#1703]
I don't have a recent copy of the map to know for certain, but there was changes pushed to fix inconsistencies like the monuments (now coal), but at the start of a match of Nostalgia when we grabbed our suits, it seems the red guy got gold helmet when he walked out while we got chainmail. Still in the fishnet and butterhead format I guess?

![](http://i.imgur.com/l04C8n2.png)

**Comment by Brottweiler** [comment]
They offer the same protection, but gold has less durability I guess.

**Comment by Electroid** [comment]
Those items have never been changed. We'll just keep it how it has been since it's so small.
