### ISSUE TITLE
Revenge TE: Red players spawn facing the wrong direction

### ISSUE THREAD

**Issue by PikminWarrior** [OvercastNetwork/Issues#1704]
On Revenge TE, blue players spawn facing towards the core and the opponent's side, but red players spawn backwards, facing away from the rest of the map.

**Comment by Ipskie** [comment]
For some reason the yaw arguments in the spawn tag were removed, which I _definitely_ do not remember doing... 
@Electroid/ @Brettogden  was the XML edited without my knowledge? Maybe when the stained pain timers were removed? It looks like you reinstated the old spawn systems, which are wrong: the spawn should start at height limit, not y=36

**Comment by Ipskie** [comment]
I think we can close this now
