### ISSUE TITLE
Palace CTF V1.1.0 Update

### ISSUE THREAD

**Issue by Diamyx** [OvercastNetwork/Issues#1705]
Changelog:
- Added ladders to river
- Made it easier to get across the river using the boat
- Moved the net to where the flag is, replace the old net with decoration
- Indented stone paths by .5
- Added more obstacles such as: a hole to the sewer, market stalls, raised bits of land
- Made it more obvious that the inside of the buildings is actually usable, and added more bridges to help attackers
- Added feather falling
- Added stone sword
- Added golden apple killreward, as well as 1 golden apple on spawn

XML: https://gist.github.com/ajtag5/a84de6349157f5c7d5b8
Packaged Download: http://www.mediafire.com/download/enp1a3vpr43s6u1/Palace+CTF.zip

**Comment by Brottweiler** [comment]
Protip: When making lists, you need to have a space after the dash, like this:

```
- Added ladders to river
```

**Comment by JTerwiesch** [comment]
Closed by JT. Yo. Github makes sense now.
