### ISSUE TITLE
Website bug?

### ISSUE THREAD

**Issue by Cevans98** [OvercastNetwork/Issues#1706]
So when I do oc.tc/FORUMS or OC.TC/FORUMS (I use caps for sprint, it's often enabled) it takes me to oc.tc/ItzChilledO_o (aka Chilledfillet aka forums). I'm guessing since his old name was forums, capatalized forums takes you to his profile? Bug?

**Comment by mrapple** [comment]
Not a bug, you need to use the proper casing to access our web pages.
