### ISSUE TITLE
The Grove - Fall damage and slime block glitching

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1708]
Issue 1 - Fall damage
You take fall damage exiting out of spawn

Issue 2 - Slime blocks glitching
You can't use the pressure plates + slime blocks 0n the map to jump up because its very glitchy and teleports you back down (I assume its NCP)

**Comment by Electroid** [comment]
Done.

**Comment by TheMolkaPL** [comment]
Slime blocks doesn't work. Tested Larnia on CTF, and NCP had teleported me back down.
