### ISSUE TITLE
My Ping has been increasing for no reason.

### ISSUE THREAD

**Issue by nebwr** [OvercastNetwork/Issues#1711]
So I just moved back to where I used to live and I used to have around 70 ping but now I have around 200ms instead. I use the same computer, same cable and same internet provider. So basically nothing changed except for my ping

I also checked through speedtest what my ping to Amsterdam isand I have 48 ping to all Amsterdam servers

**Comment by Ipskie** [comment]
This is not really a place to report these kinds of issues, particularly if it's not everyone. I'm willing to bet this is purely client side

**Comment by mrapple** [comment]
Please send your IP and traceroutes to support@oc.tc
