### ISSUE TITLE
Players with /nick can nick themselves as just one letter

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1714]
Not sure if intentional, but i think it shouldn't be because people can't get those names anymore as a real name.

**Comment by matic0basle** [comment]
The point of the command (for me) is to make the people blend in and not be able to get recodnised so they can record without being disturbed. This completely removes the blending part so even if its intented it should be changed.

**Comment by matic0basle** [comment]
Just a question. Could this could as abuse of the /nick command?

**Comment by Brottweiler** [comment]
@matic0basle not really

**Comment by matic0basle** [comment]
@Brottweiler In my eyes I thought it could be because it just attracts more attention and defeats the purpose of the command. Thanks for the responce.

**Comment by Brottweiler** [comment]
@matic0basle it's a bug that needs to be fixed

**Comment by Tapetepato** [comment]
Players can nick themselves as a number:
![2015-03-16_21 30 29](https://cloud.githubusercontent.com/assets/8422075/6680936/1cb477a4-cc24-11e4-992a-f04fb3a6b0a2.png)
(also yeah nicked  player is definitly being a good sport)

**Comment by Brottweiler** [comment]
@Tapetepato Numbers are not illegal characters in usernames, the bug is that they can nick themselves one letter (or number).

**Comment by Biix** [comment]
The minimum number of letters for nicks should be 3, also I've been seeing a lot of nick abuse recently.

**Comment by Electroid** [comment]
Report any abuss at oc.tc/report. For now, no more comments.

**Comment by Brettogden** [comment]
New rules have been announced. https://oc.tc/forums/topics/5511950a5f35b9c8ef001ef0

Use oc.tc/report to report abuse.

**Comment by Brottweiler** [comment]
This is still a bug that needs fixing, though, since 1-2 letter usernames aren't actually possible.

**Comment by jedediah** [comment]
fixed
