### ISSUE TITLE
TF2 Badlands CTF - Engineer class can painloop and spawn infinite mobs

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1715]
You've probably seen it yourself; a spawn spammed with more mobs than 10 guys could create. When an engineer suicides (or jumps in his own portal again; thanks Ipskie) he can spawn mobs over and over, resulting in something close to this:

http://i.imgur.com/DVYIHVn.png

Its probably a known bug, but I just wanted to report it.

**Comment by Ipskie** [comment]
Actually you don't even need to commit suicide you just need to jump into the class-wiping portal and reselect engineer

**Comment by Electroid** [comment]
Known bug, but unfixable. It's awaiting a future module that has not be announced.

**Comment by DoomRobotBoy** [comment]
You can at least deny the access to players already having the engineer class to the spawn portals, because that looping is annoying and can be fixed. The suiciding may be unfixable, but it is also a pain to do (mostly because engineers can only die by enemy hand).

**Comment by Ipskie** [comment]
@DoomRobotBoy if it's waiting on a soon-to-come module, a temp fix isn't really worth it
