### ISSUE TITLE
Please change the Mini02 rotation.

### ISSUE THREAD

**Issue by Cevans98** [OvercastNetwork/Issues#1719]
It's pretty much EU's only full server, and it's been the same set of 11 maps since August 28th 2014. It is so boring and repetitive to play the exact same maps over and over and over. Especially considering that people just rush for the wool so the rot is over so quickly. Please just remove Mini02, and replace it with Mini04's rot. People LIKE dtm and dtc minis too ya know, but we never ever get to play them anymore. In fact, they're the ones that encourage the most teamwork, and generally get plenty of defenders. Which is what OCN is all about, teamwork, not who can farm the most wools.

**Comment by TiTo-418** [comment]
Please post this <a href="https://github.com/OvercastNetwork/Rotations">here</a>

**Comment by Ipskie** [comment]
Post in rotations, not here. Also some specific requests for changes wouldn't go amiss
