### ISSUE TITLE
Les V1.1.0

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1720]
Bringing you an updated version of the map with the feedback I recieved on my submittions page.

Change Log:

 - Improved paths layout
 - Added a ceiling that has bottom layer paths drawn on it
 - Changed color of wood of the top layer
 - Make the nets bigger

New download: http://www.mediafire.com/download/so74gu8d9m8sbhl/Les_V1.1.0.zip
New XML (also in DL): https://gist.github.com/matic0basle/948c31fa82f06105de13
New images: http://imgur.com/a/0V5Xk

**Comment by samtheman43** [comment]
just letting you know, you misspelled "ceiling"

**Comment by Brottweiler** [comment]
@samtheman43 it doesn't matter, and is not relevant.
