### ISSUE TITLE
[Server] Text on signs contains quotation marks or null [1.8]

### ISSUE THREAD

**Issue by MathSquared** [OvercastNetwork/Issues#1721]
PROBLEM: All signs on maps seem to be displaying with quotation marks surrounding each line. Lines that should be empty instead display the string `null` with no quotation marks.
![Picture of a sign: null - "2 - Team" - "Version" - null](https://cloud.githubusercontent.com/assets/7842810/6700464/a2dd9e7e-ccdc-11e4-88ea-ab78d25c9c53.png)
I don't have an image for this next problem, but this leads to some lines that were previously just long enough to fit on a sign being cut off. This can be seen on Grimsnes with the author's name sign.

DETAILS: Accessing the server using a 1.8.3 client, unmodded, on Ubuntu Linux 14.04.1 LTS, with Oracle Java 8u11. Problem witnessed on at least two maps, Grimsnes and The Dome. This problem does not occur in the lobby.

POTENTIAL SOLUTION: No clue, but I feel like it's a bug in either the server-to-client protocol or map storage. Maybe with the hybridized 1.7/1.8 server implementation?

**Comment by Electroid** [comment]
The map was edited in 1.8, that server is 1.7. This will be fixed automatically when we updated fully to 1.8.
