### ISSUE TITLE
Wrong objective message in few CTF Maps

### ISSUE THREAD

**Issue by ingan914** [OvercastNetwork/Issues#1722]
<a href="http://imgur.com/IhmlYU8"><img src="http://i.imgur.com/IhmlYU8.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/ao5c3Ng"><img src="http://i.imgur.com/ao5c3Ng.png" title="source: imgur.com" /></a>

150318 7:20 KST

**Comment by Superjd10** [comment]
It's the map's XML description, feel free to edit it yourself.
