### ISSUE TITLE
Offset players / bad spawn in Bliss

### ISSUE THREAD

**Issue by Tanpiku** [OvercastNetwork/Issues#1723]
This usually only occurs when something is wrong with the spawn, making them visually glitched. I'd assume this is a map problem. Occurred for another person in the same match, and I've seen this happen on the map before as well.

![](http://i.gyazo.com/9ba4b7a4b1cdb496cc1d70527395a16f.png)
![](http://i.imgur.com/kmdb5oy.png)
![](http://i.imgur.com/ICjWust.png)
![](http://i.imgur.com/MPwd9Pw.png)

**Comment by samtheman43** [comment]
Don't think this is a server-side glitch, It's a Minecraft glitch.

**Comment by ParaSpider** [comment]
I've only seen it on this map, besides a few where players would spawn on slabs or had spawn issues in general. I think it's something to do with the XML.

**Comment by Brottweiler** [comment]
It used to happen on certain maps, when spawn was fixed it stopped happening I think (Fenland for example).

**Comment by AnthonyTag** [comment]
I don't believe this is still an issue. Closing, open if it occurs again and please provide proof (video/screenshot).
