### ISSUE TITLE
Safehouse V0.1.2 [XML only]

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Issues#1731]
Change Log:
 - Add Elliott_ as a contributor for making the original XML
 - Add Valve Corporation as a contributor for making the original map
 - Lower return time on flags from 25s to 20s
 - Add gapple kill reward

New XML: https://gist.github.com/matic0basle/896188962dfa8912d059

**Comment by CaptainElliott** [comment]
Was this xml directly from maps.oc.tc?

Just checking to make sure it will merge and work fine :)

**Comment by matic0basle** [comment]
Yes and was formatted with to use 2 spaces with http://www.freeformatter.com/xml-formatter.html

**Comment by CaptainElliott** [comment]
if you could format it to 4 spaces that would be great :)

**Comment by matic0basle** [comment]
@CaptainElliott https://gist.github.com/matic0basle/bf932cdda73f1a16f11d
