### ISSUE TITLE
Disconnect for "Loading NBT data" on Broken

### ISSUE THREAD

**Issue by twizmwazin** [OvercastNetwork/Issues#1734]
This issue has happened to me twice, both on a unmodified 1.8.3 client. The client is disconnected from both the Minecraft server and BungeeCord server, due to a packet de-serialization exception. I have not found a clear action to reproduce this.

Full message:
`Internal Exception: io.netty.codec.DecoderException: f: Loading NBT data`

**Comment by matic0basle** [comment]
Someone on the server had the same issue and asked me where to report it, I gave him the link to the repo but looks like he didnt end up posting it.

And it also happened to me once with 1.8.1 but with optifine so it doesnt count because its modded,

**Comment by samtheman43** [comment]
Happened to me too.

**Comment by Electroid** [comment]
Pretty sure it's no longer an issue.
