### ISSUE TITLE
Map Update - Explosive Vengeance 2.0.0

### ISSUE THREAD

**Issue by HardstyleRaver2** [OvercastNetwork/Issues#1737]
About 3 months ago, Doomboy and I updated this map. Further details, download, and the XML of the map can be found in this thread: https://oc.tc/forums/topics/549b9d8f5f35b9cc7d001059

**Comment by Ipskie** [comment]
Link 404s

**Comment by HardstyleRaver2** [comment]
The link 404s on you because the thread is in the map submissions forums in which only the map devs can see it.

**Comment by HardstyleRaver2** [comment]
Is someone going to update this?
