### ISSUE TITLE
Bill's Town Version 1.1.0

### ISSUE THREAD

**Issue by yoyopower** [OvercastNetwork/Issues#1738]
**Changelog**

 - Fixed possible leaf parkour.
 - Fixed region bug which allowed players to enter the wrong net/spawn.
 - Changed spawn design to prevent confusion.
 - Fixed players being able to use the enemy portals.
 - Removed the time limit and changed the maximum score.
 - Changed the position of the goal.
 - Changed the spawn area.
 - Added tips on how to play the map.

https://www.mediafire.com/?8gce66cnnhheu70

**Comment by Diamyx** [comment]
http://pastebin.com/mbkC8MWM here's the XML in case the one in the download doesn't work properly
