### ISSUE TITLE
OcTc Bug : I can fly on broken

### ISSUE THREAD

**Issue by TheDarklink12** [OvercastNetwork/Issues#1741]
Hi, In broken, I'm dead. After my respawn, I want spam my space bar for up stairs more speed but I flying.
When I double space, I'm fly like a creative mode.
This is a record of my bug : https://www.youtube.com/watch?v=VRyANWYKx14&feature=youtu.be (sorry for "demo mode" in the screen)
When I join observer and rejoin a team, I again fly.
After disconnect/reconnect , the bug is solve.
Thank you 
Sorry for word mistakes, I'm french ;)

**Comment by Ipskie** [comment]
did you check if it was client side only or could you hit players and stuff while flying? Obviously you shouldn't abuse this too much but just to check

**Comment by TheDarklink12** [comment]
Yes, my friend confirmed my fly, he is with me on call and in game.

**Comment by TheDarklink12** [comment]
But now I've disconnect the server, because I do not want to get banned

**Comment by CaptainElliott** [comment]
I can't reproduce

**Comment by TheDarklink12** [comment]
It's a first time I see this bug, after disconnect / reconnect he is solved.

**Comment by Ipskie** [comment]
Please tell us what you did leading up to this, your version, any actions you may have performed, etc. If the devs can't reproduce it they can't fix it

**Comment by TheDarklink12** [comment]
Minecraft Version 1.8 with Optifine
I played normally but when other player kill me, I think I've spam my left click for respawn.
When I've respawn I spammed my spacebar to climb stairs faster.
But double space made me fly.

I try to reproduce this for help you but I can not.

**Comment by Electroid** [comment]
Unreproducible and haven't seen that bug report since. It's probably been fixed. Report back if you experience this again.

**Comment by ghost** [comment]
https://oc.tc/forums/topics/55aebd34c29635b77e00fe58

**Comment by TheNoisyBoy** [comment]
Seems to be re-appearing.

**Comment by ghost** [comment]
Broken doesn't exist anymore
