### ISSUE TITLE
[BUG] Scorebox on Bill's Town leads to enemy spawn

### ISSUE THREAD

**Issue by CrazyCreeper521** [OvercastNetwork/Issues#1742]
On the map Bill's Town, the scorebox on purple side leads to orange spawn. While on purple, you can enter the scorebox (which should not be allowed), and it will teleport you back to orange spawn as if you were an orange player.

**Comment by yoyopower** [comment]
Should be fixed in #1738

**Comment by itsmartin** [comment]
Thanks, this is a duplicate then.
