### ISSUE TITLE
Sr.Mod is offensive according to ChatMod

### ISSUE THREAD

**Issue by MobbareKurtZ** [OvercastNetwork/Issues#1744]
![2015-03-26_16 32 31](https://cloud.githubusercontent.com/assets/9394074/6849617/9244e640-d3d4-11e4-9ab2-e0d093475814.png)

As seen on the picture above, according to ChatMod "Sr.Mod" is "offensive content". Been told to report it here. This can be reproduced by simply typing "Sr.Mod" in chat.

**Comment by itsmartin** [comment]
Seems likely that it's misidentifying it as a URL.

**Comment by SuicuneScale** [comment]
I believe that this is due to Chatmod seeing it as an IP.

**Comment by MobbareKurtZ** [comment]
Yes that might be it, is there any way to filter this out from ChatMod?

**Comment by itsmartin** [comment]
Should be fixable. Actually looks like there's already an issue for this, #1097.
