### ISSUE TITLE
Incorrect regions on Blocks II

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#1747]
This map is bugged. When you break a piece of the core (at least on Blue Team), it doesn't show any touch and when it's leaked it doesn't count on stats. There are some places where you can't place or destroy blocks like the TNT, the cake, etc. Please, fix it.

**Comment by Brottweiler** [comment]
>it doesn't show any touch and when it's leaked it doesn't count on stats

Does it affect the game? Then it should count to your stats...

>There are some places where you can't place or destroy blocks like the TNT, the cake, etc

Where? Give exact locations.

**Comment by 2000thehecf1** [comment]
@Brottweiler I break a piece of the glass, it turns into obsidian, and when I break the obsidian and I leak the core it doesn't count on stats, it doesn't show on chat "2000thehecf1 broke a piece of Core"... it isn't detected. The scoreboard turns from untouched to complete when it leaks.
And, for example, when you're tunneling under some of the estructures of the map (I'm not sure which are them) and you want to go to the surface by breaking a block of that estructures, the map does not allow you to do it. I'm sorry for being unclear, but I don't know how to explain it correctly.

**Comment by FabioUnderscore** [comment]
Bumping this and giving localization: I broke a piece of glass above the core, the last level where the lava is on, and after breaking the obsidian it didn't count. The core started to leak, but didn't show as a objective touched (Like monuments). Lava started to flow and the game ended "without" touchs.
