### ISSUE TITLE
When displaying online staff, does not specify the exact server in some cases.

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1753]
Just noticed this while checking for online staff.
![2015-03-29_08 49 08](https://cloud.githubusercontent.com/assets/10585916/6885509/b27f9f72-d5f0-11e4-9848-30722c5cc329.png)
![2015-03-29_08 49 19](https://cloud.githubusercontent.com/assets/10585916/6885512/b8c4c4b6-d5f0-11e4-9bc5-2640e270886a.png)

**Comment by itsmartin** [comment]
The staff member is on eu.oc.tc. That datacenter has only one capture server.

**Comment by samtheman43** [comment]
Oh, my bad. Thanks for the clarification!
