### ISSUE TITLE
Players on one team can't use the jump pads on the enemy team side on Canopy

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1758]
![2015-03-30_17 33 17](https://cloud.githubusercontent.com/assets/8422075/6909452/8fb16ec6-d703-11e4-963b-26d7b8b5c1c9.png)
![2015-03-30_17 35 24](https://cloud.githubusercontent.com/assets/8422075/6909453/8fb8bc8a-d703-11e4-879d-1e474788a53f.png)
![2015-03-30_17 35 37](https://cloud.githubusercontent.com/assets/8422075/6909454/8fbb49f0-d703-11e4-9f6f-d4710cd08237.png)

**Comment by Ipskie** [comment]
Might be intended

**Comment by Electroid** [comment]
Intended, hence the color coded pads.
