### ISSUE TITLE
Better indication of offline servers.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#176]
# Current Behavior

Currently the play page says something like "1 server offline", when a server is offline , but it is difficult to figure out which one(s).

# Suggestion

Something like the image below, to indicate which server(s) is offline.

![](http://i.imgur.com/PneyKeo.png?1)

**Comment by ghost** [comment]
I think this can be closed, offline servers don´t show up anymore on oc.tc/play

**Comment by Pugzy** [comment]
Issue no longer applicable due to play page revamp.
