### ISSUE TITLE
Incorrect sign and spawnkit chest on Justice

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1760]
The map is called "Justice" in /map but on the sign its called "Justice at Dawn"
![2015-03-30_17 55 05](https://cloud.githubusercontent.com/assets/8422075/6909761/df89c1a2-d706-11e4-8c43-bf035b6172bb.png)
The spawnkit chest is different form the spawnkit:
![2015-03-30_17 55 19](https://cloud.githubusercontent.com/assets/8422075/6909757/d0ad9168-d706-11e4-9410-3345c491cf5a.png)
![2015-03-30_17 58 56](https://cloud.githubusercontent.com/assets/8422075/6909766/e6cc5d4e-d706-11e4-9db4-d66cbc2a22af.png)

**Comment by Electroid** [comment]
Small detail. @Tywnis can fix this if he wants.
