### ISSUE TITLE
Sometimes when you die on CTF you can fly

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1761]
![2015-03-30_17 51 21](https://cloud.githubusercontent.com/assets/8422075/6909786/0ef19f3c-d707-11e4-8528-ec381ae1b0ec.png)

**Comment by Ipskie** [comment]
#1741 related?

**Comment by mrapple** [comment]
What map is this? Some maps allow spectating after dying

**Comment by SkylerTyler1337** [comment]
That's Concourse

**Comment by Diamyx** [comment]
I think this happens on Concourse because of the Blitz respawning. You can't respawn until the flag is dropped.

**Comment by Oxinous** [comment]
You are basically on gamemode 1, you can break blocks and fly. This happens in some blitz maps.

**Comment by mrapple** [comment]
If you look at https://maps.oc.tc/CTF/Standard/Concourse/map.xml, you will see `<respawn spectate="true">`. This means you can fly around after dying. However, you should not be able to break blocks @Oxinous. My guess is your block break actions were cancelled and you weren't actually breaking blocks. I'm going to close this issue.
