### ISSUE TITLE
Private Messages send more than once

### ISSUE THREAD

**Issue by JoshuaDueck** [OvercastNetwork/Issues#1763]
**Issue:** When sending a message in-game the player receiving my message gets it 2 times, in some cases more. It seems to be random when they receive the message more than once.

**To Reproduce:** I was nicked, a friend PMed me and I PMed back. After about 1 or 2 messages from me he told me it sent twice. Throughout the conversation he told me when it did it again.

This may not be a server bug though, just an issue with the player, as the player who received the messages twice also had a similar experience with iPGz (who had screenshots). This player is Pelpelajax. I figured this was worth reporting anyways.

**Comment by JoshuaDueck** [comment]
Whoops

**Comment by Brottweiler** [comment]
Happens to a lot of people, and it's known but not sure if it was reported before.

**Comment by Electroid** [comment]
No longer an issue this is.
