### ISSUE TITLE
Players can be attacked whilst in the wool rooms in Tetrad

### ISSUE THREAD

**Issue by TheMoMan** [OvercastNetwork/Issues#1767]
https://oc.tc/forums/topics/551cedc867d52236590018b3

This is concerning a glitch in the game where players can break the glass behind the wool rooms and attack players inside the wool rooms before the glass reappears. It is currently against the rules, but it seems to be a growing issue that would just be easier to fix in the map than issuing punishments.

**Comment by Brettogden** [comment]
The map devs looked into fixing it, it's really possible to fix so we'll just punish players who abuse the glitch.

**Comment by Electroid** [comment]
Nah, can be done with magic.

**Comment by Electroid** [comment]
Magic completed.
