### ISSUE TITLE
Zap: Cubist Remix Spawn issue

### ISSUE THREAD

**Issue by himan22566** [OvercastNetwork/Issues#1770]
I dont know if this happens for any other teams, but when I was on red, 75% of the time i got stuck bouncing in the floor. I had to place water on top of myself to get out.

**Comment by samtheman43** [comment]
Your issue is a bit unclear, maybe specify a bit more?

**Comment by himan22566** [comment]
You know when you get stuck in a black and you are constantly bouncing up and down? That's what happened

**Comment by mrapple** [comment]
Where on the map do you get stuck? Can you provide more details/a screenshot?

**Comment by SkylerTyler1337** [comment]
I think he means when they spawn. They get stuck.
