### ISSUE TITLE
U-Boat Konig - "glitched" pickaxes

### ISSUE THREAD

**Issue by Zozoo1** [OvercastNetwork/Issues#1774]
On this map, once you get a few kills, you are given a pickaxe that is supposed to be used twice apparently.

But if you use it once, it's durability lowers by one, and if you hold it in your hand and right click, it's durability goes back to it's original state, meaning that you can use it more than twice, and get more diamond gear than intended.

**Comment by Brottweiler** [comment]
I think it has infinite durability still and the map xml needs to be changed so that doesn't happen.

**Comment by Ipskie** [comment]
@Brottweiler 
<killreward>
<filter>
<kill-streak count="4"/>
</filter>
<item amount="1" damage="249">iron pickaxe</item>
</killreward>

**Comment by Brottweiler** [comment]
@Ipskie I think the XML doesn't allow the tool to loose durability. I think that might be a default.

**Comment by Pugzy** [comment]
The map has received an update and pickaxes are no longer used.
