### ISSUE TITLE
Certain Ghost Squadron maps have bugged spawn signs.

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1775]
![](http://i.imgur.com/nlk5xNZ.png)

![](http://i.imgur.com/lguqIo4.png)

**Comment by Ipskie** [comment]
looks like they got converted to JSON. Say, were you in 1.7?

**Comment by matic0basle** [comment]
This might happen if you are on 1.7 and the signs were saved in 1.8. I know its something to do with versions not sure exactly how it goes though.

**Comment by Brottweiler** [comment]
Not sure if map bug or if you just need to use 1.8.

**Comment by samtheman43** [comment]
I was in 1.7 at the time I took the screenshots, though I just checked in 1.8 and they are still bugged.

**Comment by Diamyx** [comment]
Happens when a map made in 1.7 is edited in 1.8; it's the map itself that needs to be fixed, it's not server side.

**Comment by matic0basle** [comment]
@Diamyx Will be fine when the server goes fully 1.8 I think.

**Comment by samtheman43** [comment]
@matic0basle though it is still, a bug.

**Comment by ItsMiiOlly** [comment]
Will be fine in 1.8.
