### ISSUE TITLE
SuperCUBE Health Kits don't heal you

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Issues#1779]
The Health Kits on SuperKUBE don't heal you. Some players said that they still worked for them.

How to reproduce:
Get damage and drink a Health Kit on SuperCUBE.

Example:
http://youtu.be/JR14qIhY7QA

Match where the issue appeared:
https://oc.tc/matches/55218e92c8f2a521ef1ff858

**Comment by Electroid** [comment]
Should be fixed now.
