### ISSUE TITLE
Wool don´t regen in chests

### ISSUE THREAD

**Issue by RubeGamerV** [OvercastNetwork/Issues#1780]

**Comment by Superjd10** [comment]
Details? Server, map, pics, video, anything?

**Comment by Brottweiler** [comment]
@Superjd10 He's saying wool doesn't regen in chests, so you'd have to assume he means globally... if they do regen, then this issue can be closed

**Comment by mrapple** [comment]
I think they do. Provide evidence and we'll reopen.
