### ISSUE TITLE
XML Projectiles gun cant fire after reload

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1781]
i messed around with the new <prjectiles> module, and after i fire with a gun, and it is done reloading, i cant fire with it again. here is my xml:  http://pastebin.com/at5242WV the module is located from line 118 till 146.

edit: found out, by switching teams, you still cant shoot with hte guns when you already shot once that match.

@jedediah @mrapple @YukonAppleGeek @Electroid

**Comment by Electroid** [comment]
Yukon is going to make a PR to fix this as well as other problems soon.

**Comment by mrapple** [comment]
Note, no need to tag all of the developers in an issue. We already watch this repo.

**Comment by Electroid** [comment]
Fixed and deployed.
