### ISSUE TITLE
[bug] - TNTPrimed projectile gun ignores  <disabledamage>

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1784]
when using a TNTPrimed entity for your projectile gun, it deals damage to your allies, while 

<disabledamage>
    <damage ally="true"

is setted up.

xml: http://pastebin.com/3nf7ms7P line 126-163

edit: the tnt fuse time does not effect the TNTPrimed, i would like to see a fuse time option inside the projectile module or the TNTPrimed fuse time being the same as the setted up normal tnt fuse time.

**Comment by Ipskie** [comment]
Maybe it's being spawned in as world TNT? Is it crediting kills correctly when you use it?

**Comment by CaptainElliott** [comment]
Closing in favor of an internal issue but thanks for reporting!
https://github.com/OvercastNetwork/Internal/issues/207
