### ISSUE TITLE
Weird jump pads on The Grove

### ISSUE THREAD

**Issue by Diamyx** [OvercastNetwork/Issues#1787]
The jump pads on The Grove not only work on the lime stained glass square where they're supposed to work (in the side towers), but they also work in a line outside of the towers. Here's a video example: https://www.youtube.com/watch?v=1EtywNFuPY8

**Comment by Ipskie** [comment]
apply velocity="0,1.25,0" filter="not-carrier"
cuboid min="31,21,51" max="28,22,48"
cuboid min="27,21,51" max="-30,22,48"
/apply

That -30 looks suspicious
