### ISSUE TITLE
No Return - Lava on the purple side starts flowing before the lava on the blue side starts flowing

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Issues#1788]
![2015-04-06_22 24 42](https://cloud.githubusercontent.com/assets/7583795/7066934/6ab66060-dec7-11e4-943b-c7729131c3d5.png)
The lava on the purple side starts flowing before the lava on the blue side starts flowing, so the purple team has a huge disadvantage.

**Comment by CoWinkKeyDinkInc** [comment]
Both sides are triggered by tripwires, they should be going off at the same time when players spawn.  I think that a piston that breaks the redstone should be added to stop major stalling of lava like this.

**Comment by CaptainElliott** [comment]
The lava should probably flow automatically when the match starts by just having the lava not contain when the world file is saved

**Comment by Ipskie** [comment]
@CaptainElliott Use a monument mode to have a barrier disappear at the start of the map and update the lava so it starts flowing maybe?

**Comment by CaptainElliott** [comment]
@Ipskie There is no need for that, physics before the match starts are disabled so you don't need anything

**Comment by Electroid** [comment]
This has never happened before, seems weird why it would now..

**Comment by thestrangeboy1** [comment]
Are you sure the lava wasn't rendering properly for blue team's side? I played a match of No Return today and I didn't experience the lava moving any faster or starting faster/delaying longer from the match start.

**Comment by BlueManOtti** [comment]
@thestrangeboy1 since I wasn't the only one in this match who experienced this lava delay, I am pretty sure it wasn't a render error or are render errors server side? 
But I also played matches after this where this bug didn't appear.

**Comment by minimitch0199** [comment]
This occurred again yesterday. The tripwire on the purple side had not been clipped when the players spawned. I was able to force myself into the match and trigger the tripwire activating the lava.

**Comment by AnthonyTag** [comment]
Doesn't seem to be an issue anymore. If it occurs again please reopen and provide proof (video/screenshot).

**Comment by H2giulio** [comment]
It happened again today (map version 2.1.3). http://youtu.be/W_wYwJAlwBo

**Comment by AnthonyTag** [comment]
This bug is constantly going to happen randomly with every version of this map. Do not reopen this issue unless you find a way to 100% reproduce this bug every match.
