### ISSUE TITLE
If you report someone you are able to see infractions which you can't see on their infractions tab.

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Issues#1789]
If you report someone you are able to see infractions which you can't see on their infractions tab.
![1](https://cloud.githubusercontent.com/assets/7583795/7067813/6809b7c0-dece-11e4-92c1-749bb7bd8b99.png)
![2](https://cloud.githubusercontent.com/assets/7583795/7067862/a3ac9298-dece-11e4-8af2-c728f6069ffd.png)

**Comment by itsmartin** [comment]
https://github.com/OvercastNetwork/Internal/issues/206
