### ISSUE TITLE
Doors can bypass height limit

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1793]
<b>1. The issue</b>
Doors can bypass height limit (If the height limit is 50, the above block is in 51)

<b>2. Steps to reproduce</b>
If the height limit is 50, place a door in the height 49

<b>3. Miscellaneous information</b> 
https://oc.tc/forums/topics/552221ab5f35b9ff0b000c89
https://github.com/twizmwazin/CardinalPGM/issues/556

**Comment by Ipskie** [comment]
Like I said on the thread: minecrafts default height limit has a similar "bug" so this could be classified as vanilla behaviour

**Comment by CaptainElliott** [comment]
It is but it is something that should be patched. I could not find a way to detect if a block is 2 blocks high, even getting the y value on returns the Y value of the bottom block. So the only way that I am aware of is to hard-code in the 2 high blocks

**Comment by Electroid** [comment]
The way to fix this would be checking the y-values of the blockstates in BlockMultiPlaceEvent.

**Comment by ghost** [comment]
Fixed
