### ISSUE TITLE
[Website] Some user's avatar's skins have unusual white features.

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1796]
![capture](https://cloud.githubusercontent.com/assets/10585916/7108645/0c2c5338-e15b-11e4-9a26-62eaf4f4fa6e.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10585916/7108646/0da696a6-e15b-11e4-8473-9093c7dab797.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10585916/7108647/0f6be8c4-e15b-11e4-8474-5f017cc6704b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/10585916/7108649/1101bbe6-e15b-11e4-9c97-7f4fa06efd97.PNG)

**Comment by TiTi-418** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/1544
