### ISSUE TITLE
My gamemode is sometimes set to the 1.8 observer gamemode in the lobby, and sometimes not.

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Issues#1799]
I don't know if it's a bug, or if it's meant to be that way, but my gamemode switches between the regular fly perms (from my rank) where I cannot fly through blocks to some kind of 1.8 observer gamemode (I'm in 1.8.3 by the way).

Also, the reason why I find this annoying is the fact that I cannot click any signs while I'm in this "observer" gamemode.

Here is a small footage of the bug: http://youtu.be/rw1AuPfNVto

**Comment by mrapple** [comment]
How to reproduce?

**Comment by samtheman43** [comment]
I can't reproduce.

**Comment by mrapple** [comment]
Did this happen after switching servers? Bungee is notorious for losing packets when switching servers

**Comment by Timothee38** [comment]
Hello, sorry for the late response, I think it happened when I did /hub, it also does not occur offently, but it does it sometimes. Do you think it could be client related?

**Comment by mrapple** [comment]
Yeah, I don't think this is anything we can easily fix
