### ISSUE TITLE
Timelimit isn't always enforced

### ISSUE THREAD

**Issue by RubeVi** [OvercastNetwork/Issues#1800]
The limit is 10 min an this pic show 20 min
<a><img src="http://i.gyazo.com/7ce0d0db038fa6d4613e3e1d8bcaf6cc.png" /></a>

**Comment by Ipskie** [comment]
Just to check, are you sure the mod didn't extend the TL with commands?

**Comment by CoWinkKeyDinkInc** [comment]
@Ipskie The guy in the chat says thanks, I think it is.

**Comment by Superjd10** [comment]
@CoWinkKeyDinkInc @Ipskie Or maybe he /end'd the match.

**Comment by RubeGamerV** [comment]
SheriffSoco end the match, then he told "/cancel is broken" or some like that i didn´t remember

**Comment by SkylerTyler1337** [comment]
What's the actual issue?   @RubeGamerV

**Comment by Superjd10** [comment]
@SkylerTyler1337 Matches don't finish at time limit, they last longer. In the example, the mod has to end it manually.

**Comment by SkylerTyler1337** [comment]
oh

**Comment by SkylerTyler1337** [comment]
Is it just this map, or more?

**Comment by mrapple** [comment]
Checked the logs, no exceptions but the timelimit never ended the match

**Comment by Electroid** [comment]
It is enforced. A staff manually cancelled it with `/cancel`.
