### ISSUE TITLE
Not showing ingame motd

### ISSUE THREAD

**Issue by RubeVi** [OvercastNetwork/Issues#1801]
<a href="http://gyazo.com/f227dd13a84c9b612b71e8a7638000e7"><img src="http://i.gyazo.com/f227dd13a84c9b612b71e8a7638000e7.png" /></a>

**Comment by Ipskie** [comment]
Do you mean the welcome message? I can't see anything horrendously wrong with this image. Also can other people reproduce this or can you provide steps to reproduce?

**Comment by TiTi-418** [comment]
1.Join the server
2.Look at the chat
<a href="http://imgur.com/cUX4Qnw"><img src="http://i.imgur.com/cUX4Qnw.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
Fixed https://github.com/OvercastNetwork/Issues/issues/1881
