### ISSUE TITLE
Match links don't show observers that were on the match anymore

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1802]
They used to do where there are the people on the teams, but now it only shows the people that joined the teams, not the observers:
https://oc.tc/matches/553055a7c8f2b0c38469aa9f 
As you can see on that link (or on any other match link) it just has the teams and the players, no observers.

**Comment by Ipskie** [comment]
I'm willing to guess this was intentional, though there are no revisions explicitly mentioning it

**Comment by Brottweiler** [comment]
Intentional
