### ISSUE TITLE
/server does not work anymore

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1803]
/server does not show the server you are on, it says this message now:
![2015-04-16_20 05 41](https://cloud.githubusercontent.com/assets/8422075/7194396/141239c0-e474-11e4-902f-c6657f4dbf85.png)
As you can see because of the map, im on Primed on the screenshot, and i did /server to check if im on there, but instead of "you are playing on primed" it gives me the "to change servers you need to do /server" thing
How to reproduce; Go on any server and do /server

**Comment by Superjd10** [comment]
Duplicate #1608. "/server is working in the 1.8 branch" -Electroid.
