### ISSUE TITLE
Players Flickering In and Out

### ISSUE THREAD

**Issue by AgentRune** [OvercastNetwork/Issues#1806]
1. Issue: Players have begun to flicker in and out. One moment the player is there the next they have disappeared. It only started to happen in the past few days though I was inactive for a while due to fps issues which is now resolved.

2. Steps to reproduce: Its difficult to reproduce due to it being other players. However, I've noticed it mainly happens when people place blocks down as they run or block glitch. 

3. Video Evidence: https://youtu.be/TmtMsiLDk0w

**Comment by Brottweiler** [comment]
You sure you are not running any mods of any kind?

**Comment by BlueManOtti** [comment]
I think this bug only occurs in 1.8.3, but I am not sure about it.
There is also a forum post about it: https://oc.tc/forums/topics/552029d75f35b96101002507

**Comment by CoWinkKeyDinkInc** [comment]
I have seen this happen with other entities like Primed TNT.  I just have optifine installed.

**Comment by Brottweiler** [comment]
Uninstall Optifine, report back if it still happens or not.

**Comment by mrapple** [comment]
This can't be an issue on our end

**Comment by samtheman43** [comment]
I can reproduce/notice this.

**Comment by mrapple** [comment]
Do you have any client mods? Is it only on specific maps?
