### ISSUE TITLE
CTF - Able to roam freely while in death screen

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1808]
At random it seems, being killed while running allows free roam in "death mode".

Example - https://youtu.be/PGgr9mUQ-y8

**Comment by mrapple** [comment]
What map is that? Certain maps allow players to roam in the death screen

**Comment by mrapple** [comment]
https://maps.oc.tc/CTF/Standard/Concourse/map.xml

```xml
<respawn spectate="true">
    <message>{ translate: "death.respawn.confirmed.waiting.flagDropped" }</message>
</respawn>
```
