### ISSUE TITLE
Sometimes on CTF, the flag gets captured multiple times at once

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1811]
On this match, blue team was 1/3, and red was at 0/3. Me and sunbear1565 were carrying the flags (me the red one and he the blue one), He got killed and i captured it, and then he picked it up again, went to capture it, and the sound of losing/getting our flag captured sounded multiple, times, and they got from 0/3 to 3/3 in a second, this also showed up in chat:
![2015-04-21_19 42 10](https://cloud.githubusercontent.com/assets/8422075/7265403/e28b6914-e85e-11e4-97af-3996ef667588.png)
There you can see the picking-up flag message, and the capturing one, this one being repeated 3 times in a row.

**Comment by Electroid** [comment]
This was fixed.
