### ISSUE TITLE
Getting infinite wool out of dispensers

### ISSUE THREAD

**Issue by Gaporigo** [OvercastNetwork/Issues#1813]
https://youtu.be/Zhmmk4uKWPY?t=8m53s

Notice how he picked up the wool inside the dispenser and on his way back he can place the same wool  multiple times.

**Comment by CaptainElliott** [comment]
Ugh, forgot to close in the commit https://github.com/OvercastNetwork/Maps/commit/66c57efcefa12862b79b5de17efacdac7a9a40ec

But this is not an issue with the plugin, it does not use the auto-container refill, but instead an infinite stack (using `-1`). The map was only preventing players opening a dispenser and not a dropper
