### ISSUE TITLE
On CTF, players on a team cannot see other players before or after the match.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1820]
On the first picture, the match ended, and you can see at the chat that i was on blue team and that my /toggle obs was on "all", so i should be able to see all observers, but since i was in a team, i couldn't.
On the second picture you can see that i joined red team and that i can't see observers, that happened as soon as i joined a team, they all dissapeared.
![2015-04-29_15 07 07](https://cloud.githubusercontent.com/assets/8422075/7400419/776988e4-ee82-11e4-9a19-34924095a13c.png)
![2015-04-29_15 07 27](https://cloud.githubusercontent.com/assets/8422075/7400420/7781d5d4-ee82-11e4-876f-0d6ae2e24486.png)

**Comment by DoomRobotBoy** [comment]
I think you should add that these events only occur on CTF (the only 1.8 server).

**Comment by Electroid** [comment]
Fixed.

**Comment by ghost** [comment]
@Electroid Still happen

**Comment by Tapetepato** [comment]
can confirm it still happens on some maps

**Comment by DoomRobotBoy** [comment]
@Tapetepato I think it only happens after matches have been finished. It doesn't happen for me before or while a match is playing.

**Comment by ghost** [comment]
@DoomRobotBoy You're right, i think is only on 1.8.7
