### ISSUE TITLE
A player is online in-game but on the website it shows that he isn't

### ISSUE THREAD

**Issue by Abusa3** [OvercastNetwork/Issues#1821]
I was playing on Capture (Eu) and I noticed a player acting in an odd way, so I went to the website and opened his page and it said that he has been seen 30 minutes ago, but he is still playing in-game and his stats won't update either.

Here are some photos showing the match and the person and the times.
http://imgur.com/CVB6PQ6,oKPSoFY,kCL3iLz,yKXioP1
http://imgur.com/CVB6PQ6,oKPSoFY,kCL3iLz,yKXioP1#1
http://imgur.com/CVB6PQ6,oKPSoFY,kCL3iLz,yKXioP1#2
http://imgur.com/CVB6PQ6,oKPSoFY,kCL3iLz,yKXioP1#3

Here is the Match: https://oc.tc/matches/55449887c8f2ab95b6bf75fe
And the person:https://oc.tc/Joey7970

Sorry about this being poorly made, I had to make it in a rush. but I will try to improve it as soon as I can.

**Comment by matic0basle** [comment]
https://oc.tc/forums/topics/5544a64367d52211570005f3

**Comment by tonybruess** [comment]
Let's use #2048
