### ISSUE TITLE
executing /raindrops throws an error if no arguments are entered 

### ISSUE THREAD

**Issue by dentmaged** [OvercastNetwork/Issues#1823]
Upon typing /raindrops, you get the following error: 

![/raindrops error](http://i.imgur.com/hghJ1pI.png)

**Comment by CaptainElliott** [comment]
I reported this in slack, it appears that if you don't use any arguments

**Comment by dentmaged** [comment]
@CaptainElliott What is slack? Are you talking about OvercastNetwork/Internal?

**Comment by SkylerTyler1337** [comment]
Seems like a plugin bug. They may need to check if they no arguments

**Comment by dentmaged** [comment]
Still occurs. Possible fix (for players) is /raindrops <your username>

**Comment by ghost** [comment]
Fixed
