### ISSUE TITLE
The last suset - Unprotected beacons

### ISSUE THREAD

**Issue by Zozoo1** [OvercastNetwork/Issues#1826]
On this map, there are beacons, behind the spawn, in order to make people know where to capture the flag.

However, you can actually break the beacons (at least the blue one), and get access to the iron blocks below it, allowing you to craft iron armor.

I don't think this is intended, so maybe the XML need some editing.

Thanks

**Comment by DoomRobotBoy** [comment]
Oh dayum. I haven't been able to test the map after the update, but I'll be sure to update this problem and try to find more. Thanks for reporting.

**Comment by thestrangeboy1** [comment]
Should be fixed now.
