### ISSUE TITLE
setting the default channel to /g gets resetted after map cycle (1.8)

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1829]
whenever i set my default channel to the global chat on ctf, it will get resetted when a game ends, and the pgm cycles to the next map.

**Comment by matic0basle** [comment]
Related? https://github.com/OvercastNetwork/Issues/issues/1786

**Comment by Brottweiler** [comment]
Seems like a duplicate https://github.com/OvercastNetwork/Issues/issues/1786
