### ISSUE TITLE
Map update - SweetTooth

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#1831]
Updated: 
I fixed a few holes in the map where players could get stuck

I added speed pods and arrows hidden around the map

I also added a map.png: https://www.dropbox.com/s/5fadvm2nz3crlog/map.png?dl=0

Updated Download: https://www.dropbox.com/s/a2oh1ewcizr0tx4/SweetToothUpdate.zip?dl=0

**Comment by ajtag5** [comment]
Make sure when getting the download for the map, the weather and time is at the state you wish for them to be. It is raining on the updated download.

Give me a link with the weather/time fixed and I'll update it.

**Comment by Oo-TheFrog** [comment]
Sorry about that i will get the correct download as soon as a admin on
joldev can give me it.

**Comment by Oo-TheFrog** [comment]
K updated https://www.dropbox.com/s/orfrcv0dt69w6g3/SweetTooth.zip?dl=0

**Comment by minimitch0199** [comment]
You have mobs in your world download. Can you please remove them via the `Delete Entities` button in MCEdit?
