### ISSUE TITLE
Picking up wools translated to Swedish isn't correct

### ISSUE THREAD

**Issue by MobbareKurtZ** [OvercastNetwork/Issues#1832]
If you have Minecraft in Swedish and play on Capture, you'll see:
"[Player] plockade upp [Team] för [Wool]." which translates to "[Player] picked up [Team] for [Wool]." whenever someone picks up the wool. It should be "[Player] plockade upp [Wool] för [Team]."

Here you can see the problem:
![2015-05-08_15 51 41](https://cloud.githubusercontent.com/assets/9394074/7537403/f3fa06aa-f598-11e4-9acc-4eb520864d83.png)

**Comment by Superjd10** [comment]
You should help translating that correctly in http://translate.oc.tc (plugins)

**Comment by MobbareKurtZ** [comment]
@Superjd10 Forgot about that... Matic fixed it anyways.

**Comment by Brottweiler** [comment]
This was fixed just now (approved it).
