### ISSUE TITLE
[CTF] Observers not visible when toggled on after matches

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1834]
![2015-05-08_16 19 44](https://cloud.githubusercontent.com/assets/10585916/7544777/37a2c2fc-f59e-11e4-8aef-5a321f9ebcbf.png)

**Comment by samtheman43** [comment]
This may be server wide, I'll check now.

**Comment by Tapetepato** [comment]
https://github.com/OvercastNetwork/Issues/issues/1820

**Comment by Brottweiler** [comment]
Duplicate https://github.com/OvercastNetwork/Issues/issues/1820
