### ISSUE TITLE
Raindrop message's dead player's name isn't properly colored

### ISSUE THREAD

**Issue by Superjd10** [OvercastNetwork/Issues#1836]
## The issue

When you kill a player, the player's name in the raindrops message isn't colored with the player's team color.

## Steps to reproduce

Kill any player, check the raindrops's message.

## Miscellaneous information

![image](https://cloud.githubusercontent.com/assets/1649155/7548770/13035098-f5de-11e4-979e-42356eee5aec.png)

**Comment by Ipskie** [comment]
This is because capture is on 1.8, and the dead player has had their name color changed until they respawn. This can be observed on CTF too. Purely cosmetic though I suppose it could be regarded as a bug

**Comment by Tapetepato** [comment]
it looks good and i assume its intended because it has been like that for a while

**Comment by SkylerTyler1337** [comment]
They hey the color of their tab name which is dark gray ?

**Comment by mrapple** [comment]
Intended
