### ISSUE TITLE
You and friend listed as common friends

### ISSUE THREAD

**Issue by Ipskie** [OvercastNetwork/Issues#1837]
![screen shot 2015-05-09 at 2 23 05 pm](https://cloud.githubusercontent.com/assets/7846005/7549011/3a52d884-f657-11e4-8edb-40172e303a45.png)

**Comment by Brottweiler** [comment]
I think this is a duplicate issue but can't find it. Maybe there was never an Issue created for it.

**Comment by itsmartin** [comment]
Fixed
