### ISSUE TITLE
You can kill your teammates in RAGE as an observer.

### ISSUE THREAD

**Issue by javipepe** [OvercastNetwork/Issues#1845]
# The issue

You can "obskill" your teammates in RAGE.

# Steps to reproduce

1. Aim at a teammate
2. Shoot
3. Get killed by an enemy before the arrow reaches its destination.
4. Kill your teammate (+ receive raindrops)

**Comment by Tanpiku** [comment]
This has been reported before, and was a large scale issue back around 2 years ago.

**Comment by javipepe** [comment]
@Tanpiku Well it still happens, and I couldn't find any issue on here :/

**Comment by TiTo-418** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/200
