### ISSUE TITLE
Map Update - Secluded Caverns Version 1.5.0

### ISSUE THREAD

**Issue by yoyopower** [OvercastNetwork/Issues#1846]
Changelog:
- Changed spawn location.
- Added hills to direct playerflow.
- Fixed some lighting.

Download: http://www.mediafire.com/download/9u8915bb1ytt5qa/Secluded_Caverns(5).zip

**Comment by ajtag5** [comment]
Did you change the gamemode to KoTH? When I tested it, it seemed to be straight up KoTH rather than TDM which is what it was originally.

**Comment by yoyopower** [comment]
@ajtag5 Yes. I may end up keeping a TDM aspect but I wanted to test a version with just hills.

**Comment by ajtag5** [comment]
@yoyopower we can do so on my mapdev server next time we are both on. I'd rather not go straight to repo if it is a different gamemode.
