### ISSUE TITLE
Wooden axes on Elysium do not work for moderators

### ISSUE THREAD

**Issue by koipen** [OvercastNetwork/Issues#1852]
On the map Elysium players spawn with wooden axes. Moderators cannot use these because of our WEdit perms. Could they be switched to stone axes so everyone could use?

**Comment by Superjd10** [comment]
I think this thing happened in a @chickolympics's map, he placed a sign there with instructions of how to change it, maybe the map needs that sign somewhere.

**Comment by itsmartin** [comment]
`/toggleeditwand` disables the worldedit wand, I think.

**Comment by khazhyk** [comment]
Changed permissions priorities, should be fixed, test?

**Comment by itsmartin** [comment]
Tried it on capture by crafting an axe and it still worked as WE wand.

**Comment by khazhyk** [comment]
Oh, the default groups require a server restart, try waiting until a server restarts.

**Comment by jedediah** [comment]
Seems that worldedit still treats the wood axe as edit wand even if you don't have permission for it. There is no permission to disable the wand itself AFAIK.

**Comment by khazhyk** [comment]
No that's not true @jedediah, normal players for example aren't affected. If you remove the /wand permission and the /sel permission it should disable the wand. It's worked before.

**Comment by khazhyk** [comment]
Oh i see the issue. We remove "worldedit.selection" which might have used to expand out to all the sub nodes. Let me try removing all the subnodes individually and seeing if that affects things.

**Comment by jedediah** [comment]
This should be fixed now
