### ISSUE TITLE
Outdated copyright

### ISSUE THREAD

**Issue by njb-said** [OvercastNetwork/Issues#1855]
On the 404 page the copyright is 2014
![https://imnjb.me/i/vEvkUe.png](https://imnjb.me/i/vEvkUe.png)

**Comment by itsmartin** [comment]
Duplicate of #1589, remember to search before posting.

**Comment by njb-said** [comment]
@itsmartin This is just for the 404 page, the other pages for the site are fine :confused:

**Comment by itsmartin** [comment]
That issue is also for the 404.

**Comment by njb-said** [comment]
Ok, well either way that issue has been open since february
