### ISSUE TITLE
Server doesnt detect map author

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Issues#1856]
i was on the ctf server today, and there were like 44 people playing, and after the game ended, i could not see any map ratings. i didnt have a map author star either, so i just didnt got detected as map author. the map does have the correct player uuid, and if i do /map, the name is identical to my current name.
 a screenshot:
http://i.imgur.com/5KAV23K.png

**Comment by Ipskie** [comment]
Shot in the dark, any whitespace that could mess up the name? Also please don't add your own tags in the title

**Comment by kroest** [comment]
what are my own tags? and the xml is correct, it worked before, with this last update, and with 2 names i had before i changed it to this. i think it has something to do with the us server being down for a moment.

**Comment by mrapple** [comment]
Strange, not sure what caused this

**Comment by kroest** [comment]
okay, it seems to be fixed, i dont know why it didnt detect me that time.

**Comment by mrapple** [comment]
Strange. I doubt this is reproducible, probably going to close.
