### ISSUE TITLE
PrimedTNT from projectiles is owned by 'world'

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#1857]
In FFA you can defuse "WORLD" TNT.

Found on map Kryta

**Comment by mrapple** [comment]
Not sure if intended. @cubist?

**Comment by minimitch0199** [comment]
FYI, the TNT is from the projectiles module if that helps at all.

**Comment by nixter1029** [comment]
@minimitch0199 Now that you mention that, it might be due to the fact that it was a projectile instead of  it being because of FFA. I test it next it next time I play.

**Comment by minimitch0199** [comment]
![tntprojectile](https://cloud.githubusercontent.com/assets/6386297/7697533/0113c0ea-fe4c-11e4-9db8-d0ccdc1d3517.PNG)
I was able to defuse Primed TNT that was from the projectiles as it is owned by `world`. TNT from placed blocks, as expected, was owned by myself and could not defuse. Results were the same on a FFA match.

**Comment by Electroid** [comment]
List of all projectiles issues are in Internal. This was one of them.
