### ISSUE TITLE
Posting a topic provides errors (ghost topics?)

### ISSUE THREAD

**Issue by Tanpiku** [OvercastNetwork/Issues#1858]
Hello,

I tried posting a map 10 minutes after I posted one before. No issue here.
![](http://i.gyazo.com/cf6fab8d710f189c8c0244200205be79.png)

But unfortunately clicking it after the 9 seconds was up, it spun me an issue. When I posted it first, it gave no reason at all and essentially ghosted the topic saying that it was posted, but it's not anywhere on the forum.
![](http://i.imgur.com/VTs3B0t.png)

 It then made me wait another 10 minutes to post it, where as I have had my quota reached yet it still delayed it.

![](http://i.imgur.com/CYgv9jL.png)

**Comment by mrapple** [comment]
#1822
