### ISSUE TITLE
Mumble Room Comment

### ISSUE THREAD

**Issue by knightopress** [OvercastNetwork/Issues#1860]
The Issue:
The commented images for the game rooms "Dota 2" and "League of Legends" are reversed.
Steps to Reproduce:
1. Go on Mumble.
2. Mouse over the room "Dota 2" and see an image of the game League of Legends.
3. Mouse over the room "League of Legends" and see an image of the game Dota 2.

**Comment by Brottweiler** [comment]
Please just email this issue to mumble@oc.tc.
