### ISSUE TITLE
CTF does not appear in the gamemode's section

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1865]
<a href="http://imgur.com/EpmGmx4"><img src="http://i.imgur.com/EpmGmx4.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/9GvMQS4"><img src="http://i.imgur.com/9GvMQS4.png" title="source: imgur.com" /></a>

**Comment by thestrangeboy1** [comment]
Should now ;)

**Comment by ghost** [comment]
Yep
<a href="http://imgur.com/pISRRzQ"><img src="http://i.imgur.com/pISRRzQ.png" title="source: imgur.com" /></a>
