### ISSUE TITLE
Able to place upper half of doors while in observer mode

### ISSUE THREAD

**Issue by samtheman43** [OvercastNetwork/Issues#1868]
Noticed this while watching a match.
https://youtu.be/Cb3JeUCR3SM

**Comment by nixter1029** [comment]
Is this client side or are the blocks actually being placed?

**Comment by CaptainElliott** [comment]
This just looks client side to me as well

**Comment by Pingy** [comment]
Is this related to the bug where the upper half of 2 block high plants would stay?

**Comment by samtheman43** [comment]
@Pingy Yeah I think that it would do the same thing with 2-high plants.

**Comment by CaptainElliott** [comment]
@samtheman43 are the door's actually being placed?
Like when you join are they still there? otherwise this is just client side

**Comment by minimitch0199** [comment]
@CaptainElliott They are still there when you join, however they are still client side. Other players can walk through them and when interacted with, they disappear.

**Comment by ElliottWhyman** [comment]
that means that for the server, the door is not there - therefore this is client side. This cannot be fixed via the plugin.

**Comment by Pablete1234** [comment]
@CaptainElliott it can be fixed using player.sendBlockChange(Material, data), it's deprecated, but it still would fix the issue. Whenever you call event.setCancelled(true), also call sendBlockChange
