### ISSUE TITLE
Rules in spanish | "Website Behavior"

### ISSUE THREAD

**Issue by SantiTheGamer** [OvercastNetwork/Issues#1869]
I was reading the rules (in Spanish) and I saw that the "Website Behavior" / "Comportamiento en la Web" rules... have the title in Spanish but the rules are in English.

https://oc.tc/rules/es

**Comment by SantiTheGamer** [comment]
https://github.com/OvercastNetwork/rules/pull/120/files

**Comment by itsmartin** [comment]
Thanks, we already have an issue for this on the rules repo.
