### ISSUE TITLE
Deathscreen Breaking Blocks

### ISSUE THREAD

**Issue by Joshua171** [OvercastNetwork/Issues#1871]
I found that when I break block while dead some of those blocks wont reappear when I respawn and when I walk onto the space with no blocks I get stuck and cant move

https://www.youtube.com/watch?v=kiCS7fFhjYY&feature=youtu.be

**Comment by nixter1029** [comment]
Client side.

**Comment by Joshua171** [comment]
I understand its client side but I was just reporting it so that maybe it could be prevented with the old deathscreen or making breaking blocks impossible while dead I don't know

**Comment by CaptainElliott** [comment]
A fix would be putting the player in adventure mode when they are dead

**Comment by Ipskie** [comment]
#1827
