### ISSUE TITLE
(Ghost Squadron) Because of the 1.8 update, FFA is broken because each team requires one player.

### ISSUE THREAD

**Issue by ocktick** [OvercastNetwork/Issues#1875]
To reproduce, go to /server gs with two people and join. The game will not start.

**Comment by Ipskie** [comment]
Looks like the XML needs to be reconfigged to work with the new FFA stuff

**Comment by CaptainElliott** [comment]
I'm going to make this a task in the internal issue tracker

**Comment by kroest** [comment]
this applies to certain 4 teams rage maps to, like for instance plus side, needs 4 players to start, where you normally only need 2 people, so the title should get changed to serverwide, instead of ghost squadron.
