### ISSUE TITLE
Friends' in common is having a problem

### ISSUE THREAD

**Issue by Guicotsch** [OvercastNetwork/Issues#1877]
I saw recently that if you're friend with someone and you look into the 'in common friend' you'll see your own name and the name of the friend. To be clear i took a pic : 
![fr](https://cloud.githubusercontent.com/assets/7735022/7865832/caf2a1c6-056b-11e5-9734-44d0a5eed614.JPG)

I didn't manage to have my mouse on the 'in common' button but my friends in common with KhaleesiDaenerys are : KhaleesiDaenerys and Guicotsch (myself)

Thank you

**Comment by itsmartin** [comment]
#1837 duplicate
