### ISSUE TITLE
Servers-switching-signs are missing on servers

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1878]
The signs used to switch servers (still present in the lobbies) are missing when on one of the servers (Blitz, Capture1, Mini01, etc.). 

I don't know if the following screenshots suffice as potential evidence, though its pretty easy to check if the bug is present (just go to a gamemode-server):
http://i.imgur.com/8C1Mq1p.png
http://i.imgur.com/TEUtoeo.png

I, myself, find the sign more useful than the command to use for switching servers and its also easier for new players and players not used to using commands.

*also thanks to phil8338 for confirming the issue network-wide*

**Comment by DoomRobotBoy** [comment]
The oddness occurred that the signs returned. I don't know how to explain why they didnt appear yesterday (yes I tried relogging/shutting down minecraft as well).

**Comment by Ipskie** [comment]
Close until it can be reliably reproduced or someone else reports this?

**Comment by DoomRobotBoy** [comment]
Will do
