### ISSUE TITLE
Enchanting Tables

### ISSUE THREAD

**Issue by higgerblick5** [OvercastNetwork/Issues#1879]
Just played a round of Bliss on Blitz, and couldn't enchant anything due to a lack of lapis on the map. This also effects every map in which enchanting is included.

**Comment by CoWinkKeyDinkInc** [comment]
Lapis should be included by default on Enchantment tables.

**Comment by Brottweiler** [comment]
On some maps you can include lapis ores and on others I guess just have it as kill reward or spawn with it in your inventory.

**Comment by twizmwazin** [comment]
I think a good solution to this issue would be to implement an XML element that will automatically populate enchantment tables. It would be disabled by default, and give the map author the choice to allow players to enchant without needing lapis. I feel this is a better solution than adding a kill reward, as many maps have enchantment tables, however they aren't necessarily a main feature.

**Comment by ajtag5** [comment]
@twizmwazin I think this could be a good idea. If enabled, all enchanting tables would have lapis in by default

**Comment by higgerblick5** [comment]
@CoWinkKeyDinkInc It should be, but it isn't. Without lapis in the tables, a huge function of some maps such as Bliss are completely ruined.

**Comment by AnthonyTag** [comment]
Are there any more maps that need fixing? Preferably only rot maps although I understand if it's a map that is in the repo and set a lot.

**Comment by AnthonyTag** [comment]
I'm just gonna close this. If something comes up with multiple maps we can reopen it. Otherwise, just make an issue for a specific map.
