### ISSUE TITLE
Sometimes, you can go through blocks in the lobby

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1880]
https://www.youtube.com/watch?v=wBi71bAJfHo

**Comment by itsmartin** [comment]
Are you getting put into spectator mode?

**Comment by CaptainElliott** [comment]
https://github.com/OvercastNetwork/Issues/issues/1799. No  body was able to be reproduced and this was considered inconsistent/nothing could be done to fix it

**Comment by Tapetepato** [comment]
yeah i think, itsmartin

**Comment by Tapetepato** [comment]
https://youtu.be/UXEU8RYLnZc 
Happened today again when i logged in

**Comment by mrapple** [comment]
Yeah no clue how to reproduce/fix. Seems to happen extremely rarely.
