### ISSUE TITLE
Spectators recieve team kits

### ISSUE THREAD

**Issue by SantiTheGamer** [OvercastNetwork/Issues#1882]
http://gyazo.com/105c21b87745eff120449254272bd692
http://gyazo.com/8270e8514c0d1e1b85cfff845a5c81b7

Note: These screenshots aren't mine

**Comment by TiTo-418** [comment]
https://oc.tc/forums/topics/5568ea3667d5228751002c9c

**Comment by SantiTheGamer** [comment]
I know, I just submitted it here

**Comment by itsmartin** [comment]
Is there a reliable way to reproduce this?

**Comment by SantiTheGamer** [comment]
What do you mean with "reproduce"?

**Comment by itsmartin** [comment]
To make this bug happen again.

**Comment by SantiTheGamer** [comment]
I don't know, I should find an Empire match or ask a mod to /sn it

**Comment by SantiTheGamer** [comment]
Matsuzen sn'd it on Mini01 (US), I'm waiting the current match to end to record it

**Comment by themtz** [comment]
Same thing happened at Blocks II, Didn't even screenshotted and I don't know where I did.

**Comment by CaptainElliott** [comment]
Was the macro mod installed when this happened?

**Comment by SantiTheGamer** [comment]
No, yesterday, I asked Matsuzen to /sn it and I recorded it, uploading it right now =)

**Comment by High-Tower98** [comment]
This has happened to my friends and myself quite a few times on multiple maps.

**Comment by SantiTheGamer** [comment]
@itsmartin @CaptainElliott @mrapple https://www.youtube.com/watch?v=Mr0SXKO7SRs

**Comment by CaptainElliott** [comment]
Does this happen all the time?

**Comment by SantiTheGamer** [comment]
@CaptainElliott At least in all the Empire matches I've played, Never happened to me in other maps

**Comment by nixter1029** [comment]
Easy fix. It's because the default spawn is in the red team spawn element.

**Comment by nixter1029** [comment]
```xml
<spawns team="red" kit="red">
    <spawn yaw="180" pitch="90">
        <point>-1.5,55,85.5</point>
    </spawn>
    <default yaw="-90">
        <cylinder base="-70.5,11,12.5" radius="2.5" height="0"/>
    </default>
</spawns>
```

**Comment by nixter1029** [comment]
As for Blocks II, same issue:    
```xml
<spawns team="blue" kit="blue">
    <spawn yaw="90">
        <cylinder base="-87,29,-271" radius="2" height="0"/>
    </spawn>
    <spawn yaw="-90">
        <cylinder base="-183,29,-271" radius="2" height="0"/>
    </spawn>
    <default yaw="-90">
        <cylinder base="-216,54,-172" radius="1" height="0"/>
    </default>
</spawns>
```

**Comment by SantiTheGamer** [comment]
Happened again on Infernal Shadow http://gyazo.com/59eadfae5caf0492e4b3e163a84aada7
