### ISSUE TITLE
Spawn/woolroom borders are set below what is needed to protect

### ISSUE THREAD

**Issue by JexeI** [OvercastNetwork/Issues#1886]
From first glance, this does not seem like a problem. I have noticed this problem many months ago. But by running into the protective border in a map, you are not able to fall downwards if hit into this border. Many maps have a border that is set to y=0 and below, causing a player to "fly" in thin air. This applies for woolrooms, spawn protection borders, etc. I do not have a video of this, but I do have a screenshot. I may be able to demonstrate if possible.
![2015-05-30_19 51 05](https://cloud.githubusercontent.com/assets/8964867/7900060/49df6838-0707-11e5-9c31-3881e0580d67.png)

**Comment by mrapple** [comment]
What map

**Comment by jxl8437** [comment]
@mrapple 

The map in the screenshot, Deepwind Jungle (may be fixed) and Dynamo (also may be fixed). Those are the ones I know have/had the bug.

**Comment by mrapple** [comment]
Ah I forgot the map name was on the tab list

**Comment by jxl8437** [comment]
If I were you guys, I would carefully check the XML on every map if the border is set below y=0 if possible. I have no idea how XML works...

**Comment by mrapple** [comment]
Our map repository has hundreds on hundreds of maps. We’re not going to check every map. If you run into this bug on certain maps, please which maps.

**Comment by jxl8437** [comment]
I will check another day, I have little time today. I assume every map which has a protection border, but that may not be the case. For now, those are the maps I had this bug with.

**Comment by thestrangeboy1** [comment]
This is caused by regions using rectangles instead of cuboids which would extend the y up and down infinitely. It really isn't a problem as long as don't keep on trying to move forward into the region. If you just let go, you'll be able to fall in the void just fine.

**Comment by jxl8437** [comment]
Once, I got knockback'd so hard I couldn't even move... I'm more worried that people will abuse this bug to not die.

**Comment by ajtag5** [comment]
We could always make a compliment for above whatever y level the bottom of the map is and the rectangle…I think. Or just a cuboid up to 256.

**Comment by jxl8437** [comment]
that's fine, I think.

**Comment by AnthonyTag** [comment]
I fixed the issue in the maps mentioned. It is impossible for us to go through all 700+ maps loaded in the repository so we'll just look out for it now and fix it when we find it.

**Comment by jexeI** [comment]
Ok, @ajtag5 is it ok to report more maps here ?

**Comment by eliyap** [comment]
@JexeI You should probably make another issue, I don't think we want "mega-issues"

**Comment by AnthonyTag** [comment]
@JexeI You can reopen this with some more maps if you wish.
