### ISSUE TITLE
Index of /Other/Tournament/House of Cores/ has maps of The Last Life

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1887]
<a href="http://imgur.com/hVb7jy1"><img src="http://i.imgur.com/hVb7jy1.png" title="source: imgur.com" /></a>

**Comment by TiTo-418** [comment]
Closing this, look at Index of /Other/Tournament/hocArchive/

**Comment by ajtag5** [comment]
Just to explain, we decided to keep the servers set up to reading the "House of Cores" directory. But we wanted to keep the HoC repo hence the archive folder.
