### ISSUE TITLE
Player's name showing in the "friends in common" list

### ISSUE THREAD

**Issue by Abusa3** [OvercastNetwork/Issues#1889]
I've noticed this: (I know it's not a major issue but thought that you guys should be aware of it)

Here, as you can see in these two images, the person's name appears as if it was a friend in common with his/her friend, which doesn't really make sense.

http://i.imgur.com/5ByYpEJ.png
http://imgur.com/5ByYpEJ,r2gdz5d#1

**Comment by itsmartin** [comment]
Duplicate of #1837. Remember to search before posting.

**Comment by Abusa3** [comment]
My bad, thanks for the reminder.
