### ISSUE TITLE
Outback celebrates a 1000 ratings - Let's add it to the Capture Rotations

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#1892]
Nothing much to say here. The Current Version plays awesome and has as a average-rating of 3.825. 
In particular they're 1004 ratings with a average of 3.77.

https://oc.tc/maps/outback

**Comment by samtheman43** [comment]
Umm, it's not your decision what gets in the rotation, and I don't think the issue tracker is a place for a celbration.
