### ISSUE TITLE
[BoomBox] Mining quartz makes it infinitely spawn behind you.

### ISSUE THREAD

**Issue by ryanw-se** [OvercastNetwork/Issues#1897]
On BoomBox when you mind quartz it spawns behind you, as long as you run on quartz it spawns infinite amounts of quartz behind you, (basically in a trail). Keep in mind that quartz block, doesn't drop quartz in Vanilla, so this is a modified drop. I can't confirm whether this issue also occurs on blue team, although it probably does.

**Comment by CaptainElliott** [comment]
I'm guessing that's a bug with the new trampling feature of block drops

**Comment by Pablete1234** [comment]
it's not about mining cuartz, it's about walking on quartz while holding the pickaxe

**Comment by CaptainElliott** [comment]
This has been fixed
