### ISSUE TITLE
Map Update - Shrine CTF

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1900]
More parts of the map's XML appeared to be broken, but I hope that those are fixed now. I also simplified the map a bit cause it occurred to me that players struggled with playing on the map.

Changelog:
- Fixed Shrine Flag drop-offs
- Fixed speed pots
- Removed some tips
- Removed kills/death adding/deducting points

https://github.com/DoomRobotBoy/Maps-XML/blob/master/Shrine.xml

**Comment by Brettogden** [comment]
You're missing the "hight" attribute for the regions starting on line 65 and the xml version 1.1.0 is getting rejected by PGM. Please fix these so we can update the map.

**Comment by DoomRobotBoy** [comment]
@Brettogden Updated the XML. Link stays the same (in OP). Thanks for mentioning both errors!
