### ISSUE TITLE
Maps page not updating

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#1906]
If you visit newer maps on https://oc.tc/maps you'll get an Error 404. I noticed this bug with the following maps of the repository (there might be some more).

- https://oc.tc/maps/drastic_change

I don't know why this is happening, but it's definitely a bug.

**Comment by kroest** [comment]
that is ffa.

**Comment by CaptainElliott** [comment]
As said before Paradiso is FFA and therefore is not yet synced to the maps page

**Comment by rockymine** [comment]
@CaptainElliott: Drastic Change is no FFA and the bug is still there. Image resolution etc. is all correct. Do you know a reason for that error?

**Comment by mrapple** [comment]
FFA hasn't been added as a gamemode to the website

**Comment by rockymine** [comment]
@mrapple: Why did you modify the title. It wasn't really the ffa I was talking about. Drastic Change is no ffa! I'm referring that map :(

**Comment by mrapple** [comment]
Oops. Also, fixed

**Comment by kroest** [comment]
uhh https://oc.tc/maps/gamemode/ffa is not there yet.

**Comment by mrapple** [comment]
Separate issue
