### ISSUE TITLE
Crash - Map Foxtrot

### ISSUE THREAD

**Issue by unixfox** [OvercastNetwork/Issues#1909]
When I play on Foxtrot, I always crash on this map and I don't know why.

Here is my log crash : http://pastebin.com/QxDg30pL.

**Comment by matic0basle** [comment]
Try it without mods. Solving an issue that appears when you are using mods isn't the maps fault, its the mods so if it doesn't happen when you don't use mods then its not an issue.

**Comment by Brettogden** [comment]
After reviewing the crash report and in game investigation, I think your mods caused you to crash not the map.
