### ISSUE TITLE
Fix the wool rooms on 8th & 9th's Law.

### ISSUE THREAD

**Issue by Facu713** [OvercastNetwork/Issues#1912]
I was playing on Capture2 server on US Overcast Network, after a few tryes of rushing I got into the woolroom and when I stept on the preassure plate to get the cyan wool the dispenser/dropper didn't droped it. It's the first time that happened to me on that map.
After that, I joined Observers with the purpose of watching if this happened to someone else. For my surprise, this was happening with everybody who was going to take the cyan wool.
That wool was already touched so I can affirm that the dispenser/dropper it dropped the wool once but then it didn't dropped it any more.
I'm sorry but I don't have any video to show.

**Comment by 2000thehecf1** [comment]
The 6th Law is a Rage map, so I think you are meaning 9th Law. This also happens on The 4th Law and The 8th Law, but I remember that Fox Strife, Fox Strife Void and Fox Strife - Mines use dispensers to give the wool, so even they aren't in rots, they should be fixed for possible setnexts.

Edit: Clover dispensers are bugged too.

**Comment by 2000thehecf1** [comment]
I don't know if 9th Law is already fixed, but the other cited maps aren't yet.
