### ISSUE TITLE
Arrow Lag- Shooting in game, arrow firing at observers

### ISSUE THREAD

**Issue by PoseidonsM** [OvercastNetwork/Issues#1913]
I fired at a player in game, and shortly before the arrow fired (I had released) I was killed. The arrow then fired from me, but on the observers platform

This is a mixture between two issues: 
1. Australian lag, which I appreciate as not your problem 
2. The new insta-teleport upon death in rage. I was teleported to the platform instantly upon death, when the arrow still had lag? (Which confuses me, may be a one-off).

**Comment by PoseidonsM** [comment]
Not a one-off, issue happened again and a fellow observer somehow caught on fire (although that may have been me).

**Comment by itsmartin** [comment]
I guess that the server would have seen your arrow as being fired by you as an observer, so I don't think this could affect the game. As far as the server is concerned, you didn't fire until after you died. So I'm not sure this is a problem.

**Comment by PoseidonsM** [comment]
Cheers, I'll close this.
