### ISSUE TITLE
Ocn Weeklies Github: Page not found

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#1915]
In the bottom section that says "Weeklies

'Weeklies' are issue tracker milestones created by Overcast Network staff each weekend. Issues slated to be resolved on any given weekend are assigned to that weekend's relative milestone, so that progress on the weekend's issues can be easily visualized.

Overcast Network Weeklies can be found here." 

The link is dead.

**Comment by Electroid** [comment]
It's gone. We haven't done the weeklies program for a while.
