### ISSUE TITLE
Blitz multiple lived maps need player to left click to re-spawn

### ISSUE THREAD

**Issue by jxl8437** [OvercastNetwork/Issues#1916]
So far, this issue has not been occurring in every map, but when in Infinite, by AtlasGames, you can stay in the dead state forever, which will cause the game to tie. 
![thing](https://cloud.githubusercontent.com/assets/8964867/8106857/9d552ac8-100a-11e5-9c3e-ef28513a3e79.png)

**Comment by Brottweiler** [comment]
I think this is the same issue as in the past that blitz with multiple lifes doesn't have a force respawn?

**Comment by jxl8437** [comment]
no, it does not have a force respawn
