### ISSUE TITLE
Way to use /me without having permission

### ISSUE THREAD

**Issue by SantiTheGamer** [OvercastNetwork/Issues#1918]
If you do /minecraft:me *message* in game, it will display a message exactly like the /me one, and it works for everyone. Screenshot:

![2015-06-11_23 52 56](https://cloud.githubusercontent.com/assets/12377290/8122741/fbfe27b6-1094-11e5-80de-4597acb1eb0c.png)

**Comment by thestrangeboy1** [comment]
#1911
