### ISSUE TITLE
Custom XML Projectiles deviate from a straight path 

### ISSUE THREAD

**Issue by xXFracXx** [OvercastNetwork/Issues#1926]
**Issue:**
https://youtu.be/fMMpI66ggsk

**Comment by Electroid** [comment]
Looks like a visual bug that corrects itself after a bit. The projectile is probably going too fast.

**Comment by xXFracXx** [comment]
Thing is before it corrects itself, it seems that it doesn't hit players in the correct path.

**Comment by Yukon** [comment]
If you make projectiles go too fast there is precision errors which I think this is the case. Don't make them go super fast.
