### ISSUE TITLE
Mob disguises are removed, Shop is now giving false information

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#1930]
In the perk box below every "rank" in the shop, it says that you unlock mob disguises. But (correct me if I'm wrong) the mob disguise gadget has been removed from the lobby.

**Comment by Matic0B** [comment]
Related
https://github.com/OvercastNetwork/Issues/issues/1641

**Comment by Brottweiler** [comment]
Well since it's a dupe I'll close it.
