### ISSUE TITLE
See Plugins in Server 

### ISSUE THREAD

**Issue by monchiestevez** [OvercastNetwork/Issues#1933]
o/, i don't know if this enought for a bug but when you type in chat /pl or /plugins you can see plugins in the server where you are.

![e938935353c72322fcf44c354ce520bb](https://cloud.githubusercontent.com/assets/12588861/8269468/a78568a4-17a9-11e5-960c-228ab3a94603.png)

**Comment by Brottweiler** [comment]
Not a bug.
