### ISSUE TITLE
The command "/staff" is broken.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1934]
Hello! As you can see in this video, when I do /staff It doesn't show me any staff online but in the same match there was a moderator (SheriffSoco).

Video -->  https://www.youtube.com/watch?v=2HrDtVpTvFk&feature=youtu.be

**Comment by Brottweiler** [comment]
What server was this on?

**Comment by ghost** [comment]
Mini01 EU

**Comment by 96alexmr** [comment]
@Brottweiler Couldn't this be due to the time it takes for EU to send it's data across the network?

**Comment by 2000thehecf1** [comment]
I think this is something related with /nick. This sometimes ocurres on the web too

**Comment by BlueManOtti** [comment]
Maybe the same issue that appears here #1531

**Comment by Electroid** [comment]
Not a bug anymore.
