### ISSUE TITLE
Armor not unbreakable on Remant Souls

### ISSUE THREAD

**Issue by PartyToad** [OvercastNetwork/Issues#1935]
Kinda of a bad thing if you survive for a while and your armor breaks. 

Recreate:
Join a match and look at the armor

**Comment by Brettogden** [comment]
This isn't a map issue, it's the map makers choice to include unbreakable armor or not.

**Comment by Electroid** [comment]
Let's fix this.

**Comment by Brettogden** [comment]
@Electroid Fix what? A gameplay choice by the map maker?

**Comment by Tywnis** [comment]
I'd rather have long-living players' armor break to spice up the game and weaken a position they've held for a long time. So yes, choice.
