### ISSUE TITLE
[Timberwood] Update 1.1.0

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#1938]
- Fixed up a few problems with some terrain 
- Added Team colored banners on either side
- Speed Potion in "secret" chests is now a strength potion for 0:05 seconds.
- No map.png displayed on the map's specific page, here's one
- Updated observer spawn 
  http://i.imgur.com/5aUn79q.png
  https://dl.dropboxusercontent.com/u/100723916/samtheman43/samtheman43-1.zip

**Comment by AnthonyTag** [comment]
Please refrain from making issues before you have the download necessary for us to update. No need to reserve an issue! ;-)

**Comment by samthecat** [comment]
@ajtag5 Updated.

**Comment by samthecat** [comment]
Thanks :)
