### ISSUE TITLE
[Canopy] Random floating grass patches on the outside of the map. 

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#1939]
![2015-06-21_11 16 44](https://cloud.githubusercontent.com/assets/10585916/8272208/fd35ddb6-1807-11e5-947e-fefa7634b74c.png)

**Comment by Tapetepato** [comment]
what map is that?
Edit: sorry, didn't see that in the tile :/

**Comment by ResentFeeds** [comment]
That's  Canopy

**Comment by eliyap** [comment]
Not pruned properly I'm guessing, or accessed in SP after it was pruned

**Comment by samthecat** [comment]
@Ipskie yup, that'll do it.
