### ISSUE TITLE
Multiple /servers

### ISSUE THREAD

**Issue by LoveRokenbok** [OvercastNetwork/Issues#194]
The servers list has turned into a giant mess with the addition of blitz and ghost squadron servers, so perhaps we could use a server list like this:

/servers -- Shows all servers on the lists and pages below (Like /help)
/servers pa -- Shows the Lobby and Project Ares servers on the list.
/servers blitz -- Shows the Lobby and Blitz servers on the list.
/servers gs -- Shows the Ghost Squadron servers on the list.

(Marble37's idea)

**Comment by Electroid** [comment]
Servers list isn't a giant mess anymore; this obsolete.
