### ISSUE TITLE
Incorrect title in Battle ecliptica II Blitz

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#1941]
![2015-06-21_23 39 12](https://cloud.githubusercontent.com/assets/8332105/8273442/d58cff9e-186e-11e5-923a-6ffd7ddbdf89.png)
"You may not join during a players remaining match"

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/1932

**Comment by eudaldca** [comment]
@mrapple Feel free to label #1932
