### ISSUE TITLE
King Cube (RAGE) does not force respawn

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#1943]
Title says it all. You have 2 lives.

https://oc.tc/maps/king_cube

**Comment by Brottweiler** [comment]
Does any blitz map have force respawn when they have multiple lifes?

**Comment by jexeI** [comment]
some do, I know Plus Side, 101 rooms, and Prolieum do. I think Cubed3 dosent, but I don't remember for sure.

**Comment by jexeI** [comment]
Is there a way to check in the XML of the maps?

**Comment by 96alexmr** [comment]
@JexeI https://maps.oc.tc/

**Comment by Brettogden** [comment]
King Cube has been removed from the repo, closing now.
