### ISSUE TITLE
Transverse | You can place blocks in your own spawn.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1944]
Here, as you can see in this picture, you can place blocks in your team's spawn (water).

http://gyazo.com/30fa207adaed47591ec0534a3493b44b

**Comment by mattarnold98** [comment]
This map isn't loaded on the servers, it was only tested (probably doesn't need an issue).
I'll send this to elijah over skype to notify him though.

**Comment by eliyap** [comment]
Map does not officially exist, so this ain't the place. Also I fixed this. Thanks for the heads up!
