### ISSUE TITLE
Map Update- Larnia v1.4.2(XML Fix and Small Map Change)

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#1951]
Download with level.dat region and map.xml
https://www.dropbox.com/s/l4ue7t72lw3mbyr/larnia1.4.2edit.zip?dl=0(Fixed)

Changelog v1.4.2

> > Added Regeneration 2 for 3 seconds as kill reward
> > Changed Speed so both teams to just have Speed 1 for 2 Minutes.
> > Fixed off region for flag room denial
> > Changed the armor so its equal for both teams(hoping PvP turns more friendly for killing attackers, as it seems rather challenging).
> > Changed some of the bridges to be slanted and "choppy" so its more natural. 
> > Added a Regeneration 2 Potion in the "miniature cave".
> > Changed some of the pathways to make attackers approach or way back a little more slow.

**Comment by eliyap** [comment]
So mitch loaded this up for me, and nothing changed. I looked through the XML and the map, I couldn't find any of what you're describing

**Comment by LArrowHead** [comment]
everything i described should be there... the xml is fine, i checked it, it was updated. I also even replaced the download in the original post with a new one just now. The speed is in the main kit(spawn). The Regeneration i added is in the kill reward. There was an off region where i added a negative to the cords in the xml. I made the armor equal for both teams in their kits. I changed the bridges slightly, to have little edges in them, if you can see that. I added a chest in this little cave area in the middle of the map(hard to see). I also just replaced some stairs in areas with ladders to make some of the map slower for both teams to go through.

**Comment by LArrowHead** [comment]
so i fixed the download, try and load it back up!

**Comment by eliyap** [comment]
Yeah, it was my mistake, sorry

**Comment by LArrowHead** [comment]
no its alright i actually did get the wrong download
