### ISSUE TITLE
Sign Board not updating in the lobbies.

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#1952]
<img src="http://imgur.com/6CbSwbT.png">
<br>
<br>
The same maps have been on the sign board all day, not changing, facility is always on mini01, saying it has 24 out of 28 people, but when you join, its something else in the rotation. Also, none of the new servers that have opened throughout the day are showing up when they turn on, so i feel like the lobby is "frozen".

**Comment by tonybruess** [comment]
Is this still an issue? Usually rolling lobby restarts fix this whenever there's a database blip

**Comment by LArrowHead** [comment]
It only occured that once for me, it might have just been a slight bug, i
haven't seen it since. (Sorry for late reply I never checked my email in a
few days)
