### ISSUE TITLE
Hot Dam Mini Glitch: No lava in core

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#1954]
I just played a match on hot damn mini where i came on late, both teams only had one obsidian left and you could break the birch planks or glass around it and get the objective, there was no lava left, so it had to be ended.

**Comment by ghost** [comment]
https://oc.tc/forums/topics/558c9c735f35b9f5b00007a3?page=1#558c9ce0c29635aae0007770
Can confirm.

**Comment by LArrowHead** [comment]
^^yea, it was hard to find because there was only one piece left each team.

**Comment by Pugzy** [comment]
Unable to replicate issue.
