### ISSUE TITLE
Settings command doesn't show the correct amount of pages.

### ISSUE THREAD

**Issue by Pingy** [OvercastNetwork/Issues#1955]
<a href="http://imgur.com/7KDZLRJ"><img src="http://i.imgur.com/7KDZLRJ.png" title="source: imgur.com" /></a>

As you see in both pages it says there is only 1 page of available settings but in reality there are 2 total pages of settings.

**Comment by Brottweiler** [comment]
Those two pages look identical to me.

**Comment by Pingy** [comment]
oh wait

**Comment by Pingy** [comment]
god dangit Im an idiot
