### ISSUE TITLE
Zemphon is always high on the online list (forums) eventhough he hasn't got any ranks

### ISSUE THREAD

**Issue by andrgorr** [OvercastNetwork/Issues#1957]
Have seen Zemphon multiple times over or inside referees list and if I recall properly, inside of the mods list.

This shows him being inside the referees:

![image](https://cloud.githubusercontent.com/assets/7956703/8384637/add596dc-1c42-11e5-9c6a-4ccc18bd0d6c.png)

<a href="https://oc.tc/Zemphon">This is his profile</a>:

<img src="http://i.imgur.com/9w1EdHY.png">

**Comment by jedediah** [comment]
fixed
