### ISSUE TITLE
Dying whilst carrying the flag on Canopy lets you keep the flag on respawn

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1959]
Original post by OreMiner28

Today while I was playing on Canopy, something weird happened. I was running with the flag to my base, and was shot. But when I respawned, I was still carrying the flag, and was able to capture it. This happened two other times in the match with other people as well. Because of this, my team won the game.

Here's the chat when this happened

![enter image description here](http://i.imgur.com/jSv0gHp.png)

As you can see, I picked up the flag instantly after I died.

And here's me with the flag, still on my head even though I had gotten killed

![enter image description here](http://i.imgur.com/BCzgte0.png)

Posted this here on github as a reminder. I know that Electroid knows about the bug, so if this issue is not needed, you can just close it.

**Comment by ElliottWhyman** [comment]
This is not handle by the map so this would be a plugin issue, going to test this as I think this may have been fixed

**Comment by ElliottWhyman** [comment]
Fixed with a plugin update, not a map issue.
