### ISSUE TITLE
Empty inventory in Tenebrous. 

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1960]
As you can see in this video, when the match start in Tenebrous, your inventory is empty. 

This match was in Capture EU

Video --> https://www.youtube.com/watch?v=W6zdUp6PjzU&feature=youtu.be

**Comment by Brottweiler** [comment]
Should be fixed

**Comment by ghost** [comment]
Yeah, It looks fixed. Thanks anyways ;)
