### ISSUE TITLE
FFA on oc.tc/maps makes objective message move up

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#1961]
I know FFA isn't implemented to oc.tc/maps but since some GS maps use FFA I decided to report this since it already happens on maps pages of the GS FFA maps.

![](http://i.gyazo.com/40b44585fa76854524d82f011e7e5930.png)

https://oc.tc/maps/prototype_ffa

Since theres no teams it makes the objective message move up.

**Comment by ghost** [comment]
No longer an issue
<img src="http://prntscr.com/98ks25/direct">
