### ISSUE TITLE
Map Update - Explosive Vengeance

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#1963]
A small XML-only update.

https://github.com/DoomRobotBoy/Maps-XML/blob/master/ExplosiveVengeance.xml

Fixed:
- Missing blocks in spawn kit
- Wrong objective
- Kills not counting
- some filters

**Comment by Pugzy** [comment]
I have explained the map issues with @DoomRobotBoy and the map has currently been removed from the repository until made functional.
