### ISSUE TITLE
Users using /nick appears like observers in tab.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1965]
![#1](http://i.imgur.com/rYMvDK4.png)
![#2](http://i.imgur.com/ylM3rM4.png)

**Comment by Matic0B** [comment]
Can confirm even if the users are not friends.

**Comment by LArrowHead** [comment]
well there is a same issue like this except the crossed out name is not there, instead its just a light aqua color with the nicked player, so its extremely obvious they are nicked.

**Comment by Matic0B** [comment]
@LArrowHead Its crossed if the users are friends because friends can see your nick

**Comment by Brottweiler** [comment]
Does it still happen?

**Comment by ghost** [comment]
Yes, it still happend.

Screenshot evidence --> http://gyazo.com/02606c5293f15d121a32636054feaf49

**Comment by tonybruess** [comment]
Fixed

**Comment by 2000thehecf1** [comment]
It isn't already fixed http://gyazo.com/6ea220d2bb1049037fdd6cc3cc3734bc

**Comment by Brottweiler** [comment]
Issue might still exist for nicked players.

**Comment by tonybruess** [comment]
That server wasn't updated
