### ISSUE TITLE
Wrong wool placement coordinates on Ouroboros

### ISSUE THREAD

**Issue by Geeeees** [OvercastNetwork/Issues#1975]
Well i was playing Ouroboros and when i place the blue wool at the blue monument i just can't place it, so i place it in the red wool and here is the result:

http://prntscr.com/7p8r8n

Sorry if the issue was reported before :P

**Comment by eliyap** [comment]
Maybe change the title to "Wrong wool placement coordinates on Ouroboros" or something

**Comment by Geeeees** [comment]
I'll change it.
