### ISSUE TITLE
Map update - Secluded Palace version 1.2.0

### ISSUE THREAD

**Issue by mattarnold98** [OvercastNetwork/Issues#1980]
**Changelog:**
- Fixed possible ways to escape the map.
- Added a second floor to the palace.
- Added more cover.
- Reduced middle chest contents.
- Changed spawn location.

Download: http://www.mediafire.com/download/gu9d4ijacyyaqpt/SecludedPalace.zip

(Includes map.xml as the spawn location was changed.)

**Comment by Pugzy** [comment]
Currently in the process of fixing a few physical issues on the map.

**Comment by AnthonyTag** [comment]
@iPGz ever get this done?

**Comment by Pugzy** [comment]
@ajtag5 we were waiting on the update map commands to fix these quick small issues however its status seems to be non-functional so the map changes will need to be made else where @yoyopower

**Comment by Electroid** [comment]
@iPGz It works now.
