### ISSUE TITLE
Fallencrests 2 | Alert Rate message is wrong

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1981]
When you are going to rate the map and you haven't participated in this map enough, the message is wrong, as you can see in this screenshot.

-Sorry, You haven''t participated in this match enough to rate the map.

http://gyazo.com/41e86bfc03f1ef346651e79ba0f5f962

**Comment by ResentFeeds** [comment]
I'm pretty sure that is intended

**Comment by mitchts** [comment]
Dupe, #1884
