### ISSUE TITLE
MOTD broken on Forge clients

### ISSUE THREAD

**Issue by unixfox** [OvercastNetwork/Issues#1982]
A classic version of Minecraft 1.8.x displays MOTD perfectly : 
![](http://puu.sh/iRu4f/c0f6532835.png)
But a version of Forge Minecraft 1.8 displays MOTD differently : 
![](http://puu.sh/iRukb/ba6faa453b.png)

**Comment by eliyap** [comment]
I don't think we deal with problems from non-vanilla clients

**Comment by Brottweiler** [comment]
Report it to Forge.

**Comment by ghost** [comment]
http://www.minecraftforge.net/forum/index.php/topic,31893.0.html

**Comment by tonybruess** [comment]
That looks like a font/texture pack issue. Does forge change the font or do you have a texture pack?

**Comment by unixfox** [comment]
As LexManos [said on Forge forums](http://www.minecraftforge.net/forum/index.php/topic,31893.msg166502.html#msg166502), this is a problem with the check mark : 

> The MOTD isn't 'broken' its just rendered in a smaller width to make room for the check mark.

@tonybruess Yes I've a texture pack but without there is no difference : 
![](http://puu.sh/iRP7D/2e6eec5a45.png)

**Comment by tonybruess** [comment]
Seems a little strange he doesn't mind breaking vanilla motds. Why not just put the check mark in line with the player count/ping bars?

**Comment by ghost** [comment]
@tonybruess "Because it looks good where it is, and it'd have the same 'issue' as this one where long server names wouldn't display 'properly'
You can fix it on your end by lowering the width of your banner, pretty sure MOTD's rendering supports \n"

**Comment by Brottweiler** [comment]
@TiTo-418 Ofcourse we _can_ fix it by making the MOTD shorter, but we shouldn't have to fix anything because forge breaks it.
