### ISSUE TITLE
The core does not count on Blocks 2 

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1983]
I broke a piece of the glass turned into obsidian. I then broke that and lava leaked out this caused the game to end. However it never said someone broke a piece of a core or awarded me the core. 

I mined from the bottom of it

**Comment by DoomRobotBoy** [comment]
Dupe from #1747. Different titles, same subject.

Oh btw, Pugzy and I narrowed the error down and found out that you cannot use blockdrops on a core. The cores worked fine without the extra blockdrops, and for what I know Pugzy already reported it to the devs?

**Comment by ghost** [comment]
People should have more descriptive titles.
