### ISSUE TITLE
Emoji's don't display in Chrome tabs

### ISSUE THREAD

**Issue by eliyap** [OvercastNetwork/Issues#1988]
![screen shot 2015-07-11 at 7 38 50 pm](https://cloud.githubusercontent.com/assets/7846005/8633631/88470324-2804-11e5-964f-8605ea02ef13.png)
As you can see, Emoji's are displaying their names, whereas in ioioy's scrim video post, the flag icons work. Both are images.
Threads:
https://oc.tc/forums/topics/559e8b6e67d522d4fc001d57
https://oc.tc/forums/topics/5586d46067d522cd72001949
Chrome version info:
Google Chrome   43.0.2357.132 (Official Build) (64-bit)
Revision    7df48020529f8b262116e261b3d2bdc91edcfdc7-refs/branch-heads/2357@{#494}
OS  Mac OS X 
Blink   537.36 (@197431)
JavaScript  V8 4.3.61.34
Flash   18.0.0.203
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by Brottweiler** [comment]
https://github.com/OvercastNetwork/Issues/issues/965
