### ISSUE TITLE
You can hurt yourself with your own arrows (cannot hurt other teamates)

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#1989]
https://youtu.be/6n3syL9a_F8

**Comment by Brottweiler** [comment]
Apparently occurs on not only RAGE, that you can shoot yourself.

**Comment by jexeI** [comment]
Yeah, works on all gamemodes

**Comment by jexeI** [comment]
And if you look at my profile, I get the kill and death, which I just recently found out. Thought It wouldn't show up because it was a teamkill.

**Comment by ghost** [comment]
I think this should be kept as it allows you to have more ways of getting around things and could lead to some interesting tactics

**Comment by Brottweiler** [comment]
@orky48 it's a bug report, not feature request. You can make those on the forums. Keep this ontopic.

**Comment by LArrowHead** [comment]
well i was just about to report this. huh.

**Comment by jedediah** [comment]
This is not a bug. You are supposed to be able to hurt yourself with arrows. A bug in Minecraft prevented self-damage if you were on a team with friendly-fire disabled, and I fixed that bug yesterday. The bug affected TNT as well, but only if you activated it with a flint & steel, so few people noticed.

However, suicide showing up as a PvP encounter on the website is a bug. I'll fix that.

**Comment by tonybruess** [comment]
Fixed
