### ISSUE TITLE
Incorrect linking in docs.oc.tc

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#1994]
Under modules, regions tab, under "Applying Things to Regions", under value, "filter" redirects to docs.oc.tc/modules/filter instead of /filters. This makes the docs.oc.tc home page appear.

**Comment by Matic0B** [comment]
Created a pull-reqiest.
https://github.com/OvercastNetwork/docs.oc.tc/pull/197

**Comment by ElliottWhyman** [comment]
This belongs on the docs.oc.tc issue tracker
