### ISSUE TITLE
Random grey stained clay block on Lobby

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#1997]
![2015-07-13_15 31 43](https://cloud.githubusercontent.com/assets/8422075/8660119/98b3c424-2974-11e5-9caa-2979f15a0dbc.png)

**Comment by Electroid** [comment]
The work of a moderator. Will be gone on restart.

**Comment by samthecat** [comment]
@Electroid could that have been a certain Sheriff? :P
