### ISSUE TITLE
oc.tc/practice leads to 404

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#1998]
![](http://i.gyazo.com/570480a9900a17f74bb431f3f75d3db2.png)

It leads to a 404 page, probably because it leads to a hidden topic from the previous tournament.

**Comment by itsmartin** [comment]
Fixed, thanks for reporting.

**Comment by ghost** [comment]
It's happening again

**Comment by itsmartin** [comment]
Fixed.
