### ISSUE TITLE
Chest of Spaceship Battles TE are wrong sided on Tournament Servers

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#1999]
Only in the Red team side 

![Image1](http://i.imgur.com/n1F7Wfh.png)
![Image2](http://i.imgur.com/mNtRhVS.png)
![Image3](http://i.imgur.com/RfbgiBG.png)

Edited Images.

**Comment by ghost** [comment]
They remain wrong sided...

**Comment by ghost** [comment]
@Vixo1 /restart?

**Comment by ghost** [comment]
Keeps wrong /server xxoemyixx

**Comment by Qixit** [comment]
@Vixo1 According to the players currently on the server, there are no problems with the map. Are you sure?
