### ISSUE TITLE
Server Online Tag

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#2]
Add a feature that it just does not only show what server you are on your profile, but also on the forums. (Example is attached.)
![Online Status](https://f.cloud.github.com/assets/2856681/428778/49f83f00-ae1e-11e2-9b19-c233b309663b.PNG)

**Comment by Electroid** [comment]
It hath been done, deployed soon.

**Comment by ghost** [comment]
> and if you hover, you get the current server they're on.

Any chance of a tooltip saying the server - would probably make it easier to understand and add more functionality to the feature.

Can I suggest things on a suggestion, or am I still breaking the rules? :stuck_out_tongue:
