### ISSUE TITLE
Friendly fire restriction bypassed if shooter joins observers while arrow is in flight

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/Issues#200]
### The issue

If a player shoots an arrow, then joins observers (e.g. by dying on Blitz), their arrow is able to damage their former teammates.

### Example

See the bottom 4 lines of the below screenshot:

![screenshot](http://gyazo.com/1057a9ae92b18cd412b5e460b6ed317a.png)

(This is taken from [this thread](https://oc.tc/forums/topics/51a60eefa8785878b70064bb))

### Proposed solutions

* Arrows should remember which team their shooter belonged to at the time they were shot.

or

* When a player leaves a team, all arrows shot by them should be removed

**Comment by Pugzy** [comment]
I believe this is fixed.
