### ISSUE TITLE
Map Update - SweetTooth

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2007]
Map Changes:
-Made it a perfect circle
-Made paths flatter
-The arch is now easier to get up onto

XML Changes:
-Gave players speed 2 
-Added another life
-Moved obs spawn
-New map.png

Download: https://www.dropbox.com/s/xty3jmpl6i97ujw/SweetTooth.zip?dl=0

**Comment by Oo-TheFrog** [comment]
@iPGz Any reason for why the lives were lowed back down to 2?

**Comment by AnthonyTag** [comment]
@Oo-TheFrog They were moved down to one soon after the initial addition of the map because many found 2 lives to be too long and compared to other rage maps, it was.

**Comment by Oo-TheFrog** [comment]
@AnthonyTag I added speed 2 and made the map smaller so 2 lives fit better, the ratings went up with the 2 lives.
