### ISSUE TITLE
Bug in Desert Sanctuary TE

### ISSUE THREAD

**Issue by SnickerCRC** [OvercastNetwork/Issues#2011]
If you have the flag and you jump in to the void and fast press f3+s you stay flying.
https://www.youtube.com/watch?v=0dmGbNb4JvU can you see in this video

**Comment by ghost** [comment]
this s not a map issue, but an issue with the pgm.

**Comment by Pugzy** [comment]
This is not a PGM issue, but an issue with Minecraft.

**Comment by ghost** [comment]
@iPGz  you can make a plugin that detects if a player is still mid air for longer than a certain period of time. doesn't make it a pgm bug tho.

**Comment by Matic0B** [comment]
f3+s reloads sounds which the players client freezes for a bit and i guess that could count as lagging for a bit? idk

**Comment by ElliottWhyman** [comment]
@matic0basle I don't think he did `f3+s` but rather right clicked the minecraft window bar

**Comment by Matic0B** [comment]
@CaptainElliott OP: 

> and fast press f3+s you

**Comment by ElliottWhyman** [comment]
@matic0basle yes, I know it said that but I don't think that's what caused it, even if it did the issue will also arise when you right click the task bar which is much more serious

**Comment by Matic0B** [comment]
@CaptainElliott I did a test jumping out with one account and seeing it through another. Can confirm it happens with F3+S
