### ISSUE TITLE
How-to book cannot be opened in observers

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#2015]
As simple as this, you can no longer open the book. I'm going to guess it is due to the new localisation of the book.

**Comment by Superjd10** [comment]
@mitchiiii The how to book is in https://maps.oc.tc/howto.xml, most likely a "Map" bug (maps repo) and not a Plugin bug.

**Comment by AnthonyTag** [comment]
@Superjd10 but the plugin handles the book, the xml is just the contents

**Comment by ghost** [comment]
Fixed http://prntscr.com/8rtjgs

**Comment by ghost** [comment]
Ok, now it doesn't even appear in the inventory 
![2016-02-28_22 39 30](https://cloud.githubusercontent.com/assets/11008016/13383743/b623de92-de6c-11e5-9bbf-86d2a9f698f4.png)

**Comment by ghost** [comment]
Fixed 
![screenshot_5](https://cloud.githubusercontent.com/assets/11008016/14067664/1b0604d2-f440-11e5-970d-86d683aa5219.png)
