### ISSUE TITLE
Snowball deaths don't give the kill to anyone

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2023]
![2015-07-22_21 58 24](https://cloud.githubusercontent.com/assets/8422075/8854610/515e94fa-3126-11e5-96b3-67fc0421bda2.png)
it just says "hit by a stray Snowball" when you shoot someone with a bow that shoots snoballs (Like on Glacial Impact)

**Comment by Brottweiler** [comment]
Related https://github.com/OvercastNetwork/Issues/issues/2024

**Comment by mitchts** [comment]
Fixed
