### ISSUE TITLE
Enderpearl kills have an incorrect name and don't give the kill to anyone

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2024]
![2015-07-22_20 57 33](https://cloud.githubusercontent.com/assets/8422075/8854661/98287928-3126-11e5-8fa5-5bbe5b1565ff.png)

when you kill someone with a bow that shoots enderpearls (like in Ozone)
the death message doesn't give a kill to anyone, and instead of saying "by an enderpearl" or "with an enderpearl" it says " by a stray entity. ThrownEnderpearl.name"

**Comment by Brottweiler** [comment]
Actually this is the same thing as https://github.com/OvercastNetwork/Issues/issues/2023
