### ISSUE TITLE
Observers can put out fires

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2025]
No, this is not client-side only.

**Comment by Brottweiler** [comment]
Were there an ingame player that confirmed that you could put out the fire?

**Comment by jexeI** [comment]
Yes, I put some out for others to see, and another player put some out for me to see and confirm.

**Comment by jexeI** [comment]
Oh, This occurred in the RAGE game mode.

**Comment by jedediah** [comment]
I just tried this and it's client-side only. What map did you see it on?

**Comment by jexeI** [comment]
Fallen courtyard in RAGE

**Comment by jedediah** [comment]
The fire on the hoppers? Yeah, I can't put it out as an obs. It only disappears on the client, and it comes back if I right click it.

**Comment by jexeI** [comment]
Hmm? Really? I put out the four on both of the spawns, and when the match started, they were still gone, but I had another obs put out the other 4 on the sides, and it worked.

**Comment by CoWinkKeyDinkInc** [comment]
I already reported this in #1107 as a client-side problem.
