### ISSUE TITLE
You can see other players' nick.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2029]
As tittle says, you can see other players' nick when you don't have them as friend http://i.imgur.com/deBUo5h.png

**Comment by Pugzy** [comment]
@Kenner390 are you friends with this players?

**Comment by ghost** [comment]
@iPGz no

**Comment by jedediah** [comment]
Any idea how to reproduce this? I can't

**Comment by ghost** [comment]
@jedediah Maybe add a friend and remove it

**Comment by mitchts** [comment]
Looks like this was closed by accident.

**Comment by jedediah** [comment]
I actually fixed this today
