### ISSUE TITLE
If you leave a match after breaking an objective, but not completing it, it doesn't count on your stats after its broken completly

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2041]
The only map i have seen this happen is on The Nile, since it usually lasts long and i don't play the whole match.
Example of this:
![2015-07-29_21 39 09](https://cloud.githubusercontent.com/assets/8422075/8984764/5e0c19de-3699-11e5-85bf-070ee40decd0.png)

https://oc.tc/matches/55b9760ac8f2b3cfc50dd4cc
https://oc.tc/Tapetepato
I joined a The Nile match yesterday, on the picture, you can see me breaking red team's monument, in the chat and in the breaking animation. I managed to break 2 pieces. Then, a lot of minutes passed, and also, a long time in the match before i broke the monument. I left the game eventually, and it ended like 20+ minutes after i broke those 2 pieces. As you can see in the match link, blue team won, but i didn't get the objective on my profile.

**Comment by Pugzy** [comment]
@Tapetepato is this the objective you are talking about?

![](http://i.imgur.com/VmzvE8Q.png)

**Comment by Tapetepato** [comment]
yes, it didnt show up for those 12 hours
