### ISSUE TITLE
Small Issue on Tetrad

### ISSUE THREAD

**Issue by Joshua171** [OvercastNetwork/Issues#2043]
Nothing major just, while most of the islands connecting 2 colours look like this:

![](http://i.imgur.com/Go9HFQC.png)

The island connecting Green and Red has one that looks like this:

![](http://i.imgur.com/aSzcoe9.png)

**Comment by Brokennz** [comment]
I do not think this will affect the gameplay, just it's a error in decoration.
You should change the name.

**Comment by Brottweiler** [comment]
https://oc.tc/forums/topics/5418a2cdc296359af0003671
