### ISSUE TITLE
Server portal doesn't show the correct ammount of players

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2046]
![2015-07-31_10 27 46](https://cloud.githubusercontent.com/assets/8422075/9010938/b5ea1a44-376f-11e5-8523-72c725027445.png)
![2015-07-31_10 27 56](https://cloud.githubusercontent.com/assets/8422075/9010939/b5ec485a-376f-11e5-953c-e64203075b96.png)
 The portal shows that there's one player but the sign shows theres 22

**Comment by Brottweiler** [comment]
https://github.com/OvercastNetwork/Issues/issues/1952
