### ISSUE TITLE
DK crossovers DTE issue

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#2047]
The bottom of the spawn drops can be broken, resulting into getting easily griefed.
![2015-07-31_23 45 31](https://cloud.githubusercontent.com/assets/8332105/9018393/e9169e6e-37de-11e5-880b-e9c1fbe880b1.png)

**Comment by DoomRobotBoy** [comment]
The entire map was broken, so not only the spawn drops could be broken :c 

The entirety of this issue and all other issues in DK Crossovers are fixed in an upcoming update.

**Comment by mitchts** [comment]
Fixed in the update that was just pushed.
