### ISSUE TITLE
Badlands: CTF

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2051]
Badlands CTF is showing the blue team as "Blu"
Pic: http://gyazo.com/54337291b3fe38f37d4a26ce2e114118

**Comment by Qixit** [comment]
The map is based off a map from Team Fortress 2, where the teams are named Blu and Red. This is no error, well at least I think so. I'll try asking the mapmaker.

**Comment by mitchts** [comment]
This is intentional.
