### ISSUE TITLE
Update Coniferous Forest to 1.5.1

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#2052]
There's been a lot of changes happening in my Residency back in May 2015. I can't list them all, but here's some of them:
- Moved Spawn (there's two spawns now!)
- widened Caves
- removed Pit
- added Health Spawner
- Redesigned Flag Area
- Terrain Changes
- Huge XML Changes
- Defending was made easier
- ...

Overall it plays better now (:

http://www.mediafire.com/download/wdjt0jy88hdcq0b/Coniferous+F.zip

**Comment by Pugzy** [comment]
May I ask how you got to your current version number of `1.5.1` the version on the server seems to be `1.1`.

Also your XML within the file above contains the outdated `damage="-3000"` whereas the current version in repo has `unbreakable="true"`.

**Comment by rockymine** [comment]
@iPGz: Over the residency I have made a document where I have listed all the changes, like that I found out that Coniferous Forest currently is in Version 1.5.1. About the XML I'm sure that Electroid changed it to unbreakable when he did that huge Update-Session for all repo maps.

**Comment by AnthonyTag** [comment]
@rockymine May I suggest when you update your map's xml to save the one on the repo from maps.oc.tc? I believe you have to navigate to the file and then right click > save as...

This will get rid of silly mistakes like the unbreakable situation! :smiley:

**Comment by rockymine** [comment]
@AnthonyTag: No don't use that one, please...It's totally outraged, you have to use the one in my download. Just fix that mistake then.

**Comment by Pugzy** [comment]
@rockymine he is saying that in the future you should use the XML on maps.oc.tc as a base when updating your map. If map developers make changes to the XML (like in this case) the version on your PC will be out dated.

Check out this post for more info: https://oc.tc/forums/topics/557effb55f35b9d00200b7b1
