### ISSUE TITLE
You can now break the beacon on Koi

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2053]
Since the new map update, which allowed you to break literally all the blocks on the map, you can now break the center beacon, get enough gold blocks, and make a really OP beacon. I personally consider this a bug, but if it was meant to be like this, then you can close this issue.

**Comment by Tapetepato** [comment]
I think it was meant to be like this, and it gives more options to the maps like defending or tunneling

**Comment by ghost** [comment]
fixed, thanks for reporting

xml download: https://www.dropbox.com/s/6j41nev5mglo2v0/map.xml?dl=0

**Comment by jexeI** [comment]
Can this be closed?

**Comment by Brottweiler** [comment]
@JexeI oh yeah in the future, you can close your own issues. :)

**Comment by ghost** [comment]
i dont know if the xml is actually pushed to the server, if not, this is not fixed

**Comment by AnthonyTag** [comment]
Reopening until I push this.

**Comment by jexeI** [comment]
Like until the Xml is implemented?

**Comment by Qixit** [comment]
Yes @JexeI .
