### ISSUE TITLE
The 4th law - wools in the dispensers are gone.

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Issues#2063]
As you can see: 

![The 4th law is broken](http://puu.sh/jxxp6/098df2f430.jpg)

It has to do with the "-1" wools

**Comment by 2000thehecf1** [comment]
#1912 ?

**Comment by Pugzy** [comment]
I'll leave this for @Tywnis as I don't have a clue where the no-void regions start and end, don't want to mess it up.

**Comment by mitchts** [comment]
Was fixed in https://github.com/OvercastNetwork/Maps/commit/04458516b479bb9bbdf9dacb8e12642f94a2af4b
