### ISSUE TITLE
Enchanting impossible on Viridun as of 1.8

### ISSUE THREAD

**Issue by WolfLink** [OvercastNetwork/Issues#2066]
It is impossible to enchant in Viridun since the new version of enchanting requires lapis as well as experience points.  An easy fix would be to add lapis to the chests that also contain experience bottles.

Also, since the new mod causes potion bottles to be consumed upon drinking, it is impossible to brew potions in Viridian's potion rooms.  An easy fix would be to add empty bottles in or near the potion room chests.

**Comment by ghost** [comment]
this should be 'related to 1.8', since it is not only related to 1.8.8, but to all of the 1.8 versions.
