### ISSUE TITLE
Sometimes observers may spawn at the default world spawn

### ISSUE THREAD

**Issue by skippy369** [OvercastNetwork/Issues#207]
When switching servers, joining obs, etc, observers may be spawned in random locations around the map.

Video of the glitch: http://www.youtube.com/watch?v=do8S9lvVS-c&feature=youtu.be

I've noticed that on specific maps that the bug spawn location is usually in the same place:

SSB's is usually a good amount of blocks above the actual observer spawn.
Soviet Mills' is usually in the open field.
RFV3 is usually under the map in the void.

**Comment by Electroid** [comment]
This doesn't happen anymore.
