### ISSUE TITLE
/Find [name] show old information

### ISSUE THREAD

**Issue by Brokennz** [OvercastNetwork/Issues#2071]
If you do /find Gaange (for example) it will says that he was 1 month ago in Primed.
But that information is false.

![2b62ee1b4fb33106fa8745554e726c0a](https://cloud.githubusercontent.com/assets/11890645/9242134/a5c7fd0c-4142-11e5-8289-c1bdd5c30465.png)
![b0d9c39bddb64e5c438ded14eeed3658](https://cloud.githubusercontent.com/assets/11890645/9242135/a5ca0aca-4142-11e5-8939-4167f03c2c21.png)

Thanks for your time.

**Comment by itsmartin** [comment]
The player in the first screenshot is https://oc.tc/Gangee, the player in the second is https://oc.tc/Gaange.
