### ISSUE TITLE
The Website is bugged 

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2076]
The Account Accomplished_ got banned for Kill aura [V] and the website says he is still on and that is wierd can you fix that because when you do /seen Accomplished_  it says last seen 22 hours ago! pls fix this i have two screenshot proofs!

Images
http://imgur.com/SfpQ96b,cHGz7YA

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/2048

**Comment by ElliottWhyman** [comment]
Please give more appropriate titles in the future
