### ISSUE TITLE
Map sizes are wrong on Ranked servers at oc.tc/play

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2077]
https://gyazo.com/65f3b03948bc471c9e27a0c54397c7f5

In this example we see that Desert Sanctuary appears with 40 slots, when in ranked matches it only has 20. It happens aswell with all the other maps that have a public version.

**Comment by CoWinkKeyDinkInc** [comment]
I think Plastix and others said the reason for this was to reflect how tourney maps, are 10v10.  Also, all of them are 10v10.

**Comment by jedediah** [comment]
It's showing the team size for the non-ranked version of the map. We don't handle duplicate map names very well right now.
