### ISSUE TITLE
After cooldown timer on ranked matches ends, it displays "3 out of 3 matches played" When I haven't played any yet.

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#2079]
![2015-08-18_15 14 42](https://cloud.githubusercontent.com/assets/10585916/9340194/5e8d1232-45bc-11e5-80aa-94986c1e6b65.png)

**Comment by tonybruess** [comment]
You played your 4 ranked matches 24 hours ago. They're gradually becoming available.

**Comment by samthecat** [comment]
oh.

**Comment by tonybruess** [comment]
We should probably clarify the message

**Comment by samthecat** [comment]
yeah, that makes sense.
