### ISSUE TITLE
Map ratings stay the same on latest version and all versions on some maps.

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2086]
I don't know if this is an xml issue or web, I have updated this map a few times. 

https://gyazo.com/214b13c42ca1ffb384677675c49df2a9

https://gyazo.com/28a095d822c9e83813d8e8203c65cd42

**Comment by mitchts** [comment]
The `Latest Version` tab only changes for major or minor changes, [not patches](http://semver.org/).
