### ISSUE TITLE
Ranked match doesn't appear on my profile.

### ISSUE THREAD

**Issue by Sylife** [OvercastNetwork/Issues#2088]
Yesterday I played a ranked match on Desert Sanctuary but it doesn't appear in my profile. 
Match Details: https://oc.tc/matches/55d5578fc8f2c9ea6689e00e
I don't know if it's my error or what happened, but I checked the other players that were on the same match and it's on their profile.

**Comment by Brottweiler** [comment]
Actually, I think some matches 2 days ago were lost due to database maintenance. Report again if it still happens.
