### ISSUE TITLE
Messages being duplicated

### ISSUE THREAD

**Issue by eliyap** [OvercastNetwork/Issues#2089]
![screen shot 2015-08-21 at 5 13 28 pm](https://cloud.githubusercontent.com/assets/7846005/9405171/10949168-4828-11e5-90dc-091c08a5c70f.png)

**Comment by Brottweiler** [comment]
This has been a problem before, but apparently wasn't reported on the issue tracker it seems. Not sure if it was fixed then it happened again or what.

**Comment by ghost** [comment]
@Brottweiler https://github.com/OvercastNetwork/Issues/issues/1763

**Comment by AnthonyTag** [comment]
Dupe
