### ISSUE TITLE
Map update - Arabian Nightmare 2.0

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2090]
apparently this map was loaded into the repo a year ago. we totally revamped the looks, made the main paths wider, and several other changes.

download:
https://www.dropbox.com/sh/efni56d29a9qra3/AADnlPXv6lmMhkuVsXro7uKZa?dl=0

**Comment by Qixit** [comment]
Whoops I did a typo, its updated now anyway. :smiley_cat:
