### ISSUE TITLE
Ranked servers still have the old server menu

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#2093]
![2015-08-22_13 07 05](https://cloud.githubusercontent.com/assets/8007420/9423679/0d279d02-48cf-11e5-8baf-5f0a4d87602c.png)

Unsure if the servers have to restart before the server signs are changed AND if they actually have/haven't restarted since the change, which could potentially make this issue invalid.

**Comment by Brottweiler** [comment]
I don't think the sign in your inventory on any server has the ranked servers.

**Comment by DoomRobotBoy** [comment]
@Brottweiler no, I meant that there is a new server menu showing all servers as signs instead of wools and the one ranked (as shown above) still has the old server menu.

**Comment by DoomRobotBoy** [comment]
It seems to be fixed now.
