### ISSUE TITLE
On  twitch.tv/ocnlive the ranks don't show all the perks

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2098]
Title. https://gyazo.com/96133f790696ff292afa4ebc18e5dbbc

**Comment by ghost** [comment]
Seems to be fixed now.

![](https://i.gyazo.com/b4d3fa2a0486d2ab96e6e504c613a904.png)

**Comment by Matic0B** [comment]
Just also going to put this here and also I'd like a responce from an admin:
Could you make the premium perks picture better? It looks very cluttered and also doesn't state the raindrop multiplier.

I know this isn't for suggestions but I'd just like a quick answer. @Brottweiler @itsmartin

**Comment by itsmartin** [comment]
@matic0basle: Forwarded that feedback to the creative team.
