### ISSUE TITLE
Add evidence feature to punishments

### ISSUE THREAD

**Issue by rmsy** [OvercastNetwork/Issues#210]
## The Issue

It would be useful to allow evidence to be attached to punishments (and visible on the punishment page). Users could also submit their own evidence (to prevent the creation of unnecessary reports just to submit evidence), which would need to be approved by a staff member before appearing with the punishment.

**Comment by Electroid** [comment]
It was decided a while ago at a meeting, that instead of an evidence field, staff would store it in a report.
