### ISSUE TITLE
Justice has two power bows missing in chests

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#2101]
One on the right purple tower and one on the center left thing.
![2015-08-24_16 35 47](https://cloud.githubusercontent.com/assets/7586568/9454348/888b5fb4-4a7e-11e5-801f-6d443181ce16.png)

![2015-08-24_16 35 24](https://cloud.githubusercontent.com/assets/7586568/9454339/6bc0f682-4a7e-11e5-8430-c745ff069070.png)

**Comment by Qixit** [comment]
Thanks for reporting the bug!
