### ISSUE TITLE
Can not loading servers

### ISSUE THREAD

**Issue by unixfox** [OvercastNetwork/Issues#2103]
Sometimes I can't load the servers with the sign. : https://www.youtube.com/watch?v=Hrnt512V0ms.

Time of the bug : 15H17 27 August 2015 (UTC+2)

Logs :

> [15:17:21] [Client thread/INFO]: [CHAT] The match has started!
> [15:17:38] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:17:39] [Client thread/INFO]: [CHAT] Loading servers...
> [15:17:40] [Client thread/INFO]: [CHAT] [Tip] Need to report someone? Alert the staff using /report
> [15:17:40] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:17:59] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:00] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:18:02] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:03] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:18:05] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:06] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:18:09] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:13] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:18:14] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:16] [Client thread/INFO]: [CHAT] Stopped loading servers
> [15:18:17] [Client thread/INFO]: [CHAT] Loading servers...
> [15:18:18] [Client thread/INFO]: [CHAT] Stopped loading servers

**Comment by tonybruess** [comment]
Database maintenance
