### ISSUE TITLE
Map Update - DK Crossovers v1.3.8

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#2108]
Last update had a huge error that I tried to fix here, with some additional edits. The center temporarily wall could be broken which of course wasn't meant to happen. I also removed water buckets from the spawn kit as that was laggy. I hope this fixed it.

Packaged World Download: https://www.dropbox.com/s/rqgf80lvog1uxlu/DK%20Crossovers%20DTE%20v1.3.8.zip?dl=0

Thanks a lot!

**Comment by Pugzy** [comment]
@DoomRobotBoy I'm having a few issues with the map, please drop me a message when available.

**Comment by DoomRobotBoy** [comment]
@iPGz Ye I'm available now
