### ISSUE TITLE
Map Update- Larnia v1.5.2(XML)

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2113]
XML: https://github.com/LArrowHead/Maps-XML/blob/master/Larnia

Changelog v1.5.2

> > Changed recover to 15s on flag
> > Changed slowness 3 to 2

**Comment by Pugzy** [comment]
@LArrowHead would this not make it easier for the attackers to win?

https://oc.tc/maps/larnia the balance currently still favors `Attackers`.

**Comment by LArrowHead** [comment]
I was complained to by strange and a few others in mumble that the slowness
3 was rather hard to get out(I don't completely think so). Also, I was
complained 10 seconds was too short at the beginning to retrieve the flag
back.

**Comment by LArrowHead** [comment]
However, I wouldn't mind if this update was put on hold so that I could see
how balanced it really is from the update.
