### ISSUE TITLE
Match won but counted as lost on the statistics page.

### ISSUE THREAD

**Issue by unixfox** [OvercastNetwork/Issues#2115]
[lechampionkev](https://oc.tc/lechampionkev) won a [match](https://oc.tc/matches/55e61ff4c8f2b9be0377429a) but the match was counted as lost on the statistics page.
## ![](http://i.unixfox.eu/2015-09-02_00-24-07.png)

![](http://i.unixfox.eu/2015-09-02_00-27-43.png)

**Comment by jedediah** [comment]
Should be fixed now, let us know if it happens again
