### ISSUE TITLE
GS:Twisted maps are showing Twisted CTW in matches page

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2116]
https://oc.tc/matches/5320d7dfc8f245ff861d0506
This is a pretty old match. The correct map is supposed to be GS: Twisted, not Twisted CTW. You can clearly see that the 2 teams in Twisted (CTW) is not Red vs Blue, it is Purple vs Cyan.

**Comment by mitchts** [comment]
Wasn't this the map the was renamed to `Tangled` because of this?

**Comment by jexeI** [comment]
The GS or ctw?

**Comment by mitchts** [comment]
The [Ghost Squadron map](https://oc.tc/maps/tangled).

**Comment by jexeI** [comment]
oh, never really noticed that. So maybe old maps need to be fixed?

**Comment by Strangeys** [comment]
Should no longer be an issue with the map being renamed.
