### ISSUE TITLE
Bug - The Last Sunset II

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2117]
Both north and south blue flag spawn on the same posts. 

https://maps.oc.tc/CTF/Standard/The%20Last%20Sunset%20II/map.xml

**Comment by Oo-TheFrog** [comment]
@iPGz  The fix got reverted in the last update.

**Comment by Pugzy** [comment]
@Oo-TheFrog @DoomRobotBoy this is what happens when you don't use the latest XML from maps.oc.tc!

Is this still an issue?

**Comment by DoomRobotBoy** [comment]
@Pugzy I copied the XML from maps.oc.tc since you had fixed some stuff for the previous update... so I don't really know where the issues are coming from ._.

**Comment by Oo-TheFrog** [comment]
@iPGz  Yes it is still an issue, you can see it at maps.oc.tc/standard/the_last_sunset_ii/xml
