### ISSUE TITLE
Alpha Conquer Blitz Ghost Squadron Ranked1 and Ranked2 EU always setnext the map that is playing.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2120]
As tittle says, You go to Mini01 EU and you can see that when the map Banana split ends, then it setnext Banana split again.

Screenshot --> http://i.imgur.com/ubWmQta.png

The same in Alpha EU ---> http://i.imgur.com/bC7NWu7.png

Ghost Squadron EU --> http://i.imgur.com/c0j3zdO.png

Conquer EU --> http://i.imgur.com/1Sabbuf.png

Blitz EU --> http://i.imgur.com/LARPfTF.png

Ranked1 EU --> http://i.imgur.com/KuKjtqk.png

Ranked2 EU --> http://i.imgur.com/kmO1fKy.png

**Comment by Brottweiler** [comment]
Fixed after server restart.
