### ISSUE TITLE
Old punishment can be shown.

### ISSUE THREAD

**Issue by ryush00** [OvercastNetwork/Issues#2123]
I heard that OCTC hide old punishments. But when I go to report page, I can see his whole punishments.

**In profile page**
![In profile page](https://i.imgur.com/VXvMtp1.png)

**In reports page**
![In reports page](https://i.imgur.com/GfDNZyZ.png)

Is it bug?

**Comment by Brottweiler** [comment]
It is a bug, but it has been reported on our internal tracker (https://github.com/OvercastNetwork/Internal/issues/206) already, so I will close this.
