### ISSUE TITLE
Map Update - Chocolate Diamonds CTF 2.0

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2125]
Kroest is letting me fix this broken map. Here is proof -  https://oc.tc/forums/topics/55e9936067d522fa5f0020c9

XML:  https://gist.github.com/Oo-TheFrog/111469739005d8ae6612

Map: https://www.dropbox.com/s/bqswd5y6d09yrqu/Diamonds%20CTF.zip?dl=0

Changes:

Lowered the player count to 14 max
Replaced the outer layer of bedrock with clay
Removed all chests
Added 2 almost brokenPunch1 bow to middle
Changed mineable regions around the flag post and beacon
Removed the golden apple from the spawn kit
Changed the spawn kit to only have 6 arrows instead of 64
Made the diamonds bigger and removed some
Added 2 new spawn diamonds per side
Added a diamond design to the flags
Added 2 enchantment tables to middle with xp and lapis
and other small changes

**Comment by Qixit** [comment]
XML is quite broken, and I'm pretty sure its going to take a while to fix. Expect a bit of a delay.

**Comment by Qixit** [comment]
I'm getting a ton of bugs with the XML, they are minor but they are going to take me a while to fix. Expect there to be a slight delay.

**Comment by Oo-TheFrog** [comment]
@Qixit Edit: idk when I will get time to fix it.

**Comment by Qixit** [comment]
It's okay @Oo-TheFrog I'll try getting it done sometime soon.

**Comment by Qixit** [comment]
Made a few changes to the XML, you're welcome to revert them (Extended flag nets, increased the height of spawn regions to prevent players getting stuck in blocks, added golden apples to spawn kit, edited contribution for your author position, fixed messages for editing spawns and flag nets and added carry messages to flags, something that most maps lack and need). There were also a few bugs that I fixed up. I'm not sure if maps.oc.tc is instanteous with updates to XML files or not so if you want to review them you may need to wait. Or if you would really like I'll make a github gist for you.

**Comment by Oo-TheFrog** [comment]
Thanks @Qixit

**Comment by Qixit** [comment]
Anytime mate.
