### ISSUE TITLE
Void enter on Woolrooms is not allowed (Placid Springs)

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2127]
Title says it all. I have made an earlier post about maps that do not allow void enter. If you do not know what it means, the video should help.
https://youtu.be/mQWHHdiIfDk
THIS VIDEO IS FOR DEMONSTRATION PURPOSES ONLY, AND WAS NOT MEANT TO GAIN IN-GAME ADVANTAGE.

**Comment by jexeI** [comment]
How to reproduce: Go to your own woolroom, jump into the void while "hugging" the woolroom protective border.

**Comment by Qixit** [comment]
As much as I don't see this being too much of an issue, it shouldn't take too long to fix.

**Comment by jexeI** [comment]
Yeah, not really. I did make a similar post with different maps couple of months ago. People can sorta avoid death by doing that.
