### ISSUE TITLE
Bug - NextGen

### ISSUE THREAD

**Issue by RickAstIey** [OvercastNetwork/Issues#2128]
Signs in the Red team's wool monument should be Lime and Orange but here we have Yellow and Purple which are blue team's wools.

Image: http://imgur.com/2IFDRNM

**Comment by ghost** [comment]
Related? https://github.com/OvercastNetwork/Issues/issues/2082

**Comment by Qixit** [comment]
This issue must also be apparent in the normal version of NextGen.

**Comment by Qixit** [comment]
Actually this wasn't fixed in #2082 , must have been in another version by mistake.

**Comment by RickAstIey** [comment]
Yes this bug is in the normal version of NextGen which is on Ranked rotations. I have not checked the tournament edition tho.

**Comment by Qixit** [comment]
Should be fixed now.
