### ISSUE TITLE
Team link on profiles messed up. (Placement wise)

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2132]
Not quite sure what's up. But for what ever reason the team link on my profile is in the wrong place. 
https://gyazo.com/2608725dc3fe0556444a77d5f8ed406b
There's nothing in the slot next on the left of the team link, and the team link should go there. Deleting the team and re-adding it does nothing.

**Comment by itsmartin** [comment]
This should no longer be happening since the bootstrap update.
