### ISSUE TITLE
/nick not displaying names properly in Lobby

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2137]
So, I saw this guy join the lobby, who had a steve skin and a WHITE nametag. I was not sure if this was an actual person with a messed up nametag, or a player in /nick. When the player left the lobby, his real name (which flashed on my screen for 0.05 seconds or something) was revealed. I do not know what the person's name was, but I did see the moderator's badge before his/her name.

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/1074

**Comment by jexeI** [comment]
Ok, Ill close then.
