### ISSUE TITLE
The navigation bar can get pushed to two lines when sale, streamer, and alert icon are active

### ISSUE THREAD

**Issue by JsKingBoo** [OvercastNetwork/Issues#2139]
http://i.imgur.com/KUoY9QT.png

It could be dependent on monitor size, but I'm not 100% sure on this. My screen resolution is 1280x1024, anyways

**Comment by Brottweiler** [comment]
You could just resize your window so it goes outside of the screen to see if it changes. This does not happen for me if I lower my window size. 

What browser, browser version and OS are you using?

**Comment by JsKingBoo** [comment]
Firefox 40.0.3

Windows 10

I actually haven't tried resizing my window, but unfortunately I can't test it right now because the streamer icon is not up

**Comment by Electroid** [comment]
Not anymore it is.
