### ISSUE TITLE
Map Update - Chocolate Diamonds CTF

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2145]
XML: https://gist.github.com/Oo-TheFrog/111469739005d8ae6612

Download: https://www.dropbox.com/s/j9espqcjsaah6w7/Chocolate%20Diamonds.zip?dl=0

Changes:

Removed enchanting tables
Added arrow spawner to middle
Fixed broken regions
Lowered the arrows in spawn kit to 6
New bigger middle islands
Faster axe and pickaxe 
Longer flag respawn timer
Renamed the map from Chocolate Diamonds CTF to Chocolate Diamonds

**Comment by Qixit** [comment]
Don't forget to indent your XML! :smile:  Other than that, this time around there weren't any errors.

**Comment by Oo-TheFrog** [comment]
@Qixit  Thanks for pushing the update! I'm not sure how to indent my xml with github.gist,  on a side note there is an area of the map protected from block breaking but I can't find the region where it is.

**Comment by Qixit** [comment]
I suggest you indent the XML on a separate file, and then copy it over to the github. Sublime Text is a good application for this.
