### ISSUE TITLE
You only get a golden apple killreward on Aleppo if you have none in your inventory.

### ISSUE THREAD

**Issue by RickAstIey** [OvercastNetwork/Issues#2146]
Well I'm not sure if this is supposed to be like this but if you play Aleppo you only get an golden apple killreward if you have none in your inventory.

Here you have a video: https://youtu.be/PiB5jYgvpVw

Thanks!

**Comment by samthecat** [comment]
I'm looking into this

**Comment by Pugzy** [comment]
@samtheman43 this is because you specify a slot for the 1 apple, so every time you get a kill it sets an apple in that slot. Removing the slot should fix it, I think.

`````` <killreward>
    <kit>
        <item amount="1" slot="2">golden apple</item>
        <potion amplifier="2" duration="5">speed</potion>
        <potion amplifier="1" duration="2">night vision</potion>
    </kit>
</killreward>```
``````

**Comment by Qixit** [comment]
By removing the slot attribute, the golden apple will stack with other golden apples or go into a free slot.
