### ISSUE TITLE
Wither clearly visible when boss bar is filled less than halfway

### ISSUE THREAD

**Issue by connorjayr** [OvercastNetwork/Issues#2150]
The title explains most of the problem.  
**Solution**: Change the wither's Invul data value to a number in the high 800s, specifically 880. I did a lot of experimenting and a contributor over at Cardinal helped to implement the boss bar, which has a much less noticeable wither.

**Comment by ghost** [comment]
Fixed in 1.9 due to new bukkit api
![2016-04-02_06 11 52](https://cloud.githubusercontent.com/assets/11008016/14225457/d783c07e-f899-11e5-840c-1e9e5f225b41.png)
