### ISSUE TITLE
Servers that exceed the line on oc.tc/play sometimes display the same person type that is on your friends list

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2151]
i don't really have a screenshot of it, however right now "ghost squadron(US)" exceeds to the second line and one of my friends is repeated twice.

(Text example)
     Ghost              (same Name)
Squadron(US)      (same Name)

**Comment by ghost** [comment]
http://prntscr.com/8wxv0w

**Comment by LArrowHead** [comment]
I guess this particular issue is fixed now, but sometimes staff members are
doubled
