### ISSUE TITLE
Can't select any package to buy

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2153]
<a href="https://gyazo.com/bccff218500d8afde3df3210a1e8ab5a"><img src="https://i.gyazo.com/bccff218500d8afde3df3210a1e8ab5a.png" /></a>

**Comment by samthecat** [comment]
you can't select any packages because you've purchased them all. It says it right on each one. If you're trying to buy a rank for someone else, you would need to change the username in the box at the top.

**Comment by Brottweiler** [comment]
![](https://i.imgur.com/Cn8dHOs.png)

He only has optio, and can't buy the higher ranks. That's the bug he's reporting.

Can be related to [this](https://oc.tc/forums/topics/5601712b67d5221c360003ee) though.

**Comment by ghost** [comment]
Actually i still waiting an answer

**Comment by ghost** [comment]
Fixed
