### ISSUE TITLE
Banned people can`t enter the store

### ISSUE THREAD

**Issue by Prodigy4532** [OvercastNetwork/Issues#2156]
Can`t

**Comment by Brottweiler** [comment]
They're banned and don't need to go there.

**Comment by Prodigy4532** [comment]
and if I want to buy something for someone ?

**Comment by tonybruess** [comment]
We don't want banned users purchasing anything. This is very intentional.

**Comment by Prodigy4532** [comment]
oo :/, ok

**Comment by Prodigy4532** [comment]
as I can buy a rank to a friend ?

**Comment by Brottweiler** [comment]
You cannot.

**Comment by Prodigy4532** [comment]
ok.
