### ISSUE TITLE
Small Map Update (bug fix) - Pixelmissing

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#2159]
You could still place lava which wasn't supposed to happen, sorry! (missed a little apply closing tag :()

Update: https://www.dropbox.com/s/hli12reluh62i1d/map.xml?dl=0

Thanks for quick fix!

**Comment by AnthonyTag** [comment]
couldn't you just get rid of the bucket? Is there a point to it if you can't place lava?

**Comment by DoomRobotBoy** [comment]
Well the water is actually a nice part of how the map plays, but I guess it can be removed for the halloween update!

**Comment by AnthonyTag** [comment]
Is there any water in the halloween version? If I remember correctly, you spawn with an empty bucket. So if there isn't any water on the map, or it isn't game breaking leaving it out, it would be much easier to just get rid of the bucket in the spawn kit.

**Comment by DoomRobotBoy** [comment]
There is actually @AnthonyTag, in the halloween version each player spawns with a water bucket instead of an empty bucket. Removing it also seems like a good idea tho!

**Comment by AnthonyTag** [comment]
Sorry I'm stupid, your xml works fine...I'll push the update now!
