### ISSUE TITLE
Add Backspook - Outback Halloween Edit

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#2164]
![](http://i.imgur.com/OtvgY79.png)

Get backspooked!

**Changelog**
- Halloween theme
- Night
- Spookers vs. Lollipops

**Download**

http://www.mediafire.com/download/9f2kq5t99ap90fh/Backspook.zip

_rockymine_

**Comment by Strangeys** [comment]
Is it possible that you could add more lighting to the map? It looks way too dark for players to have to play through.

**Comment by rockymine** [comment]
@thestrangeboy1 Sure! 

http://www.mediafire.com/download/eyl7s5pb372xowd/Backspook1.0.1.zip

**Comment by Pugzy** [comment]
@rockymine why BackSpook and not SpookyBack?

**Comment by rockymine** [comment]
@iPGz Because I like to get "backspooked". If you dislike the name then that's your problem, but seeing that you're the one in charge makes me worried. You could just change it.

**Comment by samtheman43** [comment]
wtf

**Comment by Brottweiler** [comment]
@samtheman43 Please don't comment if you don't have anything to contribute. I removed your spam comment.

**Comment by ElliottWhyman** [comment]
@rockymine No need to get all defensive, Pugzy asked a simple question as he was curious, there is no need to reply like that. Map Devs are here for you, we are not the 'ones in charge' we simply oversee what you want. Keep that in mind :)
