### ISSUE TITLE
clicking on a player's name to teleport on Ranked dosen't seem to work

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#2168]
![2015-10-05_17 46 10](https://cloud.githubusercontent.com/assets/10585916/10294656/b035f23c-6b89-11e5-9c15-c5c44d55a971.png)
![2015-10-05_17 50 38](https://cloud.githubusercontent.com/assets/10585916/10294657/b1b394d4-6b89-11e5-87ac-7ce5b9403282.png)

**Comment by jedediah** [comment]
Teleporting is disabled for an hour or two while a bug fix is being deployed.

**Comment by samthecat** [comment]
dosent seem to be working now either @jedediah
