### ISSUE TITLE
Small  Map Tweak - Aleppo/AlepBOO!

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#2172]
respawn timer is now 4 seconds.
enemy name tags are now invisible.
Aleppo updated XML
https://gist.github.com/samtheman43/19cbb484a34f2470400e

AlepBOO! updated XML
https://gist.github.com/samtheman43/1d3cc82ccf3c852328b5

**Comment by samthecat** [comment]
@Qixit for some reason, the flag pickup messages on AlepBOO! show cyan beacon instead of "gray beacon" and yellow beacon instead of "orange beacon" 

And the flags are the right colors, but they should be called "Pumpkins Flag" and "Spooks Flag"

**Comment by Pugzy** [comment]
@samtheman43 I changed the flag names to match the flag colours, I will updated these and then push.

And the reason it says the messages it does it because that's what you have in your XML...

`carry-message="`bBring `aflag`bto `3cyan beacon`

**Comment by samthecat** [comment]
and the pickup messages too? @iPGz

**Comment by Pugzy** [comment]
@samtheman43 I'm not sure what you mean, you can use maps.oc.tc to see the latest version.

**Comment by samthecat** [comment]
@Pugzy everything looks good, thanks.
