### ISSUE TITLE
Grammatical error with /friends command

### ISSUE THREAD

**Issue by applenick** [OvercastNetwork/Issues#2174]
I could not find any submitted issues about this, but when performing /friends the word 'ago' appears twice. I personally believe the gray 'ago' should be removed. Just my opinion :smile: 

To reproduce: /friends
![screen shot 2015-10-08 at 3 46 50 pm](https://cloud.githubusercontent.com/assets/3377659/10382019/89e07c9a-6dd4-11e5-995b-e84b0ea19688.png)

**Comment by ghost** [comment]
Fixed http://prntscr.com/8w1tu4
