### ISSUE TITLE
@<username> <message> overrides /toggle msg

### ISSUE THREAD

**Issue by PoseidonsM** [OvercastNetwork/Issues#2180]
If somebody has " /toggle msg" set to nobody you can still message them by doing @ as long as you are on the same server as them. If a friend is on the same server (Ranked1/Capture1/etc) as me and I want to /msg them but they have messages toggled off I can override the toggles and message them by using @ . Also, /r only replies to /msg aliases and not an @ message.

**Comment by Pablete1234** [comment]
This should be closed, it's fixed
