### ISSUE TITLE
/seen <name> reveals nick'ed players

### ISSUE THREAD

**Issue by PoseidonsM** [OvercastNetwork/Issues#2181]
For instance, if a nick'ed mod is in game, and I'm semi-suspiscious and I know what mod they are, I can use /seen to see if they are online. Or, I can look at the forums and see what mods are online there, to do /seen to find if any of them are online. If a mod/nicked player logs out with their name, /seen reveals their nicked name.

**Comment by kashike** [comment]
I reported this to Qixit via PM a few days ago as well.

**Comment by ghost** [comment]
Seems to be fixed http://i.imgur.com/vaX6ikg.png and http://i.imgur.com/XVe9EVp.png

**Comment by PoseidonsM** [comment]
TiTo-418, if you read the issue it says that using "/seen <modusername>" reveals their nicked name, not /msg. For instance, if turtle had that nick, and I did "/seen MySquishyTurtle" it would say, "MonsterJerky is online." Thus revealing the nicked player.
Could this be reopened please.

**Comment by mitchts** [comment]
Tested this earlier - it's fixed
