### ISSUE TITLE
Forum avatar white-face bug

### ISSUE THREAD

**Issue by NanuCNS** [OvercastNetwork/Issues#2190]
We doesn't have mush information about this bug. Is happen <b>randomly<b> and look like some layer of the avatar turning in transparent without any change by skin owners.
![desktop 19-10-2558 19-20-34-59](https://cloud.githubusercontent.com/assets/8971312/10579201/04b5453e-76a1-11e5-9c47-90e0ca031318.png)

Thread : https://oc.tc/forums/topics/5624c2115f35b96270001202

**Comment by Brottweiler** [comment]
Seems like black pixels sometimes becomes transparent.

For example, the threads looks like this for me atm: ![](https://i.imgur.com/gZxEcla.png)

**Comment by Brottweiler** [comment]
Let's close this in favor of https://github.com/OvercastNetwork/Issues/issues/1544
