### ISSUE TITLE
Minor XML Update - SpOOky Diamonds

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Issues#2191]
Added arrows to item remove
Removed the oak log k/r
Added a gapple k/r
Changed the stained clay color

XML: https://gist.github.com/Oo-TheFrog/12a7249369e1889f39fa

**Comment by Pugzy** [comment]
Would this apply to both Spooky and Regular?

**Comment by Oo-TheFrog** [comment]
Just spooky for now

**Comment by Pugzy** [comment]
Make sure you update the version number for every update.

Also you would need to change the damage value of the clay and not the item name.

![](http://i.imgur.com/zOvJr0r.png)
