### ISSUE TITLE
Observers can break fire in Ranked NextGen.

### ISSUE THREAD

**Issue by RickAstIey** [OvercastNetwork/Issues#2192]
I don't know if this happens only in Ranked NextGen. Also I couldn't find another issue like this one sorry if there is one already.

Video: https://youtu.be/f6vY78X_574

**Comment by Pugzy** [comment]
This has been reported and closed several times, #2064

From Apple, "To clarify, fires extinguished in observer mode do not regenerate but the issue is client side."
