### ISSUE TITLE
oc.tc/play matches are completely frozen

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2202]
These matches https://gyazo.com/63a8072b6c2de1a71f76449c50013f66 are there since like 2 or 3 hours ago and they never cycle. Also, the next map isn't been shown.

**Comment by ghost** [comment]
This is most likely also linked to the fact the server signs are not working ingame.

**Comment by 2000thehecf1** [comment]
Closing this since it seems to be already fixed.

**Comment by 2000thehecf1** [comment]
nvm it's wrong again, sorry.

**Comment by ghost** [comment]
Fixed http://prntscr.com/8vw11j
