### ISSUE TITLE
Some bug with the TNT.

### ISSUE THREAD

**Issue by Matilaina** [OvercastNetwork/Issues#2205]
I found one bug with the tnt on ssb Halloween, I think the problem is only on this one map but im not sure. so I made one Spread cannon and didn't work, like the tnt just flew 5 or 6 blocks and fall, I saw others cannons from them team and it did not work too. Did I cant record because the map just end and cycle one next

**Comment by mitchts** [comment]
I can't seem to reproduce this at all. If this becomes an issue again, please record it.
