### ISSUE TITLE
I can view nicked staff members via /staff Bug

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2209]
Well I just check if any mods were on and what the heck I viewed staff members that were nicked :o! I know we can view nicked friends. But these mods are not on my friend list. So why can i still view nicked mods? Is that a bug or a new feature? Please Respond fast as you can! 

Video Evidence: https://youtu.be/6gB1stSJ7HM

**Comment by johannestheigen** [comment]
Thanks pugzy!

**Comment by jedediah** [comment]
fixed

**Comment by johannestheigen** [comment]
OMG Thanks!!!
