### ISSUE TITLE
Profile Bug 

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2214]
Well i was just trying to join /server pugzy and normally it says you are not whitelisted but that's not the problem. When i was on destroy and i checked my profile it said i was on server pugzy one min ago? What the heck i was on destroy and my profile said i was on pugzy less than a min ago!!! Please fix this!!!

Video Evidence: https://youtu.be/ucqTYrU2U8c

**Comment by Brottweiler** [comment]
dulicate
