### ISSUE TITLE
Dopamine has two practice servers

### ISSUE THREAD

**Issue by RickAstIey** [OvercastNetwork/Issues#2224]
Well there are two Dopamine signs in the TM lobby.

https://gyazo.com/b24c26d8ddec0436388609a41d5e699b

**Comment by ghost** [comment]
You should change the title to "Dopamine has two practice servers."
http://prntscr.com/905zy4 | https://oc.tc/forums/posts/563d9a175f35b938570002de

**Comment by RickAstIey** [comment]
Zenith has two servers as well.

https://gyazo.com/209c48871d627d144991e18007f01583

**Comment by RickAstIey** [comment]
It's fixed now!
