### ISSUE TITLE
Players can be teleported outside of the world

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2228]
Right now on TM servers you can :
/tp someone 99999999 0 0 and crash their client / ilegal position error, if you try:
/minecraft:tp someone 99999999 0 0 it says the number is too big, max is 30000000.

**Comment by tonybruess** [comment]
We're not going to fix this

**Comment by TiTo-418** [comment]
Then can we report the people who do this?

**Comment by tonybruess** [comment]
If someone is doing this don't play on their server
