### ISSUE TITLE
Map update - The grand dueling tournament Version 0.2

### ISSUE THREAD

**Issue by mattarnold98** [OvercastNetwork/Issues#2230]
https://github.com/yoyopower/YoyoMaps/blob/master/theGrandTournament.xml

Changelog:
- Remove any chance of a mutation.
- Hopefully refix a bug that was causing some arenas not to drop.
- Add more broadcasts.
- Shorten capture times on a few hills.

**Comment by Pugzy** [comment]
One little error with the new alerts you added;

`every="1s" after="5s">`4--> Round 1 is starting <--</alert>`

You can't use `>` and `<` as these are used to close elements instead you need to use `&lt;` for `<`, and `&gt;` for `>` (I had made this change already just an fyi).

**Comment by AnthonyTag** [comment]
Was this pushed?

**Comment by Pugzy** [comment]
@AnthonyTag nope, Yoyo wanted to make a few changes, he sent me the updated version last night.

**Comment by AnthonyTag** [comment]
@iPGz Aight just wanted to make sure this wasn't forgotten about :stuck_out_tongue_winking_eye:
