### ISSUE TITLE
Raindrops are recived for destroying own teams wool

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2232]
As in, a wool your team has to defend. I assume this is not intended behaviour, however I may be wrong
![An image to illustrate this bug](http://i.imgur.com/Qlo4cKX.png)

**Comment by mattarnold98** [comment]
I always presumed that this was intended (although I may be wrong).

It's a very small reward for defensive kills and it also helps teach new players how to play the game, by providing them with a small reward when they do something good. For example, If you kill an enemy who has your wool you don't want to just leave it there for them to take. You want to destroy it.

**Comment by Pugzy** [comment]
@yoyopower I believe the bug is that you get points for destroying wool your team must cap not vice versa.

**Comment by ghost** [comment]
That's the opposite of what I'm reporting. I'm confused, but if there is a bug here, then I'll leave this open. Confirmation from developer?

I was saying that destroying a wool your team must defend shouldn't give you raindrops, but thinking about it it does seem like the expected behaviour, as why would you destroy a wool you have to capture.

**Comment by ghost** [comment]
You don't receive raindrops for destroying your own wool, you receive raindrops for destroying the other team's wool. You can see in the scoreboard how the `Blue team` has to cap the `Orange wool`

**Comment by Brottweiler** [comment]
@TiTo-418 Red has to defend orange though, and OP is red, and he broke the orange wool?

Edit: Lol this is confusing. So, as I wrote above, Red defends orange. If blue places safeties of said wool, Red gets raindrops from breaking the wool. This is intended.

> As in, a wool your team has to defend.

Breaking the wool your team has to defend is defence, and earns you raindrops.

**Comment by ghost** [comment]
Yes, that's the expected behaviour

**Comment by ghost** [comment]
To clarify then, as I'm pretty sure everyone is incredibly confused, wool destruction raindrops should  give for both destroying wool you are defending and wool you are capturing?

**Comment by Brottweiler** [comment]
@elephantLocator No. The raindrops you get from destroying wool you defend is because you are doing your team a favor. Destroying this wool prevents the enemy from getting it easier.

When you destroy the wool your team is capturing, you are collecting it yourself (which gives you raindrops for offence) and you are making your teammates not able to get the wool you just took.

The raindrops you get from destroying wool you have to defend is for defence. If you get raindrops, there's a reason to destroy them other than helping your team. It's encouraging players into breaking them.

**Comment by ghost** [comment]
@Brottweiler Okay, makes sense. Giving raindrops when attacking seems to be the bug here then? In other words, the opposite of what I just reported as destroying wool you are meant to be capturing seems like teamgriefing.

**Comment by Brottweiler** [comment]
@elephantLocator Are you saying that if you break the wool your team is supposed to cap, you get raindrops? Are you sure that you are getting raindrops from **breaking**, and not **collecting** the wool?

**Comment by ghost** [comment]
@Brottweiler Could be what I'm thinking of. I'm terrible at attacking, so we'll have to wait and see if anyone can confirm this, but I seem to recall it giving you raindrops. Don't quote me on that though.

**Comment by Brottweiler** [comment]
@elephantLocator You get raindrops when you collect the enemy wool (when the wool you need to cap comes into your inventory). It does not make sense to me that you should get raindrops when breaking this wool, but if you are, then I can't say if it's a bug or feature, but @OvercastNetwork/devs can probably.
