### ISSUE TITLE
Outdated Footer and Missing Header on page 500

### ISSUE THREAD

**Issue by odsseus** [OvercastNetwork/Issues#2233]
![2015-11-12 21 57 55](https://cloud.githubusercontent.com/assets/7188301/11130985/794e24d4-8988-11e5-9a02-3e5cc116532e.png)

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/1589

**Comment by odsseus** [comment]
Oops my bad, closing this.
