### ISSUE TITLE
When an invisibility mutation occours name tags are still visible.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2234]
And armour you spawn with, but I don't see a way of fixing that one.

**Comment by Brottweiler** [comment]
Invisibility is broken in 1.8.

The armor is vanilla feature.

**Comment by ghost** [comment]
Couldn't name tags be disabled like they are in Badlands CTF?

**Comment by Brottweiler** [comment]
Not sure if you can disable nametags only because of a mutation. @OvercastNetwork/devs ?

**Comment by Electroid** [comment]
It's will be fixed in the next version.

**Comment by ghost** [comment]
Can you reopen this please and close it when it is fixed? This is the most annoying bug ever

**Comment by ghost** [comment]
Fixed in 1.9
