### ISSUE TITLE
Forum bug, posts not showing

### ISSUE THREAD

**Issue by andreskv** [OvercastNetwork/Issues#2235]
Threads that were recently created have no content, they show 0 posts. http://imgur.com/cSRsobL,xJkLVhZ

**Comment by JanPaulMosterdijk** [comment]
urgent! new topics cant be made!

http://i.imgur.com/UzOUtP2.png

it would also be great if we could get notified when the issue is solved.

**Comment by ghost** [comment]
Seems to be fixed
