### ISSUE TITLE
Staled punishments viewable when reporting

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2239]
Punishments that have staled - i.e. gone from public view are visible in reports to non staff.

[An example](https://oc.tc/reports/564facc8c296356d79001082) where the punishment for iron hoarding is not visible on profile but is on the report.

I guess this could be a feature, but it seems weird to show it to players.

**Comment by Electroid** [comment]
@elephantLocator Can you provide a screenshot for reference please?

**Comment by ghost** [comment]
![](http://i.imgur.com/4AQgLuw.png)
On the reports page
![](http://i.imgur.com/jaE5py4.png)
On profile

**Comment by Brottweiler** [comment]
https://github.com/OvercastNetwork/Internal/issues/206
