### ISSUE TITLE
Christmas map - Connected 

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2244]
i only have seen it played 2 times, ill wait for the original map to be updated as well so i can ask for some more setnexts, but i am quite convinced it will play pretty good based on the last 2 tests.

download: 

https://www.dropbox.com/sh/lt3w3hvshlt9ltz/AAAEasYfuHhL_ZAmOoH6Y_pYa?dl=0

**Comment by ghost** [comment]
You should upload the map in this section of the forum https://oc.tc/forums/53f7a8d1d7c83698b7b67499

**Comment by JanPaulMosterdijk** [comment]
oh fuck ur right

**Comment by JanPaulMosterdijk** [comment]
looks like we are actually supposed to make an issue about it
