### ISSUE TITLE
I can view nicked staff members that has denied my friend request!

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2246]
So Qixit is not on my friend list but I can view his nickname while he is nicked online! Please fix this!

Video Evidence: https://youtu.be/eUw4t10cNdk

**Comment by ghost** [comment]
I think this is more a website bug than a plugin bug

**Comment by johannestheigen** [comment]
Yup!

**Comment by johannestheigen** [comment]
Hopefully Cubist aka Last_username will take a look at this.....

**Comment by Superjd10** [comment]
@McFanta Be patient. All the issues are known and are most likely being worked in a solution, but those fixes are not "instant" and are not rushed.

**Comment by MySquishyTurtle** [comment]
I just tested this with my friend LimeSauce after it was brought up to me by Raandom. Raandom can see my friend requests even though I am not his friend, but he has sent me a friend request on the forums. I tested it just now with my friend LimeSauce. I removed him as a friend and he could not see my nickname, then he sent me a request and could see my nickname.

Screenshot of LimeSauce's view: http://i.imgur.com/LsPMX07.png

I then denied LimeSauce's friend request and he could still see my nickname.

Screenshot of LimeSauce's view: http://i.imgur.com/X6LzkKr.png

I'd already denied Raandom's friend request and here's a screenshot of what he sees:

Screenshot of Raandom's view: http://i.imgur.com/jUlttvv.png

**Comment by johannestheigen** [comment]
@MySquishyTurtle I can still see most nicked staff that are not in my friendlist. So I think it's a wierd bug with the website.

**Comment by ghost** [comment]
@McFanta Are those just staff members who you've added and been denied by for friendships? I think thats what @MySquishyTurtle was saying

**Comment by johannestheigen** [comment]
@elephantLocator But still how can I view them? What If a friend of a hacker who is a community member of ocn reveals a nicked staff who has denied his friend request? I am not saying that will happen.

**Comment by ghost** [comment]
@McFanta Yea, it's a bug and needs to be fixed. Just clarifying where the bug is, as I haven't been able to replicate it.

Okay, replicated. If a friend request is pending you can see the nickname. I understand now.

**Comment by johannestheigen** [comment]
@elephantLocator I think we are done with this discussion. For now let's just wait until @jedediah  (Cubist) will take a look at this.

**Comment by mitchts** [comment]
Fixed.
