### ISSUE TITLE
EU Lobby signs missing alpha and RAGE

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2249]
The sign is missing in the EU lobby since the update.
![2015-11-30_17 55 40](https://cloud.githubusercontent.com/assets/12920658/11479792/b00eb504-978b-11e5-9e7d-aab375e1bb78.png)

**Comment by Qixit** [comment]
I see quite a lot of signs in the EU lobby, are there any specific signs missing? A lot of issues regarding Lobby sign bugs were fixed yesterday so it's likely this issue has already been resolved.

**Comment by ghost** [comment]
The two specific signs missing are Alpha and RAGE, and they seem to have not been fixed assuming the new lobby has been pushed to the server, as none of the three lobbies have them.

**Comment by ghost** [comment]
Now occours again
