### ISSUE TITLE
The Grand Dueling Tournament have a massive spam

### ISSUE THREAD

**Issue by Brokennz** [OvercastNetwork/Issues#2251]
After you finish a round, it will tell you all the time: --> ROUND 2 IS STARTING <--.
![2015-11-30_20 30 50](https://cloud.githubusercontent.com/assets/11890645/11490877/76c2ca6c-97a2-11e5-8967-9f14fd12bfb8.png)
![2015-11-30_20 33 55](https://cloud.githubusercontent.com/assets/11890645/11490881/7ae80dd2-97a2-11e5-898e-fb5c68be7655.png)

**Comment by mattarnold98** [comment]
This should fix it: https://gist.github.com/yoyopower/8b93adf0c243de882485
