### ISSUE TITLE
Christmas map - Frosty Stadium

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2253]
map by creephunter, his edit looks pretty great tbh.

not my map but he asked me to package and post it since he doesn't have a github account.

download:

https://www.dropbox.com/sh/za5yui6kgxjhmkt/AAA6bgNYZXxi05cgnh31oBWoa?dl=0

**Comment by Brottweiler** [comment]
New maps are posted to the [Submissions](https://oc.tc/forums/53f7a8d1d7c83698b7b67499) forum though?

**Comment by JanPaulMosterdijk** [comment]
@Brottweiler  'If you have a map loaded in the repository and create a Christmas/winter themed version of it, make an issue on our issue tracker! '
from this topic:
https://oc.tc/forums/topics/564b9081c296357afd00125e

it may not be clear enough that this is just a christmas version of a map already being in the repo (bouncy stadium).

**Comment by Qixit** [comment]
Added.
