### ISSUE TITLE
Ranked matches not showing properly

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2255]
On the top right in the well it says 0 matches, 0 wins, 0 losses and 0 forfeits but I've lost 2 matches.

![](https://i.gyazo.com/1c295ff25141cd4ef6a3b6d7a93f678b.png)

**Comment by Brottweiler** [comment]
Same for mine which are 3 months old, but if you look at [someone with recent ranked matches](https://oc.tc/Matilaina) it shows. So, maybe our matches are old so they don't count anymore? Not sure if such a feature exists, though.

**Comment by Brottweiler** [comment]
The stats dissapear for games older than 90 days.
