### ISSUE TITLE
No arrow kill reward on bow shots - Christmas Eve : Rage

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2256]
On the map Christmas Eve : Rage you receive an arrow kill reward for melee, but not for bow shots

**Comment by Pugzy** [comment]
@CrazyCreeper521 are you sure this is the case, XML says arrow for `killreward`, these can't be specified for what type of kill though.

**Comment by eudaldca** [comment]
I guess that it's due to #2260.

**Comment by mitchts** [comment]
Same issue as what @Eudaldca referenced
