### ISSUE TITLE
Map update - Connected + Connected Christmas 1.0.2

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2257]
- lowered buildlimit so people cant jump in the woolroom
- moved the spawners 1 block further from the barrier because wools glitches through the barrier to the other side of the woolroom
- replaced some of the dirt on Connected Christmas by snow

the xml's are identical except the name.

download Connected: https://www.dropbox.com/sh/2415nq97vr9l8sp/AADeSI4KpZNhJmRnyLNkAjNxa?dl=0
download Connected Christmas: https://www.dropbox.com/sh/lt3w3hvshlt9ltz/AAAEasYfuHhL_ZAmOoH6Y_pYa?dl=0

**Comment by Pugzy** [comment]
The regular `Connected` seems to have rain when loaded however quickly stops, not sure what is causing this but I've edited the level.dat to set `raining: 0`.
