### ISSUE TITLE
Map update - Connected + Connected Christmas 

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2259]
sorry for the update rain, but i feel responsible for the map since its in the rot.  people could still jump in the woolroom (well, blockglitching, but still), so i added some barriers so they can't jump on the staircase sticking out of the lane.  

no xml update, i only changed the world, so as fas as i know i dont need to bump the version number.

connected: https://www.dropbox.com/sh/2415nq97vr9l8sp/AADeSI4KpZNhJmRnyLNkAjNxa?dl=0

connected christmas: https://www.dropbox.com/sh/lt3w3hvshlt9ltz/AAAEasYfuHhL_ZAmOoH6Y_pYa?dl=0

**Comment by chleongithub** [comment]
Did you change the victory monuments?
