### ISSUE TITLE
Merry Drought on capture rotations

### ISSUE THREAD

**Issue by chleongithub** [OvercastNetwork/Issues#2261]
From i know of Merry Drought isn't a capture map. It should be on destroy
EDIT: This only shows on the website for a reason http://i.imgur.com/RKigUl7.jpg

**Comment by Pugzy** [comment]
Yeah it is a DTM, I'll see what I can do.

**Comment by Pugzy** [comment]
This map was set-next by a moderator and is not in rotation.
