### ISSUE TITLE
Enthral version 1.1.0

### ISSUE THREAD

**Issue by mattarnold98** [OvercastNetwork/Issues#2263]
Link: https://gist.github.com/yoyopower/4c87cf2d45012c915fbb

Changelog:
- Matches are now a lot more fast paced.

**Comment by rockymine** [comment]
Link: http://www.mediafire.com/download/dj3mbc938dv4d94/Enthral%282%29.zip

Changelog:
- Fixed some trees
- Filled empty chests
- Added more chests

_The Download only includes: region and level.dat_

**Comment by rockymine** [comment]
Link: http://www.mediafire.com/download/9l5qhs6ypc74ecc/Enthral+Update.zip

Changelog:
- Fixed two Map Errors
- Added Ladders to Boats
- Campfires!

_The Download only included: region and level.dat_

**Comment by Strangeys** [comment]
Done
