### ISSUE TITLE
Remove TnT Mutations!

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2264]
What is even the point by having tnt mutations? I can tell you the issues. I know tnt mutations can be useful for defending! But it has some issues especially on small maps or ctw maps! It makes more people to grief even players that were trying to defend can be kicked because mods believe they are griefing. I've talked to a bunch of players about this and it seems not everyone enjoys tnt mutations. The flint and steal on tnt mutations is also a good point for griefing. For example you can grief your team and burn down the bridge. Example two, you can burn players which is also griefing. Example 3, small maps like dynamo can be defended good with tnt, but is not actually a good idea because it's the dream to griefers to blow up a map. As I said mods may kick players that might tried to defend with tnt through a tnt mutation. I'm not saying mods are not doing their usual job. The thing I say is, tnt mutations is a bad idea. That's my opinions. We can add more tnt maps to rots instead of using the worst mutation ever called tnt mutations! 

Thanks For Reading!!

Regards McFanta_

**Comment by ghost** [comment]
Read the [CONTRIBUTING.md](https://github.com/OvercastNetwork/Issues/blob/master/CONTRIBUTING.md). 

"[Do Not] Submit issues that are general suggestions, as opposed to specific, technical bugs or confirmed features"
This would probably be more suited to a post [here](https://oc.tc/forums/4fc17142c46375149200001c) on the website where it possible to gauge community opinion. 

Anyway, I think TNT mutations are one of the best ones there are, and they actually work fairly well. You can't use greifing as an argument against really - should we also remove all maps with TNT?

**Comment by chleongithub** [comment]
I think tnt mutations are very fun. It happens very unexpected and causes new gameplay.

**Comment by itsmartin** [comment]
This issue tracker is for bugs, not suggestions.
