### ISSUE TITLE
Add Snow Wall (Christmas version of Sand Wall)

### ISSUE THREAD

**Issue by chleongithub** [OvercastNetwork/Issues#2265]
Sand Wall: https://oc.tc/maps/sand_wall
Snow Wall thread: https://oc.tc/forums/topics/5664cf95c29635778d00ab58
Packaged Snow Wall DL: https://www.dropbox.com/s/x7cwwsw5gpjy4u3/Snow%20Wall.zip
XML: https://gist.github.com/chlegists/79d2de07458369aa6b10

**Comment by Pugzy** [comment]
@chlegists Are you the author of this map?

The map isn't within the world file and the XML says `Sand Wall`.

**Comment by chleongithub** [comment]
@iPGz No, _3Each is. But i'm the one who takes care about updating and stuff.
Sorry, my bad. New DL: https://www.dropbox.com/s/x7cwwsw5gpjy4u3/Snow%20Wall.zip
I have updated the XML file too.

**Comment by Qixit** [comment]
@chlegists There still isn't any map within the world file. I spawn in the void.

**Comment by Qixit** [comment]
It looks like the only things that have actually been changed are the map and the XML map name. You need to actually update the spawn coordinates, team names and kit names most likely, and other various things. I'll update it this time, but next time you'll need to it yourself.
