### ISSUE TITLE
oc.tc/maps doesn't sort map ratings corectly

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2266]
my map just hit the 300 ratings, and its average is 3.79. It should be on the first map page https://oc.tc/maps/gamemode/ctw ,but it is actually still sitting on the last page, https://oc.tc/maps/gamemode/ctw?page=5

**Comment by Strangeys** [comment]
Are you talking about Connected Christmas? It has 3.79 and is on the first page. It must have taken a bit of time.

**Comment by JanPaulMosterdijk** [comment]
@thestrangeboy1  it shows differently for me, even when im logged out:

http://m.imgur.com/PWV4wry,sfveiIA

**Comment by JanPaulMosterdijk** [comment]
interesting, it dropped down to 1.78 a few hours ago, 2 mins ago a game ended that bumped it back to 1.78, and that caused it to update for me as well.
