### ISSUE TITLE
Multiple Server connections with Lobby Sign

### ISSUE THREAD

**Issue by applenick** [OvercastNetwork/Issues#2267]
When a server sign is right clicked on, It sends 2 joining messages then an "Already Connected" message.

![screen shot 2015-12-07 at 6 36 38 pm](https://cloud.githubusercontent.com/assets/3377659/11646367/389854d0-9d12-11e5-8a80-939f8e50e499.png)

![screen recording 2015-12-07 at 06 39 pm](https://cloud.githubusercontent.com/assets/3377659/11646360/236c66dc-9d12-11e5-9f99-d99873f96fc5.gif)

**Comment by Brokennz** [comment]
Dupe #2197
