### ISSUE TITLE
Is unable to see the stats of a team page

### ISSUE THREAD

**Issue by Brokennz** [OvercastNetwork/Issues#2268]
Don't know if this a bug from my Chrome version. If this is not an issue just close it.
![bug](https://cloud.githubusercontent.com/assets/11890645/11658785/3795b56e-9d8a-11e5-8d29-29a0ed758073.png)

**Comment by Pugzy** [comment]
Seems to be working fine for me, what version of Chrome are you running and have you tried reloading the page with `Shift + F5`?.

**Comment by Brokennz** [comment]
@iPGz it's now fine.
