### ISSUE TITLE
Cannot connect to oc.tc servers, urgent

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2271]
tm.oc.tc had this issue before, http://imgur.com/a/mNlrT, it has 'just another Bungeecord - forced host' as server modt. after some refreshing i am sometimes able to connect, when the modt is fixed.

**Comment by ghost** [comment]
Seems to be working for me?

**Comment by Brottweiler** [comment]
fixed

**Comment by ghost** [comment]
<img src="http://prntscr.com/9ts80t/direct">

<img src="http://prntscr.com/9ts92g/direct">

When I try to join us.oc.tc

<img src="http://prntscr.com/9tsame/direct">

**Comment by AnthonyTag** [comment]
@TiTo-418 fixed
