### ISSUE TITLE
Creating a new post, then opening a new page sends the notification to that page.

### ISSUE THREAD

**Issue by 96alexmr** [OvercastNetwork/Issues#2273]
If you create a post and before it finishes loading and you open another web page on ocn, the notification for the post being successfully created gets sent to the new page and not the thread.

Post created: https://oc.tc/forums/topics/50494e68b944ec59bc00596c?page=134#5668db2467d52266fe001601

Page loaded: http://i.imgur.com/DJEINwI.png

**Comment by Brottweiler** [comment]
Happens for anything. If I hide a post, and before it loads go to a new page it sends the notification there. Happens with web reports etc too.

**Comment by itsmartin** [comment]
This is a rails limitation. I don't think it would be worth fixing.
