### ISSUE TITLE
When jr.mods join full teams, they kick out a player on one of the teams to free up space for a "premium player"

### ISSUE THREAD

**Issue by ch4teau** [OvercastNetwork/Issues#2280]
I tried to join a match on one of the arcade servers, when I did I kicked out a player. They said that they were shown "You were kicked out to make space for a premium player." (or something similar, not sure what it exactly said). Seems like this doesn't happen to regular moderators.

**Comment by Pugzy** [comment]
Moderators are given permissions equivalent to `Dux` thus they are a `premium player`.

**Comment by ch4teau** [comment]
but when other mods tried apo

**Comment by ch4teau** [comment]
oops, accidentally closed it. When another mod tried on the arcade servers, he couldnt join the game.

**Comment by ghost** [comment]
Premium perks only work before the match has started, so was he trying after the start?

**Comment by Superjd10** [comment]
Also, I would think Arcade servers are not connected to the Database, hence they don't get the perks.

**Comment by Electroid** [comment]
The player was probably opped.
