### ISSUE TITLE
Stats relating to play time are frozen

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/Issues#2284]
[Reported on forums](https://oc.tc/forums/topics/567182bb67d5225c6a000436). The _Hours played_ profile statistic is not updating for people.

**Comment by 2000thehecf1** [comment]
Days played and days observed are too.

**Comment by ghost** [comment]
All stats seem to be frozen under the stats tab? Kills/Deaths do not match current ones.

**Comment by itsmartin** [comment]
@elephantLocator They look fine to me, can you give an example?

**Comment by ghost** [comment]
@itsmartin Wait no I'm an idiot. Stats are actually GS+Blitz+PA. I forgot about the existence of Blitz and Ghost squadron.

That's been confusing me for a while.

**Comment by itsmartin** [comment]
Ah, OK

This bug is fixed anyway.

**Comment by 2000thehecf1** [comment]
@itsmartin Days played are still frozen

**Comment by itsmartin** [comment]
Should be fixed now, comment if not.
