### ISSUE TITLE
Update An Overcast Christmas

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2285]
The gameplay isn't really good, the map is a huge chokepoint for players. The enchantment system is just chaotic. This map should be updated!

Regards

McFanta_

**Comment by mattarnold98** [comment]
https://github.com/OvercastNetwork/Issues is for issues such as:
- Map updates (you're the map author posting a download link)
- Bugs

Please keep map recommendations to the forums. Another place this can go is https://github.com/OvercastNetwork/Rotations
