### ISSUE TITLE
Forum thread instantly archiving after creating (Map Making - Discussion)

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2286]
![](https://i.gyazo.com/6eb1837b63a45b7c74f21060079fb901.png)

![](https://i.gyazo.com/8eac45cefe3982bb5e11108ed6f60eea.png)

I just created a thread under Map Making - Discussion and it was instantly archived. Just posting here since Electroid didn't respond in-game. I'd also like to ask if I could have it un-archived.

**Comment by itsmartin** [comment]
Unarchived it. Looks like all new threads are dropping to the end of the list of topics. Presumably an issue with the timestamp.

**Comment by Matic0B** [comment]
Thank you for unarchiving it.

**Comment by Brottweiler** [comment]
Should be fixed.
