### ISSUE TITLE
You can't see other players' trophies through /trophies <name>

### ISSUE THREAD

**Issue by Picajoluna** [OvercastNetwork/Issues#2290]
Hi,

In-game, one can run /trophies and view their own trophies.
When running "/help trophies", the server returns: "List your trophies, or another player's trophies."

However, you cannot add any arguments/names after /trophies (e.g. "/trophies Apple") other than your own; the server returns: "You do not have permission." This means you cannot actually look up other users' trophy case while in-game, as yet states the /help command.

This is a very minor bug, but one nonetheless.

Thanks!

**Comment by Electroid** [comment]
Just because you don't have permission doesn't make the command description invalid.
