### ISSUE TITLE
Missing "Add as Friend" button

### ISSUE THREAD

**Issue by Saeruh** [OvercastNetwork/Issues#2291]
A user couldn't add me as a friend because the button was missing. I didn't have friend requests disabled, and she was also logged in on the forums. She claims that she wasn't able to add anyone – the button was missing on everyone's page. It was eventually fixed after I told her to log out and log back in. I'm not sure how to reproduce the following bug.

Here are some images for reference: 
*This was her perspective:
![Alt Text](http://imgur.com/6xhcSTP.png)

*These are my settings:
![Alt Text](http://imgur.com/S3ApVCO.png)

**Comment by Brottweiler** [comment]
It was fixed when she relogged, so unless it happens again I'll close this for now.
