### ISSUE TITLE
You can have multiple paid ranks ingame but not on the website

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2292]
For upgradable ranks
![](https://i.gyazo.com/d885ba48ad01790832f251bd2dfb7130.png)

Even for ranks with no expiration date

![](https://i.gyazo.com/9b15a39eda4015d1ed67d181247795a7.png)

I'm assuming this is a bug as it doesn't occur on the website: As soon as I purchased dux my centurion disappeared.

**Comment by Brottweiler** [comment]
I just tested this. Bought Imperator, and got this

![](https://i.imgur.com/WYh7z4C.png)

~~Also, in the lobby, I am still only Dux.~~ Lobby was probably not restarted.

![](https://i.imgur.com/tnsheQH.png)

**Comment by ghost** [comment]
Fixed now
