### ISSUE TITLE
Apple Picking - Atlas mapdev server - OBS and playing

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2294]
So I joined the game and this happened. I was shown as I was participating in the match but I had the observer hotbar, was in creative and could fly but I couldn't score even though I was in the match.

![](http://i.imgur.com/KIPCF9C.jpg)

**Comment by Electroid** [comment]
Map flaw.. And it's just because they raised the player limit.

**Comment by elephantLocator** [comment]
Duplicate of #2220 ?
