### ISSUE TITLE
404 page not found.. displaying 'Not found'

### ISSUE THREAD

**Issue by Pugzy** [OvercastNetwork/Issues#2295]
The website `404` page doesn't currently work (directing them to custom 404 page).

For example this link [https://oc.tc/not_a_real_link](https://oc.tc/not_a_real_link) displays a white page with `Not found` in the body.

**Comment by Matic0B** [comment]
https://oc.tc/user/ya
That displays a normal 404 page

https://oc.tc/ya
This does not

**Comment by itsmartin** [comment]
Looks fixed now.
