### ISSUE TITLE
Map update: Xi 1.1.1

### ISSUE THREAD

**Issue by chleongithub** [OvercastNetwork/Issues#2299]
Updates in this version:
- Reduced the amount of trees by about 2/5
- Fixed the water glitch
- Added a defending kit chest
- Updated the map.png to the most recent version
- Added a <broadcast> node which says that there are 3 diamond blocks behind the spawn
- Removed some of the water and replaced it with stained glass or ice

<a href="https://gist.github.com/chlegists/995820c0dbb5af74f927">XML</a>
<a href="http://www.mediafire.com/download/d2n40h737wa74u0/Xi+1.1.0.zip">New Packaged Download</a>
<a href="https://oc.tc/maps/xi">Xi</a>

**Comment by chleongithub** [comment]
I updated the xml: https://gist.github.com/chlegists/995820c0dbb5af74f927. Please use that xml instead of the one in the download

**Comment by chleongithub** [comment]
new dl: https://www.dropbox.com/s/gkpfh8df65uxvha/xi%20v1.1.1.zip

**Comment by AnthonyTag** [comment]
@yoyopower any update on this? Are you guys working this out or does this still need to get done?

**Comment by chleongithub** [comment]
I think its done @AnthonyTag
