### ISSUE TITLE
Out of the world and off a high place shots take distance incorrectly.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2303]
The message for this shots is for example:

Player1 was shot out of the world by Player2 from 200 blocks.
The thing is, the message implies that the player was shot from a distance, meaning, the distance from the shooter to the place the player was shot. But instead it takes another place (i think the place where they died in the void). This causes shots to be incredibly long,for example, on a map with a long void  fall distance such as sky traffic 1 or 2, a 60-70 blocks shot turns into a 170-200 one. On a map like crossfire it can turn a 40-60 blocks shot into a 70-90s one, and so on.

How to test: Try to get on a server and shoot people on the same spot, something such as a bridge. Get an out of the world kill and a normal kill, and you will see the big difference.

**Comment by ghost** [comment]
https://github.com/OvercastNetwork/Issues/issues/2182
