### ISSUE TITLE
Riot on EU lobby as well as US lobby as well as recurrence of #2249

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2304]
The weird thing where Torn is brutally murdering little children is shown on the EU lobby as well as the US lobby, when there is no riot server.
![2016-01-02_12 13 06](https://cloud.githubusercontent.com/assets/12920658/12074414/3bbd829c-b14a-11e5-99a8-8bce8160f898.png)

Also the signs for Alpha and RAGE are missing again #2249

**Comment by Brokennz** [comment]
Yes there is a Riot server, just type /server riot.

**Comment by ghost** [comment]
@brokennz On EU as well?

I don't think so, as I'm getting "No servers matched query" and there is no rotation document at [OvercastNetwork/rotations](https://github.com/OvercastNetwork/Rotations)

**Comment by Pugzy** [comment]
Hmm yeah this is an issue, I'll see if we can replace the center piece with something else.

**Comment by AnthonyTag** [comment]
Just rename the item stands to something like "Welcome to Overcast Network"

**Comment by AnthonyTag** [comment]
Err actually, my previous idea would not work. I was thinking of renaming the item stands in **just** EU but with our current setup for lobbies, that is unable to happen.

Maybe it's best to just wait for Riot to be out of Beta and have a server on EU?

**Comment by Pugzy** [comment]
@AnthonyTag I think the best suggestions is the one you mentioned five days ago, something generic and not server specific. Do you know if anyone is currently actively working on updating the lobby at the moment. As I've seen a few issues and bugs that people keep reporting.

**Comment by AnthonyTag** [comment]
@iPGz No idea, I pushed a fix yesterday for a few other issues, but I don't know if anyone is working on it...I'd assume you're fine to fix it.

**Comment by Brettogden** [comment]
The recent update removed the riot area on US & EU lobbies. This isn't an issue anymore.
