### ISSUE TITLE
Returned flags disappearing

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#2310]
![2016-01-07_14 07 19](https://cloud.githubusercontent.com/assets/8332105/12171261/9be0289e-b548-11e5-94dd-9cd9929e77c8.png)
![2016-01-07_14 09 02](https://cloud.githubusercontent.com/assets/8332105/12171262/9e742d44-b548-11e5-8565-973cf40318c3.png)

**Comment by AnthonyTag** [comment]
I have no idea what would be causing this. Possibly plugin related? Maybe map/client?

**Comment by eudaldca** [comment]
Must be a plugin bug, since that map hasn't had any issues afaik

**Comment by Pugzy** [comment]
Isn't this one of the maps where the flag doesn't respawn unless you capture both flags?

**Comment by eudaldca** [comment]
Didn't notice, my bad.
