### ISSUE TITLE
Spawnkilling is an issue on RFV3

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Issues#2313]
At this moment, people just shoot the iron supplies with all the no-stuff players. This is quite a bit of an issue, as the new rule declares that spawnkilling/camping is basically allowed. Although, I think a fix would be good as the map is just not fun due to this spawnkilling issue.

I suggest barrier blocks to be added on the top of the iron supplies for both spawns.

**Comment by ghost** [comment]
https://oc.tc/forums/topics/55e23c61c29635f9be000596?page=6

**Comment by Timothee38** [comment]
@TiTo-418 http://puu.sh/mpbob/2d610214c2.jpg

**Comment by Qixit** [comment]
I don't mind where the issues are made, forums or github. I've added barrier blocks to each spawn to prevent projectiles from entering.
