### ISSUE TITLE
Allow the map creator to disable mutations on their own map

### ISSUE THREAD

**Issue by chleongithub** [OvercastNetwork/Issues#2315]
It just happened on my map Xi during a test and it just broke the whole gameplay and everyone began to rate it 1. It just pissed me off so much when it happened.

**Comment by CoWinkKeyDinkInc** [comment]
I'm sure there is an XML option to disable that.

**Comment by itsmartin** [comment]
You can disable all mutations for a map, or change the probability of specific ones, in XML.

Also, please use the forums for feature requests - github is for bugs only.

**Comment by ghost** [comment]
[When this is implemented](https://oc.tc/forums/topics/566b51df67d522188e0020ad)
