### ISSUE TITLE
[Web Bug] Wrong Copyright Year On Translate.oc.tc and docs.oc.tc

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2317]
So I Was Just Checking Translate.oc.tc for some reason because I wanted to take a look at it again and then I saw that the copyright year was 2014 and I believe it is supposed to be 2016. Same with docs.oc.tc, I were there because I wanted To check some xml stuff there for maps and then I saw the same error (bug) there too. the copyright year was 2015 and I know it should be or supposed to be 2015. Please Fix This!

Regards 

McFanta_

Here you can look at some picture some pictures:
![bug01](https://cloud.githubusercontent.com/assets/13437351/12304975/a2f2078a-ba32-11e5-905f-318af0c29506.png)
![screenshot_59](https://cloud.githubusercontent.com/assets/13437351/12304978/a9753f64-ba32-11e5-91bd-e8c7821af80b.png)

**Comment by johannestheigen** [comment]
Thanks @yoyopower (Yoyo_) Fun bug right?

**Comment by ghost** [comment]
#1699 for translate.oc.tc

For docs, I'm confused. I thought I had fixed it in OvercastNetwork/docs.oc.tc/pull/206, but apparently no change is seen. What did I do wrong this time?

**Comment by johannestheigen** [comment]
@elephantLocator I believe you fixed the main website not docs. I may be wrong or not :P!

**Comment by itsmartin** [comment]
Docs will update when it's deployed.

**Comment by johannestheigen** [comment]
what about translate @itsmartin

**Comment by ghost** [comment]
@itsmartin I see. Assuming the nice yellow highlighting doesn't work on the docs revisions page then :(

well I'm an idiot. See what's going on now :/

**Comment by itsmartin** [comment]
@elephantLocator I'm not sure what the revisions page shows, but the docs front page shows what the latest revision that's been deployed is.

@McFanta the issue mentioned above is for translate.

**Comment by johannestheigen** [comment]
okay
