### ISSUE TITLE
Map update - 360° 2.0.0

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2319]
I am very happy about the fact that you permanently added Connected to the rotations and I get a great feeling inside when i see so many people play my maps. I'll try to continue making maps purely because i love to see people play them and I'll try to not think about any other frustrations about how some things are currently handled by the staff. I am trying to be a lot less active on the forums and I won't openly talk about some opinions i have about the overcast. I really appreciate that you consider adding 360° to the rot, so I decided to update it. I have a few good ideas to fix maps I currently have in the repo, so this won't be the last update coming up this weekend.

Changelog:
- 2 wools per team, last connection between the two lanes is in front of spawn, the wools should be a lot harder to cap. 
- removed diamond chestplates from woolroom
- only the woolrooms connected to the inner ring have access to the middle staircase of the woolroom, to prevent an easy double cap. 
- added small void gaps to the midline, i may change it around more but i want to see how this goes first. 
- removed boats from spawnkit
- updated victory monument
- naturalized the //naturalize

pictures: http://imgur.com/a/GbeJz
download: https://www.dropbox.com/sh/pzl2od7a6f1l429/AACqZv6te17A2XKW6xYVdSRYa?dl=0

**Comment by AnthonyTag** [comment]
The sugar in the wool room was named `Snus` which references drugs so I feel it is not very appropriate. Removing and and pushing another update
