### ISSUE TITLE
Overcast Stats - Playing time not updating

### ISSUE THREAD

**Issue by sovrynn** [OvercastNetwork/Issues#2320]
Hello, I was looking at my friends account and it says he has only played 3 hours, when I am sure that he has played for multiple days at least.

Also, on my stats my playing time has stayed at 71 hours for probably 1-2 months now. I remember seeing that number a long time ago.

My IGN is Jongh.

**Comment by ghost** [comment]
https://github.com/OvercastNetwork/Issues/issues/2284
