### ISSUE TITLE
Inaccuracy in our privacy policy

### ISSUE THREAD

**Issue by cpsiff** [OvercastNetwork/Issues#2327]
The privacy policy says: "All text sent through in-game chat or private messaging on our servers is saved indefinitely."

We should specify that we do not keep logs for mapdev servers.

**Comment by itsmartin** [comment]
Changing it to "may be" would suffice, but this doesn't really matter... the privacy policy doesn't exist to make any guarantees about logging, it exists to inform players of what we may store and how we may use their information.

Also, I believe logs are kept, they are just less accessible than logs of public servers.
