### ISSUE TITLE
Scoreboard not showing completed objective (check mark)

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2333]
I don't have a screenshot but when the match ends the team that has one check - mark does not have the second(or however many) check-marks to indicate that the team has won. An example is on mystic point. The first monument was completed and displayed a check mark at the end of the match, but when the second monument was completed to end the match, it only displayed a "touched" symbol and not the check mark when the match was over.

Now have a screenshot:

http://imgur.com/piTUrVr

**Comment by DoomRobotBoy** [comment]
don't know if obvious from op but above issue counts for every gamemode

**Comment by jedediah** [comment]
fixed
