### ISSUE TITLE
You can't cancel friend requests, maybe it's glitched

### ISSUE THREAD

**Issue by Brokennz** [OvercastNetwork/Issues#2338]
I saw that I sent a friend request to Tito but I can't cancel it, and aIso I can't press the cancel button.

![ku1us5s](https://cloud.githubusercontent.com/assets/11890645/12665836/5cb74882-c600-11e5-9b4e-cf2ba48342d6.png)

![t5cs0uq](https://cloud.githubusercontent.com/assets/11890645/12665837/5cc38f16-c600-11e5-97d0-d6be0ba8b31c.png)

**Comment by jexeI** [comment]
That means he denied it. This is not a bug.

**Comment by ghost** [comment]
I don't want you to spam my notifications so I denied it, this is not a bug

**Comment by Brokennz** [comment]
Ok, thanks (:
