### ISSUE TITLE
Unload '360 degrees' and 'King of the fortress' 

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2339]
I would like it if you could unload 360 and King of the fortress because they are currently broken and i wont be able to fix them.  Ethereal is kinda broken as well but ogel didnt want it to get unloaded.

**Comment by AnthonyTag** [comment]
I made a [backup](http://www.mediafire.com/download/83ut8tgzoyup65w/360%2BKing-of-the-Fortress.zip) for you just in case

**Comment by Qixit** [comment]
@JanPaulMosterdijk Contact me on skype if you need help with anything.
