### ISSUE TITLE
Update Adhbaerye to 1.0.1

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2341]
[New XML](http://pastebin.com/6Kefhr5L)
[New Download](http://www.mediafire.com/download/8dthce4aw1z9c2j/Adhbaerye_1.0.1.zip)

**Changelog:**
- Tweaked around the leaves/bushes.
- Removed some vines.
- Added some more spawn points.
- Respawn timer raised up to 3.5s.
- Added a regen effect as a killreward to prevent people from killing someone that just got a kill.

_Thanks in advance!_ :smile:

**Comment by Qixit** [comment]
In future @Tapetepato please go over your XML and check for errors. Throughout the whole XML there was at least 15+\* errors. Also don't forget to properly format the vectors of `<point></point>`, adding `.5` to `x` and `z` values. This will make the player go into the middle of the block, none of your points had this.
