### ISSUE TITLE
Unload maps

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Issues#2343]
Hello, i would like it if you could remove the following maps from the repo:
- Flag run
- Vanessa
- Connected
- Koi

Basically all maps i made without any other author. I would also like it if you could not load any maps i submitted in the past, excluding maps that i made with someone else.

**Comment by chleongithub** [comment]
No. Please.

Those maps are fun, come on!

**Comment by chleongithub** [comment]
I really disagree on the removal of connected

**Comment by Pugzy** [comment]
@chleongithub this is down to the author, we are only completing requests.

**Comment by chleongithub** [comment]
:sob:
