### ISSUE TITLE
Falling below -64 in the lobbies does not respawn the player

### ISSUE THREAD

**Issue by vortz** [OvercastNetwork/Issues#2346]
**The Issue:**
When the player flies below -64 in any server while in Observators (Creative Mode), he/she gets teleported to the spawnpoint of the map (I guess it's done when the player would take damage). In the lobbies, instead, the player falls infinitely, as the player is in God Mode.
**Steps to reproduce:**
Go to any of the edges of the lobby, and fall to the void.
**Miscellaneous information:**
It could be fixed by removing the godmode after a certain height, or by coding something to make players respawn after reaching -64 or above.
I don't know if it can be done if the player takes damage, as it can "take damage" if another player uses the "Raindrop Gun" on it.

**Comment by Qixit** [comment]
Isn't this to do with plugins, not the map? @AnthonyTag

**Comment by AnthonyTag** [comment]
@Qixit We can fix it with gamerules. I believe it's configurable.

**Comment by ghost** [comment]
It's happening again on tm lobbies
