### ISSUE TITLE
Dropping a flag ontop of a flag causes weird stuff

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2355]
Steps to reproduce:
Get one flag, drop it on the ground
Get another flag, stand where the first flag is, and jump (it will set the last valid position to ontop of the other flag), and then drop it

You will end up with a flag placed ontop of another flag, now, go ahead and pick up the bottom flag, you get a floating flag, and if you try and pickup the floating flag, for some reason it creates a black banner where the bottom flag was.

I belive it may be related to the fact that you can't remove the block on the bottom of a flag ("You may not break the block under the flag!"), and since you removed it (by picking up the flag) it for some reason, places it back (but without the banner data that makes it not be black (color, patterns, etc))? 
May also be related to water being replaced by ice, and when you pick up the flag it sets the block that was there before, and that happens with any block, instead of just with ice.

IMO the way to fix this is not to remove the posibility of dropping flags ontop of flags (atm i belive you can just drop flags in any Material.isSolid()), but just fix it so that it only sets the old block on the bottom of the flag if water was replaced when dropping it.

PS: if when you have 2 flags one ontop of eachother, you pickup the bottom one, and drop it ontop of the top flag (1 blocks up on the air), and pick up the flag that's only 1 block ontop of the ground, the top flag gets buggy, and can't be picked up anymore, (https://youtu.be/3WxA4DYnbaE)

**Comment by eudaldca** [comment]
https://youtu.be/3WxA4DYnbaE

**Comment by itsmartin** [comment]
Is this game breaking?

**Comment by eudaldca** [comment]
0:49. Yes, since once you do this you can no longer pick your flag up.

**Comment by itsmartin** [comment]
This should be fixed once servers have restarted.
