### ISSUE TITLE
Small xml update on Adhbaerye

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Issues#2357]
[New XML](http://pastebin.com/WNcVYrCd)

I noticed that the last time the map played the potion kill-reward wasn't showing up so i changed the killrewards to a kill-reward kit as i saw other maps use it, hopefully this fixes it.

**Comment by ghost** [comment]
In the tip shouldn't it be "as many kills as possible" not "as much kills as possible"?

**Comment by mitchts** [comment]
The tip really shouldn't even be there @elephantLocator

**Comment by Tapetepato** [comment]
I added it to explain to new players what to do since it is a new gamemode

**Comment by AnthonyTag** [comment]
We'll eventually be removing all of the tips that explain what FFA is, but we'll deal with that when it comes time.
