### ISSUE TITLE
9th Law Spawn bug

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2361]
On the map 9th law you sometimes get stuck in the bottom of the spawn area and can't move.
I do not know if I need to make a second issue for this but it would also be nice if a broadcast tip gets shown at the beginning of the game which gives you a hint where you can find water on this map because most of the players don't know especially new players.

**Comment by nigges60** [comment]
The issue still exists. Pls reopen.
https://youtu.be/mhfLk7J_MNw

**Comment by Brottweiler** [comment]
I don't think the server has restarted yet to have the new map version.

**Comment by Pugzy** [comment]
The server doesn't need to restart, if changes are detected with the map the latest version will be loaded/played.

**Comment by 2000thehecf1** [comment]
It's still happening. It has happened me some minutes ago.

**Comment by Qixit** [comment]
I've increased the spawn point by an extra `.5` in an effort to fix this. I've done the same with other maps in the past and it seemed to work.

**Comment by 2000thehecf1** [comment]
Still not fixed.

**Comment by mitchts** [comment]
I've observed multiple matches on 9th Law and not once did a player get stuck in the ground. I know when I have a poor connection, I can often get stuck in the ground.. but that has nothing to do with the map. So, that's what I think is happening. We've already done pretty much everything that we can in the XML to prevent this. Increasing the spawn y value further wont do much, if anything.

**Comment by AnthonyTag** [comment]
From what I can tell this does not occur anymore. Also no one has commented in the past few months explaining that this has occurred to them as well. Closing, open if it happens again.

**Comment by 2000thehecf1** [comment]
Two players reported it yesterday night on Capture EU.

**Comment by ghost** [comment]
I've had to teleport someone out of spawn too, pretty sure the issue still exists.

**Comment by Pugzy** [comment]
This was fixed but the issue was added back when 9.5th Law was added (as the commit included the reverted spawn heights).
