### ISSUE TITLE
Profile has all the information in the "about me" section

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#2375]
So I just finished making a few additions to my profile, and when I finished up, I noticed that all of my information, including my trophies and objectives, was laid out on the main section. And the tabs no longer work.

https://oc.tc/samthecat43

I have no idea what caused this, or how to fix it.

**Comment by itsmartin** [comment]
Looks like it was caused by something weird about your HTML. I've edited your HTML so it doesn't happen any more. Looking into why it happens.

**Comment by samthecat** [comment]
I think I figured it out. In the line 
`<h4><div style="display:block;"> Promoted to <div class="label" style="background-color:#0066dd;color:white;">Builder</div> February 27, 2016</div></h4>`
The first `<h4>` tag seems to enable/disable it.

I'll remove it.

**Comment by itsmartin** [comment]
Yeah, this appears to be a bootstrap bug. I'm not sure if we can fix it on our end.

**Comment by samthecat** [comment]
If it's not something on the server's end, then I guess this is resolved?

**Comment by samthecat** [comment]
It happened again, I don't know what's causing it this time.

**Comment by ghost** [comment]
![screenshot_53](https://cloud.githubusercontent.com/assets/11008016/14867928/6cbed3ca-0ca1-11e6-8b3c-ad7a7b028361.png)

Could you close those tags?

Edit: It was the error, I closed those tags and now it's fixed (https://oc.tc/TiTo_418), this can be fixed server-side checking if the html is valid

**Comment by Brottweiler** [comment]
@samthecat Looks fine to me? Screenshot?

Edit: Nvm i scrolled down and I see what you mean now.

**Comment by samthecat** [comment]
@Brottweiler https://oc.tc/samthecat43 scroll to the bottom of my profile.

**Comment by Brottweiler** [comment]
Notice the edit. 😛

**Comment by samthecat** [comment]
Seems to be fixed when I end the tags, but I wanted to make the text bigger in the first place

Could anyone tell me how?

**Comment by itsmartin** [comment]
As @TiTo-418 said, the only way to avoid this happening is to make sure the HTML is valid. It's caused by improper nesting of tags.

We can't fix this directly. We would have to enforce valid HTML on profiles, but that probably isn't worth it since this issue only seems to happen in _very_ specific circumstances.
