### ISSUE TITLE
I can't see anybody's profile.

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2376]
Whenever you try to enter anyone's profile, you receive this message:
https://gyazo.com/e2d411c25cd1c37aa6cd3f6dfe3881f7

**Comment by ghost** [comment]
https://oc.tc/forums/topics/56d846025f35b92483000002?page=1#56d8782a186c61650a000001

**Comment by itsmartin** [comment]
The issue is being actively worked on, sorry for the inconvenience.

**Comment by itsmartin** [comment]
Should be resolved now.

**Comment by 2000thehecf1** [comment]
@itsmartin It is, thank you.
