### ISSUE TITLE
Fly players

### ISSUE THREAD

**Issue by xWhitePVP** [OvercastNetwork/Issues#2377]
Hello, the day March,4 2016 i are playing in Sunrise Over Paradise and i watch a player named [name removed] fly with no armor

[image removed]
[image removed]

**Comment by AnthonyTag** [comment]
If this is meant to be a report, then send this over to https://oc.tc/report

When you asked me in chat where to send issues I sent you here because this is where you send issues with the servers (i.e. Plugins, Maps, etc.).

**Comment by xWhitePVP** [comment]
@AnthonyTag you can check my octc report?

**Comment by Pugzy** [comment]
I've removed the player info and images from the issue OP. 
Like stated above the Github issue tracker is for issues not reports.
