### ISSUE TITLE
Map Update - Winter Wakening

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#2378]
DL: https://www.dropbox.com/s/gp6mf0iq859ix1m/Winter.zip?dl=0
- removed some trees
- edited the pre-made defenses
- added a chest with some gear for defenders on the wool lanes
- made iron mines a bit more visible

ty!

**Comment by Pugzy** [comment]
Have you uploaded the correct version? The XML still says `1.0.0`. @DoomRobotBoy 
- The observer spawn (in the XML) is about 10 blocks too high.
- The map doesn't seem to have been pruned correctly.

**Comment by DoomRobotBoy** [comment]
@iPGz got around updating it; its now pruned and xml has been updated

DL: https://www.dropbox.com/s/gp6mf0iq859ix1m/Winter.zip?dl=0
