### ISSUE TITLE
Portals (docs) 

### ISSUE THREAD

**Issue by ResentFeeds** [OvercastNetwork/Issues#2380]
# When I try to view the Portals page. It gives me this.

**StaticMatic::TemplateError in ./src/modules/portals.haml**

./src/modules/portals.haml is not valid US-ASCII

**Backtrace**

/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:75:in `initialize'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt.rb:61:in`new'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt.rb:61:in `new'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/render.rb:90:in`tilt_template'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/render.rb:16:in `render_template'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/render.rb:29:in`render_template_with_layout'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:34:in `block in generate_site_file'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:32:in`open'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:32:in `generate_site_file'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:8:in`block in build'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:4:in `each'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/mixins/build.rb:4:in`build'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/lib/staticmatic/base.rb:74:in `run'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/bin/staticmatic:71:in`build'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/gems/staticmatic2-2.1.6/bin/staticmatic:142:in `'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/bin/staticmatic:23:in`load'
/home/deploy/apps/docs/shared/bundle/ruby/2.1.0/bin/staticmatic:23:in `
'

**Comment by itsmartin** [comment]
Should be fixed now.
