### ISSUE TITLE
1.9 known issues

### ISSUE THREAD

**Issue by jedediah** [OvercastNetwork/Issues#2381]
- [x] Potions all kinds of broken (fix needs testing)
- [x] Long-range TNT causes NPE
- [x] NPE in `TabRender.updateFakeEntity`
- [x] Armor kits (fixed upstream)
- [x] Teleport while gliding does something weird
- [x] Map rating click causes `ArrayIndexOutOfBoundsException`
- [x] Stuck on death screen
- [x] Creation of tipped/spectral arrows (looks like a possible upstream bug in `CraftWorld#createEntity`)
- [x] Dispensing mob egg crashes server
- [x] Fill bucket in observer does not restore the block client-side
- [x] Default collision rules
- [x] Entity translations missing in death messages
- [x] ghost players in boats
- [x] lingering potions not cancelled
- [x] players can hear observers hitting them
- [x] observer equipping elytra with right-click causes client desync
- [x] Kill reward doesn't stack in your off hand
- [x] Some GUI buttons need tooltip stuff hidden
- [x] Saturation effect causes fast healing all the time
- [x] void kill detection is broken
- [x] /kill is completely broken
- [x] boats collide with non-colliding players
- [x] freeze player in boat doesn't work

**Comment by Pablete1234** [comment]
@jedediah Long-range TNT never worked in 1.8 (maybe it didn't throw errors, but it didn't display)

**Comment by Timothee38** [comment]
Adding onto the "stuck on death screen" issue the one where when you respawn after dying on blitz (with 1 life) you get stuck (you can't move your head around or even move at all). (I thought I shouldn't make a whole issue as I guess it's sort of part of this death screen issue.)

**Comment by Pablete1234** [comment]
@jedediah TNT in 1.9 displays up to half your render distance
Example:
8 chunk distance = 128 blocks distance = see tnt 64 blocks away
16 chunk distance = 256 blocks distance = see tnt 128blocks away

PS: 
The change seems to be to some entities.
Both falling sand and TNT are render distance dependent.
Armor stands / ItemFrames seem to render with the chunk (if chunk is loaded you see it), 
Minecarts render ~70 blocks away, regardless of the render distance
Paintings render ~40 blocks away, regardless of the render distance

**Comment by eudaldca** [comment]
Freezing and unfreezing someone who is riding a boat (tested by freezing pablete, who was driving the boat) gives many issues.

**Comment by manmanrod** [comment]
*You are not allowed to choose team" when you have centurion in dv.oc.tc

http://i.imgur.com/tDzZPIe.png

**Comment by elephantLocator** [comment]
@ImKenner Any donor rank afaik. It's like on mapdev servers I guess, if that's a bug?

**Comment by Brottweiler** [comment]
I got poisoned and it got me down to 1 HP, but after I got to 1 HP I started to regen health again, and while still having poison potion effect I was not taking damage. I had blood enabled, and I got the damage particles from that, but I did not loose health. I was regenerating health like normal.

**Comment by ghost** [comment]
Death screen bug: https://www.youtube.com/watch?v=DPe0L9u9bZM&edit=vd

**Comment by ghost** [comment]
![2016-03-26_12 24 12](https://cloud.githubusercontent.com/assets/12920658/14060054/c5d05e5a-f34e-11e5-82b0-668043ae3e1d.png)

This happened on DATABasin.

Also, not really worth making a new issue for, but Ozone elytra /map still references teams.

**Comment by Pablete1234** [comment]
You still respawn every tick if you fall to the void in obs (it keeps teleporting you to diferent valid spawn locations for observers team)

**Comment by Pablete1234** [comment]
Just a suggestion, IMO, bossbars would be alot cooler if:
Team huddle bossbar was yellow
Start bossbar was green
Waiting for players bossbar was red
