### ISSUE TITLE
Map Update Desert Country to Version 1.0.5

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2386]
![2016-03-14_20 18 42](https://cloud.githubusercontent.com/assets/17301322/13757159/6a182374-ea23-11e5-9f7f-e713855f012b.png)

**Notable Changes**
- Changed Woolroom entrance
- minor aesthetic fixes
- XML changes: Bigger Wool Room Area

**Problem**
- We got feedback that iron armor does not drop although I don't see where this is written in the XML can you help me to make iron armor and diamond armor dropping?

[**Download**](https://www.dropbox.com/s/be8c6o450e9fddv/Desert%20Country%20v.1.0.5.zip?dl=0)

**Comment by Qixit** [comment]
@nigges60 The DL is broken.

**Comment by nigges60** [comment]
@Qixit sorry this one should work: 
https://www.dropbox.com/s/xudwmaykkhih65t/Desert%20Country%20v.1.0.5.zip?dl=0

**Comment by Qixit** [comment]
Please remember to properly format your `map.png`, with a size of `290x246`. There is more packaging advice on [docs.oc.tc](https://docs.oc.tc/guides/packaging/compiling_releasing). Also your map version shouldn't be going from `v1.0.0` to `v1.0.5`, unless there has been some error. For now I've changed it to `v1.0.1` and I've formatted your `map.png` correctly.
