### ISSUE TITLE
1.9 gameplay issues

### ISSUE THREAD

**Issue by Electroid** [OvercastNetwork/Issues#2388]
- [ ] Shields do not protect from damage
- [x] Armor is weaker (increasing attributes values by `1-2` should work)
- [x] Custom potions now add the default attributes of its damage value #2385 
- [x] Some tile entities are missing from chests (requires `MCEdit` filter and patch)
  - [x] Cooked fish (Fortress Battles)
- [x] Spawners with stackable item drops no longer work (Boom)
- [x] Item stack arrows and arrows stuck in blocks don't stack up
- [x] player push flags don't seem to work
- [x] add splash potions to itemremove
- [ ] knockback enchantment needs custom implementation
- [ ] smooth out inferred player velocities to prevent extreme knockback
- [x] jump pads should use absolute velocities, as they did previously
- [x] vanilla respawn screen on dwyer hill
- [x] off-hand TNT is infinite on dwyer hill

**Comment by Pablete1234** [comment]
@Electroid regarding player push flags (Team collision rules) they used to work in the first sportbukkit 1.9 releases (tested in cardinal) but they got broken in one of the updates

**Comment by eudaldca** [comment]
Knockback is still an issue, even after @jedediah 's last fix.

**Comment by nigges60** [comment]
For me it seems that damage needs to be reworked as well because the damage is to low. This breaks the whole gameplay because rushing gets quite easy. Just have a look at the time of the games of Capture EU almost no game lasts longer than 5 minutes.
