### ISSUE TITLE
1.9 arrow mechanics render bows useless when player has downwards velocity

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2392]
Here is a video demonstrating: https://www.youtube.com/watch?v=aCdt74F4T2o

The most common theory is that when you bow, the player's velocity is given to the arrow after you shoot it, so it you're falling, any arrows you shoot will go right into the ground. This is a problem on OCN in particular, as many maps incorporate vertical elements such as SSB (water streams, skybridges) and Directrix (jump pads), and players often encounter situations in which they shoot arrows while falling.

**Comment by jedediah** [comment]
I wouldn't call that "useless". It seems like something players could adapt to, and maybe use to their advantage. That is how physics actually works, after all.

**Comment by MarcRoizman** [comment]
After playing some maps with it though, it's apparent that you only have a range of 5-10 blocks or so when you're falling no matter how high you aim, so the extent to which players could "adapt" to this is limited. I forgot to note in the original post that this also breaks archery when double jumping on maps which include that, such as Lost World. 

I just feel that this limits what players can do, and in a bad way. Even stuff like [this video](https://www.youtube.com/watch?v=4Aom9bAIOuo), which attracted 100k+ views and was essentially free advertising for OCN, relied on the player being able to bow other players while falling.

While this is how physics actually works, I just feel that any change which removes functional mechanics for no real reason is a negative one. Same thing with the underwater arrow change IMO, the mechanics went from being unique in that arrows were slower but usable in 1.7, to just removing any kind of underwater archery by greatly reducing their underwater range in 1.8.

**Comment by Pablete1234** [comment]
I do not think this change is just "removing the posibility to shoot while falling" i think this change "allows you to shoot further away while jumping", be a bit more optimistic about changes

**Comment by MarcRoizman** [comment]
That's great that you can now shoot father while jumping, but that's not the part of the change I'm concerned about. I'm concerned that a perfectly functional mechanic was removed for no reason, and it now limits what the player can do, on OCN in particular.

**Comment by Brottweiler** [comment]
Sounds more like a feature request than a bug, no? Since this is the way arrows work in 1.9.

**Comment by mitchts** [comment]
https://oc.tc/forums/topics/5701d4135f35b913ea000006
