### ISSUE TITLE
Tab list showing offline players

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2393]
![](https://i.gyazo.com/0060a35e01e0cf94aa14c725658799c7.png)

"Berfo" is a player that's not online, but it's showing on the tab list

PS: the offline player keeps showing even after reloging, map cycles, etc

**Comment by andreskv** [comment]
More of this

<img src="http://i.imgur.com/Kq7nkLU.png" />

**Comment by Pablete1234** [comment]
Even more:

![](https://i.gyazo.com/c883b3d14970230b2e38eb8607e79107.png)
![](https://i.gyazo.com/3036c494b550bc991af6544de3e99939.png)

ps: the "offline players" count towards the count of the server's players (in the GS image, the GS server says it has 3 players)

**Comment by ghost** [comment]
If the player comes back they duplicate. When the real player leaves the fake one stays. Please fix it's somewhat creepy.

![](http://i.imgur.com/aJLRVis.png?1)

**Comment by Pablete1234** [comment]
I found how to replicate the bug consistently:
![image](https://cloud.githubusercontent.com/assets/11789291/15083162/ffc33ea0-13cb-11e6-8795-e6cebe98db40.png)

The bug occurs when a player disconnects from a world that isn't the same as the current match.
To replicate it (in tm's), you can abuse a bug with execute and tp, that makes it so that tp doesn't remember the world: `/execute @p ~ ~ ~ /tp @a 0 100 0` that command will teleport you to the default bukkit world, now, when someone disconnects while on that world, they get bugged, I highly doubt that anyone disconnected in public matches while in another server, but i think this happens in public if someone disconnects while the match is in the middle of a cycling to the next map

**Comment by LArrowHead** [comment]
I don't have a screenshot but sometimes players still appear on the observers tab when they are on a team.

**Comment by Pablete1234** [comment]
This has been fixed, and should be closed
