### ISSUE TITLE
Match Start Cancelled pops up when match is over.

### ISSUE THREAD

**Issue by johannestheigen** [OvercastNetwork/Issues#2394]
Here are some few screenshots.
![2016-03-27_19 23 05](https://cloud.githubusercontent.com/assets/13437351/14066710/d34442d2-f451-11e5-9758-692a90e7ea71.png)

![2016-03-27_19 31 07](https://cloud.githubusercontent.com/assets/13437351/14066744/825a21ba-f452-11e5-8681-6138324a01ed.png)

![2016-03-27_19 34 49](https://cloud.githubusercontent.com/assets/13437351/14066755/02af200e-f453-11e5-9383-6e13ca7dfebc.png)

I am not sure if there have been already made an issue about it. But for now I'll leave the issue here.

Looking forward for a stable 1.9! :smile:

**Comment by ghost** [comment]
http://prntscr.com/b9yal9
