### ISSUE TITLE
Enchanted bows disappearing, normal bows don't shoot

### ISSUE THREAD

**Issue by andreskv** [OvercastNetwork/Issues#2400]
Yesterday this same thing happened to me with a punch bow, first it lost its enchantments and right after it disappeared from my inventory. Sometimes regular bows get buggy and won't shoot at all. I guess it's server lag, my connection is perfectly fine.

https://youtu.be/0jl3ZWN2dUI

**Comment by AnthonyTag** [comment]
Did you have any mods installed on your client while recording this?

**Comment by Brottweiler** [comment]
The bow was never in your slot at all, I wouldn't know the cause of this but very well it might be client sided and due to a mod. Are you sure you had 100% vanilla client when testing this?

Closing since afaik this isn't an issue.
