### ISSUE TITLE
Tip at the top/bossbar not showing correctly

### ISSUE THREAD

**Issue by Musyaffaq** [OvercastNetwork/Issues#2401]
1. Instead of just showing 'Change your class using /cl (name)', it also says 'in 3599542 seconds' at the end.
2. To reproduce it, play the map 'DATABasin'. I'm not sure if this occurs on other maps though.
3. Screenshot: http://imgur.com/RZX5UvU

**Comment by ghost** [comment]
https://github.com/OvercastNetwork/Issues/issues/2381#issuecomment-201801662
