### ISSUE TITLE
Player crashing when map cycles

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2403]
https://i.gyazo.com/c626645ce0a15609736b30ab16493f50.png

As you can see in the image above, a player says the he crashes when a map cycles. He says this happens when he uses Optifine (the only mod he uses), and without it. He has only had this issue since the server updated to 1.9. 

I'm not sure if this is a client side issue, or a server one. I figured I would report it anyways. I also remember hearing about some other players who crashed for no reason, so maybe they had the same problem, and just didn't realize it was from the server cycling?

**Comment by CrazyisCreeps** [comment]
This is now occurring to me for the first time ever. It has now crashed twice in a row when the map cycles (so 2 different cycles)
I don't know if these means anything to you guys, but here's the crash report.
http://pastebin.com/ZJsiekHL

**Comment by ghost** [comment]
It's an optifine bug. As you can see in your crash report, you are using the first release which has a lot of bugs (it was a alpha), [updating it](http://optifine.net/adloadx?f=OptiFine_1.9.0_HD_U_B1.jar) may fix the issue
