### ISSUE TITLE
Countdowns do not show in chat

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2404]
Countdows for the end of a TDM, nor for match cycling.

![2016-03-29_12 37 27](https://cloud.githubusercontent.com/assets/12920658/14106739/3efeb53e-f5ab-11e5-839b-c152725195e1.png)

Should be showing match start countdown

![2016-03-29_12 35 49](https://cloud.githubusercontent.com/assets/12920658/14106740/3eff7e60-f5ab-11e5-9b05-baa21d57e125.png)

Should be showing time until end countdown

![2016-03-29_12 37 00](https://cloud.githubusercontent.com/assets/12920658/14106741/3f006f46-f5ab-11e5-9732-5127c0390db3.png)

Should be showing cycling countdown.

**Comment by Brottweiler** [comment]
They don't need to show countdown in chat, you have the bossbar for that.

**Comment by ghost** [comment]
[Fair enough, Martin said it _might_ be a bug](https://oc.tc/forums/posts/56fa6705c2963562870001e2),  so thought I should post it to be safe. I'll close then, as it's intended.

**Comment by Brottweiler** [comment]
Confirmed intentional, not a bug.
