### ISSUE TITLE
Player not showing in the right place in tab

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2406]
https://gyazo.com/8302a5f46b376a351489c0fa50543103
https://gyazo.com/7580149f2c60f2341a2173d034afb846

**Comment by Pablete1234** [comment]
@MrPetrus was that player actually in that same server, and in that team?

**Comment by ghost** [comment]
@Pablete1234 yeah, that player was in that server, playing in that team.

**Comment by ghost** [comment]
Found the cause, #2393. The player was a so-called "ghost obs". leading to being displayed twice when joining the server. If you look, he's also under the team list.

**Comment by itsmartin** [comment]
I think this is the same issue as #2393.
