### ISSUE TITLE
Obs Bugs/Tab Bugs 1.9

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2409]
The people used in the screenshots were on multiple servers at once, and they at times had two of the same names displaying. 

Also, I could see one of them as you can see in the screenshot.

Album:
http://imgur.com/a/CFJjG

"Ghost Obs"-- They arent on the server but they are displaying.
image: http://imgur.com/PQvCd6j

**Comment by Pablete1234** [comment]
Duplicate of #2393

**Comment by LArrowHead** [comment]
@Pablete1234 The first part isn't with the obs being seen, but yes the others are duplicates of #2393

**Comment by Pablete1234** [comment]
@LArrowHead well, that "ghost obs" is there because of the tab bug / is related in some way (it's the same player that is buggy on the tab), so i guess it could be in the same issue

**Comment by itsmartin** [comment]
This is covered by #2393.
