### ISSUE TITLE
Desert Country Map Update to v.1.0.2

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2413]
Changelog
- fixed the water pits

Download link: https://www.dropbox.com/s/kyb1bkcpsxtkflx/Desert%20Country%20v.1.0.2.zip?dl=0

**Comment by Qixit** [comment]
@nigges60  Please remember to prune your map.

**Comment by nigges60** [comment]
@Qixit I changed nothing at the map actually just the XML.

**Comment by nigges60** [comment]
Nevertheless I'll prune it next time!
