### ISSUE TITLE
Wooden slabs on Fairytales 2: A Tale or Two are very outdated

### ISSUE THREAD

**Issue by Palmidence** [OvercastNetwork/Issues#2418]
Pretty sure all of the other maps that used stone wooden slabs were fixed, so I was thinking Fairytales was left out. As there is no longer a texture, it doesn't look pretty when defending. It's not gamebreaking, but it's an inconvinence to defenders (as one who crafted an axe to break them).

![](http://i.imgur.com/O1GD1a0.png)
![](http://i.imgur.com/K8eMzhl.png)

_List of maps it occurs on so far:_
- [ ] Battle of Tenjin 1
- [ ] Blocks DTC
- [ ] Fairytales 2: A Tale or Two
- [ ] Sky Traffic 2

**Comment by ghost** [comment]
I believe this is also the case on Battle of Tenjin (1) and possibly A Watery Grave, but haven't played that in a long time so could not be the case.

**Comment by ghost** [comment]
The stone slabs in chests on Sky Traffic 2 also have this issue.
