### ISSUE TITLE
Update Government 5x5 v1.0.2

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#2419]
- fix broken spawnpoint
- add Rockymine as contributor 
  http://www.mediafire.com/download/04uakt7fb05y795/Government+5x5+v1.0.2.zip

**Comment by AnthonyTag** [comment]
I assume the broken spawnpoint was the one that had players spawn out in the void?

**Comment by stormer1267** [comment]
Yes, was there an issue for it? I am really new to this 🎓

**Comment by Pugzy** [comment]
@stormer1267 If you have only changed things with the XML then you only need to provide us with the updated version (within a Gist etc).

In your updated version you have set the `max-overfill` to be 0, this is incorrect and would cause errors, its use is stated on `docs.oc.tc`.

> Maximum team size hard limit, nobody can join this team once this limit is reached. 
> Must be greater than the defined max.

You also need to bump the version number.
