### ISSUE TITLE
Randomly Timing Out

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2427]
I'm timing out completely randomly since yesterday and I changed nothing. The message I get is "Disconnected". Can provide a screenshot soon when randomly disconnect again.

**Comment by ghost** [comment]
Sounds like #2360 ?

**Comment by nigges60** [comment]
I also got this message now: http://i.imgur.com/3Gxfhin.png

**Comment by nigges60** [comment]
Seemed to be a problem of my internet provider.
