### ISSUE TITLE
Purple team has no villagers on Rift

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2431]
Purple team was missing all of the trading villagers at their spawn. Cyan team had theirs, and were able to trade with them. 
I was unfortunately not able to get a screenshot in time.

**Comment by CrazyisCreeps** [comment]
Never mind, Cyan team also has no villagers

**Comment by Qixit** [comment]
These villagers were intentionally removed I'm pretty sure, and they won't be added back unless Lyzak wants them to I think.

**Comment by CrazyisCreeps** [comment]
Bump. Although Qixit said this is intended, I still think it's a spawning bug. The OP pigmen spawners also don't spawn pigs, leading me to think it has something to do with 1.9 and how mobs spawn.

Also, it if intended, it would be nice to remove the trading stations to remove all possible confusion.
