### ISSUE TITLE
Tanker TNT has no supply chests

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2432]
On the map Tanker TNT the supply chests on the left and right (those chests normally have the TNT supplies) have turned into bedrock.
https://i.gyazo.com/17de46a8956c1e713c10878f8676058f.png

**Comment by mattarnold98** [comment]
I'm 90% certain there was already an issue about this, and Tywnis responded saying he just moved the supply chests. 

EDIT: I checked the map, they're on the islands to the right/left of where you spawn.
