### ISSUE TITLE
Tab List Broken

### ISSUE THREAD

**Issue by cak-e** [OvercastNetwork/Issues#2434]
As you can see in the screenshot, the tab list is broken. In this example, you can see djrcapo's name is below all other's, with the observers. Another example is that the tab list shows some players even though they aren't in fact there. This can be shown with Twilight_Bloom.

**Comment by cak-e** [comment]
![2016-04-11_19 09 03](https://cloud.githubusercontent.com/assets/18396276/14445158/e1b615de-0018-11e6-80f8-1f7e502964d4.png)

**Comment by itsmartin** [comment]
#2393

**Comment by cak-e** [comment]
I just saw that infact, but the new bug is the djrcapo.

**Comment by itsmartin** [comment]
It would be best to post this as an example on that bug. I think the two issues probably share a root cause.
