### ISSUE TITLE
OCN KB it's not fixed at all.

### ISSUE THREAD

**Issue by xHeimskr** [OvercastNetwork/Issues#2438]
https://www.youtube.com/watch?v=yMeYGZAh-sA&feature=youtu.be

**Comment by itsmartin** [comment]
Tested just now, sprint hitting a player twice (resetting sprint in between) gives the expected 10 blocks of knockback. Maybe the server you were on was not updated.

**Comment by itsmartin** [comment]
[Seems fine now](https://www.youtube.com/watch?v=ge1NUcrdhr8).
