### ISSUE TITLE
Arrows are extremely overpowered on Assault in 1.9

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2441]
Arrows deal up to 6.5 hearts of damage on Assault, which is way too much. Perhaps either add significant projectile protection or get rid of the power of the bows, or do both. Either way, it needs to be changed because it plays almost like a rage TDM right now.

**Comment by 2000thehecf1** [comment]
Just debuff arrows serverwide, they deal more damage than they should on every map.
