### ISSUE TITLE
It's possible to bypass link restriction

### ISSUE THREAD

**Issue by unixfox** [OvercastNetwork/Issues#2448]
Every link that contains "oc.tc" in the chat is allowed, so if I send a message with "oc.tc.exemple.com" it is not blocked.
Everyone can create a random domain with "oc.tc" for the subdomain and send bad links on the chat without being blocked.

Evidence:
![](https://i.unixfox.eu/11-15-09-2016.png)

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/805
