### ISSUE TITLE
Woolroom diamond chestplate is bugged on Race for Victory 3

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2449]
When you have the chestplate equipped, it isn't recognized as a piece of armor so you are easily killed while wearing it.

Evidence: https://youtu.be/GtYfkI2S1_k

**Comment by ghost** [comment]
Dupe? https://github.com/OvercastNetwork/Issues/issues/2423

**Comment by Eslakon** [comment]
Nice song lmao

**Comment by samthecat** [comment]
#2423

**Comment by 2000thehecf1** [comment]
I think this might be related with attributes on armor since it only happens to me on RFV3 and with GD3's woolroom chestplate.
