### ISSUE TITLE
Brewing no longer works as intended on Viridun

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2450]
Due to the potion bottle remove thing, you can no longer get empty potion bottles to brew with on Viridun. It's not game breaking, but it removes an interesting feature of the map and I think this is one map that potion bottles should be droppable/attainable on.

**Comment by mitchts** [comment]
Wouldn't blaze powder also need to be added somehow?

**Comment by MarcRoizman** [comment]
I believe there are already a few blaze rods in the chest of brewing supplies.

**Comment by samthecat** [comment]
@nygiants10 I think it's blaze powder

**Comment by AnthonyTag** [comment]
@samthecat throw a blaze rod in your crafting section of your inventory and you get powder, right?

**Comment by mitchts** [comment]
Fixed in https://github.com/OvercastNetwork/Maps/commit/e912586fc0c676ee6301475cd4d0684702bc0a2b
