### ISSUE TITLE
Map Update Desert Country to Version 1.0.3

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2458]
The Map already got updated this day to v1.0.3 but there is a little XML failure. The monuments are not identified on the correct place. Here is the correct version of it: http://pastebin.com/Q9bemgs3

**Comment by Pugzy** [comment]
@nigges60 the XML you provided has lost all formatting due to it's format, are you able to re-upload the XML and save it as the correct file format? It makes everyone's lives a little easier, thanks.

**Comment by nigges60** [comment]
@iPGz sure but not today probably tomorrow. Sorry for this complicated way.

**Comment by mitchts** [comment]
Completely forgot about changing those values.. I'll be able to fix this in a few hours if no one else does it before me.
