### ISSUE TITLE
Sidebar text collapses on itself when re-sizing window

### ISSUE THREAD

**Issue by Szboy** [OvercastNetwork/Issues#2459]
![](http://img.prntscr.com/img?url=http://i.imgur.com/Mw0FjUw.png)
This happens when clicking on subforums and then re-sizing the window back to full.

**To reproduce:** 
1. Reduce the window from full size to a size that shows the orange subforums button
2. Click on the subforums button to open the subforums  and then click on the button again to re-collapse.
3. Maximize the screen.

**Comment by itsmartin** [comment]
Fixed.
