### ISSUE TITLE
Iron axes are too much on Circus DTC

### ISSUE THREAD

**Issue by guillevn** [OvercastNetwork/Issues#2465]
I get that they are there to break wood fast, but with no iron armor (i think there is an ingot kill reward but meh) they should either be lowered to a stone axe with efficiency 3 (unbreakable of course) or just lower the damage it makes through XML.
You can two hit kill with iron axes.

**Comment by guillevn** [comment]
This is an actual issue in all maps that give you low armor (leather) and iron axes

**Comment by Brottweiler** [comment]
This isn't a bug, though, create a feedback thread on the forums.
