### ISSUE TITLE
Winter Wakening armor not dropping

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2468]
Iron armor is not dropping although it is not on itemremove. I assume normally armor should drop but it does not.

**Comment by samthecat** [comment]
Just tested it out and and iron armor drops for me.. are you able to reproduce it?

**Comment by mitchts** [comment]
The `keepInventory` gamerule is set to true, which could be the reason as to why it isn't dropping.

**Comment by mitchts** [comment]
Fixed in https://github.com/OvercastNetwork/Maps/commit/bbfe82ad08d68c128a1acc95db77baca2c80493e
