### ISSUE TITLE
YouTube embed does not work with timestamps

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#2471]
Putting an valid link into the embed with a timestamp such as this does not work:
`[youtube:GfEKGum0kGQ?t=40s]`

This does work however.
`[youtube:GfEKGum0kGQ]`

https://youtu.be/GfEKGum0kGQ?t=40s

**Comment by itsmartin** [comment]
Added.

**Comment by CoWinkKeyDinkInc** [comment]
Thank you!
