### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lanenavlogs** [OvercastNetwork/Issues#2473]
hola gente necesito que alguien me diga que tengo que hacer yo compre el minecraft y quería jugar a un servidor pero hace unos días que me dice que no soy premium por lo tanto no puedo elegir el equipo por favor que alguien me diga que puedo hacer para solucionarlo aquí dejo una imagen 
![captura](https://cloud.githubusercontent.com/assets/19612979/15616854/7c06e7b6-2446-11e6-9839-8b09a70c60d4.PNG)

**Comment by mitchts** [comment]
Refer to https://github.com/OvercastNetwork/Issues/issues/2474
