### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lanenavlogs** [OvercastNetwork/Issues#2474]
hola gente necesito Que alguien me diga Que Tengo Que Hacer yo compre el Minecraft y queria jugar una un Servidor Pero Hace UNOS Días Que Me dados Que hay prima de soja por lo Tanto No Puedo Elegir el equipo por favor Que alguien me diga Que Puedo Hacer párrafo Aquí dejo solucionarlo Una imagen 
![captura](https://cloud.githubusercontent.com/assets/19612979/15621551/03121652-2462-11e6-8dbb-a661aede32e4.PNG)

**Comment by mitchts** [comment]
You don't have a premium rank on the network. To choose your team, you must purchase one of our premium packages in our [shop](https://oc.tc/shop).

**Comment by lanenavlogs** [comment]
cabrones no hacéis na mas que pedir y pedir puto dinero hijos de puta ya pague por tener minecraft y ahora tengo que pagar por un puto servidor? que os jodan

**Comment by lanenavlogs** [comment]
cabrones no hacéis na mas que pedir y pedir puto dinero hijos de puta ya
pague por tener minecraft y ahora tengo que pagar por un puto servidor? que
os jodan hijos de puta

2016-05-28 7:35 GMT+02:00 Mitchell notifications@github.com:

**Comment by Pugzy** [comment]
@lanenavlogs it is completely free to play on our servers however for those who wish to support the server they're able to purchase VIP ranks which come with several perks, one of which is the ability to select their team. You can join the match by selecting the `Auto-Join` chain helmet.

**Comment by lanenavlogs** [comment]
😑 esta bien que pasa si cojo el dux? puedo elegir el equipo que yo quiera?

2016-05-28 18:11 GMT+02:00 Andrew notifications@github.com:

**Comment by Pugzy** [comment]
@lanenavlogs all of the ranks come with the same perks (found on oc.tc/shop) one of these perks is that you can `Choose your team *`. The only difference between the ranks are the lengths they last (Dux and above don't expire). So `Optio` would last for two months and then the price of that would be deducted from any further full purchase prices.

**Comment by lanenavlogs** [comment]
y por que antes si me dejaba escoger y ahora no y ni si quiera me deja
entrar en el servidor

2016-05-29 20:33 GMT+02:00 Andrew notifications@github.com:
