### ISSUE TITLE
Arrows deal significantly more damage in 1.9

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2476]
I was surprised this wasn't an official issue yet, but just to formalize it and maybe gather some specific information on this issue, I'll make one.

Bows deal substantially more damage to players in 1.9 than in 1.8. This is not inherently a bad thing, but the issue is that every single map on OCN has armor balanced around the previous damage system. Giving players better armor isn't the best idea because that could cause unwanted consequences for melee balance. Giving players a lot of projectile protection is bad because the protection by the enchantment is incredibly random, and randomness is usually a bad thing. Not to mention, applying these changes would take ages to every map in the rots, let alone the repo. 

The bow damage should definitely be reduced to pre-1.9 levels.

**Comment by guillevn** [comment]
It's not that arrows do more damage, but that armor is weaker now. The damage arrows deal without armor is the same, it only increases (for 1.9) when having pieces of armor on (when compared for the same pieces of armor in 1.8). But yeah, it should be fixed.

**Comment by MarcRoizman** [comment]
Fixed - https://oc.tc/forums/topics/5771a289c296357a3e000025
