### ISSUE TITLE
Map Makers can't pick teams on their maps

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2478]

**Comment by itsmartin** [comment]
Is the mapmaker flair also not appearing?

**Comment by ghost** [comment]
The flair was appearing last night at least, but if the player has no donor rank they are in with the rest of the users, when I assume they should be above them?

Also, #2352 is probably related?

**Comment by GoldenOre** [comment]
The flair does appear.

**Comment by jedediah** [comment]
fixed
