### ISSUE TITLE
Not being able to spawn on EU mini server (dracula)

### ISSUE THREAD

**Issue by Joop159** [OvercastNetwork/Issues#2480]
This happened on 01-06 17:20 CET, EU server.
The server was succesfully cycled, but the map Dracula could not be played, because the players could not spawn.

![2016-06-01_17 14 41](https://cloud.githubusercontent.com/assets/7500360/15715082/79f042c6-281d-11e6-808b-17a8b980606b.png)
![2016-06-01_17 15 01](https://cloud.githubusercontent.com/assets/7500360/15715083/79f1486a-281d-11e6-898f-9cb19a355b57.png)

The text means: "you are respawning as soon as possible"
I have not seen this on any other server yet.

**Comment by Pugzy** [comment]
I don't believe this is a map bug, maybe the logs will help find the cause.

**Comment by jedediah** [comment]
fixed
