### ISSUE TITLE
Map Update: Acear II

### ISSUE THREAD

**Issue by nintendoboy11** [OvercastNetwork/Issues#2482]
Hello,
I've fixed some things for this map and would like it to be updated.

You can see all of the files [here.](https://www.dropbox.com/sh/it4u9snz7ixldd5/AACvtSLtng8qYjdgZugHsXcVa?dl=0)

**Comment by Pugzy** [comment]
@nintendoboy11 please make sure the files you upload are correctly named.

Please refer to https://docs.oc.tc/guides/packaging/compiling_releasing

**Comment by samthecat** [comment]
@nintendoboy11 Also, the correct dimensions for your `map.png` file are `290x246`
Your current dimensions are `64x64`

Because there was no original `map.png` from the old version of the map, I've made one for you.

**Comment by GoldenOre** [comment]
@samthecat  I think you forgot to update the map.png 

https://gyazo.com/e214fc4576a60c6a1566b2783f55a330

https://oc.tc/maps/acear_ii

**Comment by samthecat** [comment]
@GoldenOre I swear I updated it, haha. Fixed
