### ISSUE TITLE
Map update: Ultra Twizz 1.3.1

### ISSUE THREAD

**Issue by 3Each** [OvercastNetwork/Issues#2483]
We updated Ultra Twizz! We added fences near spawn so players don't just run out of spawn and into the void. Players were also able to glitch the wool from one wool room into the other somehow, but it's fixed now.

Version 1.3.1

[Download](https://www.mediafire.com/folder/zf74iy4c4d9wg/Ultra_Twizz)

**Comment by Pugzy** [comment]
@3Each You need to make sure you bump the version number when you update the map.
