### ISSUE TITLE
Map Update - A Journey Through History

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2487]
Edited the lava parkour

https://www.dropbox.com/s/5cbu1x58c667e2r/History%20Rush%20Map.zip?dl=0

**Comment by Pugzy** [comment]
@GoldenOre You need to make sure you update the maps version when you make updated.

You should also try and follow the tabbing conventions found [here](https://oc.tc/forums/topics/5674a2ca5f35b90338000583).

The map should also be pruned after an update is made.

**Comment by GoldenOre** [comment]
I'll be sure to change the version in the future. I didn't know a map would have to be pruned after an update was made on a mapdev server.
