### ISSUE TITLE
Structures not appearing on Plunge Cavern

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2491]
![2016-06-08_16 55 58](https://cloud.githubusercontent.com/assets/12920658/15902457/eabebcee-2d9f-11e6-9966-e3f45f0ed931.png)

Didn't appear on the first level. No idea why.

**Comment by AnthonyTag** [comment]
As far as I'm aware, due to recent changes to how random structures are meant to work, the Plunge game type is unable to work - at least in it's current form. Closing for now. If I'm mistaken this shall be reopened.
