### ISSUE TITLE
Text on signs turn to gray.

### ISSUE THREAD

**Issue by Pugzy** [OvercastNetwork/Issues#2493]
After writing text on a sign (exit the sign) the colour will be formatted to gray.

![](http://i.imgur.com/84RFS7x.png)

Server tested on: Capture1 US.

**Comment by Pablete1234** [comment]
Note: it's not gray, it's white.
It's fixed in latest bungee cord [OvercastNetwork/BungeeCord@a376970](https://github.com/OvercastNetwork/BungeeCord/commit/a3769705794be231e0fad125a38a88e27c31b230) (but seems not to be deployed yet, as /bungee says it's still not updated)

**Comment by Pablete1234** [comment]
![image](https://cloud.githubusercontent.com/assets/11789291/18237385/f8ad9a24-7330-11e6-8e3b-3719a90942d2.png)
