### ISSUE TITLE
Most arcade maps aren't in the arcade maps section

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2494]
Most of the arcade maps in the rots don't appear on https://oc.tc/maps/gamemode/arcade

**Comment by mitchts** [comment]
The ones that are missing just need `<gamemode>arcade</gamemode>` added to their XML

**Comment by mitchts** [comment]
Fixed in https://github.com/OvercastNetwork/Maps/commit/f3c6d639048ff623c2b6b1cf6ca01c42314f4f4b
