### ISSUE TITLE
Can not join empty slots on 4 team maps

### ISSUE THREAD

**Issue by Seode** [OvercastNetwork/Issues#2497]
I don't know if it's specifically a 4 map problem but it happened on Battle Ecliptica 2. Blue team had one extra slot (3 out of 4 players) and none of the players in obs could join. Doing /join would send them to the lobby. https://youtu.be/D1z0vuWKIEA <- video for what I experienced.

**Comment by samthecat** [comment]
Mini servers no longer use the queue system.
