### ISSUE TITLE
Website Online Users List Bug

### ISSUE THREAD

**Issue by cak-e** [OvercastNetwork/Issues#2499]
So, I noticed that there is a bug in the website where when seeing online users, the account "OvercastReport" is shown in the same list with normal users. I may be wrong, but I believe since the rank it has, it should be seperated, and/or not shown because it technically isn't a user.

**Comment by cak-e** [comment]
EDIT: added a screenshot

![bugwithnamelistonocnwebsite](https://cloud.githubusercontent.com/assets/18396276/15993733/34feef5c-30bd-11e6-8cc7-431e507a6963.PNG)

**Comment by Pugzy** [comment]
Ranks can have different display priorities and the `Official Newsletter` one has the same priority level as a regular user hence they are displayed in the same location. Although the account isn't a player it is still a real account that needs to login to post the report.

**Comment by itsmartin** [comment]
Yeah, this isn't really a bug, it's just a side-effect of the way the ranks are sorted.
