### ISSUE TITLE
When killed with an item in your offhand, you respawn with that item in your "Boot armor slot" (Titan)

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2506]
![2016-06-18_08 29 47](https://cloud.githubusercontent.com/assets/8964867/16171321/4d9f9912-3531-11e6-8cf2-3b914c03381f.png)
I suppose this happens because the map was made in 1.8 or lower and did not include the 1.9 off-hand feature. Not sure if it happens to every map with keepinventory, but this is the only one I found so far.

**Comment by Pugzy** [comment]
As a side note the bow is on `itemkeep` so when the plugin gives the item back to the player it places it in the wrong slot.

**Comment by jedediah** [comment]
fixed
