### ISSUE TITLE
Rift and Necro villagers (and baron) do not spawn

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2507]
So I made this issue a while ago, and was told it was intentional, that the map maker removed them (on Rift).
https://github.com/OvercastNetwork/Issues/issues/2431
Considering this is what happened on Necro, I feel like this is more so a spawning bug with 1.9 mechanics. Plus, the Baron on Rift does not spawn, which I'm not sure why the map maker would remove.
https://i.gyazo.com/cbd326c4883afa55955be8f0bdb5ad69.png

**Comment by Qixit** [comment]
I will try and organise a temporary fix for this, as the villages are still there, just invisible. This bug is currently being fixed anyway so it may be better to wait. https://bugs.mojang.com/browse/MC-65040
