### ISSUE TITLE
Mini02 is to the left of Mini01 in the new server selector.

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Issues#2510]
Title.

It's a bit off putting, and the two should be switched.

**Comment by Pugzy** [comment]
This is intentional however I can understand where you're coming from.

The idea was that the mostly open and used servers would be to the top corners of the selector.

**Comment by master00ofdsiware** [comment]
The thing is, Mini01 and Mini02 generally have different playercounts at different times. It's not like Mini01 always has more players.

Switching Mini01 and Mini02 would bring no harm, and it would look a bit better.

**Comment by MarcRoizman** [comment]
Maybe you could keep 1 in the corner and put 2 below it?

**Comment by ghost** [comment]
Fixed now 
<img src="https://i.gyazo.com/b0230d5e027cc8dda31d5202036a7ecf.png">
