### ISSUE TITLE
All revisions are "Not deployed."

### ISSUE THREAD

**Issue by WesJD** [OvercastNetwork/Issues#2511]
On https://oc.tc/revisions, hovering over any revision number says it's not deployed even if it is.

**Comment by itsmartin** [comment]
Fixed.

**Comment by ghost** [comment]
Pretty sure it's still there isn't it?

**Comment by itsmartin** [comment]
@elephantLocator I'm not seeing it

**Comment by ghost** [comment]
@itsmartin hover over commits 16-20 on first page of web revisions, and all commits on subsequent pages.
