### ISSUE TITLE
Puddin' Pops score glitch 

### ISSUE THREAD

**Issue by Joop159** [OvercastNetwork/Issues#2515]
On the map Puddin' Pops (v1.2.1) you can score without returning to the spawn platform. 

**Steps to reproduce**
Run from the spawnplatform (platform 1) to the end (platform 2) where you will receive the 'Puddin pop'. And then, just walk of platform 2 into the void, while staying close to the platform. You will be teleported to platform 1 and you will have a scorepoint. This is what I mean: https://www.youtube.com/watch?v=olRtYK6tf8Q&feature=youtu.be

This glitch is present on the US and the EU server.

**Comment by MarcRoizman** [comment]
You should remove this from the rot for now since the bug essentially breaks the map.
