### ISSUE TITLE
A way to fix unneeded posts or ones breaking the rules

### ISSUE THREAD

**Issue by WesJD** [OvercastNetwork/Issues#2518]
I had an idea where people could downvote a post and once it gets to a certain amount of downvotes, hide the post and be put in a queue for staff members to check it out and take the necessary actions. 

I'm not sure if this would be a good idea, but if it's unhidden you aren't able to downvote it anymore.

**Comment by itsmartin** [comment]
Thanks for the suggestion. Post flagging is a feature we would like to implement in the future. However, this issue tracker is meant for bugs, not suggestions, so closing this issue.
