### ISSUE TITLE
Anathema has no way to power brewing stands

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2521]
I know this is kinda silly since this map isn't in any rotations, but during the Mega event, Anathema was played and brewing was impossible. The map has brewing supplies in a chest, but no blaze powder or rods so that you can't brew strength. As of 1.9, brewing stands require blaze powder as "fuel" to operate however, so no brewing can be done. 

I'm not sure whether you want to solve this by putting blaze powder in the map and allowing strength, or just removing the brewing stuff altogether.

Not sure if any other maps utilize brewing, but you could also see about going the plugin route and changing PGM to autofill any brewing stands on OCN with blaze powder that can't be taken out.

**Comment by samthecat** [comment]
@jedediah

**Comment by Pugzy** [comment]
This could either be fixed by a Map Developer adding in the required materials or two new tiny modules.

One for `auto-lapis` and another for this `auto-powder`.

**Comment by samthecat** [comment]
- 2 blaze powder can now be found in the upper left corner of all player's inventories.
-  You also receive 1 blaze powder as a kill reward.

![image](https://cloud.githubusercontent.com/assets/10585916/16787897/0ed10946-486e-11e6-9e51-034eeb3b3375.png)
