### ISSUE TITLE
Bubble Brawl issues

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2523]
The subtitle text (Knock all opponents out of the water sphere and be the last person swimming!) on both Bubble Brawl: Arena and Bubble Brawl: Turbine is too long to fit on the screen, so the beginning and end of the subtitle gets cut off.

The other issue is that death messages look kinda ugly (http://i.imgur.com/jaBr0Er.png). There are a number of ways you could change this, but I think somehow having the death message show who actually knocked them out would be the best way.

**Comment by Pugzy** [comment]
The first issue is easy to solve the second one not so much.

Maybe applying a really high downwards velocity would make them die of fall damage and the knocker would maybe still get the kill.

**Comment by MarcRoizman** [comment]
I was thinking you could put everyone on half a heart, give everyone a high level of weakness so they don't deal damage, and then enable fall damage so any fall kills them

**Comment by samthecat** [comment]
Fixed.
