### ISSUE TITLE
Remove deleted(hidden) topics from "My Posts" and "My Topics"

### ISSUE THREAD

**Issue by AustinLMayes** [OvercastNetwork/Issues#253]
![screen shot 2013-06-14 at 2 07 16 pm](https://f.cloud.github.com/assets/4269021/656205/b71e4d4e-d525-11e2-9355-d3237d3a8ec8.png)

__How to fix__
Add ```Forem::Topic.where(:hidden => false)``` in those variable definer lines in the controller.

**Comment by TiTo-418** [comment]
Implemented a few weeks ago

**Comment by Electroid** [comment]
Nah. If you can hide your own stuff you should be able to see them.
