### ISSUE TITLE
Golden Drought apple chest is useless in 1.9+

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2531]
The apple chest on Golden Drought used to be useful because you could craft a notch apple, but they are no longer craftable in 1.9+. Notch apples should get their own custom recipe added to the map as it used to be, with 8 gold blocks around an apple.

**Comment by ghost** [comment]
![screenshot_111](https://cloud.githubusercontent.com/assets/11008016/16826235/1606ec28-4952-11e6-868e-09b6f6f70710.png)
You should be able to craft it

**Comment by MarcRoizman** [comment]
Oh, last time I played this I don't think this was implemented. Sorry ;p
