### ISSUE TITLE
Map update - Coral Reef

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2533]
https://www.dropbox.com/s/vw9qz5jquu1d9jg/Coral%20Reef%20DTM%202.zip?dl=0

**Comment by samthecat** [comment]
Your `map.png` file is incorrectly sized, please resize your image.
The correct dimensions are `290x246`.

**Comment by GoldenOre** [comment]
https://www.dropbox.com/s/c0o0mshvs9xd93v/map.png?dl=0
