### ISSUE TITLE
Map update - Coral Reef

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2536]
there shouldnt be anything wrong with it this time

https://www.dropbox.com/s/olmcmooy8xlxstm/untitled%20folder%202.zip?dl=0

**Comment by samthecat** [comment]
@goldenore You're going from `1.1.1` to `1.0.4`?

**Comment by GoldenOre** [comment]
Sorry, I updated the wrong xml. New DL: https://www.dropbox.com/s/6zsxvif69s5yez2/untitled%20folder%202.zip?dl=0
