### ISSUE TITLE
Map Update - Ethereal 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2537]
Changes:

Protected Block Spawners
Changed Proto from 1.3.5 to 1.4.0 
Added more blocks to spawn kit
Added boat to spawn kit
Added Iron Blocks
Added Diamond Blocks to middle
Changed iron beacon to gold
Changed UUIDs
Removed Portals
Updated Version to 2.0.1

Download: https://www.dropbox.com/s/iaxxjjzgck9nojv/Ethereal%202.0.zip?dl=0

**Comment by samthecat** [comment]
@goldenore The XML has a huge amount of filters that don't exist and it's throwing a ton of errors.

**Comment by GoldenOre** [comment]
Don't worry about it, it really doesnt matter anymore.
