### ISSUE TITLE
Map Update - Chinatown

### ISSUE THREAD

**Issue by xCand** [OvercastNetwork/Issues#2538]
The map was laggy for some due to signs being in the flooring of the spawns. After enough people pestering me about it, I finally got around to fixing it.

http://www.mediafire.com/download/bfr5fgzdhh5wf15/1db66b88-a95d-4a17-bee6-607cf0061ef5-2+12.17.54+PM.zip

**Comment by samthecat** [comment]
@xcand What version are you updating too? It still says `1.0.0`

**Comment by xCand** [comment]
My bad, 1.1.0
