### ISSUE TITLE
Fix map duplicate in repo

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#2539]
My map Pumpkin Spice Latte is loaded two times. 
1 time as "Pumpkin Spice Latte" and 1 time as "Pumpkin Spice Latte FFA". Both maps are the same but Pumpkin Spice Latte FFA is not used and therefore a duplicate. 

https://oc.tc/maps/pumpkin_spice_latte_ffa < please remove it from the repo.
https://oc.tc/maps/pumpkin_spice_latte < please do **not** remove from the repo

**Comment by mitchts** [comment]
There is only one copy of the map in the repository. The issue is that when the original map was renamed to its current, it was renamed incorrectly. This caused the database to think that they're two different maps, rather than the same thing. We are unable to remove the duplicate map page.
