### ISSUE TITLE
Map Update Rush Wars 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2541]
https://gist.github.com/GoldenOre/370b7b506474a8c047782266beb72b9a

**Comment by samthecat** [comment]
Can I get a changelog?

**Comment by GoldenOre** [comment]
Added another author, removed power on bows, longer time limit, and something else that i forgot

**Comment by Qixit** [comment]
Could be a repeat of #2552 #2547 .

**Comment by Qixit** [comment]
Remember not to indent after `<map>` 😋  @goldenore
