### ISSUE TITLE
Ghost Spleef needs a survivor time result

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2542]
Currently in Ghost Spleef, there's no time result, so if the match runs out of time with 2 Ghosts and 1 Survivor, the ghosts win because they have more players. It needs a Survivor time result.

**Comment by mitchts** [comment]
https://github.com/OvercastNetwork/Maps/commit/4a5d0a7918081853fb7ac03e7b4f495ce76e73f0
