### ISSUE TITLE
Wools on Tetrad can be acquired through item frames in spawn

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2546]
Games are ending in <30s because the wool in the item frames on the wool monument can be shot and used in the monument. The item frames need to be removed ASAP because this is really broken.

**Comment by ElliottWhyman** [comment]
Nuked from rot, pending fix

**Comment by mattarnold98** [comment]
Cubist fixed this, the map is back in the rot.
