### ISSUE TITLE
Explosive Vengeance's Scoreboxes Do Not Work

### ISSUE THREAD

**Issue by Seode** [OvercastNetwork/Issues#2548]
Entering a scorebox teleports you back to your spawn but your team does not get any points. I'm assuming the scorebox is supposed to give points.

**Comment by Qixit** [comment]
- Void filter breaks when changing `<filters>`.
- Scorebox code plays up when structure of line/s is changed.
- Moving `<filters>` to another location in XML only fixes one team's scoreboxes.

No time to fix this at the moment. I have reverted my changes as well.

**Comment by mitchts** [comment]
Portals and scoreboxes appear to be working correctly.
