### ISSUE TITLE
Build parkour: always in fly

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2549]
For all three parts of the map. Pretty major bug there.

**Comment by Pugzy** [comment]
I've labeled this as a map bug however this was probably created due to a plugin change.

**Comment by mitchts** [comment]
Definitely a map bug as I can't actually see anything that removes the flying ability. Was probably something I forgot to include when implementing dynamic filters into the map.

Edit: Actually, I'm not too sure. None of the kits that use dynamic filters are being applied, so there might be more to this bug than I initially thought.

**Comment by mitchts** [comment]
https://github.com/OvercastNetwork/Maps/commit/1eb86dd77933c8e1cfdbcc160ec8ef4f43d1f343
