### ISSUE TITLE
Filter Matches Button on oc.tc/matches is unordered.

### ISSUE THREAD

**Issue by TehZaner** [OvercastNetwork/Issues#255]
<b>The issue:</b>
When you click the button a large dropdown menu opens that goes very far down the page (With the GS Servers) The list may have an order (last played match or similar) but I couldn't make that out.

<b>Possible Solutions:</b>
Order List into categories

<b>Steps to Reproduce:</b>
oc.tc/matches
Click the button "Filter Matches"

Also, it includes lobby servers.

**Comment by itsmartin** [comment]
This was fixed a while ago.
