### ISSUE TITLE
Update Pumpkin Spice Latte to 1.2.5

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#2553]
Only XML updates:
- Changed the name to "Pumpkin Spice Latte: Venti"
  https://gist.github.com/stormer1267/46e8ce20d863a4b0951cb6bdd836de94

**Comment by mitchts** [comment]
For future reference, you must add a [slug](https://docs.oc.tc/modules/main) to the XML in order for it to retain previous ratings and matches.
