### ISSUE TITLE
Load Chimeric II

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Issues#2561]
Chimeric II was completed in terms of everything - gameplay, and XML. It would be nice to be able to play it on public matches during the final week of Overcast, and to show that those three weeks of residency was well spent.

I have attached the necessary files in the event that the originals are not easily accessible for you at the moment. As it is CTW and DTM, the proper place is the Mixed folder.
[Chimeric II.zip](https://github.com/OvercastNetwork/Issues/files/441243/Chimeric.II.zip)

**Comment by Qixit** [comment]
Is this map already in the map repository? @master00ofdsiware

**Comment by master00ofdsiware** [comment]
@Qixit No, it is not.

**Comment by master00ofdsiware** [comment]
It was the map that I fixed during map residency.

**Comment by Qixit** [comment]
You can't request a map to be added to the Map Repository, unless it's a seasonal makeover version.\* Submit your map on the forums and a Map Developer will view it and respond accordingly.
