### ISSUE TITLE
UUID XML Update for 11 maps

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2566]
All I did was switch out my old account's uuid for my new one.

Paradiso, https://gist.github.com/GoldenOre/cc624455752e314ff8b1a8017de8225f

Pompeii the giant ffa not the micro, https://gist.github.com/GoldenOre/6a893ae01db9f6106dd6c9cb0add600a

Sweet Tooth, https://gist.github.com/GoldenOre/d2e36af005aa3c2be7639187223a12ae

Sore Teeth, https://gist.github.com/GoldenOre/9f6593f108323175f0208c4126aa2cbd

Chocolate Diamonds, https://gist.github.com/GoldenOre/815d842e9e5b66e2c193ec03b353d61c

The Last Sunset II, https://gist.github.com/GoldenOre/454271fda1bf281795f0db3dd81903c6

A SpOOky Sunset, https://gist.github.com/GoldenOre/bb910fb5b6c785d93ff59323900a5fab

Ethereal, https://gist.github.com/GoldenOre/603eaf92d6a7f9a7e1623f6424f28671

SpOOky Diamonds, https://gist.github.com/GoldenOre/18c1d10e88675a3dd935819642f5d752

Snowy Diamonds, https://gist.github.com/GoldenOre/7f03e73c3061dc510467062d10a1d1e8

School's Out, https://gist.github.com/GoldenOre/1d9f5ae8845c5805e6b474dcd4344563

**Comment by Pugzy** [comment]
There has to be a command to do this in Git, I'll check it out later.

**Comment by Pugzy** [comment]
Done :+1:

**Comment by GoldenOre** [comment]
Thanks!
