### ISSUE TITLE
TNT license message appears after every kill

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2570]
I get granted a tnt license every time I kill someone. I revoked it this morning, that could be the cause.

Edit: It happened over mutiple servers, but once the server I was on restarted it stopped

**Comment by Pugzy** [comment]
The server restarting may fix this, does this still occur? @elephantLocator

**Comment by ghost** [comment]
It happened over multiple servers when I switched, as well as logging out in the middle, but once I was on a server that restarted it stopped.
