### ISSUE TITLE
Stonehenge spawn issue

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2572]
![screenshot from 2016-09-04 16 16 02](https://cloud.githubusercontent.com/assets/12920658/18231836/ff0aba12-72ba-11e6-9519-4fdc49b3d439.png)
^ spawn inside a thing get stuck

**Comment by samthecat** [comment]
are you kidding me, I thought I fixed them all

**Comment by ghost** [comment]
I thought so too :disappointed:

**Comment by Pugzy** [comment]
@samthecat go into gamemode 3 and have a quick fly around to spot them 2 high holes.
