### ISSUE TITLE
Arcade and Micro Maps don't have player count

### ISSUE THREAD

**Issue by sovrynn** [OvercastNetwork/Issues#2576]
On the oc.tc/play page, none of the Arcade and Micro maps have a max player count, so for example it says: 

Arcade1(US) 9/0 players

When it should be something like

Arcade1(US) 9/10?? players

EDIT: I just double checked and Creep Slap displays a max player count of 8, so maybe it's just that new map authors are forgetting to include a max player count when they upload their map or something like that.

**Comment by Pugzy** [comment]
Both these servers/gamemodes have a queue system which allows the max players to expand.

**Comment by mitchts** [comment]
It's actually due to the maps using free-for-fall which is covered by https://github.com/OvercastNetwork/Issues/issues/2278.. it has nothing to do with the queue system
