### ISSUE TITLE
Arrow particles have color issues

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2577]
The particles that were recently added to arrows are redstone particles, by default minecraft uses therse to add particles to redstone dust, and it's done with a non-set RGB (0), so if any of the 3 (red, green or blue) value is 0, minecraft will default it to the RGB for redstone.

The easy fix is just to use a very small number so that it isn't 0, and therefore minecraft doesn't understeand it as "use the redstone r/g/b here", instead understeands it as "r/g/b 0".

For testing, colors that are very noticable are: black, dark blue, dark green and dark aqua, they have a 0 on red, that will be bumped up, so dark aqua looks pink, and black just looks exactly like redstone.

**Comment by xSelfie** [comment]
Hello? any response?

Also can you make a toggle for this please

**Comment by Electroid** [comment]
Fixed.
