### ISSUE TITLE
Arrows don't work as usual

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2578]
I don't really know how to explain, but probably since they have been changed today something has been messed up, when you shoot with a bow they feel different, like the direction they take, I don't know you can just compare them to how they worked before and something is wrong.

**Comment by Qixit** [comment]
A video to accompany this issue would be useful. Did you happen to use a texture pack before the change? If so, perhaps the change from different arrow particles is throwing you off. I for one have not noticed any issues with arrows.

**Comment by 2000thehecf1** [comment]
@Qixit Actually it might be the resourcepack, because looking to a video recorded some days ago it seems pretty similar, but I'm not sure yet. I'm closing this for now as it looks like no one else is having this issue and it might just have been an optical illusion.
