### ISSUE TITLE
In-Game custom potions have acquired an extra effect which restores their function to vanilla

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Issues#2581]
After OCN converted to 1.9, all in-game _custom_ potions have acquired an extra effect to their existing set of effects.

E.G. on Totally War II there is a chest full of custom Invisibility potions which are originally meant to last 10 seconds. Because of update these invisibility potions now have an additional effect which makes them last for 3 minutes (just like a vanilla invisibility potion from the Creative Menu would give you).

(see the top effect, excuse for the spanish version)
![2016-09-05_20 10 34](https://cloud.githubusercontent.com/assets/8007420/18255875/7afa78a8-73ae-11e6-93eb-82314417804d.png)

Haven't found other maps that also have broken custom potions stored in chests, but if any are located the bug is at least known.

**Comment by jedediah** [comment]
Fixed
