### ISSUE TITLE
Emoji previews don't show up with new text editor?

### ISSUE THREAD

**Issue by sovrynn** [OvercastNetwork/Issues#2586]
Before, if you typed a colon and then started typing something, emoji preview would pop up, for example :heart: or :+1: -> ": heart :"

However with the new text editor these don't seem to show up, when you're making a forum post.

**Comment by jacobbearden** [comment]
@hjongh by "new text editor" are you referring to the code editor added by [Overcast Plus](//github.com/jacobbearden/overcast-plus)?

**Comment by Pugzy** [comment]
This seems to be working fine. Are you using the Overcast+ extension which already has an issue for this.

https://github.com/jacobbearden/overcast-plus/issues/14
