### ISSUE TITLE
Proximity doesn't update on CTF maps

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2587]
I think it's happening since the serverwide crash, and it leads to unfair ties.

**Comment by Pugzy** [comment]
@2000thehecf1 is this still an issue?

**Comment by 2000thehecf1** [comment]
@iPGz Can't confirm if it is right now but it still was like 2 days ago so probably yeah

**Comment by Pugzy** [comment]
Closing this in favour of https://github.com/OvercastNetwork/Issues/issues/2702
