### ISSUE TITLE
Two Tier woolroom is compeletely unbreakable (even cobwebs)

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Issues#2593]
Not sure if intended but I don't think so as in the previous versions of the map it wasn't.

**Comment by Pugzy** [comment]
@samthecat was this indented?

Also it looks like the map needs some block 32 adding around the highlighted areas.

![](http://i.imgur.com/WdpIt0Z.png)

**Comment by samthecat** [comment]
Cobwebs should definitely be breakable..
