### ISSUE TITLE
Server selector could be improved

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2595]
Server selector has been changed to include new cool looking player skulls:
![](https://i.imgur.com/Id4lB5W.png)

The problem is the number of players blocks the view of the face, a good solution would be to just change the skins, so they have the face on a side, so the face would appear in the left side of the skull, so the number wouldn't block it.

**Comment by itsmartin** [comment]
I don't think this fits here really, since it's a feature suggestion, not a bug.

Feedback will be passed on to the mapdev team in any case.
