### ISSUE TITLE
[BUG] Player displacement?

### ISSUE THREAD

**Issue by ItzCal** [OvercastNetwork/Issues#2599]
https://www.youtube.com/watch?v=ewkiCtgXGYs

On my screen he is hitting me when i'm not near him but on his screen i'm am probably standing still 2 blocks infront of him.

This only happens on capture1 and only on OCN

halp xd

**Comment by ItzCal** [comment]
Just realised that the link doesn't work, how can I show you the video?

**Comment by samthecat** [comment]
@ItzCal It's linking to a github page, are you copying the correct URL?

**Comment by ItzCal** [comment]
Yes, it's the url from the youtube video

**Comment by ItzCal** [comment]
@samthecat ahhhh, i've fixed it now, I was using the "add a link" button xD

**Comment by samthecat** [comment]
This looks like lag to me, not a bug.
