### ISSUE TITLE
Update Acear II to 2.3.0

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#2600]
Prettied up the XML
- Put the <tip> tag on one line instead of 3.
- Updated all the coordinates so that the lowest would be at min and
  the highest at max.
- Updated the <kits> tag to make use of a parent kit to make it easier
  to edit in the future.

Updated file:
https://github.com/stormer1267/MapsXML/blob/master/Acear%20II.xml

(nice get with the #2600th issue ;) )

**Comment by Pugzy** [comment]
The `min/max` coordinates thing really isn't something that needs to be done, if it worked the first time then I see no reason to change them around.
