### ISSUE TITLE
Update Barr to 1.2.5

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#2601]
Updated XML
- updated regions so that the bridging zones are now correct 
- fix the pork

Map update: 
Remove half of the cobwebs to prevent people from using them to get across. 

Updated Download link:
https://www.dropbox.com/s/f41ixwrh5i22v2o/Barr%20DTC%20v1.2.5.zip?dl=0

**Comment by samthecat** [comment]
You forgot to close a `<regions>` tag, be careful :P
