### ISSUE TITLE
Impossible to enchant due to missing lapis

### ISSUE THREAD

**Issue by hunter98789** [OvercastNetwork/Issues#2604]
On the maps Fairy Tales: A Tale or 2 and Mushroom Gorge (I might be missing a few). Enchanting was a major part of the map. But since 1.9, you need lapis to enchant, a feature that was not present before the update. Because of this, you cannot enchant on either map. There are 3 simple fixes to this problem: 

1) Make Lapis ore mineable. All you would need to do is add a few of the ores to the rooms in Mushroom Gorge, or put it underground (either in the middle islands or the spawn islands) on Fairy Tales.

2) You could include stacks of it in chests. On both of these maps, there are convenient locations for the ores to go. On Mushroom Gorge, they could go in the pre-existing chests next to the enchant tables. On Fairy Tales, they could go in the jukebox chest inside of the obsidian "vaults". In the vaults, you get the enchanting tables, so you could not miss the lapis.

3) Lastly, you could do what larger servers do (Mineplex, Hypixel, ect.). The tables are ALWAYS full with an unlimited source of lapis, so you cannot run out. When a player uses the lapis, the table replenishes to exactly 3 lapis inside. No more or no less lapis will ever be in the tables, so you cannot run out. Breaking the chest will not drop the lapis. 

Closing remarks: This glitch is hindering the gameplay of these 2 maps. A barrier between someone with full protection 1 armor and sharpness 1 sword held a large advantage against a full iron opponent, and it provided a easy time advantage that added a whole different aspect to these maps. With any of these 3 simple solutions, this problem could be easily solved.

**Comment by Pugzy** [comment]
On Fairy Tales 2: A Tale or Two every two kills the player gets a single lapis. I can do the same to Mushroom Gorge when I'm able to test.

**Comment by hunter98789** [comment]
Thank you, I was not aware this solution occurred on fairy tales. I cannot write more, as I am on my phone.
