### ISSUE TITLE
Splash page layout issue on big monitors

### ISSUE THREAD

**Issue by jedediah** [OvercastNetwork/Issues#2606]
<img width="2556" alt="screen shot 2016-09-27 at 8 59 07 am" src="https://cloud.githubusercontent.com/assets/35292/18895146/52b7d62c-84e5-11e6-9067-8134b4ebfbe6.png">

Background images are not wide enough

**Comment by itsmartin** [comment]
https://github.com/OvercastNetwork/Web/commit/697117437e137dfb7d593a671e93c09ac02e7478
