### ISSUE TITLE
/vi command to view a player's inventory

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/Issues#261]
## The issue

Sometimes it's not easy to right-click on a player to view their inventory. It would be useful to have a command to do the same thing.

## Suggestion

`/vi Player` - if you are an observer, opens Player's inventory, as if right-clicked.

(/vi suggested for similarity with AutoReferee)

This would be particularly useful for moderators checking for things like nofall, as it sometimes takes several seconds to reach a player and click on them, making it harder to immediately check for damage.

**Comment by Electroid** [comment]
Done.

**Comment by TiTo-418** [comment]
What's the command?
