### ISSUE TITLE
Amount of Alerts not shown correctly

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2614]
If you have one alert you see a 5 and if you have two 6 and probably so on.
http://imgur.com/a/aulYC

**Comment by itsmartin** [comment]
This seems to be affecting a few people, not sure how to reproduce it.

**Comment by MarcRoizman** [comment]
A solution I've found is to hit "Mark All Read" on your alerts page, this resets it and it works properly.

**Comment by itsmartin** [comment]
Hopefully fixed, let me know if you see it again.
