### ISSUE TITLE
Crenel V1.1.1 (only XML)

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2615]
Minor update to the XML

https://gist.github.com/matic0basle/7e038ecb8611bbea3d3d58fa0db77780

Change Log:
- Add tips for map information
- Add kill streaks

**Comment by Pugzy** [comment]
You've changed the entire protocol, this is a little bit more than a "minor update".

The indentation doesn't follow the typical conventions and for ease of use the gist can have a `.xml` type.
`<apply block="deny-all" />` -> should be `never`, doesn't specify a region ("everywhere") 
For your kits, `name="blue-kit"` -> should be an ID (proto 1.4.0).

The crops on the map have seem like only a few chunks are full grown, is this intended?
If players shouldn't be able to edit the map then maybe `adventure` mode would be beneficial.

**Comment by Matic0B** [comment]
@iPGz The crops on the mal are all full grown as of update 1.1.0. They were broken back in the original version but that was fixed a couple days ago or at least, It should have been. I grown the crops. Players don't edit the map with the exception of opening chests and doors.

The proto used to be 1.3.6 but I figured there shouldn't be that many issues with updating since there isn't any filters. Stormer went through the XML and fixed some stuff, not sure if he checked if everything would be fine updating the proto.

You could use the proto 1.3.6 as it used to be but I am not sure if kill streaks work as intended. This should be the one with proto 1.3.6
https://gist.github.com/matic0basle/b348b3459c6dff22cdfeda256ffd461c

I'm not really that handy with XML but since its a simple map where theres no block breaking or placing, I figured it shouldn't be too complicated to bump up the proto without big mistakes. Thanks for the notifications

**Comment by Pugzy** [comment]
The previous version of the map also required pruning, more info can be found at https://docs.oc.tc/guides/packaging/pruning_chunks

You can download the latest version of your map for future updates from https://oc.tc/maps/crenel
