### ISSUE TITLE
SolitudeMC Halloween V1.3.6

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2620]
Change Log:
     - Update observer spawn
     - Update observer spawn kit chests
     - Decrease amount of ladders in spawn kit from 32 to 16
     - Add beacons and iron blocks to itemremove
     - Make beacons breakable
     - Replace torches with redstone torches
     - Change clouds from white to red
     - Replace fences with nether brick fences
     - Replace brown stained clay with soulsand
     - Add jack-o-lanterns
     - Remove torches
     - Add special halloween tip at the start
     - Magenta team is now Green
     - Add TNT as kill streak reward
     - Set TNT licensing to FALSE

Download available in submissions: https://oc.tc/forums/topics/57f3d87367d5227a7c000035

XML: https://gist.github.com/matic0basle/f1e416ed22cd70b46b3dc3b26692472e (included in dl)

**Comment by Pugzy** [comment]
@matic0basle Do the Halloween and regular version use a similar XML for the core functionality?
- Regions, Kits, Filters, Spawns, Objectives etc.

Like I said earlier, when creating a gist make sure you add the `.xml` to the name so it gets its fancy colour making it easier to read. Indenting should also be done for each module and the `<map>` element doesn't count towards this.

**Comment by Matic0B** [comment]
@iPGz Thanks for the reminder. Forgot about .xml. The core features are the same with the exception that the Halloween version uses Green team instead of Magenta on the original. Coords are the same, just changed magenta to green. So green armor in kits, green team tag for spawns etc.

**Comment by mitchts** [comment]
Make sure you use the correct bukkit name for items and adjust the kits for the team colour change next time.
