### ISSUE TITLE
Cake Wars 3 is really laggy

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2622]
I'm not sure why but whenever its set it takes about 5 seconds for the map to load before you can even move.

**Comment by Pugzy** [comment]
I'll take a look into this, not sure if there's anything I can do though. :)

**Comment by Pugzy** [comment]
Two things I think this could be related to, moving minecarts or the large amount of cauldrons used on the roof. Either way this maps is within the Testing folder so probably shouldn't be played anyway.
