### ISSUE TITLE
Map Update: Ethereal 1.3.0

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2628]
Change Log:

Added Iron Blocks
Removed Portals 
Added 2 diamond blocks to middle
Removed a few trees
Minor edits to terrain 
Added boat to spawn kit
Changed Kroest's UUID

Download: https://www.dropbox.com/s/1hhr7hql56zdrob/Ethereal%201.3.0.zip?dl=0

**Comment by JanPaulMosterdijk** [comment]
wowowowowow who said i agreed on these changes?!??!?

**Comment by Pugzy** [comment]
Made a few changes to the XML but other than that it was :+1: .
- Removed one layer of indenting to follow OCN conventions.
- Changed team names to not include the word "Team" (again conventions).
- Removed the `damage="2"` from the boats as it created a missing texture block/item.

Map download available from the oc.tc/maps page.

**Comment by GoldenOre** [comment]
Thanks!
