### ISSUE TITLE
Map Update Spooky Country to Version 1.0.1

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2630]
Download link: https://www.dropbox.com/s/fhdwtdhdpk3usgh/Spooky%20Country.1.0.1.zip?dl=0
Changes:
- slightly reduced nether bocks from 40 to 30
- Updated author and contributor list

**Comment by Pugzy** [comment]
Is this just a `map.xml` update?

**Comment by nigges60** [comment]
@iPGz Yes it is.

**Comment by Pugzy** [comment]
Updated, changed that block amount to 32 rather than 30, seems more logical.
