### ISSUE TITLE
Remove or modify the check for version type

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Issues#2635]
It is inconvenient that xml does not allow having a non-numeric version number. There would be no harm in allowing alphabetical characters, as long as it is clear that the version number should still be reasonable.

**Comment by Pugzy** [comment]
It's nice to have something consistent and the docs have always specified that versions should be semantic. 

The version numbers are used in several places, for example ratings on the website. In the form of `major.minor.patch` the latter does not create a new set of ratings whereas a major or minor will.

You may be interested in the `phase` element which allows you to select between `development` and `production`.

**Comment by master00ofdsiware** [comment]
Never mind, didn't know that the ratings page changed based on these version numbers.
