### ISSUE TITLE
You can bridge between woolrooms on Pumpkin Madness

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Issues#2640]
Since this map is in  the halloween rotations, this problem should be fixed.

**Comment by mitchts** [comment]
When did you experience this issue? Pretty sure I fixed this in https://github.com/OvercastNetwork/Maps/commit/fd89c220e61707d13bafb418e2d1f1cb924a5387 which was 17 hours ago.

**Comment by Pugzy** [comment]
This happened in the previous game, I can't remember if this was a thing back when I added the map or not.

**Comment by master00ofdsiware** [comment]
It was about an hour ago

**Comment by mitchts** [comment]
Should definitely be fixed now. https://github.com/OvercastNetwork/Maps/commit/1edbc3577cbf31b797390fdd66778af8fd1fecac
