### ISSUE TITLE
Arrows don't drop on Dynamo

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2644]
In both Dynamo and DynaboOo you spawn with a single arrow and a bow with Infinity so it seems understandable to have arrows on ItemRemove. The issue comes when you kill a woolcapper and they drop their diamond leggins, the wool, their op bow... but no arrows (the bow in woolrooms has Power but no Infinity). So in terms of fairness, you should be able to pick those arrows up and give them a taste of their own medicine with that Power I bow you just earned. Cheers.

**Comment by Pugzy** [comment]
@Brottweiler do you know if this is intentional?

**Comment by Brottweiler** [comment]
It is intentional, for same reasons as in the OP; you spawn with infinity bow. This is the case for many other wool maps too, like Ring Race.
