### ISSUE TITLE
Unable to break blocks in the Two Tier wool rooms 

### ISSUE THREAD

**Issue by blade00000009** [OvercastNetwork/Issues#2645]
There is cobwebs in the wool rooms of Two Tier and if you get stuck in you cannot get out easily and if there is someone shooting into the wool they can kill you because you can't break it nor place blocks to stop you from dying. So edit the xml so you can break blocks in the wool room.

**Comment by Pugzy** [comment]
https://github.com/OvercastNetwork/Issues/issues/2593
