### ISSUE TITLE
Spawning at ~y 800 on Databasin

### ISSUE THREAD

**Issue by BassamR** [OvercastNetwork/Issues#2656]
When spawning on Databasin, I sometimes end up spawning outside of the map and at very high y coordinates (around y 800), and then fall out of the world.

**Comment by mitchts** [comment]
You spawn at y `999`, but there is a portal 4 blocks below with the range of y `996` down to `980` which would catch you and teleport you to the appropriate spawn point or your class. These two regions have the same x and z coordinates for both the `min` and `max` which could mean if the player spawned on the very edge on the region and moved outwards, you would miss the portal completely. Best way to fix this would be to make the portal larger on the x and z axis, or make the spawn region smaller.

**Comment by Pablete1234** [comment]
@mitchiiii can't such portal just be an intersection of bellow 996 & above 980, and let everything else be handled by filters?

**Comment by mitchts** [comment]
@Pablete1234 That is also a possible solution, yes.
