### ISSUE TITLE
Potion effects are active during spawn freeze time

### ISSUE THREAD

**Issue by mitchts** [OvercastNetwork/Issues#2659]
When players spawn with the spawn freeze timer they are given the kit instantly which includes any spawn potion effects the kit has. The issue with this is that the duration of these effects are reducing while the players are frozen, so for maps that give resistance or regeneration immediately to prevent spawn killing or for spawn drops, they might not work. I can't think of any maps in rotation that this would affect, but I found that I died when I first spawned on Xi from the spawn drop.

**Comment by jedediah** [comment]
fixed
