### ISSUE TITLE
Pumpkin Madness - Region issues & Spawn exit

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2665]
1. Region issue preventing placing buttons on a part of the wall near wool rooms

![](http://i.imgur.com/ZisgI4p.png)

 2. You get spammed in chat when placing buttons on the wall at the wool room

When you place buttons on the wall you get spammed in chat that you may not enter that area. The wall is in the region for the wool room.

![](http://i.imgur.com/GbG8vpL.png)

 3. In the front spawn exit there are trap doors which you can open and block the exit. Just a slight inconvenience

![](http://i.imgur.com/WDscx2c.png)

**Comment by Pugzy** [comment]
First issue not "fixed" as this is logical due to the lanes shape.
