### ISSUE TITLE
Item mods affects Navigator and Team Selection menus

### ISSUE THREAD

**Issue by mitchts** [OvercastNetwork/Issues#2668]
![example_1](https://cloud.githubusercontent.com/assets/6386297/19880372/d8df3fa2-a050-11e6-905c-f9ad7c17fffd.PNG)
![example_2](https://cloud.githubusercontent.com/assets/6386297/19880374/d9d6d1ea-a050-11e6-9a3c-98cfed85c425.PNG)

**Comment by Electroid** [comment]
Fixed.
