### ISSUE TITLE
Map Update - Coral Reef 1.1.3

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2670]
Removed monument mode

XML: https://gist.github.com/GoldenOre/8d5bc084d9df9a67cff48aaf4cb64753

**Comment by Pugzy** [comment]
May I ask why you wish to do this? Are matches ending too sudden after the mode change?

**Comment by GoldenOre** [comment]
Yeah, most of the time it ends 10 seconds after the mode change.
