### ISSUE TITLE
Nicked players still showing in chat

### ISSUE THREAD

**Issue by BassamR** [OvercastNetwork/Issues#2671]
Not sure if this is a bug, but here it is: today i was playing with a nicked teammate (his real ign is pierrotwinner). Of course, he was nicked so normal players couldn't see his name, only his nick. But when he entered the woolroom and picked up the wool, his usual ign was written ("Lime wool picked up by pierrotwinner"). Before you say anything, I am sure he was nicked because his name was in strikethrough (he's on my friends list). What i'm trying to say is that his normal ign shouldnt appear on the chat. Instead, it should be "Lime wool picked up by (nick)". Screenshot: 

![2016-11-09_20 58 56](https://cloud.githubusercontent.com/assets/18619720/20147039/cecd117c-a6bf-11e6-92c8-1d97ff9991a8.png)

**Comment by Brottweiler** [comment]
You seem to have that player on your friend list since you can see his name in strikethrough, that means when they pick up the wool, or touch the core etc, you will see their name and not nickname. You, as their friend, will never see their nickname.
