### ISSUE TITLE
Stats are gliched in profile

### ISSUE THREAD

**Issue by hunter98789** [OvercastNetwork/Issues#2672]
If you go to a players stats, the section that says "Teams Joined" displays incorrect information. 
For instance, if you go to my profile, you will see this: https://gyazo.com/2e5200592c34f68a7bf9009998aedb3c

Although it says I have joined 7000 teams, I have never joined a team.
I do not know what stat this might be showing, all I know is it is inaccurate.

**Comment by jedediah** [comment]
That means teams in matches, not tournament teams.
