### ISSUE TITLE
Unum lana issues

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2677]
The map becomes impossible to end if both teams setup defenses. All the blocks you get is 16 clay and 8 glass, with no kill reward, this makes it very hard to make an skybridge, or rushing into the wool, as you run out of blocks very quickly. A kill reward, or a couple block spawners would fix the issue.

**Comment by Pugzy** [comment]
Blocks need adding as a kill-reward.

**Comment by MarcRoizman** [comment]
A gapple killreward would also make it slightly easier to end long stalemates, as it currently stands, you can kill multiple defenders, be on low health, and still not be anywhere near the wool.

Discussed here: https://oc.tc/forums/topics/581d1d575f35b93bfb000006
