### ISSUE TITLE
Some mistakes in the Regular's FAQ

### ISSUE THREAD

**Issue by BassamR** [OvercastNetwork/Issues#2679]
Some things should be updated in that FAQ, such as the name of the server (lifeboat instead of overcast), and some links in questions, as they do not work (they link to a 404 page).

**Comment by Brottweiler** [comment]
You should tell us what the problems are so we can fix them. "some links" does not help.

**Comment by BassamR** [comment]
1. It should be rebranded (from overcast network to lifeboat pc)

2. Some wrong links: in the question "Why do moderators ignore my reports?" , one of the answers is "Moderators get too many reports to follow up on all of them, so they look for the ones that are most likely to be accurate. Here is a forum topic about writing good reports, and here is another one". The forum topics linked in that answer don't work (they display a 404 page). Here are the links: https://oc.tc/forums/topics/520b34efaf7fb00a1b000573 and https://oc.tc/forums/topics/51cf6a48ba60877fea00482d.

**Comment by Brottweiler** [comment]
Fixed  in

1. https://github.com/OvercastNetwork/RegularsFAQ/commit/3034d1fe4a26781be3983b225893df15fea86b83 
2. https://github.com/OvercastNetwork/RegularsFAQ/commit/b379930caac4f162098ee76d9fa27c585a9d0bbb
