### ISSUE TITLE
Portals (nether and end) crash servers

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2682]
ANY PLAYER (obs, or player) who try to enter a portal in a match that is ongoing, not started, or ended will immediately crash the server. Was observed in 1.10. This does not happen with end gateways.

**Comment by jexeI** [comment]
Side note: When I entered a portal on "Build", I was given the "could not connect to server" message, and following that, the server lagged, and crashed.

**Comment by jedediah** [comment]
fixed
