### ISSUE TITLE
Christmas Map: Desert Country

### ISSUE THREAD

**Issue by OCNsOMEN** [OvercastNetwork/Issues#2685]
This is the Christmas version (X-Mas Country) of Desert Country:

- Download: https://www.dropbox.com/sh/0b2bwu5w1zu2bv7/AAAHhBGo1A5Y2sliv37F2Iosa?dl=0

**Comment by Pugzy** [comment]
Currently conditionals on Map Development servers are non-functional so seasonal maps can't currently be tested.

If your Christmas edition needs to be merged into the regular version (using conditionals) then here's the guide/thread for you. https://oc.tc/forums/posts/5816e961c29635517f000026

**Comment by mitchts** [comment]
https://github.com/OvercastNetwork/Maps/commit/31ece8f9aa97d70f3e1bc265b16a4927966d6a04
