### ISSUE TITLE
Fix Juggernaut (Arcade)

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2686]
You can get blocks
![2016-11-27_16 59 39](https://cloud.githubusercontent.com/assets/18105497/20649602/9c22d4fc-b4c3-11e6-9b07-94fd0b08bc59.png)

**Comment by jexeI** [comment]
This is the same with the other map made by atlas, I believe.

**Comment by dustinn1** [comment]
Fixed
