### ISSUE TITLE
Fix Lunar Barrage (Arcade)

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2687]
![2016-11-27_17 02 10](https://cloud.githubusercontent.com/assets/18105497/20649628/f438b35a-b4c3-11e6-80fa-44a0cbdd8d80.png)
Ghast projectiles stop spawning and it's not fun

**Comment by Pugzy** [comment]
Fireballs that make it through the "moon" end up floating in the void below the map limiting the amount that can spawn hence it gets slower as the game goes on.

The fireball must still be moving as the life attribute doesn't cause it to despawn and altering the MaxNearbyEntities attribute for the spawner doesn't seem to work either.

**Comment by Pugzy** [comment]
Fixed this by upping the MaxNearbyEntities however the I also altered the speed at which the fireballs spawn. I think the server had to restart for the changes to be made.
