### ISSUE TITLE
Map Update - Library DTE 1.0.1

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2689]
Change Log:

Allowed players to build across the void

XML: https://gist.github.com/GoldenOre/965d3efbe0102b29785321b05adf025e

**Comment by Pugzy** [comment]
@GoldenOre

Building on the glass walls does seem very overpowered to cross the void.

ATM players can build anywhere on the map (outside the glass walls too).

**Comment by GoldenOre** [comment]
Alright, i'll fix that then reopen this.
