### ISSUE TITLE
Map Update - Coral Reef 1.2.0

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Issues#2690]
Change Log:

Added chests with power/infinity bows
Redesigned frontlines
Disabled boat crafting
Changed andesite paths to gravel
Moved building that the monument was in
Added barriers to prevent people from getting stuck in spawn

DL: https://www.dropbox.com/s/8gdfj56o1l5z4ey/Coral%20Reef%201.2.0%20.zip?dl=0

**Comment by Pugzy** [comment]
- `<respawn delay="2s" />` removed as this is default.
- XML indented back one tab.

I added a `allow-stained-clay` filter and gave the negative region an id so the stained clay floating outside the map can be broken, don't think this breaks anything. You can get the latest download from the oc.tc/maps page. :+1:

**Comment by GoldenOre** [comment]
Thanks!
