### ISSUE TITLE
Map Update- Block Runner: Christmas (1.0.1)

### ISSUE THREAD

**Issue by jexeI** [OvercastNetwork/Issues#2692]
Changelog (1.0.1): 

- Removed `<itemremove>` due to the fact that the `skywars.xml` include file already has `doTileDrops` set as false

- Fixed double spacing in the Elytra and Leather Hat name

- Tweaked Region names

- Re-organized `<regions>`

- Disabled Natural Regeneration (This is mainly for the elytra section of the map, where players can crash into walls and die)
 
**No world changes have been made, only XML
Updated XML is in my [Jexel] Build Folder, _Block Runner- Christmas_**
https://www.dropbox.com/s/tnd0xxt1zyuvj1i/map.xml?dl=0

**Comment by Pugzy** [comment]
@JexeI can you please provide an XML download link here as I don't have access to your private folder.

**Comment by jexeI** [comment]
@iPGz https://www.dropbox.com/s/tnd0xxt1zyuvj1i/map.xml?dl=0
