### ISSUE TITLE
Christmasquad: primed bug after spawning

### ISSUE THREAD

**Issue by BassamR** [OvercastNetwork/Issues#2694]
Okay so in christmasquad, you spawn in a cube above your base, and after 50 seconds you fall down and start fighting (that's what normally happens). Well, i just played that map, and after 50 seconds when falling, instead of having all players drop in their base, they all died.

**Comment by mitchts** [comment]
https://github.com/OvercastNetwork/Maps/commit/1d23214005a7ff4ecce251ad8fe2fff804cd0688
