### ISSUE TITLE
Tips not showing properly

### ISSUE THREAD

**Issue by BassamR** [OvercastNetwork/Issues#2695]
The screenshots should be enough.

![2016-12-03_18 54 32](https://cloud.githubusercontent.com/assets/18619720/20860123/34a1763c-b98a-11e6-821a-c2e3450e983d.png)
![2016-12-03_14 11 18](https://cloud.githubusercontent.com/assets/18619720/20860126/3db6f95e-b98a-11e6-841f-dc7c7b11b881.png)

**Comment by jedediah** [comment]
fixed
