### ISSUE TITLE
Items from dead players not dropping in Skywars

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2696]
It happened to me 2 times, the first one I thought that it was a random bug, but it happened again so here I am. I have no idea how to reproduce this bug, but I think it might be related to the first kill of a match. The second time, it happened in Village, by Flashee.

**Comment by Pugzy** [comment]
@MrPetrus does this occur on any other map or just Village?

**Comment by ghost** [comment]
I don't know, was it fixed?
