### ISSUE TITLE
New player stats and cps message are on the same line

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2699]
They end up getting in the way of each other when you get a kill or die, while clicking to activate the cps message.
![2016-12-05_18 21 31](https://cloud.githubusercontent.com/assets/7937351/20906805/0991c30e-bb18-11e6-9800-daa434fbfd05.png)
![2016-12-05_18 21 30](https://cloud.githubusercontent.com/assets/7937351/20906810/0d973574-bb18-11e6-9a9c-6c59e4380a92.png)

**Comment by CrazyisCreeps** [comment]
Those pictures don't really do justice to show the issue. I could not however, get a good picture to show the two lines of text overlapping

**Comment by Pablete1234** [comment]
There is absolutely no way we can fix that, the stats message is forced to stay for a couple seconds, but the cps will eventually override it if you click

**Comment by CrazyisCreeps** [comment]
What about making a way to toggle the player stats thing? That way, at least I can choose which one I want to take up that line @Pablete1234

**Comment by CrazyisCreeps** [comment]
Thanks fam
