### ISSUE TITLE
Arch: Issues with map, spawn update

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2704]
The new level.dat and region files are here:

https://www.dropbox.com/s/y94e66o1m1f2fpv/Arch1.7%20region%20leveldat.zip?dl=0

The XML and map.png can be found on this post:

https://oc.tc/forums/topics/582f5c3067d5223b2f0000b9

**Comment by PoseidonsM** [comment]
@DowlyMC The XMl and map.png haven't changed, have they?

**Comment by ghost** [comment]
No, but Matic0B has been editing the XML because I don't know how to code it. The map.png is the same.

**Comment by Matic0B** [comment]
I haven't changed anything yet since I haven't seen the world download but if I remember correctly you mentioned changing monument material. If you can, please write down all of the changes that need to be done in here.

**Comment by ghost** [comment]
The monument is changed from Packed Ice to Endstone.

The main difference in the XML is that the opposing team should be able to place blocks inside the wool rooms for cover, since there isn't any safe spots.

**Comment by Matic0B** [comment]
The gamerule "randomTickSpeed" is set to 10000 for the world. Could you set it back to the normal value (3) and update the download?

**Comment by ghost** [comment]
The randomTickSpeed has been set back to 3.

The new level.dat and region are here:
https://www.dropbox.com/s/7wlitmusy7qz83r/Arch%201.0.8.zip?dl=0

And the map.png has not changed.

**Comment by Matic0B** [comment]
Map has been updated. I recommend adding a shovel to the spawn kit.
