### ISSUE TITLE
Eleytra fly bug in servers

### ISSUE THREAD

**Issue by hunter98789** [OvercastNetwork/Issues#2706]
On the server, you can induce a state of flying while playing a match with the eleytra. This state is the equivalent of flying with a eleytra, and cannot be reset during a match.
The way you induce this state is:
1) Join the lobby and find a steep cliff
2) Jump off the cliff and activate the eleytra
3) Join a server while in eleytra mode

You will be a block under ground, but able to gain speed and fly as you are in eleytra. Also, other players will see you as flying inside a block

The ways to cancel this mode are: 
1) Hit shift
2) go into fire
3) get stuck inside of a block
4) entering water

Things this mode does not do:
You can fly through non solid blocks as if they dont exist (slabs, stairs)
You can do 1x1 tunnels, if the block removed is the bottom
You can go up staircases and fly to wool (I never tried but I went up a staircase)

Solutions: Solutions to this problem are very tough, as the eleytra is a feature in the lobby
1) Do not allow changing servers while moving
2) Have spawns have a water pit
3) Remove eleytra in lobby

**Comment by hunter98789** [comment]
Update: You see yourself in the ground, but others see you as standing up, flying
You cannot fly through lamps

**Comment by jedediah** [comment]
deploying fix shortly
