### ISSUE TITLE
Player able to interact with objectives briefly at the end of the huddle period of ranked matches

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2713]
This player must have somehow punched a block on the monument right when the huddle period ended? The touch came immediately at the start of the game, right as we spawned. No blocks appeared to be broken, but the touch did count on the scoreboard. The player was unable to recall what they were doing prior to the match start.
![touch](https://cloud.githubusercontent.com/assets/7623955/21470232/4e4f495a-ca4d-11e6-935f-a92cc12878a1.png)

**Comment by MarcRoizman** [comment]
This is more of an issue than I originally thought. In ranked CTF maps, users can stand on top of the flag during the huddle period and start the game carrying the flag.

**Comment by MarcRoizman** [comment]
This may be caused by the new 3 second countdown teleport thing, where it puts you in your spawn and changes your gamemode 3 seconds before it starts? This doesn't happen at all on ranked, you don't get spawned in until the very end of the huddle period, no 3 second warning.

**Comment by MarcRoizman** [comment]
Can be 3 of the ranked gamemodes, you can pick up flags, cap wools, and break monuments/cores all before matches start.

**Comment by Musyaffaq** [comment]
On Desert Sanctuary, if you grab the flag before the match starts, your teammates and you would not spawn because it's Flag Blitz (your team would not respawn if you have the flag).

**Comment by jedediah** [comment]
fixed
