### ISSUE TITLE
Capture Points on Foundry default to red/blue instead of the neutral gray

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2714]
When a KotH hill goes neutral now in PGM, it defaults to its original state rather than a neutral gray color. So on 5CPs like Foundry, the 2nd and Last points have a neutral state the same color as the team whose side they're on.

**Comment by Pablete1234** [comment]
This is a map issue, not a PGM issue, as this has worked this way pretty much forever

**Comment by MarcRoizman** [comment]
~~Up until a couple weeks ago, maps like foundry worked fine and you could always see the neutral state on every hill. Suddenly, it's stopped working and second and last no longer turn gray. Something has changed in the KotH code, and I believe this is a PGM bug.~~

After talking with Pablete, this is a map specific bug on Foundry that occurred likely due to a level designer saving the map after an edit made on their server, causing the default hill colors to be saved as red/blue.
