### ISSUE TITLE
Victory monument location change (Arch)

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2718]
A couple updates to Arch:

-The victory monument has been moved.

-Cobwebs have been removed from remaining defensive chests.

Here's the .zip without the XML.

https://www.dropbox.com/s/wtv7d3tf07s5bms/Arch1.9%20w%3Aout%20XML.zip?dl=0

_EDIT: DO NOT USE THAT LINK! THAT IS AN OUTDATED LINK AND WILL BE DELETED! NEW LINK BELOW_

**Comment by Pugzy** [comment]
You should try and update the XML. This would include updating the following things.

- The map version number, add a .1 to the end value.
- Coordinates for the new monument locations (F3 can show you the block you're looking at).

**Comment by ghost** [comment]
I don't have the newest version of the XML. Plus, I have 0 experience of coding XML... Matic0B has been coding it for me and he has the latest version. I have an older version of the XML.

**Comment by Pugzy** [comment]
@DowlyMC well now's your chance, its a couple of simple changes.

- Log into the website.
- Goto your profile oc.tc/username
- Click on the maps tab.
- Open the map link.
- Press the download button.

Once you've made the changes you can upload the XML to Github as a Gist (https://gist.github.com/) and link it here.

**Comment by ghost** [comment]
Here's the whole Arch.zip file:
https://www.dropbox.com/s/jx8gsdtrx9srmhr/Arch1.0.9.zip?dl=0
Here's the new XML on GitHub Gist:
https://gist.github.com/DowlyMC/a94b32cdec3fb217a1334b6b7fd573cd
Hope I did the XML right :o


EDIT: New links. I added SrNativee's name to the XML and pruned the map (I was pretty sure it was already pruned, but it never hurts to do it again).

**Comment by ghost** [comment]
One more change. SrNativee helped me create a new observer spawn.

**Comment by Pugzy** [comment]
When you update the world you need to make sure that you do the following things.

- Clean the files, http://docs.oc.tc/guides/packaging/cleaning_files
- Prune, http://docs.oc.tc/guides/packaging/pruning_chunks
- Compile, http://docs.oc.tc/guides/packaging/compiling_releasing

This means the content inside the zip file can be reduced by like 90%.

To add another contributor take a look at line 12 and 13 of your XML, that's a working example for you. Them two lines can be copied below and then edited for your needs, change the contribution from "XML" to what you want and the UUID and name for your friend (to get the UUID use https://mcuuid.net/).

**Comment by ghost** [comment]
Thanks for the help iPGz

**Comment by Pugzy** [comment]
In a few place you've used `”` rather than `"`, I've changed this to correct formatting and pushed the update.

The `map.png` was an incorrect size (more info on the compile link from earlier).
