### ISSUE TITLE
Arch 1.0.91 (Bug Fixes)

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2720]
-Observer spawn has been corrected to the right place.
-Max players increased to 48 from 32.

Map download: https://www.dropbox.com/s/2rjrqz6379cr195/Arch1.0.91.zip?dl=0

XML: https://gist.github.com/DowlyMC/1b6c949229da182b63750a1677257255

Pictures: http://imgur.com/a/XKLGk

**Comment by Pugzy** [comment]
Feedback on this one.

- To bump the version number you add 0.1 to the end as it's a bug fix.so the 1.0.9 -> 1.0.10.
- If you've only updated the XML (not made map edits) then you don't need to provide a world download.

**Comment by ghost** [comment]
Alright thanks for the advice. Do I need to change the XML or did you do it already?

**Comment by dustinn1** [comment]
Updated
