### ISSUE TITLE
Puddin' Pops Respawn Scoring Glitch

### ISSUE THREAD

**Issue by MarcRoizman** [OvercastNetwork/Issues#2723]
On the arcade map Puddin' Pops, jumping into the void with the "Puddin' Pop" item on you allows you to score a point. It probably teleports players back to spawn, and THEN clears their inventory, allowing the point to be scored from the redeemable.

**Comment by MarcRoizman** [comment]
This happened a long time ago too.
#2515

**Comment by jedediah** [comment]
fixed
