### ISSUE TITLE
When using /report, you get an error message

### ISSUE THREAD

**Issue by CrazyisCreeps** [OvercastNetwork/Issues#2731]
The report still goes through, and moderators can see the report. However on the end of the person reporting, they get a message saying that there was an internal error while processing the command.

https://i.gyazo.com/115ee2455c8d24eee6191cdad28a63e7.png

**Comment by TheMolkaPL** [comment]
Should be fixed now.

![image](https://cloud.githubusercontent.com/assets/4578571/22101597/6516bede-de34-11e6-94f3-30f8375b9ad4.png)
