### ISSUE TITLE
Duplicate Friend Request/List

### ISSUE THREAD

**Issue by nixter1029** [OvercastNetwork/Issues#298]
## Issue
Yo sometimes receive a duplicate friend request.

## Proof
![screen shot 2013-06-22 at 12 11 18 pm](https://f.cloud.github.com/assets/2856681/691020/864fc210-db56-11e2-8676-15baa9437bfd.png)

**Comment by ghost** [comment]
Seems to be fixed http://prntscr.com/8wy9ex
