### ISSUE TITLE
The damage module as a filter.

### ISSUE THREAD

**Issue by NathanTheBook** [OvercastNetwork/Issues#342]
## The Idea ##

Add a filter the exact same as the damage module _(while keeping the module)_ that allows you to deny the damage in only that region.

## Example ##

```xml        
<filter name="no-fall" parents="disable-damage">
    <disabledamage><damage>fall</damage></disabledamage>
</filter>

<regions>
    <apply damage="no-fall">
        <!-- Jump Pad -->
        <cuboid min="49,13,4" max="37,10,-4"/>
    </apply>
</regions>
```

**Comment by Electroid** [comment]
A better implementation will probably be a kit node. This allows it not only to be sticked to a filtered player, but also applied via regions.

```
<kit>
    <disable-damage>
          <damage>fall</damage>
          <damage ally="false">block explosion</damage>
     </disable-damage>
</kit>
```

**Comment by Superjd10** [comment]
@Electroid Nathan is banned from the OCN's github repos.

**Comment by mrapple** [comment]
We don't allow feature requests, not sure why this wasn't originally closed.

@Electroid move this to the internal tracker if you'd still like it.
