### ISSUE TITLE
Display server rotations on website

### ISSUE THREAD

**Issue by YukonAppleGeek** [OvercastNetwork/Issues#46]
#### The Issue:
There should be a way to view server rotations on the website. They are already stored on a database, so it should not be hard to implement rotations on to the website.

#### Expected Outcome:
Have sever rotations on website in the matches or play page.

#### Steps to Reproduce:
Not applicable

#### Other Info:
Related "Ask the Admins" post https://oc.tc/forums/topics/5181782dba6087d6f8007d6f

**Comment by ParaSpider** [comment]
https://oc.tc/maps/ Can close, implemented.

**Comment by Electroid** [comment]
:pray:
