### ISSUE TITLE
Improve appeal user identification

### ISSUE THREAD

**Issue by khazhyk** [OvercastNetwork/Issues#546]
Currently, it's rather easy for an unregistered user to lose access to their appeals.

I saw this post on reddit that shows a example light weight auth only server, we could use something similar to this to allow banned users to register accounts to use for appeals, so less appeals are left with no access.

https://github.com/barneygale/authserver

This would be involved, so this is just a proposal to look into it.

**Comment by Electroid** [comment]
This feature was implemented a while ago.
