### ISSUE TITLE
When clicking 1 friend request notification, the others remain a notification

### ISSUE THREAD

**Issue by censink-** [OvercastNetwork/Issues#583]
i have 2 friend requests

i clicked 1
i arrived on the friend requests page
i went back to forums
i have the other request in my notifications

solution: like with forum notifications, remove all notifications when entering the related page (nicely done btw :+1:)

**Comment by ghost** [comment]
Dupe https://github.com/OvercastNetwork/Issues/issues/586

**Comment by tonybruess** [comment]
Not a dupe

**Comment by ghost** [comment]
Yes it is https://github.com/OvercastNetwork/Issues/issues/669

**Comment by tonybruess** [comment]
Different bug

**Comment by ghost** [comment]
It is the same bug, Martin said:

> Not an issue for friend requests, only for forum quotes. (https://github.com/OvercastNetwork/Issues/issues/583#issuecomment-51577633)

The friends issue have been fixed, that leaves only the quote issue, and it is the same as https://github.com/OvercastNetwork/Issues/issues/669
