### ISSUE TITLE
Minor capitalization error on match summary page

### ISSUE THREAD

**Issue by SeanBarker** [OvercastNetwork/Issues#601]
**Issue at hand:**
TNT, when displayed as a most/least common weapon, is spelt "Tnt". It's not a huge deal, but if there are no other bugs to squash it may be reasonable to fix this quick capitalization error.

**Steps to reproduce:**
Visit any match summary page in which TNT is used as a most/least common weapon. For example, https://oc.tc/matches/525b376e0cf2cfb3717714d7

**Comment by Electroid** [comment]
There isn't any bug about it.
