### ISSUE TITLE
Feedback books - not enough time + not showing up

### ISSUE THREAD

**Issue by TinyOrange** [OvercastNetwork/Issues#654]
With the new feedback books, the concept is great, but there are some annoyances. 

First, in Rage the maps cycle faster, giving you little to no time to comment. (Writing in the book after you /rate)

Second, if you are on a gamemode in which you get a bunch of items in your inventory, the book goes to your inventory if your hotbar is full. This requires you do go into the creative menu and extract it. This could be fixed by making the book show up in a certain slot every time it gets given to you, like the compass.

**Comment by Electroid** [comment]
This feedback book feature was removed. This is no longer relevant.
