### ISSUE TITLE
Project Ares referenced in forum category tooltips

### ISSUE THREAD

**Issue by Jake0oo0** [OvercastNetwork/Issues#691]
Some of the category tooltips on the forums still reference Project Ares, that should technically be Overcast Network. 

The affected categories are:

Overcast Network
  * Website Feedback
  * Server Feedback
  * Media

Announcements:
  * Admin Blog

The tooltip for the fall tourney should probably be changed too..

**Comment by Electroid** [comment]
This seems to be fixed. Forums have been revamped several times after this issue was created.
