### ISSUE TITLE
Switching pages in the "Happy Children" tab sends you back to the "Wishful Elves" tab

### ISSUE THREAD

**Issue by JsKingBoo** [OvercastNetwork/Issues#697]
1. Go to https://oc.tc/secretsanta
2. Click "Happy Children"
3. Go to page 2 (or 3, or 4, or last)
4. When the page reloads the tab selected is "Wishful Elves".

**Comment by itsmartin** [comment]
Still happens.

**Comment by ghost** [comment]
Fixed (66f740)

**Comment by mitchts** [comment]
Switching to `Happy Children` and going to another page, lets say 3, carries over when you go back to the `Wishful Elves` tab and select a page. So selecting a page on wishful (after doing what I've just said) sends me to page 3 of happy children.  `santa?happy=true&happy_page=3&wishful_page=3`

**Comment by Electroid** [comment]
Not anymore.
