### ISSUE TITLE
Attempting to report a non-existant player gives a 404

### ISSUE THREAD

**Issue by Jake0oo0** [OvercastNetwork/Issues#708]
When attempting to create a report for a null player, let's say 'someguy', you're redirected to: https://oc.tc/reports/new/someguy - Which is a 404 page. Instead I suggest adding an alert/popup/whatever you call them to the top of the report page if you try to create a report for a null player.

**Comment by ghost** [comment]
Now appear "Could not find the specified user."

**Comment by Pugzy** [comment]
^
