### ISSUE TITLE
Leprechaun's can walk on water and lava in Ghost Squadron

### ISSUE THREAD

**Issue by Nadastorm** [OvercastNetwork/Issues#718]
Leprechaun's can walk and run on water and lava in Ghost Squadron

Steps to reproduce
-Double jump
-Press shift and space at the same time and hold it
-Initiate chat, then move around

Video
https://www.youtube.com/watch?v=7R6cLpBJ6v4

**Comment by mitchts** [comment]
Fixed

**Comment by tonybruess** [comment]
You sure?

**Comment by ghost** [comment]
Yes, we tested this yesterday

**Comment by mitchts** [comment]
Tested on multiple servers, I'm sure.
