### ISSUE TITLE
Mobs from spawners on Ghost Squadron can attack teammates once the spawner dies

### ISSUE THREAD

**Issue by JsKingBoo** [OvercastNetwork/Issues#722]
Steps to reproduce
1. Go to a GS server
2. Choose spawner
3. When game starts spawn a bunch of mobs
4. Die (falling in lava, fall damage, etc)
5. Watch how your mobs kill your own team

Possible fix
Have mobs tagged with team and player. So if a player dies, the mob will still have its team color and continue attacking the enemy rather than allies.

If a spawn egg is used and the player switches teams (like Cake Wars, for example) then the mob will prioritize team color over player tag, and the player tag will be removed. An example death message in this instance can be:

BluePlayer was slain by Cave Spider (Cave Spider text is red)

**Comment by Electroid** [comment]
Fixed a while ago.
