### ISSUE TITLE
Hiding Threads

### ISSUE THREAD

**Issue by TinyOrange** [OvercastNetwork/Issues#753]
A month ago (ish) there was a website feature added where you can hide threads. I have already accidentally hidden two threads of mine, and although this might be my stupidity, there should be some kind of confirmation.

I think that when you click on hide,  it'll just ask you to confirm it, and tells you what you're about to do.

"Are you sure you want to hide this thread"

Like that. I'm pretty sure this wouldn't be too hard to add.

Thanks,
Tiny

**Comment by Electroid** [comment]
#1011
