### ISSUE TITLE
A game can start with no players on a team

### ISSUE THREAD

**Issue by JsKingBoo** [OvercastNetwork/Issues#763]
1. Start a game, but with all premium players on one team
2. Have every premium player switch to the other team

I've seen this happen in Blitz and Ghost Squadron. In Blitz/GS, the match ends when one person suicides.
This can be fixed by automatically ending the match
And here's the thread that reminded me of this bug: https://oc.tc/forums/topics/52ff935e12ca955cf500048f

**Comment by ghost** [comment]
This was fixed with the min tag
