### ISSUE TITLE
Kill rewards can be given after death but before respawn and therefor offset inventory.

### ISSUE THREAD

**Issue by Firey02460** [OvercastNetwork/Issues#798]
Rewards for killing a player can be given after you die but before you respawn, causing all the items in your inventory to be shifted over a slot (or more, depending on how many items are given in the reward).

You can reproduce this by:
1) Joining a map with a specified kill reward.
2) Punching a player from the opposing team off into the void.
3) Being killed before that player dies in the void, and sitting in the respawn menu until they die.

**Comment by Electroid** [comment]
This was fixed.
