### ISSUE TITLE
Now Playing Label Needs A Data Center Identifier

### ISSUE THREAD

**Issue by AustinLMayes** [OvercastNetwork/Issues#819]
Currently on the maps page if a map is playing on the same servers on both US and EU the labels appear to be duplicated,
![screen shot 2014-05-16 at 5 38 13 pm](https://cloud.githubusercontent.com/assets/4269021/3003069/efa1aca0-dd4a-11e3-9adf-8c6e3889ddd3.png)
Some users might see this and think this is an error and report them here.
Also, if a user is looking for a map that is playing and they have no indication as to which set of servers the map is being played they could join the wrong set and miss the map being played entirely

**Comment by Electroid** [comment]
New play page, no longer an issue.
