### ISSUE TITLE
Back Button On /matches/MATCH_ID Not Really A "Back" Button

### ISSUE THREAD

**Issue by AustinLMayes** [OvercastNetwork/Issues#821]
Let's say you go to a punishment and click on the "Map" link. On the match page linked there is a map button. If clicked, the expected behavior is to be returned to the punishment (or any previous page of that matter). Instead, the user is returned to the root matches page. The button should either be renamed to "All Matches" or have an actual back function.

**Comment by ghost** [comment]
Back button removed, this can be closed. Also, dupe https://github.com/OvercastNetwork/Issues/issues/1825

**Comment by TiTo-418** [comment]
Also, dupe https://github.com/OvercastNetwork/Issues/issues/1825

**Comment by ghost** [comment]
http://prntscr.com/8tp4hh
