### ISSUE TITLE
Player stars aren't showed in the tab list / in the name if nick'd (Lobby)

### ISSUE THREAD

**Issue by Superjd10** [OvercastNetwork/Issues#848]
1. The issue:
If a player is nick'd (a IF for example) and you see the tab list or his name, his stars aren't showed.

![image](https://cloud.githubusercontent.com/assets/1649155/3347434/b27d89c2-f8e1-11e3-9ac4-befcb64b2bba.png)

2. Steps to reproduce:
Join in the same lobby of the player, press the tab list or /tp to him.

3. Miscellaneous information:
/fr show the stars

**Comment by Superjd10** [comment]
Adding from the discussion in #1573: I was able to see the real name above the player as we are friends, looks like if you aren't friends you see the nick above the player.

**Comment by mrapple** [comment]
This will be fixed when we move to 1.8
