### ISSUE TITLE
Topics in server information are getting archived

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#86]
Issue:

Topics in Server Information are getting archived. This surely shouldn't happen as this part of the forum provides guides for newer players, and is a place for them to ask questions.

Example:

[This guide](https://oc.tc/forums/topics/5071a4ccb944ec7fa7000d5c) is an example of this, it would be better if a player asked about the /punish command on this guide, instead of elsewhere.

**Comment by itsmartin** [comment]
I think it's fine to let topics archive in all subforums. If something needs to remain open for questions, it can be pinned, which prevents it from archiving.
