### ISSUE TITLE
Can't pickup water from own core

### ISSUE THREAD

**Issue by Maccrafter** [OvercastNetwork/Issues#869]
You can put water on your own core, but you can't pick it up.
![2014-07-10_19 41 12](https://cloud.githubusercontent.com/assets/3052396/3542734/4c7c63fe-085a-11e4-8d86-66c98a8631c1.png)

**Comment by Electroid** [comment]
If we allow water to be removed, then you risk allowing a player to make their own core leak. Unless PGM changes the logic to block destruction of only essential blocks to keep the core intact.
