### ISSUE TITLE
cos(tnt) - Stained clay on control points doesn't regenerate properly

### ISSUE THREAD

**Issue by Diamyx** [OvercastNetwork/Issues#963]
Video: https://www.youtube.com/watch?v=q53BcB3eAro
Explanation: On cos(tnt), if a team captures a control point then someone breaks the stained clay around the glass on the control point, it regenerates as white stained clay.

**Comment by Electroid** [comment]
I could use filter magic to fix this, but it's such a small bug. I'll let this be. The map will be getting a 1.8 update eventually too.
