### ISSUE TITLE
Emojis show up in title bar

### ISSUE THREAD

**Issue by hayleyjames** [OvercastNetwork/Issues#965]
Hi,

The emoji text representation shows up in the webpage title bar.

Screenshot:
http://prntscr.com/4d5gsl

**Comment by ezfe** [comment]
You're able to transfer the emoji unicode character to the image, so you can transfer it back. The issue is that the Emoji picker (`:rocket:`) isn't being parsed in the title page, which is fix-able by parsing it to a unicode character instead of an image.
